### ISSUE TITLE
Suggestion: Namespace according to version

### ISSUE THREAD

**Issue by PDRDaveF** [FirelyTeam/firely-net-sdk#1072]
Currently working on a system that uses DSTU2 and STU3 versions, and spotted the two different NuGet packages use the same namespace of HL7.Fhir.Model, and so this causes a collision.

Injecting the version into the namespace would remove the collision and allow multiple versions to be used together safely.

**Comment by brianpos** [comment]
You can add both to the same project, check the fhirpathtester project on github for an example of using it.

**Comment by PDRDaveF** [comment]
Thanks for that @brianpos , never seen that target name before!

Not wishing to cause offence, but it seems a convoluted way of going about things when good practice would indicate minimising the risk of putting yourself in that position in the first place?

Does the trick though, so thanks again.

**Comment by ewoutkramer** [comment]
Yep - it's convoluted.  I have been thinking about this (because we're being asked about this now and then), but this namespace change would break all existing code...... isn't that too scary to consider?   Maybe we could have a parallel set of assemblies that DO use it, so you can switch and do the rename on your own time?

**Comment by PDRDaveF** [comment]
Could you not bump the package version up to reflect it is a breaking change? That way packages can be enforced not to upgrade to it.

Alternatively, have parallel namespaces and drop the obsolete attribute on the current ones? Won't break existing code, but will allow for a slow transition?

**Comment by brianpos** [comment]
This then mives the problem to your code when you want to move from stu3 to R4 too.

**Comment by BradBarnich** [comment]
You could give our fork a try, it supports all versions in the same library, separated by namespaces. 

https://www.nuget.org/packages/CareEvolution.Fhir.Core/1.3.2

**Comment by PDRDaveF** [comment]
Sorry for not getting back sooner - @BradBarnich I may take a look at that on the next version, thank you.

@brianpos IMO it _should_ be a code problem. When moving up a major version you can then split at some level - e.g. microservice or repository layer - and use feature flags to toggle between the two for testing and have rollback at a configuration level.
