### ISSUE TITLE
Use new "HandleDuplicateProperties"

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#1075]
Newtonsoft has added settings to handle duplicate properties in Json - before it just hid the fact that duplicate properties existed at all.  We can now better validate the json - and (by use of a  setting?) trigger validation errors on encountering duplicate properties.

**Comment by mmsmits** [comment]
duplicate of: https://github.com/FirelyTeam/firely-net-sdk/issues/1075
