### ISSUE TITLE
Allow for async setting of authentication header

### ISSUE THREAD

**Issue by joshclark** [FirelyTeam/firely-net-sdk#1077]
In order for me to make rest calls to a server that requires authentication, I have to handle the `OnBeforeRequest` event.  In this handler, I need to make an async call to my authentication server to get a token.  The problem is, I end up having to call `Task.Result` to get my value out of the asynchronous call.

It would be much better if I could pass in something like a `Func<HttpWebRequest, byte[], Task>`.  The code could then await on my call and then continue on.

**Comment by ewoutkramer** [comment]
Hi Josh, where would we pass this Func<> in?  To every call on FhirClient?  Or would we need something like an async event not unlike OnBeforeRequest, that was instead such a function?

**Comment by mmsmits** [comment]
Hi @joshclark, sorry for the very late reply.
In the newest current version of the FhirClient (based on HttpClient), you can write your own MessageHandlers to configure such behavior. Documentation and examples of custom handlers can be found here:
https://docs.fire.ly/projects/Firely-NET-SDK/client/request-response.html
