### ISSUE TITLE
SnapshotGenerator - Fix normalization of type slices in extensions

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/firely-net-sdk#1098]
Fix validator unit test `WalkToExtension`
Issue: generated snapshot contains renamed element `valueCode` in expansion of referenced extension `data-absent-reason`.
Expecting type slices in snapshot with normalized paths, i.e. `value[x]:valueCode`

**Comment by mmsmits** [comment]
This currently not an issue, we will reopen this when this breaks for someone,
