### ISSUE TITLE
SnapshotGenerator - verify resolved external profiles

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/firely-net-sdk#1124]
We could improve the `SnapshotGenerator` by verifying external profiles returned by the resolver, e.g. generate a warning if the resolved profile represents a logical model when that isn't expected/valid.

https://chat.fhir.org/#narrow/stream/179239-tooling/topic/Forge.20-.20can't.20profile.20careplan.3F

**Comment by mmsmits** [comment]
We will replace this by adding an issue for adding error messages to why we can't resolve certain Resources in our resolvers.
