### ISSUE TITLE
Use of non-static SymbolTable for FhirPathCompiler

### ISSUE THREAD

**Issue by abelenthoven** [FirelyTeam/firely-net-sdk#1181]
In some applications of the FhirPathCompiler (e.g. in IValueProviderFPExtensions) the default constructor of FhirPathCompiler() is used. The default constructor uses FhirPathCompiler.DefaultSymbolTable, which is a static property.
If we change this DefaultSymbolTable (which we do to work around some unsupported path segments) the table is obviously changed for all consumers. This becomes a problem when our product is used as a library, since the consumer of the library is not aware of the changes we made to the SymbolTable and may not want those changes.
Ideally, we would like to be able to create our own Symbol table and just use it in a call to, let's say, 'IValueProviderFPExtensions.Select'. Perhaps an overload? Or, alternatively, have a Select on a FhirPathCompiler?

**Comment by brianpos** [comment]
That exists in most places I know of, as I provide a specific one for my use cases.
What is the case where you need it? 
We provide an easy way if you don't need things, and an alternate where you provide it.

**Comment by abelenthoven** [comment]
Ok that's good to know Brian. It doesn't exist in IValueProviderFPExtensions

**Comment by brianpos** [comment]
The extensions are the shortcuts.
I'll take a look again.
In the validator the compiler/symbol table is able to be provided, and it doesn't use the extension shortcuts.

**Comment by ewoutkramer** [comment]
The new `FhirPathCompilerCache` solves this problem now!
