### ISSUE TITLE
Add WriteAsync support to Serializers 

### ISSUE THREAD

**Issue by jerchap** [FirelyTeam/firely-net-sdk#1224]
In an ASP.Net core web api, I am serializing  useing the FhirXmlSerializer and FhirJsonSerializer.  The Serialize method of the R4 package throws an exception

> Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead

I could allow synchronous IO but that can contribute to performance degredation.  Can the serializers support WriteAsync?

Here is my usage:

```
public class FhirXmlFormatter : TextOutputFormatter
{
    public FhirXmlFormatter()
    {
    }

    public override Task WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
    {
        if (context.Object != null)
        {
            Hl7.Fhir.Serialization.FhirXmlSerializer ser = new Hl7.Fhir.Serialization.FhirXmlSerializer();

            using (System.Xml.XmlWriter w = System.Xml.XmlWriter.Create(context.HttpContext.Response.Body))
            {
                ser.Serialize((Hl7.Fhir.Model.Base)context.Object, w);
            }
        }
        return Task.CompletedTask;
    }

}
```

**Comment by brianpos** [comment]
I've done the AllowSynch on my web api project and has been working fine so far.
https://github.com/brianpos/fhir-net-web-api/blob/develop-r4/src/Hl7.Fhir.WebApi.AspNetCore/XmlFhirFormatter.cs
(do have a few local commits I haven't pushed yet)
Updating to include Async serializers would be quite some effort...

**Comment by ewoutkramer** [comment]
Interestingly, microsoft has left out the Async methods on the newer System.Text.Json serializers - probably because the overhead is too large.  In fact, our experience with the validator shows that making this mostly recursive algorithm async, will cause even the smallest units of serialization (i.e. writing a single value) to become async.  And now, with the new json serializers, we would not even be able to actually do async work on the serializers.

So I am closing this issue.

**Comment by brianpos** [comment]
My facade project has a mix of usage in several versions of the OutputFormatter using the various options available
https://github.com/brianpos/fhir-net-web-api/blob/feature/FirelySdk5-r4b/src/Hl7.Fhir.WebApi.AspNetCore/JsonFhirFormatter2.cs

https://github.com/brianpos/fhir-net-web-api/blob/eaff3ebbaf49afaea93f49ae4b766ae5d8d3c501/src/Hl7.Fhir.WebApi.AspNetCore/XmlFhirFormatter.cs#L138

Where the async support isn't available, I just write it out to a memory stream, then async write that out.

You might also be interested in using the new parsers in the SDKv5 which I've just implemented too
https://github.com/brianpos/fhir-net-web-api/blob/feature/FirelySdk5-r4b/src/Hl7.Fhir.WebApi.AspNetCore/JsonFhirInputFormatter3.cs
[(there is an XML ](https://github.com/brianpos/fhir-net-web-api/blob/feature/FirelySdk5-r4b/src/Hl7.Fhir.WebApi.AspNetCore/XmlFhirInputFormatter3.cs)
