### ISSUE TITLE
R4 Condition validation failed (rule con-3)

### ISSUE THREAD

**Issue by mustiks** [FirelyTeam/firely-net-sdk#1283]
Rule con-3 has error in fhir spec instead of
category.select($this='problem-list-item').empty()
shoud be
category.select($this.**code**='problem-list-item').empty()
source https://chat.fhir.org/#narrow/stream/179166-implementers/topic/.24this.20Fhirpath.20interpretation

**Comment by ewoutkramer** [comment]
What do we think? Should we manually patch this in R4 or wait for the next technical correction?

**Comment by marcovisserFurore** [comment]
Fixed in release 3.4.0 for R4
