### ISSUE TITLE
Binary resource handling

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/firely-net-sdk#1340]
When creating a binary resource it currently switches to the binary stream rather than just pushing the XML/JSON.
There is nothing in the spec that describes this behaviour, and specifically it misses the `X-Security-Context` header value also.
http://hl7.org/fhir/binary.html
What this page does describe is the returning of the content, and this isn't handled by the FHIR Client.

**Comment by ewoutkramer** [comment]
When reviewing the FhirClient's code for SDK 5.0 I have noticed that this codepath has disappeared after the refactorings for the new HttpMessageHandler based implementation. The code is still there, but is logically unreachable.

**Comment by ewoutkramer** [comment]
I am fixing this tomorrow!
