### ISSUE TITLE
Add support for FHIR Patch operations

### ISSUE THREAD

**Issue by valeneiko** [FirelyTeam/firely-net-sdk#1374]
FHIR defines patch operations: https://www.hl7.org/fhir/fhirpatch.html
But [fhir-net-api](/FirelyTeam/fhir-net-api) does not support them.

There was a similar issue (#813) open previosuly, requesting this, but was closed, with no support for patch operations added.

**Comment by mmsmits** [comment]
Patch was added in a previous release
