### ISSUE TITLE
[SnapshotGenerator] Unnecessary child elements get generated before adding slices

### ISSUE THREAD

**Issue by mmsmits** [FirelyTeam/firely-net-sdk#1395]
In this example: https://simplifier.net/renderingengineallslice/gemerxtask
Task.input unnecessarily gets expanded with 
```

”Task.input.id”
”Task.input.extension”
”Task.input.modifierExtension”
"Task.input.type"
”Task.input.value[x]"
```

while it should be just list the slices, which now appear directly after that.This makes the renderer think there are constraints on the SliceIntro, while there aren’t any.

**Comment by marcovisserFurore** [comment]
The example is not present anymore on Simplifier. @mmsmits can you provide the example here, so we can reproduce this bug?

**Comment by mmsmits** [comment]
I really can't think where this issue came from. We can close it for now, until we encounter it again.
