### ISSUE TITLE
Should we throw an error on slicing an element that does not repeat?

### ISSUE THREAD

**Issue by wardweistra** [FirelyTeam/firely-net-sdk#1400]
See https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Simplifier.20Profile.20Problem

Java stack will throw "Attempt to a slice an element that does not repeat" error, because "The profile does try to slice identifier, and it isn't something that can be sliced.".

cc @alexzautke

**Comment by ewoutkramer** [comment]
Note that repeating is not the only criterum - you can also slice by type if the element is a choice type.

**Comment by ewoutkramer** [comment]
I did discuss this with Michel before. One question would be: is this a validator thing or should this be caught by the snapshot generator?

**Comment by alexzautke** [comment]
Discussion on Zulip: https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Slicing.20non-repeating.20elements.20to.20define.20a.20choice
