### ISSUE TITLE
Unexpected behavior ResolveExternalReferences 

### ISSUE THREAD

**Issue by vpirojkov** [FirelyTeam/firely-net-sdk#1458]
There is test
`public void ResolveExternalReferences_Test()
        {
            var validator = new Validator(new ValidationSettings()
            {
                ResourceResolver = new ZipSource("specification.zip"),
                GenerateSnapshot = true,
                Trace = true,
                EnableXsdValidation = true,
                ResolveExternalReferences = false,
            });
            var observationDefinition = new ObservationDefinition
            {
                Code = new CodeableConcept("system", "code")
            };

            var customStructureDefinition = new StructureDefinition
            {
                FhirVersion = FHIRVersion.N0_4_0,
                Url = "http://medlinx.online/fhir/StructureDefinition/ObservationDefinition",
                BaseDefinition = "http://hl7.org/fhir/StructureDefinition/ObservationDefinition",
                Status = PublicationStatus.Active,
                Name = "ObservationDefinition",
                Kind = StructureDefinition.StructureDefinitionKind.Resource,
                Abstract = false,
                Derivation = StructureDefinition.TypeDerivationRule.Constraint,
                Mapping = new List<StructureDefinition.MappingComponent>
                {
                    new StructureDefinition.MappingComponent
                    {
                        Identity = "workflow",
                         Uri = "http://medlinx.online/fhir/workflow",
                         Name = "Workflow Pattern"
                    },
                    new StructureDefinition.MappingComponent
                    {
                        Identity = "rim",
                         Uri = "http://hl7.org/v3",
                         Name = "RIM Mapping"
                    }
                },
                Differential = new StructureDefinition.DifferentialComponent
                {
                    Element = new List<ElementDefinition>
                    {
                        new ElementDefinition
                        {
                            ElementId= "ObservationDefinition.meta",
                            Path = "ObservationDefinition.meta",
                            Min = 1
                        },
                        new ElementDefinition
                        {
                            ElementId= "ObservationDefinition.meta.tag",
                            Path = "ObservationDefinition.meta.tag",
                            Min = 1,
                            Max = "1"
                        },
                        new ElementDefinition
                        {
                            ElementId= "ObservationDefinition.meta.tag.system",
                            Path = "ObservationDefinition.meta.tag.system",
                            Min=1,
                            Fixed = new FhirUrl("https://medzoom.ru/project-tag")
                        },
                    }
                }
            };

            var result = validator.Validate(observationDefinition, customStructureDefinition); 

            Assert.IsFalse(result.Success);
            Assert.AreEqual(6, result.Issue.Count);// Unable to resolve reference to profile 'http://hl7.org/fhir/StructureDefinition/ObservationDefinition'
        }`
I expecting that base specification profile will be inherited and I will get issues for customStructureDefinition. But i getting always issue 'Unable to resolve reference to profile 'http://hl7.org/fhir/StructureDefinition/ObservationDefinition'. What I do incorrect?

**Comment by mmsmits** [comment]
Hi @vpirojkov,

If you change the base to 'http://hl7.org/fhir/StructureDefinition/Observation` instead of `'http://hl7.org/fhir/StructureDefinition/ObservationDefinition` you should get rid of this error. 

The base is the canonical URL of the resource your StructureDefinition builds upon. In this case the core Observation resource which has a canonical URL of `http://hl7.org/fhir/StructureDefinition/Observation`.

Let me know if this works for you.

**Comment by vpirojkov** [comment]
Hi @mmsmits,
I want to validate resource ObservationDefinition (variable observationDefinition  in my test). Validation should be dased on base specification + my custom definition (variable customStructureDefinition).

**Comment by mmsmits** [comment]
Yes, have you changed the `BaseDefinition` in the `customStructureDefinition` from `http://hl7.org/fhir/StructureDefinition/ObservationDefinition` to `http://hl7.org/fhir/StructureDefinition/Observation` ? 

The error that's thrown can't find `http://hl7.org/fhir/StructureDefinition/ObservationDefinition` because it doesn't exist. You must mean `http://hl7.org/fhir/StructureDefinition/Observation`

**Comment by vpirojkov** [comment]
I changed the BaseDefinition in the customStructureDefinition from http://hl7.org/fhir/StructureDefinition/ObservationDefinition to http://hl7.org/fhir/StructureDefinition/Observation. But described issue exists. Could you try run my test to see issue?

**Comment by ewoutkramer** [comment]
Hi @vpirojkov, I see that you are profiling an `ObservationDefinition`, so your original base was correct, but it seems you cannot resolve even the core resources, so the configuration of the resolver must be faulty. E.g. is `specification.zip` in the path? 

For a quick test, let's do this:

```
public void ResolveExternalReferences_Test()
{
   var rr = new ZipSource("specification.zip");
   Assert.IsNotNull(rr.FindStructureDefinitionForCoreType(FHIRAllTypes.ObservationDefinition));
}
```

**Comment by vpirojkov** [comment]
Hi @ewoutkramer, 
`public void ResolveExternalReferences_Test()
        {
            var exists = File.Exists("specification.zip");
            var z = new ZipSource("specification.zip");

            Assert.IsTrue(exists);
            Assert.IsNotNull(z.FindStructureDefinitionForCoreType(FHIRAllTypes.ObservationDefinition));
        }`
I updated your test. And this test is failed on secondary assert. That is, file specification.zip exist and there are not exceptions during running test. Folder C:\Users\Victor\AppData\Local\Temp\FhirArtifactCache-1.9.0-Hl7.Fhir.R4.Specification\specification is created, but it is empty. specification.zip file not unziped( Could you help to resolve this issue?

**Comment by brianpos** [comment]
Delete the temp folder you have there and the issue should resolve.
I'd suggest this can probably be closed now.
