### ISSUE TITLE
[FhirClient] Remove exception at a 404 Not Found

### ISSUE THREAD

**Issue by mmsmits** [FirelyTeam/firely-net-sdk#1460]
Is it really necessary to throw an exception at a 404 Not Found? 
Seems kind of overkill.

**Comment by marcovisserFurore** [comment]
The architecture at the moment is designed to return a Poco.  It would be a big change to the signature of the methods to return a result object containing the poco and statuscode.

**Comment by ewoutkramer** [comment]
Indeed, this has been the design for the past 10+ years, and the new refactored FhirClient still uses these principles.
