### ISSUE TITLE
Add slice by 'profile' discrimination functionality

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#1475]
As requested by @joelemaltais and @alexzautke  - I think we have not added slice by profile to the 1.x version of the API, but it might be in the new validator.  @marcovisserFurore might know more about this.

**Comment by alexzautke** [comment]
Trying to validate a slice by profile currently results in the error message "Internal logic failure: Cannot walk into unknown StructureDefinition with canonical '<canonical>' at '<discriminator path>'".

Example: https://simplifier.net/nngm-registrationformr4/composition-example/$validate

**Comment by ewoutkramer** [comment]
Right, that bug is well known, and is caused by Simplifier throwing away all snapshots before returning them to the snapshot generator.  The newer 1.9 version (not used by Simplifier) will give better error reports, and I thought Martijn was going to fix this problem in Simplifier. @mharthoorn - do you know anything about the status?

**Comment by marcovisserFurore** [comment]
I reproduced the issue by following these steps:
- download the package [basic DE profile](https://simplifier.net/basisprofil-de-r4/$download?format=xml&filter=Resource) from Simplifier
- download the package [nNGM - Registration Form (R4)](https://simplifier.net/nngm-registration-form/$download?format=xml&filter=Resource) from Simplifier
- create this unit test:

```c#
        public void ProfileTesting()
        {
            using var client = new FhirClient("https://fhir.simplifier.net/nngm-registration-form");

            var deProfilesZip = new ZipSource("basisprofil-de-r4.zip", new DirectorySourceSettings { IncludeSubDirectories = true });
            var profilesZip = new ZipSource(@"nngm-registration-form.zip", new DirectorySourceSettings { IncludeSubDirectories = true });
            var simplifierResolver = new WebResolver(id => client);
            var resolver = new CachedResolver(new SnapshotSource(
                    new MultiResolver(ZipSource.CreateValidationSource(), deProfilesZip, profilesZip, simplifierResolver)));
            var settings = new ValidationSettings
            {
                ResourceResolver = resolver
            };
            var validator = new Validator(settings);

            var instance = simplifierResolver.ResolveByCanonicalUri("https://fhir.simplifier.net/nngm-registration-form/Composition/9067051d-67e1-4662-acf1-a821768c077a");

            var result = validator.Validate(instance);

            Assert.True(result.Success);
        }
```

The validator reports an error about the profile discriminator path:
```
The discriminator path '$this.resolve()' at http://uk-koeln.de/fhir/StructureDefinition/Composition/nNGM/Antrag-pseudonymisiert#Composition.section.entry (Composition.section:basisangaben.entry:patientenMerkmale) leads to multiple ElementDefinitions, which is not allowed.
```

**Comment by wardweistra** [comment]
Debugged by Marco to actually be a Simplifier issue: https://firely.atlassian.net/browse/SIM-1430

**Comment by marcovisserFurore** [comment]
There were 2 problems here:
- there was an error in the profile
- and Simplifier did not load the extension Symbols

Therefor I close the issue here.
