### ISSUE TITLE
IFhirClient Implementation Using Injected HttpClient

### ISSUE THREAD

**Issue by tylerje** [FirelyTeam/firely-net-sdk#1483]
Is there any plan to get away from using HttpWebRequest in the client and allow an HttpClient instance to be injected that could come from an factory in similar fashion to this alternative from Microsoft https://github.com/microsoft/fhir-server/tree/master/src/Microsoft.Health.Fhir.Shared.Client in order to avoid socket starvation?

**Comment by ewoutkramer** [comment]
Yes, in fact the new 2.0 release (now in beta1) uses HttpClient (https://github.com/FirelyTeam/fhir-net-api/issues/480).

We don't have a constructor yet to inject your own - but now we've moved on to HttpClient, this seems rather doable.

**Comment by tylerje** [comment]
Excellent. Glad to hear it. Thanks for being so responsive.

**Comment by nitin2k20** [comment]
@ewoutkramer , do we know when this change will be GA?

**Comment by cakoops** [comment]
Is the beta avaiable as nuget package?

**Comment by brianpos** [comment]
@marcovisserFurore this one is now in 3.8.3 and 4.x if I'm not mistaken and therefore can be closed now?
