### ISSUE TITLE
FhirDateTime.ToDateTimeOffset() TimeSpan parameter should be optional

### ISSUE THREAD

**Issue by joellemm** [FirelyTeam/firely-net-sdk#1498]
`FhirDateTime.ToDateTimeOffset()` requires a `TimeSpan zone` parameter, but this parameter should be optional. The `zone` parameter is only used for a `dto.ToOffset()` call _after_ the actual conversion is completed. This is a .NET library method that just shifts the DateTimeOffset to the specified time zone. 

`zone` should not be required parameter because the user may want the converted `DateTimeOffset` to simply remain in the time zone it is already in. **In fact, requiring the zone parameter makes this method destructive**: We lose the information of what time zone this `FhirDateTime` was originally displayed in because we are required to specify a new zone which it will be offset to.

Here is the code for reference.

```
        public DateTimeOffset ToDateTimeOffset(TimeSpan zone)
        {
            if (this.Value == null) throw new InvalidOperationException("FhirDateTime's value is null");

            // ToDateTimeOffset() will convert partial date/times by filling out to midnight/january 1 UTC
            // When there's no timezone, the UTC is assumed
            var dto = PrimitiveTypeConverter.ConvertTo<DateTimeOffset>(this.Value);

            return dto.ToOffset(zone);
        }
```

I noticed this because I upgraded my project fhir-net-api dependency from 0.96.0 to 1.9.0, and this broke a test.

This is quite a simple change that should not affect any existing use cases. I've created a commit, and all tests still seem to be passing. I just don't appear to have permissions to create a pull request. **If you let me know what I have to do to get permission, I can submit the pull request.**

**Comment by joelmm** [comment]
@marcovisserFurore any update on this ticket?

Here is a unit test illustrating the problem:
```
[Test]
public void FhirDateTime_Conversion_TimeZoneInformationLoss()
{
  var fdt = new FhirDateTime(new DateTimeOffset(2021, 3, 18, 12, 22, 35, 999, new TimeSpan(-4, 0, 0)));

  Assert.AreEqual("2021-03-18T12:22:35.999-04:00", fdt.Value);

  var dto = fdt.ToDateTimeOffset();

  // Fails: Actual value is "2021-03-18T16:22:35.9990000+00:00"
  // The DateTimeOffset has been offset to UTC+0 instead of the original UTC-4
  Assert.AreEqual("2021-03-18T12:22:35.9990000-04:00", dto.ToString("o"));

  // We have lost the information of what timezone the original FhirDateTime was in
}
```
As shown, the current approach of forcing `.ToDateTimeOffset` to provide a `TimeSpan` parameter **is causing information loss**. Specifically we lose the information of what timezone the original FhirDateTime was in. This is a problem for my project -- we require DateTimeOffsets to be displayed in the original time zone they were set in.

The workaround would have to be manually extracting the time zone from `fdt.Value` using our own string parser so we can then pass the correct `TimeSpan` into `.ToDateTimeOffset`, essentially passing that information in twice since it is already present in the `FhirDateTime`. This workaround is pretty clunky, and it would be far more straightforward to fix the unnecessarily destructive `.ToDateTimeOffset` method.

I believe the change required is very simple (note: only the parameter and return line have changed):
```
public DateTimeOffset ToDateTimeOffset(TimeSpan zone = null)
{
    if (this.Value == null) throw new InvalidOperationException("FhirDateTime's value is null");

    // ToDateTimeOffset() will convert partial date/times by filling out to midnight/january 1 UTC
    // When there's no timezone, *keep the existing timezone*
    var dto = PrimitiveTypeConverter.ConvertTo<DateTimeOffset>(this.Value);

    return zone == null? dto : dto.ToOffset(zone);
}
```

**Comment by joelmm** [comment]
Here's another workaround I found after looking at the above a bit more: `PrimitiveTypeConverter.ConvertTo<DateTimeOffset>(fdt.Value)`

In the test above, this looks like:
```
[Test]
public void FhirDateTime_Conversion_TimeZoneInformationLoss()
{
  var fdt = new FhirDateTime(new DateTimeOffset(2021, 3, 18, 12, 22, 35, 999, new TimeSpan(-4, 0, 0)));

  Assert.AreEqual("2021-03-18T12:22:35.999-04:00", fdt.Value);

  var dto1 = PrimitiveTypeConverter.ConvertTo<DateTimeOffset>(fdt.Value);
  var dto2 = fdt.ToDateTimeOffset();

  // Passes:
  Assert.AreEqual("2021-03-18T12:22:35.9990000-04:00", dto1.ToString("o"));

  // Fails: Actual value is "2021-03-18T16:22:35.9990000+00:00"
  // The DateTimeOffset has been offset to UTC+0 instead of the original UTC-4
  Assert.AreEqual("2021-03-18T12:22:35.9990000-04:00", dto2.ToString("o"));

  // We have lost the information of what timezone the original FhirDateTime was in
}
```

IMO this just further emphasizes the usefulness of my suggested fix above. The `PrimitiveTypeConverter` being used in `FhirDateTime.ToDateTimeOffset` is _already_ preserving the time zone information, as desired. Then the final line of `.ToDateTimeOffset` undoes that by unnecessarily calling `.ToOffset`.

**Comment by marcovisserFurore** [comment]
Hi @joelmm, thanks for the illuminating unit tests. Our March 2021 sprint is already full, but I put this on the April 2021 release.

**Comment by mmsmits** [comment]
@joellemm as of the release this morning,  we implemented a new function ```TryToDateTimeOffset```, which returns a boolean if a FhirDateTime can be converted to a DateTimeOffset, and an ```out``` parameter that returns the corresponding DateTimeOffset
