### ISSUE TITLE
ZipSource multi-thread issue

### ISSUE THREAD

**Issue by Gjoll** [FirelyTeam/firely-net-sdk#1502]
When ZipSource is created, it expands its source to a set of files under a temp directory defined at line #227, file ZipSource.cs
_return $"FhirArtifactCache-{versionInfo.InformationalVersion}-{productInfo.Product}";_

It appears that ZipSource only writes this data once, and checks to see if the data is there and is current before overwriting it.

If ZipSource is called from multiple async routines, there can be multiple threads expanding data to this directory at the same time, each of whom thinks that the data needs to be expanded. Randomly an error occurs where one thread tries to write a file that another thread has already started writing and a collision occurs.

This problem occurs in my code when SnapshotGenerator.UpdateAsync() is called multiple times ('cause its asynchronous...). SnapshotGenerator is created with a ZipSource that may need to be expanded.

The problem can be recreated by calling SnapshotGenerator.UpdateAsync() multiple times from an asynchronous routine so that there are multiple tasks executing UpdateAsync at the same time.

If my guess at to what is occurring is correct, then my suggested fix is a lock that stops more than one thread from expanding the ZipSource files at a time. i.e. each Task would have a lock around the code that determines if the source needs to be expanded, and only the first one Task would perform the expansion and would only exit the lock after the expansion was complete. Subsequent threads would see that the data was there and current so no further expansion necessary.

**Comment by Gjoll** [comment]
Sorry, forgot to put this original message.
Problem is occurring with nuget package
HL7.Fhir.Specification.R$ v 2.0.0-beta1

**Comment by ewoutkramer** [comment]
> If my guess at to what is occurring is correct, then my suggested fix is a lock that stops more than one thread from expanding the ZipSource files at a time. i.e. each Task would have a lock around the code that determines if the source needs to be expanded, and only the first one Task would perform the expansion and would only exit the lock after the expansion was complete. Subsequent threads would see that the data was there and current so no further expansion necessary.

Well, I fully agreed with your assessment, only to find that we already made that part thread-safe.  It's not completely safe however, if multiple *processes* try to unpack at the same time (really hard to do with a non-transactional file system).

Anyway, I think you must have found something new - assuming this problem occurs with a single process, but multiple threads. 

For now, can you check whether calling `ZipSource.Prepare()` explicitly when you initialize the ZipSource (and before the potential thread issue can arise) helps?  This should give you control over exactly when the ZipSource expands the file....

**Comment by marcovisserFurore** [comment]
The following unit test proves the issue:

```c#
        [TestMethod]
        public void Issue_1502()
        {
            static async void action()  
            {
                var zip = new ZipSource("specification.zip", new DirectorySourceSettings() { IncludeSubDirectories = true });
                await zip.ResolveByCanonicalUriAsync(ModelInfo.CanonicalUriForFhirCoreType(FHIRAllTypes.Patient));
            }

            Task[] taskArray = new Task[10];
            for (int i = 0; i < taskArray.Length; i++)
            {
                taskArray[i] =  new Task(action);
            }

            Parallel.ForEach<Task>(taskArray, (t) => { t.Start(); });
            Task.WaitAll(taskArray);

        }
```

**Comment by marcovisserFurore** [comment]
And an even more simpler unittest, which does not use SDK functionality:

```c#
        [TestMethod]
        public void SimpleZipExtractTest()
        {
            string extractDirectory = Path.Combine(Path.GetTempPath(), "Fhir_specification_test");

            Task[] taskArray = new Task[10];
            for (int i = 0; i < taskArray.Length; i++)
            {
                taskArray[i] = new Task(() => ZipFile.ExtractToDirectory("specification.zip", extractDirectory));
            }

            try
            {
                Parallel.ForEach<Task>(taskArray, (t) => { t.Start(); });
                Task.WaitAll(taskArray);

            }
            catch (Exception ex)
            {
                Assert.Fail(ex.Message + " " + ex.StackTrace);
            }
        }
```

**Comment by marcovisserFurore** [comment]
To solve this we need to implement a systemwide Mutex which can easily lead to deadlocks and it also needs to be implemented on different types of operating systems like Windows or Linux.

Therefor, we do not solve this issue.

An alternative is to place the Zipsource out of the threads and use the method `Prepare`. Then you could use the ZipSource in a multithreaded way:

```c#
        public void Issue_1502_alternative()
        {
            var zip = new ZipSource("specification.zip", new DirectorySourceSettings() { IncludeSubDirectories = true });
            zip.Prepare();

            async void action()
            {

                await zip.ResolveByCanonicalUriAsync(ModelInfo.CanonicalUriForFhirCoreType(FHIRAllTypes.Patient));
            }

            Task[] taskArray = new System.Threading.Tasks.Task[10];
            for (int i = 0; i < taskArray.Length; i++)
            {
                taskArray[i] = new Task(action);
            }

            Parallel.ForEach<Task>(taskArray, (t) => { t.Start(); });
            Task.WaitAll(taskArray);

        }
```
