### ISSUE TITLE
Performance issues in Xamarin

### ISSUE THREAD

**Issue by elvenprogrammer** [FirelyTeam/firely-net-sdk#1511]
Hi everyone, we're having big performance issues when using the FHIR library in Xamarin.
The first call is going to take up to 20 seconds on an android emulated device.
We tracked that down to be related to reflection being slower in Xamarin and widely used across fhir-net-api (that also forced us to use the intepreter on iOS because of emit).

The part I'm referring to is:

`mapping = ClassMapping.Create(type);`

Being called over 1000 times because of

`
            IEnumerable<Type> exportedTypes = assembly.ExportedTypes;
            foreach (Type type in exportedTypes)
`

Can you provide suggestions on how to improve?

BR

**Comment by ewoutkramer** [comment]
Accidentally, I have tried to improve the performance of the reflection in 2.0-beta2.  Can you please try this version and see whether that actually helps you?

**Comment by elvenprogrammer** [comment]
Actually way better, any plan to get rid of Emit also to increase iOS compatibility?

**Comment by marcovisserFurore** [comment]
This is solved in version 4.0 which will be released in the near future.

**Comment by brianpos** [comment]
The Emit was also resolved in 3.7.0 if I remember rightly (incase others come back and discover this)
