### ISSUE TITLE
Add documentation on how to use FHIRPath in the API

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#1515]

**Comment by MyEidos** [comment]
By the way, is it possible to use version agnostic FHIRPath?
Ex:  `.Select(...)`
I guess that not, but anyway.

**Comment by ewoutkramer** [comment]
See https://docs.fire.ly/projects/Firely-NET-SDK/fhirpath.html

**Comment by ewoutkramer** [comment]
> By the way, is it possible to use version agnostic FHIRPath? Ex: `.Select(...)` I guess that not, but anyway.

Never to late to react ;-)   Yes, it's completely move to Base/Conformance in SDK5.  Also, you can run it on ITypedElement, so it is even possible to run on data that has no POCO equivalent....
