### ISSUE TITLE
SearchParams allows "-" as a sort parameter with no name

### ISSUE THREAD

**Issue by cunninghamjc** [FirelyTeam/firely-net-sdk#1531]
**Describe the bug**
SearchParams allows "-" as a sort parameter with no name, e.g. "_sort=status,-"

**To Reproduce**
```C#
var q = new SearchParams();
q.Add("_sort", "-")
```

**Expected behavior**
FormatException with an appropriate error message.

**Screenshots**
N/A

**Version used:**
 - FHIR Version: STU3
 - Version: 1.9.0

**Additional context**
N/A

**Comment by marcovisserFurore** [comment]
This extra check can be add in the next release
