### ISSUE TITLE
Object reference not set to an instance of an object when using resolve() function with US Core Provenance profile

### ISSUE THREAD

**Issue by darena-mhaque** [FirelyTeam/firely-net-sdk#1532]
**Describe the bug**
When validating a bundle that contains a provenance resource that conforms to the US Core Provenance profile, one of the invariants fails from an object reference not set to an instance of an object exception.

**To Reproduce**
Here's some sample code:
```csharp
[TestMethod]
public void TestResolve()
{
    ElementNavFhirExtensions.PrepareFhirSymbolTableFunctions();

    var basePath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
    var path = Path.Combine(basePath, "specification.zip");
    var resourceResolver = new CachedResolver(new MultiResolver(
        new DirectorySource(Path.Combine(basePath, "Profiles")), // Add the US Core Provenance profile here. I placed it in a "Profiles" directory
        new ZipSource(path)));
    var resourceValidator = new Validator(new ValidationSettings { ResourceResolver = resourceResolver });

    var bundle = new Bundle
    {
        Type = Bundle.BundleType.Collection,
        Entry = new List<Bundle.EntryComponent>
        {
            new Bundle.EntryComponent
            {
                FullUrl = "urn:uuid:123456",
                Resource = new Practitioner
                {
                    Id = "123456"
                }
            },
            new Bundle.EntryComponent
            {
                FullUrl = $"urn:uuid:555",
                Resource = new Provenance
                {
                    Id = "555",
                    Meta = new Meta
                    {
                        Profile = new List<string> { "http://hl7.org/fhir/us/core/StructureDefinition/us-core-provenance" }
                    },
                    Target = new List<ResourceReference>
                    {
                        new ResourceReference("example")
                    },
                    Recorded = DateTimeOffset.UtcNow,
                    Agent = new List<Provenance.AgentComponent>
                    {
                        new Provenance.AgentComponent
                        {
                            Who = new ResourceReference("urn:uuid:123456"),
                            OnBehalfOf = new ResourceReference("example")
                        }
                    }
                }
            }
        }
    };

    var oo = resourceValidator.Validate(bundle); // resourceValidator.Validate(new ScopedNode(bundle.ToTypedElement())) also fails BTW
    var errors = oo.Issue.Where(x => x.Severity == OperationOutcome.IssueSeverity.Error);
    Assert.IsFalse(errors.Any());
}
```
If I go into debug mode, I can see that one of the invariants failed:

![image](https://user-images.githubusercontent.com/45796503/98030965-cd0c9b00-1ddf-11eb-9d56-eeeef9ecef44.png)

I suspect this has something to do with the error above it:
`Code="BusinessRule" Details.Text="Evaluation of FhirPath for constraint 'provenance-1' failed: Invocation of 'binary.implies' failed: Invocation of 'binary.or' failed: Invocation of 'binary.is' failed: Invocation of 'resolve' failed: Object reference not set to an instance of an object."`

Notice the "Object reference not set to an instance of an object" error.

**Expected behavior**
I expect that the validation passes since the FHIR path of the US Core Provenance profile seems correct and the provenance resource should be able to resolve Provenance.agent.who. However, it seems like somewhere in the middle it fails.

**Version used:**
 - FHIR Version: R4
 - Version: 1.9.0

**Additional context**
Attached is the US Core Provenance Profile:

[StructureDefinition-us-core-provenance.txt](https://github.com/FirelyTeam/fhir-net-api/files/5483619/StructureDefinition-us-core-provenance.txt)

**Comment by marcovisserFurore** [comment]
Hi @darena-mhaque ,

Thanks again for your issue. This issue is not related to #1525.

The problem lies in the FhirPath invariant `provenance-1`. That is defined as follow:
```
(($this.agent.who.resolve() is Practitioner) or ($this.agent.who.resolve() is Device)) implies exists()
```
the keyword `$this` is used in iterating over collections, for example `generalPractitioner.all($this is Practitioner)` where `$this` refers to the items of the collection `generalPractitioner`. 
In the case of `Provenance` there is no collection, so `$this` is not populated. You could say it can be populated to the item which is under evaluation. In this case that would be `onBehalfOf `, then again it would fail, because `onBehalfOf.agent.who` is not a valid path. 

What would work is using the buildin variable `%resource` instead:
 ```
((%resource.agent.who.resolve() is Practitioner) or (%resource.agent.who.resolve() is Device)) implies exists()
```

So I am afraid the profile _US Core Provenance_ is not correct on this point.

**Comment by darena-mhaque** [comment]
Thanks for the quick reply. I think I can agree with this, but can you clarify this one confusion that I have?

In fhir path, I thought when operating on some logic, it is always operated on a collection, even if that collection has just one value, the result of which is also a collection. So using that if you start out with the provenance resource as one item in the input collection, and then use the `$this` keyword, it would just resolve to that one provenance resource in the input collection. I am probably incorrect in understanding this but would like a little clarification if possible.

**Comment by marcovisserFurore** [comment]
You are right about FhirPath is working on collections. But the focus is here on `onBehalfOf`. The constraint (invariant) `provenance-1` is defined on the element `Provenance.onBehalfOf` and not on `Provenance`. So `$this` is set to `Provenance.onBehalfOf`. So the whole path would be: `Provenance.onBehalfOf.agent.who.resolve()` which does not exist: `agent` is not a child of `Provenance.onBehalfOf`.

I am still investigating why there is a null pointer exception at `resolve`. That could be better.

**Comment by darena-mhaque** [comment]
Ah, that makes sense. I'll have to report this back to the publishers of US Core. I'll go ahead and close this issue since my original issue is not a bug in this library.

**Comment by marcovisserFurore** [comment]
We will investigate the null pointer exception at `resolve`.
