### ISSUE TITLE
Support for JSON Patch (in addition to FHIRPath Patch in v2.0-beta2)

### ISSUE THREAD

**Issue by marnilss** [FirelyTeam/firely-net-sdk#1533]
**Is your feature request related to a problem? Please describe.**
We are trying to integrate with Cerners Millenium system using FHIR. Most have worked successfully, but we've hit a roadblock with updates using patches, even though we tried using v2.0-beta 2.. It's because their system only supports JSON Patches, and NOT FHIRPath Patches which have been implemented in v2.0.

**Describe the solution you'd like**
I would like built-in support for applying patches using plain JSON patch syntax, in addition to the FHIRPath patch support.

**Describe alternatives you've considered**

**Additional context**

**Comment by alexhawdon** [comment]
A consumer of the NHS Digital's [Personal Demographics Service FHIR API](https://digital.nhs.uk/developer/api-catalogue/personal-demographics-service-fhir) has also come up against this issue when attempting to integrate using Firely. At present our API also only supports JSON Patch and not FHIRPath Patches.

**Comment by marcovisserFurore** [comment]
To build the FHIR patch operation is still on our list. And it will move up the list if there is more demand for it 😄 . We had a PR for this operation last year, but it was not up to our standards.

**Comment by Kasdejong** [comment]
closed by #2753
