### ISSUE TITLE
.NET 5 - gRPC

### ISSUE THREAD

**Issue by ivanfarkas2** [FirelyTeam/firely-net-sdk#1549]
- Are there any .NET 5, C# 9 optimized packages with the source?
- Is gRPC supported?

**Comment by ewoutkramer** [comment]
Hi Ivan, you mean - things link probuf annotations/definitions for use with gRPC?

**Comment by ewoutkramer** [comment]
We usually switch to the newest C# dialect pretty quickly - but that's just the syntax, there's no specific functionality. So we're not using C# 8's default interface implementations for example or anything that would require a newer runtime.  I know using the .NET 5 json serializer is on your wishlist and that is something we could look at.

**Comment by ivanfarkas2** [comment]
> 
> 
> Hi Ivan, you mean - things link probuf annotations/definitions for use with gRPC?

Hi Ewout. Yes.
It would be an good feature to add.
The binary contract would increase performance and more resource friendly.

_"**[protobuf-net.Grpc](https://github.com/protobuf-net/protobuf-net.Grpc#protobuf-netgrpc)** adds code-first support for services over gRPC using either the native Grpc.Core API, or the fully-managed Grpc.Net.Client / Grpc.AspNetCore.Server API."_

**Comment by ivanfarkas2** [comment]
Why don't you just start a new .NET 5 branch and do a complete redesign for the forward thinking crowd, please?

**Comment by BradBarnich** [comment]
> gRPC would be my protocol of choice

but then it wouldn't be FHIR, it would be something else. This is a FHIR library and FHIR has a defined protocol: http://hl7.org/fhir/http.html

> Why don't you just start a new .NET 5 branch and do a complete redesign for the forward thinking crowd, please?

I hope this was a joke...

**Comment by ivanfarkas2** [comment]
I have the best intentions! This is a VERY constructive suggestion and NOT a criticism.
I'll ask you again in November 2021 when .NET 6 is released.
Perhaps than we can snap out of the **[Time Warp](https://idioms.thefreedictionary.com/stuck+in+a+time+warp)**. ;-)

**Comment by brianpos** [comment]
.net6 is now one of the native targets of the framework, and the new json serializer is implemented too.
Wondering if we need to keep this item as open (as don't know that we're planning on doing a gPRC implementation?)

**Comment by ewoutkramer** [comment]
> .net6 is now one of the native targets of the framework, and the new json serializer is implemented too. Wondering if we need to keep this item as open (as don't know that we're planning on doing a gPRC implementation?)

Yes, indeed. We now have a native S.T.J. implementation AND natively support .NET6.  We have no intention to do the work to provide gRPC out of the box. Maybe if someone came to us and volunteered.

So, yeah, let's close this.
