### ISSUE TITLE
Some references are empty in the Snapshots. 

### ISSUE THREAD

**Issue by MatthijsvdWielen** [FirelyTeam/firely-net-sdk#1550]
On Simplifier some references in the Snapshot are now empty. See for example: https://simplifier.net/nictizstu3-zib2017/nictiz.ihe.mhd.minimal.documentreference
In the code this looks like this: 
```
 <element id="DocumentReference.authenticator">
      <path value="DocumentReference.authenticator" />
      <short value="Who/what authenticated the document" />
      <definition value="Which person or organization authenticates that this document is valid." />
      <comment value="Contained resource" />
      <min value="0" />
      <max value="1" />
      <base>
        <path value="DocumentReference.authenticator" />
        <min value="0" />
        <max value="1" />
      </base>
      <type>
        <code value="Reference" />
        <aggregation value="contained" />
      </type>
```

Could have to do with the profile is setting aggregation constrains in the type and this is not correctly picked up in the snapshot
```
<type>
                <code value="Reference" />
                <aggregation value="contained" />
            </type>
```

**Comment by marcovisserFurore** [comment]
@MatthijsvdWielen : is this still an issue?

**Comment by MatthijsvdWielen** [comment]
@marcovisserFurore , good question. 

Looking at the profile https://simplifier.net/NictizSTU3-Zib2017/IHE.MHD.Minimal.DocumentReference/~xml .
I do not see the target profile specified in the differential for the elements DocumentReference.authenticator and DocumentReference.context.sourcePatientInfo. 

These also do not have a target profile in the snapshot. Is this the intended behavior?

**Comment by mmsmits** [comment]
This is expected behaviour, if you want to make constraints in a type you also have to copy the TargetProfiles list.
Otherwise, the snapshot generator thinks you want to make the constraint of not allowing certain types (or all types).
The only solution to that is always repeat the targetProfile list when contraining an element type.
