### ISSUE TITLE
IFhirClient is no longer present in latest version 2.0, so mocking the FhirClient is not possible.

### ISSUE THREAD

**Issue by zuekut** [FirelyTeam/firely-net-sdk#1551]
**Describe the bug**
I've just upgraded my project to the latest version - 2.0 and I've noticed that the IFhirClient was removed, therefore I am unable to mock the FhirClient for my unit tests. Has it been moved somewhere or was it completely removed, since I am not seeing this noted in the breaking changes? If it has been removed, what would be the alternative so that I can mock it? Thanks in advance!

**Expected behavior**
An interface of the FhirClient is available so that it can be mocked in unit tests.

**Version used:**
 - FHIR Version:  STU3
 - Version: 2.0.0

**Comment by brianpos** [comment]
I think you'd now be providing your own handler underneath it to the constructor of the new client class - haven't tried it myself yet though

**Comment by zuekut** [comment]
Thanks @brianpos , that works out quite well with mocking the HttpMessageHandler and passing it to FhirClient. For anyone facing the same problem, the mocked handler would look something like this, with [Moq extension](https://github.com/maxkagamine/Moq.Contrib.HttpClient):
`  _mockedHttpClientHandler.SetupAnyRequest().ReturnsResponse(HttpStatusCode.Created, message =>
            {
                message.RequestMessage = new HttpRequestMessage(HttpMethod.Put, "http://test");
                message.Content = new StringContent(patientResource.ToJson(), Encoding.UTF8, "application/json");
            });
`

**Comment by brianpos** [comment]
@zuekut great to hear, and now you moq test code is closer to the real thing too.

**Comment by zuekut** [comment]
@brianpos , absolutely, great change overall having the possibility to provide our own HttpClientHandler to the FhirClient!
