### ISSUE TITLE
ResourceType is obsolete and no longer supported on asp.net model binding

### ISSUE THREAD

**Issue by darena-mhaque** [FirelyTeam/firely-net-sdk#1552]
**Describe the bug**
It seems that asp.net does some model binding processing during an endpoint call. Somehow the resource type property is accessed, which is now obsolete and an exception is thrown if accessed. This is occurring on a bare new project example using .net5.

**To Reproduce**
1. Create a new asp.net project using .net 5.0
2. Create a model that accepts a bundle
3. Add a newtonsoft json converter so that the request can be properly mapped to the bundle type
4. Add a controller that accepts this new model
5. Call the controller endpoint using postman with a bundle in the request
6. Exception should be displayed

These steps are mostly general and a little hard to describe in words. I have attached a zip file that includes a bare minimum project to display the error.

**Expected behavior**
Library should work seamlessly with asp.net model binding and exception should not be thrown

**Screenshots**
![image](https://user-images.githubusercontent.com/45796503/99715903-6fca4800-2a75-11eb-8458-5bb333701b0d.png)

**Version used:**
 - FHIR Version: R4
 - Version: 2.0.0

**Additional context**
[ExceptionTest.zip](https://github.com/FirelyTeam/firely-net-sdk/files/5569299/ExceptionTest.zip)

**Comment by whyfate** [comment]
I also meet the same problem。

**Comment by marcovisserFurore** [comment]
Hi @darena-mhaque. Thanks for your well-documented issue. 

The attribute `resourceType` in the `Bundle` informs our `FhirJsonParser` which resource type this. The attribute was in the previous versions also not mapped to the Poco.  This behavior is also explained in this article: http://hl7.org/fhir/json.html#resources

When you break on the method `FhirResourceJsonConverter.ReadJson` you will see that the FhirJsonParser parses the Bundle correctly and you will get a `Bundle` object. But then the binding process tries again to bind to Bundle, which indeeds fails, because there is no counterpart for `resourceType`.

Perhaps you can tell the `FhirResourceJsonConverter` to skip this Json-attribute in the binding process? Because the attribute is only a marker for the parser. It has nothing to do with the Resource itself. For example xml does not have this attribute, because the name of the element determines the resource type:

```xml
<Bundle xmlns="http://hl7.org/fhir">
  <id value="bundle-example"/> 
  <!--    this example bundle is a search set    -->
  <meta> 
    <lastUpdated value="2014-08-18T01:43:30Z"/> 
    <!--    when the search was executed    --> 
  </meta>  
  <type value="searchset"/>
  <entry> 
    <fullUrl value="https://example.com/base/MedicationRequest/3123"/> 
    <!--    the matching resource    -->
    <resource> 
      <MedicationRequest> 
        <id value="3123"/> 
      </MedicationRequest>
    </resource>
  </entry>
</Bundle>   
```

**Comment by brianpos** [comment]
I think what you're missing is this...
(assuming you've already got your own formatter classes in place)
// options.ModelBinderProviders.Insert(0, new CustomFhirResourceModelBinderProvider());
                // The Resource.ResourceType property fails validation 
                // (and we don't need to do it anyway as we have custom formatters that do it)
                options.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(Resource)));

**Comment by darena-mhaque** [comment]
@marcovisserFurore Hmm, do you know how to skip that property in the binding process? I'm not sure of any way to do that in asp.net binding. I understand that resource type is no longer being used and is irrelevant in the new v2 library. But I'm not sure how to tell asp.net to ignore this property.

@brianpos Adding the following line has worked!
```csharp
services.AddControllers(options => options.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(Resource))));
```

This no longer produces the exception. Is this the official suggestion to go with when trying to use asp.net model binding?

**Comment by darena-mhaque** [comment]
It seems like the `ResourceType` property immediately throwing an exception whenever accessed is causing a lot of headache. I ran into another issue where we use reflection in our program and this property is accessed via reflection. Of course, there aren't any "obsolete" warnings that will pop up here. There may be other areas of the .net framework where reflection might be used to iterate over all properties.

I think this property should have been removed entirely instead of keeping it and throwing an exception whenever the getter is accessed. This can cause silent and unexpected exceptions in a lot of areas, especially the framework itself like asp.net which uses reflection in many areas (my original issue). I am hoping this is removed entirely in the very next minor or patch release.

**Comment by zuekut** [comment]
I am facing a similar issue when decorating a Resource property with JsonConverter, which does the same thing that the  FhirResourceJsonConverter.cs does of @darena-mhaque  :
```csharp
 [JsonConverter(typeof(FhirResourceDataConverter))]
 public Resource Data { get; set; }
```
When I try to deserialize the object which has this property, I get the following exception:
```
System.TypeLoadException
Could not load type 'Hl7.Fhir.Model.Resource' from assembly 'Hl7.Fhir.STU3.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, RuntimeType type, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at System.Reflection.RuntimePropertyInfo.GetCustomAttributes(Type attributeType, Boolean inherit)
   at System.Attribute.InternalGetCustomAttributes(PropertyInfo element, Type type, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
```
The same piece of code worked fine in version 1.9.0.0.

**Comment by whyfate** [comment]
> I think what you're missing is this...
> (assuming you've already got your own formatter classes in place)
> 
> ```
> // options.ModelBinderProviders.Insert(0, new CustomFhirResourceModelBinderProvider());
> // The Resource.ResourceType property fails validation 
> // (and we don't need to do it anyway as we have custom formatters that do it)
> options.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(Resource)));
> ```
> 
> You might also consider using XML/Json formatters like ones from this project:
> https://github.com/brianpos/fhir-net-web-api/tree/develop-r4/src/Hl7.Fhir.WebApi.AspNetCore

However, after `SuppressChildValidationMetadataProvider` is used, all the validation attribute will be invalid，Which i don't think is best way.

**Comment by Hightower1992** [comment]
Im having the same Issue of an obsolete ResourceType by sending any Resource over http.
I followed the official Documentation without any further Information about this.

What  i did:

1. Create new asp.net-core api project with targetFramework net5.0
2. Add HL7.Fhir.R4 Nuget Package
3. Create Controller with a GET Method that returns a Patient Object (with all attributes from the current Fhirly documentation)
![image](https://user-images.githubusercontent.com/32928105/99939668-e2377280-2d6a-11eb-8f54-156744234eff.png)

4. Make a Request with Swagger => leads to obsoletion error
![image](https://user-images.githubusercontent.com/32928105/99939477-6ccba200-2d6a-11eb-8567-118ecba3aad4.png)

I made an approach, where i use the Json Serializer and serialized the object to a string and then returned it, which worked in this case, but it seems a bit strange to me in the end.
Sadly the approach of `SuppressChildValidationMetadataProvider` doenst work for me here.

Version used:
dotnet 5.0 sdk
FHIR Version: R4
Version: 2.0.0

I hope you can help me out there.

**Comment by brianpos** [comment]
Using the fhir WebApi project above that I referenced implements all the parts of the controller, including the xml/json and prefer headers etc.
And when you're using your own custom formatter (which handles the accept or _format parameters) there is no need for a validator, as the formatter does that. 
And then you use the fhir validator for profile compliance where needed. 
Doing your own controller is going to mean more work for yourself. 
Take a look at how much is in our controller. 
https://github.com/brianpos/fhir-net-web-api/blob/develop-r4/src/Hl7.Fhir.WebApi.AspNetCore/FhirController.cs

**Comment by marcovisserFurore** [comment]
Because of some reactions we've received on this issue, we have decided to bring out an hotfix. We see that is quite annoying to have this property raising an exception when you try accessing it. So we will remove the property `ResourceType` entirely. There are some workarounds for it, like the  `SuppressChildValidationMetadataProvider` which was mentioned by @brianpos, but like @darena-mhaque  said, it give headaches on other areas.

So except to receive an hotfix soon (version 2.0.1) this week. Perhaps tomorrow.

**Comment by marcovisserFurore** [comment]
We have created a hotfix for this issue today:
- https://github.com/FirelyTeam/firely-net-sdk/releases/tag/v2.0.1-stu3
- https://github.com/FirelyTeam/firely-net-sdk/releases/tag/v2.0.1-r4
- https://github.com/FirelyTeam/firely-net-sdk/releases/tag/v2.0.1-r5

The property `ResourceType` of `Resource` has been removed entirely. The `NotSupportedException` gave too much trouble.

The NuGet packages are uploaded as well.
