### ISSUE TITLE
Add support for using multiple FHIR versions in one project

### ISSUE THREAD

**Issue by StefRoo** [FirelyTeam/firely-net-sdk#1553]
An issue we had while developing software to create FHIR resources was that using both the STU3 and the R4 versions of the FHIR library is not possible, as the resources contained in those libraries share both a classname and a namespace. Therefore, when trying to use a resource class, it leads to a compile time error. Is there a way to develop the R5 library to ensure that the resource classes don't fall into the same namespace (Hl7.Fhir/Model)? That way, it won't be necessary to create a different API when wanting to serve R5 resources.

**Comment by marcovisserFurore** [comment]
Hi @StefRoo,

Thanks for your question.  Coincidentally, I am working on a blog that explains how to work with 2 or more different FHIR versions in one C # project. The blog will be published at the end of the week, but I can give you a preview of that.

The solution lies in creating aliases for the different projects. See the inclusion of the different Firely .NET SDK packages in the project file here:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hl7.Fhir.STU3" Version="2.0.0" />
    <PackageReference Include="Hl7.Fhir.R4" Version="2.0.0" />
    <PackageReference Include="Hl7.Fhir.Support.Poco" Version="2.0.0" />
    <PackageReference Include="Hl7.Fhir.Serialization" Version="2.0.0" />
  </ItemGroup>

  <Target Name="AddPackageAliases" BeforeTargets="ResolveReferences" Outputs="%(PackageReference.Identity)">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)'=='Hl7.Fhir.STU3.Core'">
        <Aliases>stu3</Aliases>
      </ReferencePath>
      <ReferencePath Condition="'%(FileName)'=='Hl7.Fhir.R4.Core'">
        <Aliases>r4</Aliases>
      </ReferencePath>
    </ItemGroup>
  </Target>

</Project>
```

I created here an alias for the STU3 (named `stu3`) and for the R4 (named `r4`).

To use the `Patient` for STU3 and the `Patient` for R4 in the same c# unit file, you must use the aliases we previously defined:

```c#
extern alias r4;
extern alias stu3;

namespace MultipleVersions
{
   // code here
}
```

Declaring the `extern alias` introduces an additional root-level namespace to the global namespace. So in your code you can this to expend the namespace, for example like this for a R4 Patient:
```c#
    var patient = new  r4::Hl7.Fhir.Model.Patient();
```

When do not want to fully express the namespace everytime (who does btw?), you can use an alias in the using part:
```C#
   using R4 = r4::Hl7.Fhir.Model;

  /*  Inside class: */

   var patient = new R4.Patient():
```

So all together it looks like this:

```c#

using Hl7.Fhir.Model;
using System;
using R4 = r4::Hl7.Fhir.Model;
using Stu3 = stu3::Hl7.Fhir.Model;

namespace MultipleVersions
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            var code = new Code();

            var patient1 = new Stu3.Patient();

            var patient2 = new R4.Patient();

        }
    }
}
```

I hope this answers your question. Feel free to contact as again whenever you need assistance with this SDK.

**Comment by brianpos** [comment]
Have a look at this too
https://github.com/NuGet/Home/issues/4989#issuecomment-711882957

**Comment by IanYates** [comment]
Out of curiosity, could this approach also be used to use v2 of the library to include an R4 client in an app, and also v1 of the library to include a DSTU2 client in the same app?

**Comment by brianpos** [comment]
I expect so.

**Comment by marcovisserFurore** [comment]
No that will not work, because you cannot differentiate on the common packages, like `Hl7.Fhir.Serialization`. The Fhir specific packages uses the same common packages. 
So, DSTU2 v1.9 uses `Hl7.Fhir.Serialization` v1.9, and R4 v2.0 uses `Hl7.Fhir.Serialization` v2.0. In the method, described above, we differentiate on package ids. But that would not be possible with the common packages, because they have the same id.

**Comment by ewoutkramer** [comment]
@marcovisserFurore - I think we publish a completely separate set for DSTU2 now, so you don't even need the `external alias` to make this work?

**Comment by marcovisserFurore** [comment]
> @marcovisserFurore - I think we publish a completely separate set for DSTU2 now, so you don't even need the `external alias` to make this work?

I am still waiting for the tests in Simplifier. When that works, I will publish this special set of DSTU2.

**Comment by marcovisserFurore** [comment]
see also #1657

**Comment by marcovisserFurore** [comment]
See documentation here: https://docs.fire.ly/projects/Firely-NET-SDK/model/multiple-fhir-versions.html

**Comment by OlivierTD** [comment]
> No that will not work, because you cannot differentiate on the common packages, like `Hl7.Fhir.Serialization`. The Fhir specific packages uses the same common packages.
> So, DSTU2 v1.9 uses `Hl7.Fhir.Serialization` v1.9, and R4 v2.0 uses `Hl7.Fhir.Serialization` v2.0. In the method, described above, we differentiate on package ids. But that would not be possible with the common packages, because they have the same id.

Any update on this? We tried using DSTU2 v1.9 and R4 v3.4 in our project by using the alias approach but we're getting problems with the sub dependencies clashing.

**Comment by ewoutkramer** [comment]
> I am still waiting for the tests in Simplifier. When that works, I will publish this special set of DSTU2.

"waiting for Simplifier" is probably going to take a while.  Is there a way for @OlivierTD to test it?

**Comment by OlivierTD** [comment]
For what it's worth, when I try to initialize a Bundle object I get this error:

> Message: 
>     System.TypeInitializationException : The type initializer for 'Hl7.Fhir.Model.ModelInfo' threw an exception.
>     ---- System.TypeLoadException : Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.4.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.

Here are the two packages:
![image](https://user-images.githubusercontent.com/16864936/126355201-341c2a91-5e7e-4881-9a95-aba39454396d.png)

and here is my .csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hl7.Fhir.DSTU2" Version="1.9.0" />
    <PackageReference Include="Hl7.Fhir.R4" Version="3.4.0" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.17.0" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="3.1.16" />
  </ItemGroup>

  <Target Name="AddPackageAliases" BeforeTargets="ResolveReferences" Outputs="%(PackageReference.Identity)">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)'=='Hl7.Fhir.DSTU2.Core'">
        <Aliases>dstu2</Aliases>
      </ReferencePath>
    </ItemGroup>
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)'=='Hl7.Fhir.R4.Core'">
        <Aliases>r4</Aliases>
      </ReferencePath>     
    </ItemGroup>
  </Target>
</Project>
```

**Comment by marcovisserFurore** [comment]
The packages DSTU2 (1.9.0) and R4 (3.4.0) are not working together in 1 project. For example DSTU2 needs package `Hl7.Fhir.Support` version 1.9.0, while package R4 3.4.0 needs the same package but then version 3.4.0. Two versions of the same package are not allowed in one project, so the latest version will be used (3.4.0) which is not compatible with DSTU2 1.9.0.

To overcome this, we are experimenting with a special (onetime) release of DSTU2 (version 1.9.1) which uses its own packages. So DSTU2 1.9.1 will use the package `Hl7.Fhir.DSTU2.Support` instead of `Hl7.Fhir.Support`. In this case DSTU2 and R4 can exist together in 1 project. 
Be aware: this special version will released once, and will the endpoint of DSTU2.

See here the alpha version of DSTU2 1.9.1: https://www.myget.org/feed/fhir-net-api/package/nuget/Hl7.Fhir.DSTU2/1.9.1-alpha-20201201-1

**Comment by OlivierTD** [comment]
I tried adding the alpha version to my project from the .csproj but it looks like my solution has trouble finding the package.

```
  <ItemGroup>
    <PackageReference Include="Hl7.Fhir.R4" Version="3.4.0" />
    <PackageReference Include="Hl7.Fhir.DSTU2" Version="1.9.1-alpha-20201201-1" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.17.0" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="3.1.16" />
  </ItemGroup>
```

![image](https://user-images.githubusercontent.com/16864936/126498169-9d362c31-21ef-4f8d-8e39-8f09a61c1263.png)

Do I have to add anything in my Nuget package feed to get access to the alpha version?

**Comment by marcovisserFurore** [comment]
Because these DSTU2 packages are not on NuGet, you should configure the channel in the NuGet.Config:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <packageSources>
    <add key="MyGet - Firely Net SDK" value="https://www.myget.org/F/fhir-net-api/api/v3/index.json" />
  </packageSources>
  <disabledPackageSources>
  </disabledPackageSources>
</configuration>
```
Normally the `NuGet.Config` is located at:
- Windows:  `%appdata%\NuGet\NuGet.Config`
- Mac/Linux: ~/.config/NuGet/NuGet.Config or ~/.nuget/NuGet/NuGet.Config (varies by OS distribution)

For more information about NuGet.config see [here](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file).

**Comment by isaac-stovall** [comment]
Hello, The alpha version described above has worked perfectly for us.  We had the exact same issue.  

Is there an estimated date when this will move into a release?

Thanks.

**Comment by marcovisserFurore** [comment]
Hi @isaac-stovall , good to hear that it works for you. Always nice to hear feedback. At the end of this summer we can release this final version on NuGet. Be aware that this would be the final version of DSTU2: we do not maintain DSTU2 anymore.

**Comment by isaac-stovall** [comment]
Hi, @marcovisserFurore.  Has there been any update on moving the alpha 1.9.1 to a final version on NuGet?
Thanks.

**Comment by marcovisserFurore** [comment]
Hi @isaac-stovall,

At the moment we are testing this version in our products. At first site, it looks great. I wait till the final results and then I will publish this on NuGet. Probably at the beginning of October. Most likely next week.

**Comment by brianpos** [comment]
Will this just be a DSTU2 package deploy?

**Comment by marcovisserFurore** [comment]
Yes, it would be only a special deploy for DSTU2.
