### ISSUE TITLE
Missing IFhirClient interface for FhirClient in version +2.x

### ISSUE THREAD

**Issue by ncoussemacq** [FirelyTeam/firely-net-sdk#1564]
I'm upgrading my reference to HL7.FHIR.R4 from version 1.9.4 to 2.0.1 and I'm facing an issue with my existing codebase.
The legacy version of FhirClient is inheriting an IFhirClient interface , which was making it very easy to mock in unit tests. The new version doesn't have the same kind of interface which makes my existing tests impossible to update.

Do you have any plan to restore this in upcoming releases ?

**Comment by marcovisserFurore** [comment]
Hi @ncoussemacq, thanks for your issue.

We are not bringing back the `IFhirClient` interface, but you can use the `FhirClient` in your unit tests by mocking the `HttpMessageHandler` . See [here](https://github.com/FirelyTeam/firely-net-sdk/issues/1551#issuecomment-731614271) an example for doing this.

**Comment by ncoussemacq** [comment]
Hi @marcovisserFurore and thanks for this quick reply.

Thanks for this linked issue (I should have searched in closed issues before posting) . I now understand how to workaround the lack of IFhirClient. I agree that it's a possible solution for mocking but I'm not 100% convinced that it's the most efficient way to simulate the behavior of that new FhirClient in Unit tests. Using HttpClientHandler to mock FhirClient requires to know implementation details of FhirClient, which is not the case when an interface is available.
Any strong reason to remove the interface ?

Anyway, thanks again for the support !

**Comment by mmsmits** [comment]
Hi @RodrigoTHD, 
We aren't going to reintroduce `IFhirClient` solely for mocking purposes.
Reintroducing `IFhirClient` requires more maintenance on our side for something that doesn't add a lot of value.

To test your client you can mock the `HttpMessageHandler`, just like you would for Microsoft's `HttpClient`.

See [here](https://github.com/FirelyTeam/firely-net-sdk/issues/1551#issuecomment-731614271) an example for doing this.

**Comment by RodrigoTHD** [comment]
Hi @mmsmits, thanks for the reply.

I had checked the mock before.

I'll probably add a FhirClient adapter with an interface to easily mock.
