### ISSUE TITLE
Failed to use the "partial" attribute of Hl7.Fhir.Model namespace

### ISSUE THREAD

**Issue by themnexurst** [FirelyTeam/firely-net-sdk#1577]
:information_source: Do you want to ask something or start a discussion, then go [here](https://github.com/FirelyTeam/firely-net-sdk/discussions)

**Describe the bug**
According to the beginners guide on your supported website (https://docs.fire.ly/firelynetsdk/model/classes.html) the differnt models for HL7 FHIR resources consist of partial classes to add changes in implementing projects. This is not possible because the SDK package represents a compiled assembly, and therefore all partial calsses inside are compiled to complete classes (with no option to add additional code in other partial classes). I could confirm this behavior in my own project.

**To Reproduce**
1. All changes are made in one file.
2. Using Hl7.Fhir.Model namespace
3. Write own partial class (here: 'Patient') in a personal project in the namespace Hl7.Fhir.Model
4. Try to implement the class Patient anywhere else in the project (using Hl7.Fhir.Model)
5. See warning that the compiler will use only one of the classes named Patient, while two are found in the project (one in the SDK and one in your custom file)

**Expected behavior**
I ask you to update the mentioned website, to stop spreading misinformation about this behavior. If possible, find a way to support adding custom code to the classes in Hl7.Fhir.Model namespace. 

**Version used:**
 - FHIR Version: R4
 - Version: 2.1.0

**Comment by brianpos** [comment]
You are correct, they are partial to permit the code generated portion and the manually created parts of the classes within the assembly itself, not for partial outside the library.

**Comment by ewoutkramer** [comment]
Fixed, thanks for reporting this.
