### ISSUE TITLE
Cannot cast a string representing a dateTime to a date in FHIRPath

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-net-sdk#1579]
**Describe the bug**
The "toDate()" FHIRPath functions returns null when trying to convert a string representing a dateTime. Given that calling toDate on a dateTime works be truncating the date, I would have expected that this same trick could be applied when trying to cast a string with a dateTime in it to a date.

**To Reproduce**
See unit test ConvertStringWithDateTimeToDate in ConversionsTests (branch: bugfix/cast-string-datetime-to-date)

**Expected behavior**
The TryConvertToDate method in String.cs should also check if the string represents a dateTime and then truncate the dateTime to a date.

**Version used:**
 - FHIR Version: STU3
 - Version: 2.0.1

**Comment by marcovisserFurore** [comment]
According to the [standard](http://hl7.org/fhirpath/#todate-date) of FhirPath this correct behavior:

> If the item is a String, but the string is not convertible to a Date (using the format YYYY-MM-DD), the result is empty.

Your string is not convertible to a Date (because of the time part) using the format YYYY-MM-DD.

**Comment by alexzautke** [comment]
My argument is just that we could generate a string in the format YYYY-MM-DD if we wanted. Makes it easier, because you don't need to create a dateTime first and then cast that to a date.

**Comment by marcovisserFurore** [comment]
@alexzautke, do you think this is still a bug? I think the SDK is doing what the standard prescribes.

**Comment by brianpos** [comment]
I'd say it's doing what the spec dictates, if you know the content is like that, take the substring(0,10) first.

**Comment by marcovisserFurore** [comment]
I close this issue, because the SDK is following the FhirPath specification
