### ISSUE TITLE
Exception thrown parsing Encounter resource

### ISSUE THREAD

**Issue by solventusllc** [FirelyTeam/firely-net-sdk#1586]
The Fhirly.NET (HL7.Fhir.STU3 v2.0.1) parser appears to be throwing an exception on well-formatted Encounter resources when the encounter resource has a reasonCode element, even with permissive settings on the parser. The exception message received is : 

_Type checking the data: Encountered unknown element 'reasonCode' at location 'Encounter.reasonCode[0]' while parsing_

The FHIR Server used in testing is http://wildfhir4.aegis.net/fhir4-0-0/. The error will not occur for encounter resources on this server that do not have a reasonCode element. The reason code element looks like this for affected resources:

```
<reasonCode>
    <coding>
      <system value="http://snomed.info/sct"/>
      <code value="34068001"/>
      <display value="Heart valve replacement"/>
    </coding>
  </reasonCode>
```

### Steps to reproduce the behavior:

The following code will reproduce the behavior, throwing an exception on the last line.

            var parserSettings = new ParserSettings
            {
                AcceptUnknownMembers=true,
                PermissiveParsing = true,
                AllowUnrecognizedEnums=true
                
            };
            var settings = new FhirClientSettings
            {
                ParserSettings=parserSettings
            };
            FhirClient = new FhirClient("http://wildfhir4.aegis.net/fhir4-0-0/",settings);            
            var enc=FhirClient.Read<Encounter>($"Encounter/f003");
            

### Expected behavior:

I would expect the resource to be successfully parsed, complete with the reason information.

**Comment by mbaltus** [comment]
The server you use is a FHIR R4 server, so if you parse the data with the STU3 library, you will run into problems.
The reasonCode field was not present in the STU3 Encounter resource, which is causing the error.
Either change the library you use to Hl7.Fhir.R4 or change the server to an STU3 server, and the error should disappear.

**Comment by solventusllc** [comment]
Thanks very much, mbaltus. I can confirm moving to Hl7.Fhir.R4 did fix the problem. I suspected it was a versioning issue, but couldn't find a package named Hl7.Fhir.STU4 and didn't know to look specifically for Hl7.Fhir.R4. I suggest making the association between FHIR versions and package names more explicit in the "What's in the box?" section of the project description.

I also wonder if there may still be a bug or two associated with this issue. I had the VerifyFhirVersion FHIR client setting set to true in my code, and this didn't appear to catch the versioning issue. I also had the AcceptUnknownMembers parser setting set to true, which I expected would have resulted in gracefully ignoring the reason code element if there was no backing for it. Should I submit these separately as possible bugs?

**Comment by ewoutkramer** [comment]
Hi @solventusllc  - The release is officially called R4 by HL7 (and not STU4), that's why you cannot find a reference to "STU4" anywhere.  That "What's in the Box" section does mention R4 multiple times, including a link to the NuGet packages, so I don't really see what we can additionally do here.

I thinnk you are right that AcceptUnknownMembers should have avoided this error, as would VerifyFhirVersion.  Let's re-open this issue to see what's going on.

**Comment by marcovisserFurore** [comment]
Indeed the `VerifyFhirVersion` setting is not working as the following unit test shows:

```c#
       [TestMethod]
        public async System.Threading.Tasks.Task VerifyFhirVersionTest()
        {
            var mock = new Mock<HttpMessageHandler>();
            var response = new HttpResponseMessage
            {
                StatusCode = HttpStatusCode.OK,
                Content = new StringContent(@"{""resourceType"": ""CapabilityStatement"",  ""id"": ""example:"", ""fhirVersion"": ""4.0.1""}", Encoding.UTF8, "application/json"),
                RequestMessage = new HttpRequestMessage(HttpMethod.Get, "http://example.com"),
            };

            mock
               .Protected()
                   .Setup<Task<HttpResponseMessage>>(
                      "SendAsync",
                      ItExpr.IsAny<HttpRequestMessage>(),
                      ItExpr.IsAny<CancellationToken>())
                   .ReturnsAsync(response);


            using var client = new FhirClient("http://example.com", new FhirClientSettings { VerifyFhirVersion = true }, mock.Object);

            try
            {
                await client.ReadAsync<Patient>("Patient/1");
            }
            catch (NotSupportedException ex)
            {
                Assert.Fail($"Expected no exception, but got: {ex.Message}");
            }
        }
```

A quick look at the code shows that the `verifyFhirVersion` checks the property `Version` of the `CapabilityStatement` instead of the `fhirVersion`
