### ISSUE TITLE
R4 Immunization resource Getting "Element with min. cardinality 1 cannot be null"

### ISSUE THREAD

**Issue by Malleshreddyaitha** [FirelyTeam/firely-net-sdk#1588]
Hi Everyone,

I'm getting issue at POST method.
I'm passing proper json from Post man but it getting "Element with min. cardinality 1 cannot be null"

Please help me.

Thank you. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

{
    "resourceType": "Immunization",
    "status": "completed",
    "vaccineCode": {
        "coding": [
            {
                "system": "urn:oid:1.2.36.1.2001.1005.17",
                "code": "FLUVAX"
            }
        ],
        "text": "Fluvax (Influenza)"
    },
    "patient": {
        "reference": "Patient/9a0e363f-ed3a-4a3e-9cda-32807dc600a6"
    },
    "encounter": {
        "reference": "Encounter/example"
    },
    "occurrenceString": "hkl",
    "primarySource": true,
    "location": {
        "reference": "Location/1"
    },
    "manufacturer": {
        "reference": "Organization/hl7"
    },
    "lotNumber": "AAJN11K",
    "expirationDate": "2015-02-15",
    "site": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/v3-ActSite",
                "code": "LA",
                "display": "left arm"
            }
        ]
    },
    "route": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/v3-RouteOfAdministration",
                "code": "IM",
                "display": "Injection, intramuscular"
            }
        ]
    },
    "doseQuantity": {
        "value": 5,
        "system": "http://unitsofmeasure.org",
        "code": "mg"
    }
    
}

Error:
"errors": {
        "Occurrence": [
            "Element with min. cardinality 1 cannot be null"
        ],
        "StatusElement": [
            "Element with min. cardinality 1 cannot be null"
        ]
    },
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "|1f342d87-45bc85ecc35178a9."
}

**Version used:**
 - FHIR Version: [R4,]
 - Version: [ 2.0.1]

**Comment by mbaltus** [comment]
Hi! This question does not seem to relate to the Firely SDK.
The error comes from the server you are posting the data to. It seems to think the data is missing some elements. You will need to contact the server administrators to investigate why the error occurs.
