### ISSUE TITLE
Increase of resources in dataelements.xml in specification.zip R4

### ISSUE THREAD

**Issue by cknaap** [FirelyTeam/firely-net-sdk#1589]
**Describe the bug**
I discovered an unexpected difference in the specification.zip for R4 between API 1.9 and SDK 2.0. dataelements.xml went up from 318 StructureDefinitions to 6781 (!). Since we load all of this into the administration database that is not very practical. Is there an explanation for this? R3 and R5 don't have that many.

**To Reproduce**
1. Restore nuget package Hl7.Fhir.R4
2. Go to the package directory, find the specification.zip file.
3. Unzip it and open the file dataelements.xml therein.
4. It contains 6781 StructureDefinition resources.
5. Compare this to:
6. - R4 zip in API  1.9: 318 resources
7. - R3 and R5 zips in 2.0: around 300 - 400 resources.

**Expected behavior**
Since SDK 2.0 handles the same FHIR version (4.0.1) I expected the same number of StructureDefinition resources as in API 1.9.

**Screenshots**
n/a

**Version used:**
 - FHIR Version: R4
 - Version: 2.0.1

**Additional context**
-

**Comment by marcovisserFurore** [comment]
The file `dataelements.xml` is downloaded from hl7.org/fhir and is indeed much larger than the STU3 or R5 variant. I mentioned [this](https://chat.fhir.org/#narrow/stream/179177-conformance/topic/de-Quantity.2Ecomparator.20in.20dataelements.2Exml/near/185106847)  a year ago in chat.fhir,org

In the previous versions (<= 1.9) I manually deleted the extra elements in this file before adding it to the specification.zip. 

My questions is: do we need these profiles at all in the specification.zip? I rather skip this file then manually delete entries (extra work, which can also be forgotten, which happened here).

**Comment by marcovisserFurore** [comment]
Discussed in the standup today:
- dataelements.xml will be removed from the specification.zip for STU3, R4 and R5

@cknaap : do you foresee any problems in Vonk when we do this?

**Comment by cknaap** [comment]
@marcovisserFurore : No. We'll add an instruction for users to load them themselves if needed.

**Comment by marcovisserFurore** [comment]
Okay, we will remove the dataelements.xml from the specification.zip then. Do to this, we have to follow these steps:
- remove dataelements.xml from the script `build/DownloadFhirBuildProfile.ps1`
- run the script `build/DownloadFhirBuildProfile.ps1` to see if everything works okay
- Run the tool `fhir-codegen`, to see if that is still working
- Run all unit tests and repair them when they are broken
