### ISSUE TITLE
FhirClient socket exhaustion handling

### ISSUE THREAD

**Issue by vukispasic** [FirelyTeam/firely-net-sdk#1591]
Hello. I noticed that FhirClient doesn't use IHttpMessageHandlerFactory or IHttpClientFactory to get instance of httpclient or httpmessagehandler that is recyclable (https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)
This could lead to socket exhaustion problem in extreme cases as described in article above. Did you use another approach to solve socket exhaustion problem? I know there is possibility to provide instance of message handler to FhirClient constructor which can be resolved using IHttpMessageHandlerFactory , but I would like to confirm if there is some internal solution you implemented to socket problematics

**Comment by brianpos** [comment]
Which version of the fhir client are you using here?
The new version 2 package(s) cover this capability (was quite the breaking change)

**Comment by vukispasic** [comment]
Hello. I am using version 2.0.1 of hl7.fhir.r4 package. I didn't experience socket exhaustion problem with library, but I am building Azure function which will use this fhir client and by examining source code I didn't notice this problematics is handled. Since you say this library should covers the problematics, can you give me example of correct usage of fhir client that will not lead to socket exhaustion? In my case scenario there are numerous instances of azure function using fhir client.

**Comment by brianpos** [comment]
You should use the constructor here with the message handler that you create as your needs dictate.
Then the fhir client isn't creating any of that functionality.

https://github.com/FirelyTeam/firely-net-sdk/blob/074c2486dde0ca643a1e7cc2a5a98cc1c59194e3/src/Hl7.Fhir.Core/Rest/FhirClient.cs#L36

**Comment by vukispasic** [comment]
Yes, this is exast same way I handled it. I am resolving message handler from IHttpMessageHandlerFactory aqnd using it in FhirClient constructor
