### ISSUE TITLE
Mention package IDs in documentation

### ISSUE THREAD

**Issue by vadi2** [FirelyTeam/firely-net-sdk#1592]
:information_source: Do you want to ask something or start a discussion, then go [here](https://github.com/FirelyTeam/firely-net-sdk/discussions)

**Is your feature request related to a problem? Please describe.**
If one is using Visual Studio Code or any other non-VS editor, #include statements are not automatically generated - meaning when a new class is introduced, you have to do some digging to find the right includes yourself.

**Describe the solution you'd like**
Mention the package ids in documentation when relevant classes are mentioned.

**Additional context**
Better user experience outside of the Visual Studio bubble.

**Comment by mmsmits** [comment]
Thanks for pointing us to this.
We now have a better package structure, so this should be less of a problem, also, VS Code has been improved to make this easier for users as well.
