### ISSUE TITLE
Cannot select quantities with different units within a single FHIRPath select

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-net-sdk#1605]
**Describe the bug**
Executing a FHIRPath select statement on an Observation resource containing a quantity in Observation.valueQuantity and Observation.component.valueQuantity with different units results in the following exception:

System.NotSupportedException: Comparing quantities with different units is not yet supported

These values can be selected for example by the following FHIRPath statement: "(Observation.value as Quantity) | (Observation.component.value as Quantity)". This selection is for example done in the SearchParameter "combo-value-quantity" defined on Observation.

The stack trace indicates that some part of the FHIRPath stack is triggering an equal comparison by adding the second value to the result set. 

**To Reproduce**
See unit test "TestSelectDifferentQuantities" in Hl7.FhirPath.R4.Tests.FhirPathTest (Branch: fix/1605-quantity-different-units)

**Expected behavior**
A result set containing both quantities.

**Version used:**
 - FHIR Version: [R4]
 - Version: [2.0.2]

**Comment by marcovisserFurore** [comment]
Solved in hotfix 2.0.3
