### ISSUE TITLE
Can't bundle / connect resources to the patient resource

### ISSUE THREAD

**Issue by xtianus79** [FirelyTeam/firely-net-sdk#1610]
**Describe the bug**
This issue is related to the bug here but it is more than just a visual studio debugging error. https://github.com/FirelyTeam/firely-net-sdk/issues/1601 

,,,
var client = new FhirClient(configuration["resource"]);
                var patientId = reqdata.patientid;
                FhirToken fhToken = new FhirToken(configuration);
                var bearerToken = fhToken.GetBearerToken();
                client.OnBeforeRequest += (object sender, BeforeRequestEventArgs e) =>
                {
                    e.RawRequest.Headers.Add("Authorization", string.Format("Bearer {0}", bearerToken));
                };
 ,,,
 
New updated client creation code as below which you can find in feature/FHIR2 branch.
,,, 
FhirToken fhToken = new FhirToken(configuration);
                var bearerToken = fhToken.GetBearerToken();
                var messageHandler = new HttpClientEventHandler();
                messageHandler.OnBeforeRequest += (object sender, BeforeHttpRequestEventArgs e) =>
                {
                    e.RawRequest.Headers
                    .Add("Authorization", $"Bearer {bearerToken}");
                };
 
                Hl7.Fhir.Rest.FhirClient client = new Hl7.Fhir.Rest.FhirClient(configuration["resource"], messageHandler: messageHandler, settings: new FhirClientSettings()
                {
                    PreferredFormat = ResourceFormat.Json
                });
 ,,,
Now there is a failure in creating a reference between patient resource and any other resource like (diagnosisreport/Obervance/Vitals etc..) with an error
Identity=error CS0103: The name 'ResourceIdentity' does not exist in the current context
 
,var diagnosereport = new DiagnosticReport();,
                     
,diagnosereport.Subject = new ResourceReference(string.Format("Patient/{0}", fhirPatientId));,

**To Reproduce**
When adding a resource to the patient resource. 

**Expected behavior**
A resource connected to the patient id will be bundled together without issue. 

**Version used:**
2.0.3

This broke when changing to version 1.9 to 2.0.1 and 2.0.3

**Comment by mmsmits** [comment]
Hi @xtianus79,
I can't seem to reproduce this issue here. 
Assigning a resource references to DiagnosticReport.subject works fine here:

```
var id = "example-id";
var diagnosticreport = new DiagnosticReport();
diagnosticreport.Subject = new ResourceReference(string.Format("Patient/{0}", id ));

```

Your error indicates that you miss a "using" of the namespace of ResourceIdentity, which is in Hl7.Fhir.Rest.
If this doesn't solve anything, can you provide us with a small piece of code , preferably a unit test, that reproduces this?

**Comment by JasonSowers** [comment]
We are seeing the same issue, I will post details when I get back to working on this.

**Comment by marcovisserFurore** [comment]
@JasonSowers, can you provide some details about your findings? Otherwise I will close this issue.

**Comment by JasonSowers** [comment]
I honestly never got heck to that project. No harm in closing it to me.
