### ISSUE TITLE
Move some Poco's to Common

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/firely-net-sdk#1612]
The following Resources can be moved to the project Common:
- Parameters
- ResourceIdentifier
- Valueset (needs discussion because it is not Normative)

This will also mean a change in the codegen.

**Comment by brianpos** [comment]
I'm not convinced that normative resources should be going into common, I think we still need to discuss/consider this one further, as for older versions, these are not valid content, and may induce more confusion.
Needs more thought...

**Comment by brianpos** [comment]
Maybe the creation of an `Interface` for the normative resources could be considered instead?

**Comment by ewoutkramer** [comment]
I fully agree we should be careful moving all resources to common.  However, there are a few that are incredibly costly to *not* have in common - like Parameters and OperationOutcome. Small (necessarily compatible) changes to these resources will at most introduce a new property or enum into a previous version of the library (OperationOutcome IssueType.Multiplematches being a good example), but the disadvantages of such a change in this case by far outweigh the advantages of having these very commonly used classes in common!

**Comment by ewoutkramer** [comment]
ValueSet is more impactful. We are looking at having a cross-version terminology service and expansion generator. It would also be very useful if the new ITerminologyService interface would be applicable to all FHIR releases of the SDK. I am looking at the impact of moving ValueSet right now....

**Comment by marcovisserFurore** [comment]
@ewoutkramer : when you are working on this issue (and so also the code-gen) can you also remove the following warnings in the generated code?

```
Model\Resource.cs(43,9): warning CS1587: XML comment is not placed on a valid language element [D:\a\1\s\common\src\Hl7.Fhir.Support.Poco\Hl7.Fhir.Support.Poco.csproj]
Model\Resource.cs(43,9): warning CS1587: XML comment is not placed on a valid language element [D:\a\1\s\common\src\Hl7.Fhir.Support.Poco\Hl7.Fhir.Support.Poco.csproj]
Model\Resource.cs(43,9): warning CS1587: XML comment is not placed on a valid language element [D:\a\1\s\common\src\Hl7.Fhir.Support.Poco\Hl7.Fhir.Support.Poco.csproj]
```
