### ISSUE TITLE
[SnapshotGenerator] Reconsider how we are dealing with `contentReference`

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#1617]
In this discussion on Zulip: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Clarification.20on.20contentReference, Chris Moesel poses some fundamental questions on how constraints on an element are carried over if that element is referred to by another element using the `contentReference`.

Currently - in our implementation - we copy the constraints of the referring element over the original definition of the referred element *in the base definition*, so not on top of constraints that may be present in a profile on the referred element. (See https://github.com/FirelyTeam/firely-net-sdk/blob/228690e8d1a3833b7afc4e729c1b47c08335055a/src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs#L530 and https://github.com/FirelyTeam/firely-net-sdk/blob/228690e8d1a3833b7afc4e729c1b47c08335055a/src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs#L1840).

Still, this is not always desirable (Chris mentions the ValueSet.compose.include and ValueSet.compose.exclude), and elements like `description` that probably could definitely be different.

For now, it is not clear what is the "right" answer, and Chris has just decided to copy over extensions (see Zulip discussion). 

I am not asking for any action right now - we'll be asked by one of our customers in due time, but when that time comes, it's good to have these references and context available.

**Comment by mmsmits** [comment]
We are still waiting on people complaining. We are closing this for now.
