### ISSUE TITLE
Using a Firely Server container for testing the integration tests

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/firely-net-sdk#1618]
**Is your feature request related to a problem? Please describe.**
The unit tests with category `IntegrationTest` and `FhirClient` do not run in Azure Pipelines, because it needs an external Fhir Server, which is not always available. A lot of our users of the SDK uses the `FhirClient` and so this part of functionality should be part of our test suite. Not only executed manually only so now and then.

**Describe the solution you'd like**
In the Test phase of Azure Pipelines we can spin up a Firely Server docker container which can serve as a Fhir Server for the unit tests.

**Describe alternatives you've considered**
An alternatives can be to introduce Mocks for the FhirClient, like we did in this unit test: https://github.com/FirelyTeam/firely-net-sdk/blob/develop-stu3/src/Hl7.Fhir.Core.Tests/Rest/FhirClientMockTests.cs

**Comment by brianpos** [comment]
I'd almost suggest to use the HAPI command line version, so that it's being tested with a server not based on the. Net fhir client. Don't know what its storage layer requirements need though.

**Comment by marcovisserFurore** [comment]
Good idea @brianpos . We can also do both in Azure Pipelines.

**Comment by mmsmits** [comment]
This was a very good idea before we had rewritten the FHIR Client, and didn't have an extensive set of Mock tests
