### ISSUE TITLE
[FhirPath] Add `memberOf()` function.

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#1630]
**Is your feature request related to a problem? Please describe.**
The us core profiles (e.g. http://hl7.org/fhir/us/core/StructureDefinition/us-core-condition) contain invariants using the `memberOf()` function (an extension on the standard FhirPath functions, see here https://hl7.org/fhir/fhirpath.html#functions), 

**Describe the solution you'd like**
We should implement these additional functions, as much as possible, to make sure the .NET library is useable with these profiles.

**Comment by ewoutkramer** [comment]
We have a "we don't support this function" quickfix now as a PR: https://github.com/FirelyTeam/firely-net-common/pull/105

**Comment by marcovisserFurore** [comment]
Discussed in the standup today:
- The `EvaluationContext` of FhirPath should be extended with a `ITerminologyService`. 
- The function `memberOf()` should then take the valueset (argument of memberOf) and check whether the input is a valid code in the valueset (`ITerminologyService.ValueSetValidateCode()`) or not.

**Comment by marcovisserFurore** [comment]
See also #2404

**Comment by marcovisserFurore** [comment]
Resolved by PR https://github.com/FirelyTeam/firely-net-sdk/pull/2450
