### ISSUE TITLE
AzureFHIR-R4 with CosmosDB: Batch bundle Retry mechanism

### ISSUE THREAD

**Issue by Yuva-ACS** [FirelyTeam/firely-net-sdk#1636]
Based on the document (https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir-features-supported) the Azure-CosmosDB doesn't support transactions operations. So I was trying to achieve the same with a batch operation. But was unable to implement the retry mechanism perfectly as the request and response objects of the bundle are not linked.

Nuget - Hl7.Fhir.R4 by Ewout Kramer (ewout@fire.ly) - 1.9.0
Azure Fhir
	Version - R4
	DB - CosmosDB	
VS 2019
.Net Core - 3.1

**Comment by brendankowitz** [comment]
> Request and response objects of the bundle are not linked.

These should align to the same index requestBundle[0] should have responseBundle[0]

**Comment by Yuva-ACS** [comment]
If you don't mind, Can you provide me a reference link?
In the official HL7 [documentation](http://hl7.org/fhir/http.html#brules) - I understood that it will not process in the same order provided.
![image](https://user-images.githubusercontent.com/79512018/109460967-81b18300-7a87-11eb-94bf-2d6348715fc0.png)

**Comment by brendankowitz** [comment]
It is true that a server should follow these rules when processing the entries in the bundle internally. However, if you are looking at it from a client point of view, further down on that same page (http://hl7.org/fhir/http.html#transaction-response):

> The response the server SHALL return a Bundle with type set to batch-response or transaction-response that contains one entry for each entry in the request, in the same order.

I think it is implied that after receiving the bundle, servers process in the order as linked above, then reassembly the response to align with the original request.

**Comment by Yuva-ACS** [comment]
Thanks for the clarification and sorry for that, I missed seeing the response description.
