### ISSUE TITLE
[Snapgen] Implement applying constraints coming from an element, not a whole StructDef

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#1645]
**Is your feature request related to a problem? Please describe.**
A few years ago we designed a feature to re-use constraints applied to an element within a profile, instead of having to use the whole profile (remember: ElementDef.typeRef.profile normally refers to a whole profile, not a single element within that profile).

This feature can also be used elegantly to apply constraints to Questionnaire.item(.item.item.item.item....).

**Describe the solution you'd like**
We should implement this feature in the snapshot generator.  More details can be found here: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Clarification.20on.20contentReference

**Describe alternatives you've considered**
There was no alternative, this was a complex and long discussion within the FHIR-I community. I think this is as clean as it is going to get.  Moreover, it seems Grahame has already implemented it.

**Additional context**
See here for the definition of the extension: http://hl7.org/fhir/R4/extension-elementdefinition-profile-element.html

**Comment by mmsmits** [comment]
This was a pilot idea by Grahame and Ewout, but it didn't fly.
