### ISSUE TITLE
FHIRPath: 'anything'.endsWith(id) always evaluates to True 

### ISSUE THREAD

**Issue by wardweistra** [FirelyTeam/firely-net-sdk#1652]
**Describe the bug**
 'anything'.endsWith(id) always evaluates to True in SDK 2.0.2

**To Reproduce**
```
Using Firely Terminal:
PS C:\Users\Ward\Documents\FHIR-workspace\R4\temp> fhir --version
Firely Terminal 2.1.0-beta8
FHIR 4.0.1
HL7.FHIR SDK 2.0.2

PS C:\Users\Ward\Documents\FHIR-workspace\R4\temp> fhir push .\ACMEbasePatient.StructureDefinition.xml
Pushed 1 resource(s) on the stack.

PS C:\Users\Ward\Documents\FHIR-workspace\R4\temp> fhir select "id"
acme-base-patient

PS C:\Users\Ward\Documents\FHIR-workspace\R4\temp> fhir select "url"
https://fake-acme.org/fhir/StructureDefinition/ACME-base-patient

PS C:\Users\Ward\Documents\FHIR-workspace\R4\temp> fhir predicate "url.endsWith(id)"
True

PS C:\Users\Ward\Documents\FHIR-workspace\R4\temp> fhir predicate "url.endsWith('banana')"
False

PS C:\Users\Ward\Documents\FHIR-workspace\R4\temp> fhir predicate "url.endsWith(id.toString())"
True
```

**Expected behavior**
```
PS C:\Users\Ward\Documents\FHIR-workspace\R4\temp> fhir predicate "url.endsWith(id)"
False

PS C:\Users\Ward\Documents\FHIR-workspace\R4\temp> fhir predicate "url.endsWith(id.toString())"
False
```

**Version used:**
 - FHIR Version: R4
 - Version: 2.0.2

**Additional context**
See the Slack conversation with Ewout here: https://firelyteam.slack.com/archives/CJDSRK06P/p1614813383000500

**Comment by mmsmits** [comment]
The problem with this issue is that the FhirPathEngine walked into the first context (url) when using the endsWith() function. This created the scenario where it the following statement is evaluated: ```StructureDefinition.url.endsWith('StructureDefinition.url.id')```  instead of ```StructureDefinition.url.endsWith('StructureDefinition.id')```.

 Kind of a fundamental thing. The path engine should only step into the original context (url in this case), of functions that use an expression as argument. (like `where`, `select` and, `exists`).
 
 See: http://hl7.org/fhirpath/#functions:

> If the function takes an expression as a parameter, the function will evaluate the expression passed for the parameter **with respect to each of the items in the input collection.** These expressions may refer to the special `$this` and `$index` elements, which represent the item from the input collection currently under evaluation, and its index in the collection, respectively. For example, in `name.given.where($this > 'ba' and $this < 'bc')` the `where()` function will iterate over each item in the input collection `(elements named given)` and `$this` will be set to each item when the expression passed to `where()` is evaluated.
