### ISSUE TITLE
Wrong result of function FhirReleaseParser.TryFhirReleaseFromCorePackageName

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/firely-net-sdk#1655]
**Describe the bug**
The function `FhirReleaseParser.TryFhirReleaseFromCorePackageName` does not work properly. The boolean result of the function should be dependent on the `release`. Not on the `packageName`.

**To Reproduce**
```c#
var result = FhirReleaseParser.TryFhirReleaseFromCorePackageName("a.b", out FhirRelease? rel);
```
The boolean variable `result` should here be `false`. In the current version (3.0.0) the result is `true`.

**Expected behavior**
When the conversion from packagename to FhirRelease could not be made, then the result should be `false`, and the out parameter `release` should be null.

**Version used:**
 - FHIR Version: Common
 - Version: 3.0.0

**Comment by ewoutkramer** [comment]
And it should have been called Try_Get_FhirReleaseFromCorePackageName.  I missed that during PR review.
