### ISSUE TITLE
ElementDefinition.slicing.discriminator.path for complex Extensions

### ISSUE THREAD

**Issue by ArdonToonstra** [FirelyTeam/firely-net-sdk#1656]
Use case: we want to add multiple, similar, complex extensions to a profile. They are differentiated by a fixed or pattern coding in one of the complex extension, in this case the `type` extension in ( http://hl7.org/fhir/extension-patient-proficiency.html).

We can't get a correct discriminator.path that gets into the complex extension. We tried: `Patient.communication.extension('http://hl7.org/fhir/StructureDefinition/patient-proficiency').extension('type').value`

- The .NET validator is complaining about that expression: Internal logic failure: Cannot walk into unknown StructureDefinition with canonical 'type' at 'http://hl7.org/fhir/StructureDefinition/patient-proficiency#Extension (Extension)'
- The JAVA validator also gives an error. But with not anything helpful.
- Zulip: https://chat.fhir.org/#narrow/stream/179166-implementers/topic/How.20to.20discriminate.20on.20a.20value.20in.20a.20complex.20extension.3F

Added some example R4 data. It has one example instance with the different extensions and the related (draft and unfinished) profiles.

[example data.zip](https://github.com/FirelyTeam/firely-net-sdk/files/6129392/example.data.zip)

**Comment by ewoutkramer** [comment]
@ArdonToonstra, I fixed this to work with child extensions in a complex extension too, but your example profile is incorrect. This bit is wrong:

``` xml
<element id="Patient.communication.extension">
         <path value="Patient.communication.extension"/>
         <slicing>
            <discriminator>
               <type value="value"/>
               <path value="url"/>
            </discriminator>
             <discriminator>
                 <type value="value"/>
                 <path value="extension('http://hl7.org/fhir/StructureDefinition/patient-proficiency').extension('type').value"/>
             </discriminator>
            <rules value="open"/>
         </slicing>
</element>
```

Look at how you specify the discriminator to navigate to `extension().extension()` *while you are already profiling the `extension` child*.  This slicing should have been on `Patient.communication`, not on `Patient.communication.extension`.
