### ISSUE TITLE
Installing two FHIR versions in same project clobbers specification.zip

### ISSUE THREAD

**Issue by vadi2** [FirelyTeam/firely-net-sdk#1657]
**Describe the bug**
Installing the SDK for two versions of FHIR produces a single `specification.zip` in the output, which means that only one version will actually work.

Suggestion: Iinclude the version of the FHIR spec in the name of the specification.zip.

**To Reproduce**
1. Use both `Hl7.Fhir.Specification.STU3` and `Hl7.Fhir.Specification.R4` in the same project
2. Build project
3. Observe output

**Comment by alexzautke** [comment]
In Firely Server we solve the issue by renaming the specification zip. The following snippet can be added to the .csproj

```
  <ItemGroup>
    <Content Include="$(PkgHl7_Fhir_Specification_STU3)\contentFiles\any\any\specification.zip">
      <Link>specification_Fhir3_0.zip</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
      <Pack>false</Pack>
    </Content>
  </ItemGroup>
```

Make sure to set GeneratePathProperty to true in the PackageReference:

```
  <ItemGroup>
    <PackageReference Include="Hl7.Fhir.Specification.STU3" Version="$(FhirNetApiVersionR3)" GeneratePathProperty="true" ExcludeAssets="contentFiles" />
  </ItemGroup>
```

**Comment by marcovisserFurore** [comment]
Hi Vadim,
Like @alexzautke already pointed out, there is a workaround to overcome multiple specification.zip with the same name. When we would include the version number in the name, a lot of our users will encounter backward compatibility while they probably depend on this name (`specification.zip`).

**Comment by brianpos** [comment]
And that name is also in the `ZipSource.CreateValidationSource()` routine that everyone uses.

**Comment by marcovisserFurore** [comment]
We will document this in docs.fire.ly. No code change.

**Comment by marcovisserFurore** [comment]
See documentation here: https://docs.fire.ly/projects/Firely-NET-SDK/model/multiple-fhir-versions.html
