### ISSUE TITLE
Validation of valid coding value fails

### ISSUE THREAD

**Issue by AMehlem** [FirelyTeam/firely-net-sdk#1658]
Hi,

I am trying to validate an instance of the profile https://simplifier.net/packages/kbv.ita.for/1.0.3/files/319332 using the fire net api (Hl7.Fhir.R4 and Hl7.Fhir.Specification.R4 version 3.0.0) on .Net 5.0. But for all the contained codings, the validation of the coding's value fails with a message like the following: "Code '...' from system '...' does not exist in valueset '...'"
But the named code exists in the valueset and should be valid. I created a VS2019 solution containing a test to reproduce the issue and attached it to this ticket. Can you tell me how to get the attached code to validate the instance successfully?

[ValueSetValidationTest.zip](https://github.com/FirelyTeam/firely-net-sdk/files/6141630/ValueSetValidationTest.zip)

**Comment by AMehlem** [comment]
It seems that was a misunderstanding on my side. I used the canonical url of the value sets used in the codings, but the value sets import codes from code systems. And as I found out, the code has to then use the url of the code system from which the code is taken as url.

**Comment by marcovisserFurore** [comment]
Thanks for letting us know @AMehlem.
