### ISSUE TITLE
Uploading profiles to server to validate resource instances

### ISSUE THREAD

**Issue by coeliyan** [FirelyTeam/firely-net-sdk#1661]
Hello,

I’ve had some trouble validating resource instances to profiles I’ve made in Forge. I’ve made a local server, where I followed this guide: http://docs.simplifier.net/firelyserver/getting_started.html. I’ve changed the appsettings.json to 
 "Validation": {
  "Parsing": "Strict", // Permissive / Strict
  "Level": "Full", // Off / Core / Full
  "AllowedProfiles":[
//"http://example.org/fhir/StructureDefinition/SimplePatientST10"
]
},
As I work with FHIR 4.0 in Forge, I further changed the settings to: 
"InformationModel": {
    "Default": "Fhir4.0", // information model to use when none is specified in either mapping, the _format parameter or the ACCEPT header
    "Mapping": {
      "Mode": "Off"
      //"Mode": "Path", // yourserver.org/r3 => FHIR STU3; yourserver.org/r4 => FHIR R4
      //"Map": {
      //  "/R3": "Fhir3.0",
      //  "/R4": "Fhir4.0",
      //  "/R5": "Fhir5.0"
      //}
      //"Mode": "Subdomain", // r3.yourserver.org => FHIR STU3; r4.yourserver.org => FHIR R4
      //"Map": 
      //  {
      //    "r3": "Fhir3.0",
      //    "r4": "Fhir4.0",
      //    "r5": "Fhir5.0"
      //  }
    }
  },

I’ve tried uploading the profile to the server both through import from local folder, through Simplifier project and Postman, however I end up getting errors, and when I use postman GET http://localhost:4080/metadata, I cannot find the uploaded profile. The errors I get range from 
“Error on creating resource with type [StructureDefinition] and url [“http://example.org/fhir/StructureDefinition/SimplePatientST10”]: “” ” 
and “Error on updating resource with id [“StructureDefinition”/”c9f7c0b7-ba4b-458a-b688-234aa27144c5”] and url [“http://example.org/fhir/StructureDefinition/ST9Patient”]: StructureDefinition.fhirVersion (4.0.1) is incompatible with the FHIR version used for this request (Fhir3.0). If this message is unjustified, please contact us” (local folder import), 
“Artifact https://simplifier.net/st10modellering/StructureDefinition?_count=20&_lastUpdated=gt2021-03-14T15%3A20%3A14.7041782%2B00%3A00 could not be imported. Error message: The request to 'https://simplifier.net/st10modellering/StructureDefinition?_count=20&_lastUpdated=gt2021-03-14T15%3A20%3A14.7041782%2B00%3A00' failed with the following status code NotFound” (simplifier project), 
and if I use the command POST http://localhost:4080/administration/StructureDefinition in postman, where I copy the profile’s StructureDefinition in the body as raw format, I get the following error: 
“Provided resource is of type 'Binary' but request targeted type 'StructureDefinition'". I’ve also tried posting zip files, but with no luck. 

As a consequence, when I try to create a new patient instance and send it to my local server, I get the “Unable to resolve reference to profile” error, where I’ve defined the conformance profile through the instance meta.profile: 
patientInstance.Meta = new Meta()
            {
                Profile = new string[] { "http://example.org/fhir/StructureDefinition/SimplePatientST10" }
            };

I’ve tried to solve the problem, however I am not sure exactly how I successfully upload the profiles to my server. I’ve tried using Forge, which does show the profile is uploaded to my local server, and I can import the same profile to Forge through the server, however postman and visual studio still doesn't find the profile.

Another question, is it possible to validate profiles against specific profiles, when using a public server, eg. https://server.fire.ly? 

Thank you in advance

Kind regards,
Lisa

**Comment by marcovisserFurore** [comment]
Hi Lisa, I think this is more a question to the Firely Server (Vonk) team then for the SDK. @mbaltus can you help Lisa?
