### ISSUE TITLE
How to reference Contained resources inside a Bundle

### ISSUE THREAD

**Issue by pvnmurthy** [FirelyTeam/firely-net-sdk#1680]
Hi,

I would like to know how to reference a Contained resource inside a bundle and push it to Fhir server.

{
      "fullUrl": "urn:uuid:82f288be-07b8-4c48-aab8-1072a84cd8b1",
      "resource": {
        "resourceType": "ExplanationOfBenefit",
        "id": "82f288be-07b8-4c48-aab8-1072a84cd8b1",
        **"contained": [
         {
            "resourceType": "Coverage",
            "id": "coverage",
            "status": "active",
            "type": {
              "text": "Aetna"
            }**,
            "beneficiary": {
              "reference": "urn:uuid:b426b062-8273-4b93-a907-de3176c0567d"
            },
            "payor": [
              {
                "display": "Aetna"
              }
            ]
          }
        ],
        "identifier": [
          {
            "system": "https://bluebutton.cms.gov/resources/variables/clm_id",
            "value": "8e3b38d2-fe27-40ec-b8c3-6a4ea37493c7"
          },
          {
            "system": "https://bluebutton.cms.gov/resources/identifier/claim-group",
            "value": "99999999999"
          }
        ],
        "status": "active",
        "type": {
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/claim-type",
              "code": "institutional"
            }
          ]
        },
        "use": "claim",
        "patient": {
          "reference": "urn:uuid:b426b062-8273-4b93-a907-de3176c0567d"
        },
        "billablePeriod": {
          "start": "2010-04-12T12:52:44-04:00",
          "end": "2011-04-12T12:52:44-04:00"
        },
        "created": "2010-04-12T12:52:44-04:00",
        "insurer": {
          "display": "Aetna"
        },
        "provider": {
          "reference": "urn:uuid:0000016d-3a85-4cca-0000-000000000636"
        },
        "claim": {
          "reference": "urn:uuid:8e3b38d2-fe27-40ec-b8c3-6a4ea37493c7"
        },
        "outcome": "complete",
        "insurance": [
          {
            "focal": true,
            "coverage": {
              **"reference": "#coverage",**
              "display": "Aetna"
            }
          }
        ],
      },
      "request": {
        "method": "POST",
        "url": "ExplanationOfBenefit"
      }
    }

When I am referencing a Coverage contained resource with '#coverage inside ExplanationOfBenefit.insurance.coverage.reference and posting to FHIR server the Firely SDK is throwing exceptions. 
Please help me on how to correctly reference a contained coverage resource inside ExplanationOfBenefit resource.
Thanks in advance.

thanks,
Narasimha

**Comment by marcovisserFurore** [comment]
Hi Narasimha, Thanks for using our Firely .NET SDK. 

The above json is not a correct FHIR Json. You can check this for example by using our online validator:  https://simplifier.net/validate. 

First of all, this json misses a `resourceType`. I presume you want to construct a Bundle. A Bundle look this:

```json
{
  "resourceType": "Bundle",
  "id": "bundle-transaction",
  "type": "transaction",
  "entry": [
    {
      "fullUrl": "urn:uuid:82f288be-07b8-4c48-aab8-1072a84cd8b1",
      "resource": {
          "resourceType": "ExplanationOfBenefit",
          "id": "82f288be-07b8-4c48-aab8-1072a84cd8b1",
          "contained": [
          {
          //etcetera
          }
          ]
      }
   }
  ]
}
``` 
So a bundle contains of entries. Each entry consist of a resource, which can have contained resources. 

See for more information about this resource `Bundle` the FHIR standard page: http://hl7.org/fhir/bundle.html

**Comment by marcovisserFurore** [comment]
Answered.
