### ISSUE TITLE
Handle OperationOutCome resource in response

### ISSUE THREAD

**Issue by jiteshmadhu** [FirelyTeam/firely-net-sdk#1681]
Hello,

We are using firely nuget  package  version 4  in our .Net project to push data through as FHIR standard to the server.

Now, our problem is server is always giving response in OperationOutCome resource in response jSON body. It gives same response (OperationOutcome) in all the cases means In case of status is OK and in case of status is Error.

So, how can we handle that using firely framework?

We have done following code to push the patient data to the server.
..... 
var client = new FhirClient("server end point url");
var pat = new Patient();
..... 
..... 
var Objres =  client.Create(pat):
.....

As per above code we are always receving NULL value in the Objres because server is giving response body as OperationOutCome and firely framework expecting response resource should be the same resource which was pushed.

So, how can we get OperationOutCome response body jSON?

Thanks in advance!
Jitesh

**Comment by marcovisserFurore** [comment]
Hi Jitesh, thanks for using our Firely .NET SDK.

According to the FHIR standard, a FHIR server SHOULD always return the resource, see also http://hl7.org/fhir/http.html#create.

But when something goes wrong, for example the resource is not valid, then the Create method will throw an exception. In that exception you can see the OperationOutcome from the server. See here a snippet how to do that:

```c#
            using var client = new FhirClient(testEndpoint);
            try
            {
                var result = client.Create<Patient>(new Patient());
                Assert.IsNotNull(result);
            }
            catch (FhirOperationException ex)
            {
                if (!ex.Outcome.Success)
                {
                    // do something
                }
            }
```

**Comment by brianpos** [comment]
The server can return the OperationOutcome like that, and can even be requested using the prefer header
```
Prefer: return=OperationOutcome
```
http://hl7.org/fhir/http.html#ops
From the C# code you can do this like this:
``` c#
            Hl7.Fhir.Rest.FhirClient clientFhir = new Hl7.Fhir.Rest.FhirClient(_baseAddress, false);
            clientFhir.PreferredReturn = Prefer.OperationOutcome;
```
I'm checking what the `client.Create<Patient>(pat)` would do with this... But it's perfectly valid to do it.

**Comment by marcovisserFurore** [comment]
@mmsmits: can you check the last comment of Brian (update 2)?

**Comment by brianpos** [comment]
Thanks, I would expect the outcome in the outcome property, and the header values put into the other props, Id locarion, etag etc.

**Comment by mmsmits** [comment]
I checked and added the operation outcome in LastResult.outcome. Thanks @brianpos 

@jiteshmadhu:

With this fix, in the next release, you can view the OperationOutcome as previously described using:

```
var response = client.Create<Patient>(pat)
var outcome = client.LastResult.Outcome
```

If you don't want to wait for the next release this will work already, but is a bit ugly.
```
var response =  client.Create<Resource>(pat)
```
it returns the response as type Resource. And you can cast it to an OperationOutcome:

```
if(response is OperationOutcome outcome)
{
  if(outcome.Success)
     ~here comes your code
  else
     ~here comes code to handle an unsuccessful create 
}
```

**Comment by jiteshmadhu** [comment]
Thank you Smits and everybody in this discussion.

This is great help appreciated!
