### ISSUE TITLE
Make working with `List<T?>` elements easier

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#1682]
**Describe the bug**
For required bindings, we represent codes with an enumeration.   Since we assume any element may be null, a non-repeating element for a binding will be generated in a class like so:
 * For the "main" element: `Code<SomeEnumType>  SomenameElement`
 * For the shorthand element: `SomeEnumType? Somename`

When these members repeat, we unfortunately misplace the nullable indicator in the shorthand element:
* For the "main" element: `List<Code<SomeEnumType>> SomenameElement`
* For the shorthand element: `IEnumerable<SomeEnumType?> Somename`.

**Expected behavior**
The last line (the shorthand element for a repeating code) *should* have been `IEnumerable<SomeEnumType> Somename`, without the nullability marker '?'.

NOTE: This would require a new major version.

**Version used:**
 - FHIR Version: certainly since 1.x

**Comment by brianpos** [comment]
This doesn't feel wrong to me, it's consistent between list and non list.
Which property on which resource is an example of this?

**Comment by ewoutkramer** [comment]
Fixed by https://github.com/FirelyTeam/firely-net-common/pull/170
