### ISSUE TITLE
Internal reference "#" should resolve from contained resource to the container

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#1688]
This section https://www.hl7.org/fhir/references.html#contained mentions that "#" can be used in references to reference from a contained resource to its container.   This should work both in the validator and the FP `resolve()` operation (though I don't think it needs to be supported in the minimal FP dialect used for discriminators).

(Note that the ref-1 invariant on Reference will trigger for this, still, operationally we can make it work).

**Comment by brianpos** [comment]
Careful that just # will resolve to a resource with no Id, which can create an infinite loop during validation.

**Comment by alexzautke** [comment]
Would it be possible to pre-apply the ref-1 fix as proposed here https://jira.hl7.org/browse/FHIR-31732 in R4 and make this work as proposed in the validator?
The Firely Server team notices this issue during testing with data provided by a customer. No high priority issue yet, but it could be a potential issue soon.
