### ISSUE TITLE
How to read summary comments on a property of resource?

### ISSUE THREAD

**Issue by leo9223** [FirelyTeam/firely-net-sdk#1696]
The following summary element I want to read in C#.

```
/// <summary>
/// A name associated with the patient
/// </summary>
[FhirElement("name", InSummary=true, Order=110)]
[Cardinality(Min=0,Max=-1)]
[DataMember]
public List<Hl7.Fhir.Model.HumanName> Name
{
  get { if(_Name==null) _Name = new List<Hl7.Fhir.Model.HumanName>(); return _Name; }
  set { _Name = value; OnPropertyChanged("Name"); }
}
```

I have referenced Hl7.Fhir.R4 from nuget 3.1.0 version. After going to definition in C# what I am seeing is the following code, comments are in a different format.
```
//
// Summary:
//     A name associated with the patient
[Cardinality(Min = 0, Max = -1)]
[DataMember]
[FhirElement("name", InSummary = true, Order = 110)]
public List<HumanName> Name { get; set; }
```

How I can retrieve this string "A name associated with the patient" from the package? I don't want to use ZipSource technique.

**Comment by ewoutkramer** [comment]
The C# compiler extracts this information into a separate .XML file that is included in the NuGet.  Is that something you can use?  There's no way to get to this non-code using reflection - it is simply not code.

![image](https://user-images.githubusercontent.com/2276305/116526160-98365800-a8d9-11eb-9da6-9134dd11a49f.png)

**Comment by leo9223** [comment]
Yes, I think that will work for me. Thank you
