### ISSUE TITLE
Decimals without leading 0 throws exception

### ISSUE THREAD

**Issue by IDispose** [FirelyTeam/firely-net-sdk#1712]
Decimal values that do not have a leading `0` before the decimal point are considered invalid and an explicit exception is thrown by the library during parsing. Values like `.15` cause this exception. This means while parsing an HL7 message and building the FHIR JSON structure I will have to change `.15` to `0.15`. Technically the values are equivalent. 

Why does the library treat decimals without leading `0` as errors?

**Comment by ewoutkramer** [comment]
The FHIR specification describes exactly what decimals may or may not look like.

In this case, look here http://hl7.org/fhir/datatypes.html, under "decimal". The supplied regex reads:

`-?(0|[1-9][0-9]*)(\.[0-9]+)?([eE][+-]?[0-9]+)?`

explicitly demanding a leading 0.

**Comment by IDispose** [comment]
Closing ticket because library is designed to specification.
