### ISSUE TITLE
specification.zip must be loaded from a directory that cannot be controlled by code (SpecificationDirectory)

### ISSUE THREAD

**Issue by DarthGizka** [FirelyTeam/firely-net-sdk#1722]
Various code paths in the library - like `Validator.Validate(XmlReader)` - attempt to load `specification.zip` via `ZipSource.CreateValidationSource()`, which uses the read-only static property `DirectorySource.SpecificationDirectory`. This property returns directories which the programmer dealing with firely has no control over (i.e. cannot or must not control), either the appdomain base directory or the current working directory.

Moreover, the library attempts the creation of specification zip source via these problematic code paths even if a working zip source for the right zip file is already configured in the validator.

Workarounds are necessarily crude, brittle, and dangerous in the face of multithreading, except maybe the automatic copying of `specification.zip` to whatever the appdomain base directory currently happens to be (because that can be arranged in a multithread-safe way). However, dropping umpteen copies of the multi-megabyte `specification.zip` all over the place is not exactly nice behaviour.

If `DirectorySource.SpecificationDirectory` must remain a global setting for whatever reason (instead of becoming a normal instance property) then there SHOULD be a way for an application to initialise it to a suitable value before multithreaded operation commences.

Note: `DirectorySource.SpecificationDirectory` can potentially return the current working directory, which is an unpredictable user-controlled element that library code should normally not use for its own operation. *The appdomain base directory can become just as unpredictable as the current directory in connection with things like dynamic loading/unloading of assemblies and/or custom assembly resolvers. An application will be able to refer to some stable directories, but it cannot necessarily guarantee anything for the cwd or the appdomain base directory. Moreover, an application may have to add `specification.zip` to a versioned profile stash that undergoes the normal build/deploy process instead of poking around the Internet and caching what it pleases.*

Note: one quick way of reproducing the problem would be to reference the firely packages at the solution level, adding an MSTest project and writing a simple test involving `Validator.Validate(XmlReader)` (or to invoke `ZipSource.CreateValidationSource()` directly).

P.S.: thanks to all contributors for making such a useful, flexible, high-quality library. Kudos!

**Comment by ewoutkramer** [comment]
HI @DarthGizka - thanks for the feedback.  I was going to say: "but we're never using `ZipSource.CreateValidationSource()`, in the SDK, except for our tests` - but as you pointed out this is not *generally* true. 

My analysis is that `Validator.Validate(XmlReader)` is the exception. It needs access to the XML schema files - which are buried in the specification.zip, and so this codepath uses `CreateValidationSource` to create a secondary source, independent of whatever resolver you have used to configure the validator itself.

The only public SDK methods that I can see which are influenced by this are the methods in `XmlValidationExtensions.cs`, more specifically, these are calling the `internal ValidateXml()` method, which in its turn retrieves the XML schemas by use of the `SchemaCollection.ValidationSchemaSet` property.  This is a cached property that uses this "secondary", and non-user-configurable validation source.

**Comment by ewoutkramer** [comment]
I have a proposed solution coming up, but basically I am leaving DirectorySource.SpecificationDirectory untouched - it would be a breaking change to make it non-static. In addition, it's easy to configure a DirectorySource to do the right thing, as it has overloaded constructors to point it to a different place.  

These are the problems I need to fix:

1. We need to make sure that no part of the API depends (directly or indirectly) on either DirectorySource.SpecificationDirectory or ZipSource.CreateSource - it should always rely on configurable settings.
2. And so, the validator, when used to validate XML, needs to be told where to get the XML schemas from - instead of using ZipSource.CreateSource.

See PR #1765.
