### ISSUE TITLE
Encounter search with reference "patient" search parameter

### ISSUE THREAD

**Issue by leo9223** [FirelyTeam/firely-net-sdk#1733]
I am receiving an Unknown symbol 'Resolve' error on the following line in my code when I am trying to search Encounter with "patient" search parameter reference.

IEnumerable<Base> values = resource.Select("Encounter.subject.where(resolve() is Patient)");

Where I am doing wrong?

**Comment by ewoutkramer** [comment]
Nothing, this is a known bug, that we are resolving in the next (3.3) release: https://github.com/FirelyTeam/firely-net-sdk/issues/1525

The good news: this issue link also contains a work-around you can use until 3.3 is out.

**Comment by marcovisserFurore** [comment]
Yesterday we released version 3.3.0 of the Firely .NET SDK

**Comment by leo9223** [comment]
@marcovisserFurore I have upgraded to 3.3.0.

But getting the same error Unknown symbol 'resolve' 

on the following line

where the resource is and Encounter resource

resource.Select("Encounter.subject.where(resolve() is Patient)");

**Comment by marcovisserFurore** [comment]
`resolve()` is not part of the standard FhirPath function. Take a look at this [discussion ](https://github.com/FirelyTeam/firely-net-sdk/issues/1730#issuecomment-849464702)and I think you will be able to solve it.

**Comment by leo9223** [comment]
> "Great. So, if you have the 'resolve' missing in your code it means the FhirPath parser is misconfigured in the validator This can only happen in your own code if you have set the FhirPathCompiler in the ValidatorSettings to something else than the default"

@marcovisserFurore I haven't touched the FhirPathCompiler or anything.

just getting an Encounter resource in a resource variable and calling the select method to get the results.

Kindly help me how I can solve the issue I shall be thankful.

**Comment by marcovisserFurore** [comment]
Hi @leo9223 ,

You need to enable the extra FhirPath function with the following statement:
```c#
Hl7.Fhir.FhirPath.ElementNavFhirExtensions.PrepareFhirSymbolTableFunctions();
```

See here how it works:

```c#
        var patient = new()
        {
            Id = "1",
            Active = true,
            BirthDate = "2001-03-01"
        };

        var encounter = new()
        {
            Contained = new List<Resource>() { patient },
            Subject = new ResourceReference("#1")
        };

        Hl7.Fhir.FhirPath.ElementNavFhirExtensions.PrepareFhirSymbolTableFunctions();

        var result = _encounter.Select("Encounter.subject.where(resolve() is Patient)");
```

**Comment by leo9223** [comment]
@marcovisserFurore I have tested this, the error is gone but the Select method is not yielding any results!!

enumeration is empty with patient search parameter but working with subject parameter!

**Comment by leo9223** [comment]
@marcovisserFurore the patient resource is on the same server. Actually, I just wanted to retrieve a reference string of a Patient from an Encounter resource.

the same way I am retrieving using "Encounter.subject". but the subject applies to Group resource reference as well.

What I understood that the patient search parameter will retrieve the reference string of only Patient resources. Have I understood this wrong?

**Comment by marcovisserFurore** [comment]
I presume you are developing a client program, so you are fetching resources from a FHIR server?

When you fetch a Encounter from a FHIR server, the referenced resources, like patients, are not automatically fetched.

If you are  only interested in the reference string, then you could this:

```c#
var result = encounter.Select("Encounter.subject.where($this.type = 'Patient');
```

But the `type` is not always provided (it is not mandatory).
Another way would be, but more ugly:

```c#
var result = encounter.Select("Encounter.subject.where($this.reference.startsWith('Patient') )");
```

**Comment by leo9223** [comment]
@marcovisserFurore Thank you, much appreciated.

`Encounter.subject.where($this.type = 'Patient')` worked for me.

I was implementing chained parameters and wanted to implement `patient.xxx` search param for Encounter.

from `ModelInfo.SearchParameters` I am getting expression `Encounter.subject.where(resolve() is Patient)` 

is there any way or method I could automatically convert from `Encounter.subject.where(resolve() is Patient)` to `Encounter.subject.where($this.type = 'Patient')` or I am only left with manipulating strings manually by replacing chunks?
