### ISSUE TITLE
%resource and %rootResource don't work well

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#1742]
**Describe the bug**
The FP variables %resource and %rootResource are currently just static variables passed in via the `EvaluationContext`. However, the nature of these variables is that these variables are dynamic and will change as you walk into, say, a bundle, into an entry and then into a contained resource. This currently does not happen.

**To Reproduce**
Run the test `TestFhirPathRootResource()` in FhirPathTest.cs in `develop-r4`.  These tests correctly verify that these variables changes while walking a tree.

**Expected behavior**
This test -currently ignored- should be enabled and the FP engine adapted so it will run this test correctly.

**Version used:**
 - FHIR Version: R4
 - Version: 3.3

**Comment by marcovisserFurore** [comment]
Having the following bundle (coming from the `TestFhirPathRootResource()` in FhirPathTest.cs):

```json
{
   "resourceType":"Bundle",
   "id":"bundle-1",
   "type":"collection",
   "entry":[
      {
         "fullUrl":"http://example.com/patient1",
         "resource":{
            "resourceType":"Patient",
            "id":"patient-1",
            "contained":[
               {
                  "resourceType":"Patient",
                  "id":"contained-1"
               }
            ],
            "link":[
               {
                  "other":{
                     "reference":"#contained-1"
                  },
                  "type":"seealso"
               }
            ]
         }
      }
   ]
}
```
then I think the outcome should be:

|Focus|`%resource.id`|`%rootResource.id`|remarks|
|------|-------------|----------------|----------------|
|`entry.first().resource.contained`|`contained-1`|`patient-1`|Focus on the container resource|
|`entry.first().resource.contained.id`|`contained-1`|`patient-1`|Focus on the **id** of the container resource|
|`entry.first().resource`|`patient-1`|`patient-1`|Focus on the entry resource|
|`entry.first().resource.id`|`patient-1`|`patient-1`|Focus on the **id** of the entry resource|
|<root>|`bundle-1`|`bundle-1`|Focus on the bundle|
