### ISSUE TITLE
fhirpatient.identifier.remove not working

### ISSUE THREAD

**Issue by pavankuram** [FirelyTeam/firely-net-sdk#1755]
:information_source: Do you want to ask something or start a discussion, then go [here](https://github.com/FirelyTeam/firely-net-sdk/discussions)

**Describe the bug**
After we clear the fhirclient and searching for a FHIR Patient when we are trying to remove one of the identifier assigned in the patient
fhirpatient.identifier.remove("identifiervalue")
fhirclient.update(fhirpatient) is not working to remove the identifier

**To Reproduce**
1. Create a FHIR Client  as fhirclient
2. Get Patient Resource as pat
3. Inside the patient resource try to do pat.identifier.remove("idetifiervalue") and then update the pat as fhirclient.update(pat)
4. Just runs through but wont remove the identifier

**Expected behavior**
Out of bunch of identifier existing in patient resource remove the identifier which we have tried to. After we retrieve the patient it should not have the identifier we removed in previous step.

**Screenshots**

**Version used:**
 - FHIR Version: R4
 - Version: [e.g. 1.9.0]

**Additional context**

**Comment by mmsmits** [comment]
Hi @pavankuram ,

I think the local removal of the identifier doesn't work in your code, and otherwise maybe the server you are testing against doesn't allow removal of identifier.

I tried to reproduce your issue in this test, which succeeds in both version 1.9.0. (using the older ```FhirClient```) and the latest version of the SDK. 

I used http://server.fire.ly/ as a FHIR test server.

``` 
[TestMethod]
        [TestCategory("FhirClient"), TestCategory("IntegrationTest")]
        public void MissingIdentifierClient()
        {
            var client = new FhirClient(testEndpoint);
            var pat = new Patient
            {
                Id = "identifier-example",
                Identifier = new List<Identifier>
                {
                    new Identifier
                    {
                        System = "http://example.org/fhir/NamingSystem/example-id",
                        Value = "example-value"
                    }
                }
            };

            Assert.IsTrue(pat.Identifier.Count == 1);
            client.Update(pat);

            var pat2 = client.Read<Patient>("Patient/" + pat.Id);
            var identifiervalue = pat2.Identifier.SingleOrDefault(i => i.System == "http://example.org/fhir/NamingSystem/example-id");
            Assert.IsTrue(pat2.Identifier.Remove(identifiervalue));

            var pat3 = client.Update(pat2);
            Assert.IsTrue(pat3.Identifier.Count == 0);
        }
```

**Comment by mmsmits** [comment]
I'm closing this issue
