### ISSUE TITLE
Hl7.Fhir.DSTU2.Core 1.9.0 not compatible with dlls needed by Hl7.Fhir.STU3.Core 3.3.0

### ISSUE THREAD

**Issue by tstolker** [FirelyTeam/firely-net-sdk#1758]
A requirement for our application to be able to simultaneously use DSTU2 and STU3 clients.
We were using the 1.2.0 versions of the DSTU2 and R3 clients together, and these worked great.
However, after upgrading both packages to latest stable DSTU2 1.9.0 and STU3 3.3.0 these no longer peacefully co-exist. 

The error thrown is: Could not load type 'Hl7.Fhir.Specification.IStructureDefinitionSummaryProvider' from assembly 'Hl7.Fhir.Support, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.

The complete list of errors being:
[TypeLoadException: Could not load type 'Hl7.Fhir.Specification.IStructureDefinitionSummaryProvider' from assembly 'Hl7.Fhir.Support, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.]

[CannotLoadAssemblyException: Unable to load the assembly 'Hl7.Fhir.DSTU2.Core, Version=1.9.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3' because of the following exceptions:
	1. System.TypeLoadException: Could not load type 'Hl7.Fhir.Specification.IStructureDefinitionSummaryProvider' from assembly 'Hl7.Fhir.Support, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	2. System.TypeLoadException: Could not load type 'Hl7.Fhir.Specification.IStructureDefinitionSummary' from assembly 'Hl7.Fhir.Support, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	3. System.TypeLoadException: Could not load type 'Hl7.Fhir.Specification.IStructureDefinitionReference' from assembly 'Hl7.Fhir.Support, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	4. System.TypeLoadException: Could not load type 'Hl7.Fhir.Specification.IElementDefinitionSummary' from assembly 'Hl7.Fhir.Support, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	5. System.TypeLoadException: Could not load type 'Hl7.Fhir.Specification.XmlRepresentation' from assembly 'Hl7.Fhir.Support, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	6. System.TypeLoadException: Could not load type 'Hl7.Fhir.Specification.XmlRepresentation' from assembly 'Hl7.Fhir.Support, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	7. System.TypeLoadException: Method 'get_Definition' in type 'Hl7.Fhir.Serialization.ValuePropertyTypedElement' from assembly 'Hl7.Fhir.DSTU2.Core, Version=1.9.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3' does not have an implementation.
	8. System.TypeLoadException: Method 'get_Definition' in type 'Hl7.Fhir.ElementModel.PocoElementNode' from assembly 'Hl7.Fhir.DSTU2.Core, Version=1.9.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3' does not have an implementation.
	9. System.TypeLoadException: Could not load type 'Hl7.Fhir.ElementModel.Adapters.BaseNodeToNavAdapter' from assembly 'Hl7.Fhir.ElementModel, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	10. System.TypeLoadException: Could not load type 'Hl7.Fhir.ElementModel.IElementNavigator' from assembly 'Hl7.Fhir.ElementModel, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	11. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	12. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	13. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	14. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	15. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	16. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	17. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.INullableIntegerValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	18. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	19. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	20. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.INullableIntegerValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	21. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	22. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.INullableIntegerValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	23. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	24. System.TypeLoadException: Could not load type 'Hl7.Fhir.ElementModel.IElementNavigator' from assembly 'Hl7.Fhir.ElementModel, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	25. System.TypeLoadException: Could not load type 'Hl7.Fhir.ElementModel.IElementNavigator' from assembly 'Hl7.Fhir.ElementModel, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	26. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	27. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	28. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	29. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	30. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	31. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	32. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	33. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	34. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	35. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	36. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	37. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	38. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	39. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	40. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	41. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	42. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	43. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	44. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	45. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	46. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	47. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	48. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	49. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	50. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	51. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	52. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	53. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	54. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	55. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	56. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	57. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	58. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	59. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	60. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.INullableIntegerValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	61. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.INullableIntegerValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	62. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.INullableIntegerValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	63. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.INullableIntegerValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	64. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.INullableIntegerValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	65. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.INullableIntegerValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	66. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	67. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	68. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	69. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	70. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	71. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	72. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	73. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	74. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.INullableIntegerValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	75. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.INullableIntegerValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	76. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	77. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	78. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	79. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	80. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	81. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	82. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	83. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	84. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
	85. System.TypeLoadException: Could not load type 'Hl7.Fhir.Model.IStringValue' from assembly 'Hl7.Fhir.Support.Poco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.

Compilations with the 3.3 packages works well, but at runtime the above error happens.

![DSTU2](https://user-images.githubusercontent.com/9209532/121515532-9211bc00-c9ed-11eb-9fc6-5e9b8ed67be7.PNG)

This ultimately means that Dependencies listed for Hl7.Fhir.DSTU2.Core are incorrect:
  **Hl7.Fhir.Serialization (>= 1.9.0)
  Hl7.Fhir.Support (>= 1.9.0)
  Hl7.Fhir.Support.Poco (>= 1.9.0)
  Hl7.FhirPath (>= 1.9.0)**

1. Upgrade STU3 to latest stable 3.3.0
2. Upgrade Hl7.Fhir.DSTU2.Core packagesto latest stable (1.9.0)
3. Try to combine these in the same applicatione.
4. The above error will be displayed.

**Expected behavior**
I expect the latest stable DSTU2 to happily co-exists with latest stable of Hl7.Fhir.STU3.Core (and of course also with latest stable of HL7.FHIR.R4.core). Given that applications like Cerner still expose a large part of their resources only as DSTU2 resources, we will need to continue to support a DSTU2 client., 

**Version used:**
 - Hl7.Fhir.DSTU2.Core 1.9.0
 - Hl7.Fhir.STU3.Core 3.3.0

**Comment by marcovisserFurore** [comment]
Hi @tstolker,

That is right: version 1.9.0 (DSTU2) and 3.3.0 (STU3) are not compatible anymore, because we end to maintain DSTU2 already from version 2.0 in November 2020. See also our  [release notes](https://github.com/FirelyTeam/firely-net-sdk/releases/tag/v2.0.0-stu3) for version 2.0 (STU3).

**Comment by tstolker** [comment]
> Hi @tstolker,
> 
> That is right: version 1.9.0 (DSTU2) and 3.3.0 (STU3) are not compatible anymore, because we end to maintain DSTU2 already from version 2.0 in November 2020. See also our [release notes](https://github.com/FirelyTeam/firely-net-sdk/releases/tag/v2.0.0-stu3) for version 2.0 (STU3).

Hi @marcovisserFurore , it would have helped if you changed the dependencies listed for the DSTU2 package, right, >1.9.0 is incorrec!!

Then on discontinuing DSTU2 maintenance, with Cerner still requiring clients to use DSTU2, nobody so far complained about this?

**Comment by marcovisserFurore** [comment]
The `> 1.9.0` is a feature from NuGet. When it cannot find version 1.9.0, it tries to find a newer one. That is something we cannot fix in our solution, but standard behavior of NuGet.

Well, actually you are the first one who is mentioning this since November 2020. Perhaps others do not upgrade their software? We stopped maintaining DSTU2, because it takes us too much effort to maintain all the versions. Our goal is to maintain the last 2 major versions of FHIR, so now we have STU3 and R4. And even already R4B en R5 in beta phase. Those newer versions (R4B and R5) are a bit better to maintain, because  the differences are a lot smaller.

**Comment by tstolker** [comment]
Thanks, @marcovisserFurore , indeed we also stayed on 1.2.0 (from 29-3-2019) which will still be in production for the better part of this year. But as a preparation to add R4 support I wanted to upgrade our STU3 packages to latest stable, and I guess we just have to live with the consequences! :) Thanks for your quick response!
