### ISSUE TITLE
Validator rejects valid resource: Instance failed constraint xy (FhirPath constraint).

### ISSUE THREAD

**Issue by thvogd** [FirelyTeam/firely-net-sdk#1785]
**Description**
Being the first time here first of all I would like to say thank you for providing and supporting firely.sdk! It helps us a lot.

Using the validator to validate bundle resources I encountered a problem. The validator rejected a valid resource as invalid, stating that a certain FirePath constraint would not be met:

```
[ERROR] Instance failed constraint angabeAUseitErstbescheinigung "Die Angabe arbeitsunfaehig seit ist nicht gesetzt, muss aber bei einer Erstbescheinigung gesetzt werden."(further diagnostics: (         entry.where(resource is Composition).resource.type.coding.where(system = 'https://fhir.kbv.de/CodeSystem/KBV_CS_EAU_AU_Type').code = 'ERST'          or         entry.where(resource is Composition).resource.type.coding.where(system = 'https://fhir.kbv.de/CodeSystem/KBV_CS_EAU_AU_Type').code = 'ERST_END'         )implies(         entry.select(resource as Condition).where(meta.profile = 'https://fhir.kbv.de/StructureDefinition/KBV_PR_EAU_Condition_AU|1.0.2').onsetPeriod.start.exists()        )) (at Bundle)
```
This problem only occurs when validating Poco-based resources (poco -> ITypedElement). If validation is based on deserialized xml (ISourceNode -> ITypedElement) all is fine.

Looking into it it seems to me that the element node names used when validating poco-based resources (provided by PocoElementNode instances) in certain cirmcumstances are wrong. In my case a childnode named "onset" was shown. However the FirePath constraint demands the existance of a childnode named "onsetPeriod", thus failing the validation.

Attached you find a project showing the problem (and a work around when using the ISourceNode approach). Moreover I added a screenshot showing the "onset" childnode name seen in a debugging session.

**To Reproduce**
See attached solution.

[FirelyValidatorPocoElementNodeProblem.zip](https://github.com/FirelyTeam/firely-net-sdk/files/6734543/FirelyValidatorPocoElementNodeProblem.zip)

**Screenshot**
![ScreenshotChildNodeName](https://user-images.githubusercontent.com/28148886/123824916-bc74dc00-d8fe-11eb-9ba2-9a883678d28f.jpg)

**Version used:**
 - FHIR Version: R4
 - Version: 3.3.0

**Comment by marcovisserFurore** [comment]
Hi @thvogd,

Thanks for the compliments and for your question with sample code. Always great to have examples so that we can check the code ourselves.

I am afraid that the FhirPath expression in the profile `https://fhir.kbv.de/StructureDefinition/KBV_PR_EAU_Bundle` is not correct:

```
(         entry.where(resource is Composition).resource.type.coding.where(system = 'https://fhir.kbv.de/CodeSystem/KBV_CS_EAU_AU_Type').code = 'ERST'         
 or         entry.where(resource is Composition).resource.type.coding.where(system = 'https://fhir.kbv.de/CodeSystem/KBV_CS_EAU_AU_Type').code = 'ERST_END'         )
implies(         entry.select(resource as Condition).where(meta.profile = 'https://fhir.kbv.de/StructureDefinition/KBV_PR_EAU_Condition_AU|1.0.2').onsetPeriod.start.exists()        )
```

In this expression `onsetPeriod` is used for the choice element `onset`. According to the [FhirPath specification](https://hl7.org/fhir/fhirpath.html#polymorphism) choice elements are labeled according to the name without the '[x]' suffix.
So `onset` should be used here or `(onset as Period).start.exists()`. Changing that in the profile will make the validation a success.

**Comment by thvogd** [comment]
Hello Marco,

thanks for looking into the issue!

However I do not understand why the workaround succeeds if the profile is corrupt.

If you change the sample code to the following (Program.Main()):

```c#
      ////var eauBundle = Program.CreateEauBundleByPoco("EauBundle.xml");

      // Use the following line instead the one above to prevent error.
      var eauBundle = Program.CreateEauBundleByXml("EauBundle.xml");
```

the Firely validator considers the resource valid (using exactly the same profile against the same resource xml file).

Using the workaround the validator returns:

```
Validation result:
Overall result: SUCCESS

[WARNING] Instance failed constraint icd-5 "Wenn die Diagnosesicherheit "G (Gesichert)" verwendet wird, dann muss clinicalStatus auf "active" und verificationStatus auf "confirmed" gesetzt werden."(further diagnostics: code!='G' or (%resource.clinicalStatus.coding.where(code='active').exists() and %resource.verificationStatus.coding.where(code='confirmed').exists())) (at Bundle.entry[8].resource[0].code[0].coding[0].extension[0].valueCoding[0] via Bundle.entry[0].resource[0].section[2].entry[0])
[WARNING] Terminology service failed while validating code 'G' (system 'https://fhir.kbv.de/CodeSystem/KBV_CS_SFHIR_ICD_DIAGNOSESICHERHEIT'): Cannot retrieve valueset 'https://fhir.kbv.de/ValueSet/KBV_VS_SFHIR_ICD_DIAGNOSESICHERHEIT' (at Bundle.entry[8].resource[0].code[0].coding[0].extension[0].valueCoding[0] via Bundle.entry[0].resource[0].section[2].entry[0])
[WARNING] Instance failed constraint icd-5 "Wenn die Diagnosesicherheit "G (Gesichert)" verwendet wird, dann muss clinicalStatus auf "active" und verificationStatus auf "confirmed" gesetzt werden."(further diagnostics: code!='G' or (%resource.clinicalStatus.coding.where(code='active').exists() and %resource.verificationStatus.coding.where(code='confirmed').exists())) (at Bundle.entry[9].resource[0].code[0].coding[0].extension[0].valueCoding[0] via Bundle.entry[0].resource[0].section[3].entry[0])
[WARNING] Terminology service failed while validating code 'G' (system 'https://fhir.kbv.de/CodeSystem/KBV_CS_SFHIR_ICD_DIAGNOSESICHERHEIT'): Cannot retrieve valueset 'https://fhir.kbv.de/ValueSet/KBV_VS_SFHIR_ICD_DIAGNOSESICHERHEIT' (at Bundle.entry[9].resource[0].code[0].coding[0].extension[0].valueCoding[0] via Bundle.entry[0].resource[0].section[3].entry[0])
```

Moreover the "official" java FHIR validator (see https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator) also finds no error when validating the resource against the profile.

Same is true when validating the resource in simplifier.net (https://simplifier.net/validate?scope=KBV.ITA.EAU@1.0.2&fhirVersion=R4) 

![ScreenshotSimplifierValidation](https://user-images.githubusercontent.com/28148886/125492534-fbd66298-89e3-45e8-a661-c8ca317fae17.jpg)

To me this suggest that there is a problem in the Firely validator (for certain FhirPath constraints) when it comes down to validating POCO based resources.
This is especially strengthened by the observation that the Firely validator considers the resource valid when we begin with an ISourceNode (instead of the POCO) as source for the ITypedElement to validate (workaround in the sample project as activated above).

Could you please have a second look?

Thanks!
Thomas

**Comment by marcovisserFurore** [comment]
Hi Thomas,

I have created the following unit test to focus more on the expression:

```c#
        [Fact]
        public void Issue_1785()
        {
            var condition = new Condition() { Onset = new Period(new FhirDateTime(2019), new FhirDateTime(2021)) };

            // expression with POCO
            condition.Predicate("onset.start.exists()").Should().BeTrue(); // succeeds

            condition.Predicate("onsetPeriod.start.exists()").Should().BeTrue(); // fails

            var sourceNode = FhirXmlNode.Parse(condition.ToXml());
            var typedElement = sourceNode.ToTypedElement(new StructureDefinitionSummaryProvider(ZipSource.CreateValidationSource()));

            // expression with TypedElement
            typedElement.Predicate("onset.start.exists()").Should().BeTrue(); // succeeds

            typedElement.Predicate("onsetPeriod.start.exists()").Should().BeTrue(); // succeeds
        }
``` 

You see that the evaluation with POCO objects will fail, when we are using `onsetPeriod`. It succeeds when we use the correct expression `onset`. The TypedElement version does not fail when we are using `onsetPeriod` or `onset`.

We are a bit more forgiving in the TypedElement version when it comes to choice elements.

Simplifier uses the SDK validator in the TypedElement way, therefore Simplifier considers the resource valid.

But actually the POCO version is more correct when you following the [standard](https://hl7.org/fhir/fhirpath.html#polymorphism).

**Comment by ewoutkramer** [comment]
> We are a bit more forgiving in the TypedElement version when it comes to choice elements.
We are indeed, but that's not intentional, so I'd consider this a bug.

But, indeed, the FP expression referring to `onsetPeriod` is incorrect.  So, this issue really points us to *two* issues that interact confusingly in this case.

**Comment by ewoutkramer** [comment]
Since the .NET and Java engines differ in this case (although the spec is really clear on which is valid), I've opened the discussion to try to resolve this across engines here: https://chat.fhir.org/#narrow/stream/179266-fhirpath/topic/Handling.20choice.20elements

**Comment by ewoutkramer** [comment]
Ok, so Grahame is clear about this too, we should refuse `onsetPeriod`, so let's fix this - also add a test to the FhirPath testsuite to make sure the FP engines do *not* support the `onsetPeriod` anymore.
