### ISSUE TITLE
Validator issue: Internal logic failure: StructureDefinition has no snapshot component.

### ISSUE THREAD

**Issue by thvogd** [FirelyTeam/firely-net-sdk#1786]
**Description**
There seems to be an issue with the validator when it comes to validating resources against structure definitions which again refer to other structure definitions.

The validator creates missing snapshots for structure definitions if told (ValidationSettings.GenerateSnapshot = true). However in certain situation this does not work: Some structure definitions are not caught during snapshot preparation phase (maybe those only indirectly refered to by other sd?). During validation the missing snapshot in those structure definitions leads to a fatal validation error:

```
[FATAL] Internal logic failure: StructureDefinition 'http://fhir.de/StructureDefinition/icd-10-gm-primaercode' has no snapshot component.
Parametername: sd (at Bundle.entry[7].resource[0].code[0].coding[0] via Bundle.entry[0].resource[0].section[1].entry[0])
```

Attached you find a solution showing the issue (and a workaround by explicitly creating the missing snapshots).

It would be nice if the validator would create all snapshots required during validation if ValidationSettings.GenerateSnapshot is set to true. 
Don't know whether this is more a feature request than a bug.
However: Thanks a lot for looking into the issue.

**To Reproduce**
See attached solution.
[FirelyValidatorSnapshotCreationProblem.zip](https://github.com/FirelyTeam/firely-net-sdk/files/6734627/FirelyValidatorSnapshotCreationProblem.zip)

**Version used:**
 - FHIR Version: R4
 - Version: 3.3.0

**Comment by ewoutkramer** [comment]
There is one know place where we are dependent on the snapshot being present, and we do not yet generate a snapshot: whena discriminator path for a slice in a StructureDefinition is walking into another StructureDefinition that has no snapshot.  This part of the engine (which is really an alternative FhirPath implementation that understands the dialect used for discriminators) cannot yet generate snapshots.  Something for our team to double check.

In the mean time, instead of letter the Validator create the snapshots, you can use the `Hl7.Fhir.Specification.Source.SnapshotSource`. This is actually a better solution, since it removes the responsibility of generating snapshots from the Validator (in hindsight, the Validator creating the snapshots isn't really a good example of the SRP ;-)).

`SnapshotSource` is an implementation of `IResourceResolver` that wraps another resource resolver and will add a snapshot if the underlying `IResourceResolver` does not provide one.

So, something like:

``` csharp
  var resolver = ZipSource.CreateValidationSource();
  var cachedResolver = new CachedResolver(resolver);
  var snapshotted = new SnapshoSource(cachedResolver);

  validatorSettings.ResourceResolver = snapshotted;
  validatorSettings.GenerateSnapshot = false;   // relieve the validator of its task
```

**Comment by thvogd** [comment]
Hi Ewout,

thanks for your proposal! Using the SnapshotSource is in fact a much better solution than our work around, because we now no longer need to know the "problematic" structure definitions beforehand.

I updated my example project, it now uses your proposal as solution (for whoever may be interested).

[FirelyValidatorSnapshotCreationProblem_V2.zip](https://github.com/FirelyTeam/firely-net-sdk/files/6739544/FirelyValidatorSnapshotCreationProblem_V2.zip)

One question with regards to your proposal: You put the SnapshotSource around the CachedResolver.

```c#
var resolver = ZipSource.CreateValidationSource();
var cachedResolver = new CachedResolver(resolver);
var snapshotted = new SnapshotSource(cachedResolver);

validatorSettings.ResourceResolver = snapshotted;
validatorSettings.GenerateSnapshot = false;   // relieve the validator of its task
```

Wouldn't it be better to put the SnapshotSource inside the CachedResolver to cache the results of the SnapshotSource? Like:

```c#
var resolver = ZipSource.CreateValidationSource();
var snapshotted = new SnapshotSource(resolver);
var cachedResolver = new CachedResolver(snapshotted);

validatorSettings.ResourceResolver = cachedResolver;
validatorSettings.GenerateSnapshot = false;   // relieve the validator of its task
```

Or is it of no concern which one is wrapping the other one, for the SnapshotSource applies caching anyway?

**Comment by ewoutkramer** [comment]
Good point, I was wondering about that too.  But creating a snapshot normally results in a large amount of calls to the underlying IResourceResolver (the snapshot needs to get the definitions for almost all involved core types etc), so it certainly has to go on top of a CachedResolver.  The SnapshotSource - if configured to only create a snapshot when it is not present!!! - will basically become a no-op if there is a snapshot, so I figured you don't need a cache on top of it.  But it wouldn't hurt either.

**Comment by thvogd** [comment]
I see. Thanks for clarifying.

**Comment by marcovisserFurore** [comment]
So the use of a `SnapshotSource` will solve the problem here. We will document this soon on docs.fire.ly. See also [this](https://github.com/FirelyTeam/firely-net-sdk/issues/1841) feature request.
