### ISSUE TITLE
Issue with how nested extensions are formatted

### ISSUE THREAD

**Issue by rcon1012** [FirelyTeam/firely-net-sdk#1798]
I am having issues modeling a complex extension. More specifically, nested extensions that are themselves a list of extensions.

This is the profile we are modelling: http://hl7.org/fhir/us/davinci-drug-formulary/STU1.0.1/StructureDefinition-usdf-CoveragePlan.html

The drug tier complex slice is the where my specific issue lies: http://hl7.org/fhir/us/davinci-drug-formulary/STU1.0.1/StructureDefinition-usdf-DrugTierDefinition-extension.html

So for the drug tier definition, I cannot properly model with your sdk the costSharing extension. By the fhir spec, an extension which is itself a list of extensions isn't modelled as url and value, but simply url and then a list of extensions. https://www.hl7.org/fhir/extensibility.html

Am I missing something in the sdk that would allow this? Below I will post an example of one of the resources that are generated. Note the "valueExtension" field under the costSharing slice which makes this resource model invalid.

`{
    "resourceType": "List",
    "id": "Medicare-A339-FormId7",
    "meta": {
        "source": "Organization/1",
        "profile": ["http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-CoveragePlan"]
    },
    "extension": [{
            "url": "http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-PlanIDType-extension",
            "valueString": "Plan-Type"
        }, {
            "url": "http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-Network-extension",
            "valueString": "Express Scripts Network"
        }, {
            "url": "http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-SummaryURL-extension",
            "valueString": "https://www.upmchealthplan.com/find-a-medication/default.aspx#medication"
        }, {
            "extension": [{
                    "url": "drugTierID",
                    "valueCodeableConcept": {
                        "coding": [{
                                "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-DrugTierCS",
                                "code": "preferred-generic"
                            }
                        ],
                        "text": "Preferred Generic: Commonly prescribed generic drugs."
                    }
                }, {
                    "url": "mailOrder",
                    "valueBoolean": true
                }, {
                    "url": "costSharing",
                    "valueExtension": {
                        "extension": [{
                                "url": "pharmacyType",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-PharmacyTypeCS",
                                            "code": "3-month-in-mail"
                                        }
                                    ],
                                    "text": "3 month in network mail order: 3 Month Supply via in-network mail order pharmacy."
                                }
                            }, {
                                "url": "copayAmount",
                                "valueMoney": {
                                    "value": 0,
                                    "currency": "USD"
                                }
                            }, {
                                "url": "copayOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CopayOptionCS",
                                            "code": "no-charge"
                                        }
                                    ],
                                    "text": "No Charge: No cost sharing is charged (this indicates that this benefit is not subject to the deductible)."
                                }
                            }, {
                                "url": "coinsuranceRate",
                                "valueDecimal": 0
                            }, {
                                "url": "coinsuranceOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CoinsuranceOptionCS",
                                            "code": "no-charge"
                                        }
                                    ],
                                    "text": "No Charge: No cost sharing is charged (this indicates that this benefit is not subject to the deductible)."
                                }
                            }
                        ]
                    }
                }
            ],
            "url": "http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-DrugTierDefinition-extension"
        }, {
            "extension": [{
                    "url": "drugTierID",
                    "valueCodeableConcept": {
                        "coding": [{
                                "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-DrugTierCS",
                                "code": "generic"
                            }
                        ],
                        "text": "Generic: Commonly prescribed generic drugs that cost more than drugs in the ‘preferred generic’ tier."
                    }
                }, {
                    "url": "mailOrder",
                    "valueBoolean": true
                }, {
                    "url": "costSharing",
                    "valueExtension": {
                        "extension": [{
                                "url": "pharmacyType",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-PharmacyTypeCS",
                                            "code": "3-month-in-mail"
                                        }
                                    ],
                                    "text": "3 month in network mail order: 3 Month Supply via in-network mail order pharmacy."
                                }
                            }, {
                                "url": "copayAmount",
                                "valueMoney": {
                                    "value": 20,
                                    "currency": "USD"
                                }
                            }, {
                                "url": "copayOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CopayOptionCS",
                                            "code": "before-deductible"
                                        }
                                    ],
                                    "text": "Before Deductible: The consumer first pays the copay, and any net remaining allowed charges accrue to the deductible (this indicates that this benefit is subject to the deductible)."
                                }
                            }, {
                                "url": "coinsuranceRate",
                                "valueDecimal": 0
                            }, {
                                "url": "coinsuranceOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CoinsuranceOptionCS",
                                            "code": "no-charge"
                                        }
                                    ],
                                    "text": "No Charge: No cost sharing is charged (this indicates that this benefit is not subject to the deductible)."
                                }
                            }
                        ]
                    }
                }
            ],
            "url": "http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-DrugTierDefinition-extension"
        }, {
            "extension": [{
                    "url": "drugTierID",
                    "valueCodeableConcept": {
                        "coding": [{
                                "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-DrugTierCS",
                                "code": "preferred-brand"
                            }
                        ],
                        "text": "Preferred Brand: Brand name drugs"
                    }
                }, {
                    "url": "mailOrder",
                    "valueBoolean": true
                }, {
                    "url": "costSharing",
                    "valueExtension": {
                        "extension": [{
                                "url": "pharmacyType",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-PharmacyTypeCS",
                                            "code": "3-month-in-mail"
                                        }
                                    ],
                                    "text": "3 month in network mail order: 3 Month Supply via in-network mail order pharmacy."
                                }
                            }, {
                                "url": "copayAmount",
                                "valueMoney": {
                                    "value": 118,
                                    "currency": "USD"
                                }
                            }, {
                                "url": "copayOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CopayOptionCS",
                                            "code": "before-deductible"
                                        }
                                    ],
                                    "text": "Before Deductible: The consumer first pays the copay, and any net remaining allowed charges accrue to the deductible (this indicates that this benefit is subject to the deductible)."
                                }
                            }, {
                                "url": "coinsuranceRate",
                                "valueDecimal": 0
                            }, {
                                "url": "coinsuranceOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CoinsuranceOptionCS",
                                            "code": "no-charge"
                                        }
                                    ],
                                    "text": "No Charge: No cost sharing is charged (this indicates that this benefit is not subject to the deductible)."
                                }
                            }
                        ]
                    }
                }
            ],
            "url": "http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-DrugTierDefinition-extension"
        }, {
            "extension": [{
                    "url": "drugTierID",
                    "valueCodeableConcept": {
                        "coding": [{
                                "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-DrugTierCS",
                                "code": "non-preferred-brand"
                            }
                        ],
                        "text": "Non-preferred Brand: Brand name drugs that cost more than ‘brand’ drugs."
                    }
                }, {
                    "url": "mailOrder",
                    "valueBoolean": true
                }, {
                    "url": "costSharing",
                    "valueExtension": {
                        "extension": [{
                                "url": "pharmacyType",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-PharmacyTypeCS",
                                            "code": "3-month-in-mail"
                                        }
                                    ],
                                    "text": "3 month in network mail order: 3 Month Supply via in-network mail order pharmacy."
                                }
                            }, {
                                "url": "copayAmount",
                                "valueMoney": {
                                    "value": 300,
                                    "currency": "USD"
                                }
                            }, {
                                "url": "copayOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CopayOptionCS",
                                            "code": "before-deductible"
                                        }
                                    ],
                                    "text": "Before Deductible: The consumer first pays the copay, and any net remaining allowed charges accrue to the deductible (this indicates that this benefit is subject to the deductible)."
                                }
                            }, {
                                "url": "coinsuranceRate",
                                "valueDecimal": 0
                            }, {
                                "url": "coinsuranceOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CoinsuranceOptionCS",
                                            "code": "no-charge"
                                        }
                                    ],
                                    "text": "No Charge: No cost sharing is charged (this indicates that this benefit is not subject to the deductible)."
                                }
                            }
                        ]
                    }
                }
            ],
            "url": "http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-DrugTierDefinition-extension"
        }, {
            "extension": [{
                    "url": "drugTierID",
                    "valueCodeableConcept": {
                        "coding": [{
                                "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-DrugTierCS",
                                "code": "preferred-generic"
                            }
                        ],
                        "text": "Preferred Generic: Commonly prescribed generic drugs."
                    }
                }, {
                    "url": "mailOrder",
                    "valueBoolean": false
                }, {
                    "url": "costSharing",
                    "valueExtension": {
                        "extension": [{
                                "url": "pharmacyType",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-PharmacyTypeCS",
                                            "code": "1-month-in-retail"
                                        }
                                    ],
                                    "text": "1 month in network retail: 1 Month Supply via in-network retail pharmacy."
                                }
                            }, {
                                "url": "copayAmount",
                                "valueMoney": {
                                    "value": 15,
                                    "currency": "USD"
                                }
                            }, {
                                "url": "copayOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CopayOptionCS",
                                            "code": "before-deductible"
                                        }
                                    ],
                                    "text": "Before Deductible: The consumer first pays the copay, and any net remaining allowed charges accrue to the deductible (this indicates that this benefit is subject to the deductible)."
                                }
                            }, {
                                "url": "coinsuranceRate",
                                "valueDecimal": 0
                            }, {
                                "url": "coinsuranceOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CoinsuranceOptionCS",
                                            "code": "no-charge"
                                        }
                                    ],
                                    "text": "No Charge: No cost sharing is charged (this indicates that this benefit is not subject to the deductible)."
                                }
                            }
                        ]
                    }
                }
            ],
            "url": "http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-DrugTierDefinition-extension"
        }, {
            "extension": [{
                    "url": "drugTierID",
                    "valueCodeableConcept": {
                        "coding": [{
                                "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-DrugTierCS",
                                "code": "generic"
                            }
                        ],
                        "text": "Generic: Commonly prescribed generic drugs that cost more than drugs in the ‘preferred generic’ tier."
                    }
                }, {
                    "url": "mailOrder",
                    "valueBoolean": false
                }, {
                    "url": "costSharing",
                    "valueExtension": {
                        "extension": [{
                                "url": "pharmacyType",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-PharmacyTypeCS",
                                            "code": "1-month-in-retail"
                                        }
                                    ],
                                    "text": "1 month in network retail: 1 Month Supply via in-network retail pharmacy."
                                }
                            }, {
                                "url": "copayAmount",
                                "valueMoney": {
                                    "value": 20,
                                    "currency": "USD"
                                }
                            }, {
                                "url": "copayOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CopayOptionCS",
                                            "code": "before-deductible"
                                        }
                                    ],
                                    "text": "Before Deductible: The consumer first pays the copay, and any net remaining allowed charges accrue to the deductible (this indicates that this benefit is subject to the deductible)."
                                }
                            }, {
                                "url": "coinsuranceRate",
                                "valueDecimal": 0
                            }, {
                                "url": "coinsuranceOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CoinsuranceOptionCS",
                                            "code": "no-charge"
                                        }
                                    ],
                                    "text": "No Charge: No cost sharing is charged (this indicates that this benefit is not subject to the deductible)."
                                }
                            }
                        ]
                    }
                }
            ],
            "url": "http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-DrugTierDefinition-extension"
        }, {
            "extension": [{
                    "url": "drugTierID",
                    "valueCodeableConcept": {
                        "coding": [{
                                "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-DrugTierCS",
                                "code": "preferred-brand"
                            }
                        ],
                        "text": "Preferred Brand: Brand name drugs"
                    }
                }, {
                    "url": "mailOrder",
                    "valueBoolean": false
                }, {
                    "url": "costSharing",
                    "valueExtension": {
                        "extension": [{
                                "url": "pharmacyType",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-PharmacyTypeCS",
                                            "code": "1-month-in-retail"
                                        }
                                    ],
                                    "text": "1 month in network retail: 1 Month Supply via in-network retail pharmacy."
                                }
                            }, {
                                "url": "copayAmount",
                                "valueMoney": {
                                    "value": 47,
                                    "currency": "USD"
                                }
                            }, {
                                "url": "copayOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CopayOptionCS",
                                            "code": "before-deductible"
                                        }
                                    ],
                                    "text": "Before Deductible: The consumer first pays the copay, and any net remaining allowed charges accrue to the deductible (this indicates that this benefit is subject to the deductible)."
                                }
                            }, {
                                "url": "coinsuranceRate",
                                "valueDecimal": 0
                            }, {
                                "url": "coinsuranceOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CoinsuranceOptionCS",
                                            "code": "no-charge"
                                        }
                                    ],
                                    "text": "No Charge: No cost sharing is charged (this indicates that this benefit is not subject to the deductible)."
                                }
                            }
                        ]
                    }
                }
            ],
            "url": "http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-DrugTierDefinition-extension"
        }, {
            "extension": [{
                    "url": "drugTierID",
                    "valueCodeableConcept": {
                        "coding": [{
                                "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-DrugTierCS",
                                "code": "non-preferred-brand"
                            }
                        ],
                        "text": "Non-preferred Brand: Brand name drugs that cost more than ‘brand’ drugs."
                    }
                }, {
                    "url": "mailOrder",
                    "valueBoolean": false
                }, {
                    "url": "costSharing",
                    "valueExtension": {
                        "extension": [{
                                "url": "pharmacyType",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-PharmacyTypeCS",
                                            "code": "1-month-in-retail"
                                        }
                                    ],
                                    "text": "1 month in network retail: 1 Month Supply via in-network retail pharmacy."
                                }
                            }, {
                                "url": "copayAmount",
                                "valueMoney": {
                                    "value": 100,
                                    "currency": "USD"
                                }
                            }, {
                                "url": "copayOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CopayOptionCS",
                                            "code": "before-deductible"
                                        }
                                    ],
                                    "text": "Before Deductible: The consumer first pays the copay, and any net remaining allowed charges accrue to the deductible (this indicates that this benefit is subject to the deductible)."
                                }
                            }, {
                                "url": "coinsuranceRate",
                                "valueDecimal": 0
                            }, {
                                "url": "coinsuranceOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CoinsuranceOptionCS",
                                            "code": "no-charge"
                                        }
                                    ],
                                    "text": "No Charge: No cost sharing is charged (this indicates that this benefit is not subject to the deductible)."
                                }
                            }
                        ]
                    }
                }
            ],
            "url": "http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-DrugTierDefinition-extension"
        }, {
            "extension": [{
                    "url": "drugTierID",
                    "valueCodeableConcept": {
                        "coding": [{
                                "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-DrugTierCS",
                                "code": "specialty"
                            }
                        ],
                        "text": "Specialty: Drugs used to treat complex conditions like cancer and multiple sclerosis. They can be generic or brand name, and are typically the most expensive drugs on the formulary."
                    }
                }, {
                    "url": "mailOrder",
                    "valueBoolean": false
                }, {
                    "url": "costSharing",
                    "valueExtension": {
                        "extension": [{
                                "url": "pharmacyType",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-PharmacyTypeCS",
                                            "code": "1-month-in-retail"
                                        }
                                    ],
                                    "text": "1 month in network retail: 1 Month Supply via in-network retail pharmacy."
                                }
                            }, {
                                "url": "copayAmount",
                                "valueMoney": {
                                    "value": 0,
                                    "currency": "USD"
                                }
                            }, {
                                "url": "copayOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CopayOptionCS",
                                            "code": "no-charge"
                                        }
                                    ],
                                    "text": "No Charge: No cost sharing is charged (this indicates that this benefit is not subject to the deductible)."
                                }
                            }, {
                                "url": "coinsuranceRate",
                                "valueDecimal": 0.33
                            }, {
                                "url": "coinsuranceOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CoinsuranceOptionCS",
                                            "code": "no-charge"
                                        }
                                    ],
                                    "text": "No Charge: No cost sharing is charged (this indicates that this benefit is not subject to the deductible)."
                                }
                            }
                        ]
                    }
                }
            ],
            "url": "http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-DrugTierDefinition-extension"
        }, {
            "extension": [{
                    "url": "drugTierID",
                    "valueCodeableConcept": {
                        "coding": [{
                                "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-DrugTierCS",
                                "code": "medical-service"
                            }
                        ],
                        "text": "Medical Service: Drugs that must be administered by a clinician or in a facility and may be covered under a medical benefit."
                    }
                }, {
                    "url": "mailOrder",
                    "valueBoolean": false
                }, {
                    "url": "costSharing",
                    "valueExtension": {
                        "extension": [{
                                "url": "pharmacyType",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-PharmacyTypeCS",
                                            "code": "1-month-in-retail"
                                        }
                                    ],
                                    "text": "1 month in network retail: 1 Month Supply via in-network retail pharmacy."
                                }
                            }, {
                                "url": "copayAmount",
                                "valueMoney": {
                                    "value": 0,
                                    "currency": "USD"
                                }
                            }, {
                                "url": "copayOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CopayOptionCS",
                                            "code": "no-charge"
                                        }
                                    ],
                                    "text": "No Charge: No cost sharing is charged (this indicates that this benefit is not subject to the deductible)."
                                }
                            }, {
                                "url": "coinsuranceRate",
                                "valueDecimal": 0.2
                            }, {
                                "url": "coinsuranceOption",
                                "valueCodeableConcept": {
                                    "coding": [{
                                            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CoinsuranceOptionCS",
                                            "code": "no-charge"
                                        }
                                    ],
                                    "text": "No Charge: No cost sharing is charged (this indicates that this benefit is not subject to the deductible)."
                                }
                            }
                        ]
                    }
                }
            ],
            "url": "http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-DrugTierDefinition-extension"
        }
    ],
    "identifier": [{
            "system": "http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-PlanID-extension",
            "value": "Medicare"
        }
    ],
    "status": "current",
    "mode": "working"
}
`

Here is the relevant code for reference:
`
private Extension BuildDrugTierExtension(TierInfo planInfo)
        {
            var drugTierExtension = new Extension
            {
                Url = FormularyConstants.DrugPlanExtensionUrls.DrugTierDefinitionUrl
            };

            var costSharingExtensionValue = new Extension
            {
                Extension = new List<Extension>
                {
                    new Extension("pharmacyType", GetPharmacyTypeCodeableConcept(planInfo.PharmacyType))
                }
            };

            if (planInfo.IsDollarAmount)
            {
                costSharingExtensionValue.Extension.Add(new Extension("copayAmount", new Money()
                {
                    Value = planInfo.Amount.ToDecimal(),
                    Currency = Money.Currencies.USD
                }));

                costSharingExtensionValue.Extension.Add(new Extension(
                    "copayOption", 
                    GetCopayOption(planInfo.DeductibleApplies, planInfo.Amount)));
            }
            else
            {
                costSharingExtensionValue.Extension.Add(new Extension("copayAmount", new Money()
                {
                    Value = 0,
                    Currency = Money.Currencies.USD
                }));

                costSharingExtensionValue.Extension.Add(new Extension(
                    "copayOption",
                    GetCopayOption(planInfo.DeductibleApplies, 0)));
            }
            
            if (planInfo.IsPercentage)
            {
                costSharingExtensionValue.Extension.Add(new Extension(
                    "coinsuranceRate", 
                    new FhirDecimal(planInfo.Amount)));
                costSharingExtensionValue.Extension.Add(new Extension(
                    "coinsuranceOption", 
                    GetCoinsuranceOption(planInfo.DeductibleApplies, planInfo.Amount)));
            }
            else
            {
                costSharingExtensionValue.Extension.Add(new Extension(
                    "coinsuranceRate",
                    new FhirDecimal(0)));
                costSharingExtensionValue.Extension.Add(new Extension(
                    "coinsuranceOption",
                    GetCoinsuranceOption(planInfo.DeductibleApplies, 0)));
            }

            drugTierExtension.Extension = new List<Extension>()
            {
                new Extension("drugTierID", planInfo.FhirTierIdentifier),
                new Extension("mailOrder", new FhirBoolean(planInfo.PharmacyType == PharmacyType.MailOrder)),
                new Extension("costSharing", costSharingExtensionValue)
            };

            return drugTierExtension;
        }`

Then this method is simply called like this:
`coveragePlan.Extension.Add(BuildDrugTierExtension(planInfo));`

I am on version 3.4.0 for all of your nuget packages.

Lastly, here is how the serializer is being instantied:
`private static readonly FhirJsonSerializer _fhirJsonSerializer = new FhirJsonSerializer(new SerializerSettings
        {
            AppendNewLine = true,
            TrimWhiteSpacesInXml = true,
            Pretty = false
        });`

**Comment by marcovisserFurore** [comment]
Hi @rcon1012,

Thanks for reaching out to us.  This extension `costSharing` has a value of type `Extension` (`valueExtension`), which is not allowed. In the FHIR specification about [extensions](https://www.hl7.org/fhir/extensibility.html) you can see which types are allowed, like boolean, date, Code, Address, etc.
When I inspect the [definition](http://hl7.org/fhir/us/davinci-drug-formulary/STU1.0.1/StructureDefinition-usdf-DrugTierDefinition-extension.html) of this extension, then the json should look like this:

```json
{
   "url":"costSharing",
    "extension":[
       {
          "url":"pharmacyType",
          "valueCodeableConcept":{
             "coding":[
                {
                   "system":"http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-PharmacyTypeCS",
                   "code":"3-month-in-mail"
                }
             ],
             "text":"3 month in network mail order: 3 Month Supply via in-network mail order pharmacy."
          }
       },
       {
          "url":"copayAmount",
          "valueMoney":{
             "value":0,
             "currency":"USD"
          }
       },
       {
          "url":"copayOption",
          "valueCodeableConcept":{
             "coding":[
                {
                   "system":"http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CopayOptionCS",
                   "code":"no-charge"
                }
             ],
             "text":"No Charge: No cost sharing is charged (this indicates that this benefit is not subject to the deductible)."
          }
       },
       {
          "url":"coinsuranceRate",
          "valueDecimal":0
       },
       {
          "url":"coinsuranceOption",
          "valueCodeableConcept":{
             "coding":[
                {
                   "system":"http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CoinsuranceOptionCS",
                   "code":"no-charge"
                }
             ],
             "text":"No Charge: No cost sharing is charged (this indicates that this benefit is not subject to the deductible)."
          }
       }
    ]
}
```

In code this would be like this:

```c#
   var costSharing = new Extension() { Url = "costSharing" };
   costSharing.AddExtension("pharmacyType", new CodeableConcept("http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-PharmacyTypeCS", "3-month-in-mail"));
   costSharing.AddExtension("copayAmount", new Money() {Value = 0, Currency = "USD" );
   costSharing.AddExtension("copayOption", new CodeableConcept("http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CopayOptionCS", "no-charge"));
   costSharing.AddExtension("coinsuranceRate", new FhirDecimal(0));
   costSharing.AddExtension("coinsuranceOption", new CodeableConcept("http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CoinsuranceOptionCS", "no-charge"));


```

**Comment by rcon1012** [comment]
That is what I am aware of, it is when I add the costSharing extension to the that it serializes to valueExtension. I am wondering if I am somehow misusing the API.

Here is a more concise example of how it is serializing the extension.

```
var costSharing = new Extension() { Url = "costSharing" };
costSharing.AddExtension("pharmacyType", new CodeableConcept("http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-PharmacyTypeCS", "3-month-in-mail"));
costSharing.AddExtension("copayAmount", new Money() { Value = 0, Currency = Money.Currencies.USD });
costSharing.AddExtension("copayOption", new CodeableConcept("http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CopayOptionCS", "no-charge"));
costSharing.AddExtension("coinsuranceRate", new FhirDecimal(0));
costSharing.AddExtension("coinsuranceOption", new CodeableConcept("http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CoinsuranceOptionCS", "no-charge"));

var drugTierExtension = new Extension
{
    Url = FormularyConstants.DrugPlanExtensionUrls.DrugTierDefinitionUrl
};

drugTierExtension.AddExtension("costSharing", costSharing);

return drugTierExtension;
```
This generates the following:
```
{
    "extension": [{
            "url": "costSharing",
            "valueExtension": {
                "extension": [{
                        "url": "pharmacyType",
                        "valueCodeableConcept": {
                            "coding": [{
                                    "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-PharmacyTypeCS",
                                    "code": "3-month-in-mail"
                                }
                            ]
                        }
                    }, {
                        "url": "copayAmount",
                        "valueMoney": {
                            "value": 0,
                            "currency": "USD"
                        }
                    }, {
                        "url": "copayOption",
                        "valueCodeableConcept": {
                            "coding": [{
                                    "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CopayOptionCS",
                                    "code": "no-charge"
                                }
                            ]
                        }
                    }, {
                        "url": "coinsuranceRate",
                        "valueDecimal": 0
                    }, {
                        "url": "coinsuranceOption",
                        "valueCodeableConcept": {
                            "coding": [{
                                    "system": "http://hl7.org/fhir/us/davinci-drug-formulary/CodeSystem/usdf-CoinsuranceOptionCS",
                                    "code": "no-charge"
                                }
                            ]
                        }
                    }
                ],
                "url": "costSharing"
            }
        }
    ],
    "url": "http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-DrugTierDefinition-extension"
}
```

**Comment by rcon1012** [comment]
This code works however, so my original suspicion about misusing your sdk may be correct.

```
drugTierExtension.Extension.Add(costSharing);

**Comment by mbaltus** [comment]
Yes, correct. The difference is that `drugTierExtension.AddExtension("costSharing", costSharing);` is adding an extension with the costSharing extension as the value, resulting in `{ "url": "costSharing", "valueExtension": "[all the costSharing details]"}`, which is not allowed.
Since your costSharing already is an extension itself, the correct way is to add it to the list of extensions with your second example: `drugTierExtension.Extension.Add(costSharing);`.
