### ISSUE TITLE
XML escape of Hl7.Fhir.Serialization.FhirXmlSerializer is unavailable. 

### ISSUE THREAD

**Issue by KenNakane** [FirelyTeam/firely-net-sdk#1804]
:information_source: Do you want to ask something or start a discussion, then go [here](https://github.com/FirelyTeam/firely-net-sdk/discussions)

**Describe the bug**
XML escape of Hl7.Fhir.Serialization.FhirXmlSerializer is unavailable. 
FhirJsonSerializer is no problem.

**To Reproduce**
1. Set 'Quantity.QuantityComparator.LessThan' to 'Quantity.Comparator' or set XML escape characters(e.g. <, &...) to any other string properties.
2. Serialize resource by Hl7.Fhir.Serialization.FhirXmlSerializer.SerializeToString or any other serialize methods.
3. See error 'Name cannot begin with the '6' character, hexadecimal value 0x36. Line 1, position 76'(I set <65 to valueQuantity's comparator and value).

**Expected behavior**
'Quantity.QuantityComparator.LessThan' escape to '&lt;'.
Other string  properties XML escape is available.

**Screenshots**
None.

**Version used:**
 - FHIR Version: R4
 - Version: 3.2.0

**Additional context**
None.

**Comment by mbaltus** [comment]
@KenNakane Can you give a code example?
I've just tried this, and it works without errors:

```
   var q = new Quantity();
   q.Comparator = Quantity.QuantityComparator.LessThan;
   q.Value = 100;
   var output = new FhirXmlSerializer().SerializeToString(q);
   // output is now "<Quantity xmlns=\"http://hl7.org/fhir\"><value value=\"100\" /><comparator value=\"&lt;\" /></Quantity>"
```

**Comment by KenNakane** [comment]
Hi Mirjam,

I resoleved the problem.
The cause of problem is narrative data as the following.

    "text": {
      "status": "generated",
      "div": "<p><b>Weight-for-Height: </b><65%</p>"
    }

xhtml wasn't escaped on my code of Observation.
XML Serializer is no problem.

Thanks.

2021年7月8日(木) 16:07 Mirjam Baltus ***@***.***>:

**Comment by marcovisserFurore** [comment]
Problem has been solved, closing the issue.
