### ISSUE TITLE
Upgraded from R3 to R4 - Getting IResourceResolver Exception

### ISSUE THREAD

**Issue by puremass** [FirelyTeam/firely-net-sdk#1808]
I just upgraded my facade solution from R3 to R4. When I go to start up my facade I get this exception:

![image](https://user-images.githubusercontent.com/26574390/125322284-9b06ed80-e30b-11eb-8021-d2fc297b6469.png)

System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'Hl7.Fhir.Specification.Source.IResourceResolver' from assembly 'Hl7.Fhir.R4.Specification, Version=3.4.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

  This exception was originally thrown at this call stack:
    System.Reflection.RuntimeAssembly.GetExportedTypes()

Looking for any help you can provide. Thanks!

**Comment by marcovisserFurore** [comment]
Hi @puremass, 
Try to add the package `Hl7.Fhir.Support.Poco` in the project .csproj file where the `CreateWebHostBuilder` resides:

```xml
<ItemGroup>
    <PackageReference Include="Hl7.Fhir.Support.Poco" Version="3.4.0" /> 
</ItemGroup>
``` 
The SDK cannot find the assembly and to add this in your project it should be able to load the assembly. The `IResourceResolver` is located in the package `Hl7.Fhir.Support.Poco` and not in `Hl7.Fhir.Specification.R4` (anymore).

**Comment by puremass** [comment]
I added Hl7.Fhir.Support.Poco and I still get the same exception.

![image](https://user-images.githubusercontent.com/26574390/125454551-ce3fb97a-0fc0-42b8-adc0-7bd01a6055e2.png)

**Comment by puremass** [comment]
So I just install the 3.0.0 versions of those packages? I still get a similar exception.

![image](https://user-images.githubusercontent.com/26574390/125455604-469f4f2e-20f0-4dba-9f58-65466874e806.png)


System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'Hl7.Fhir.Specification.Source.IResourceResolver' from assembly 'Hl7.Fhir.R4.Specification, Version=3.0.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

  This exception was originally thrown at this call stack:
    System.Reflection.RuntimeAssembly.GetExportedTypes()
    
    
![image](https://user-images.githubusercontent.com/26574390/125455745-5582e190-6efd-4fba-8b80-b024783b809d.png)

**Comment by puremass** [comment]
![image](https://user-images.githubusercontent.com/26574390/125466353-77081bd7-27e4-4465-a0a7-93e8bfb1feab.png)

**Comment by puremass** [comment]
I cleaned my solutions, removed and restored the nuget packages after I updated them, and rebuilt. The bin version is 3.0.0. I am still getting the IResourceResolver exception. The solution and project is fairly simple. I can't find anything that is 1.9.0 or lower.

**Comment by puremass** [comment]
This is the only other project with Vonk references in the solution. The facade project references this project.
![image](https://user-images.githubusercontent.com/26574390/125468127-ef5f60f6-dec6-4896-8ee6-087c638525c3.png)

They are all 4.2.0 in both projects.

I did not set up this project/solution so I wasn't exactly sure where to look for vonk plug-ins. I did see this list in the license json file.

![image](https://user-images.githubusercontent.com/26574390/125468736-19c009fa-3af2-463e-a5a1-ae7306a020b8.png)

**Comment by marcovisserFurore** [comment]
The plugin directory is normally located in `.\plugins`, or otherwise defined in `appsettings.json` (`PipelineOptions.PluginDirectory`).

@mbaltus : can you help us out here? I think this is more a Firely Server issue, then a SDK issue.

**Comment by puremass** [comment]
This is from my appsettings file.

![image](https://user-images.githubusercontent.com/26574390/125477039-39784e74-3ba8-4bc8-8b8e-e5b80745a67c.png)

**Comment by mbaltus** [comment]
@puremass  Could you send your logfile to 'server at fire dot ly' so I can take a closer look at this issue?

**Comment by puremass** [comment]
Sorry I had a death in the family and am taking 3 unexpected days off. I will be back to work on Monday and I will get you this info.

**Comment by puremass** [comment]
Where do I obtain this log file or how do I turn logging on? I don't see a log file anywhere. I have attached the information from Visual Studio when I try to start up the facade.
[Vonk Facade Log.txt](https://github.com/FirelyTeam/firely-net-sdk/files/6842056/Vonk.Facade.Log.txt)

**Comment by mbaltus** [comment]
Sorry to hear about your loss.
The file you included was the one I asked for, so I'll check to see if I can find anything. If you could email us at the address I mentioned, that will help to discuss this further.

**Comment by mbaltus** [comment]
Hi @puremass, the problem is that you are using Vonk 3.9.2 libraries on the 4.2.0 version of the Firely Server. The 3.9.2 libraries have a dependency on the 1.9.0 version of the SDK and use the IResourceResolver. If you align the version of the Vonk libraries with the version of Firely Server, this issue will be resolved.
