### ISSUE TITLE
Make sure we do not propagate "publishing extensions" while creating a snapshot

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#1814]
**Is your feature request related to a problem? Please describe.**
The .NET snapshot generator still propagates a set of extensions that do not make sense to be propagated from a base/core profile into a derived profile.

**Describe the solution you'd like**
A full solution is described here: https://jira.hl7.org/browse/FHIR-28441, but this requires authors of some extensions to align with this solution too - which won't be the case for older extensions.  So, we should at least make sure we don't propagate the list of extensions enumerated in Lloyd comment at the bottom of the page (https://jira.hl7.org/browse/FHIR-28441?focusedCommentId=177188&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-177188).

**Comment by mmsmits** [comment]
Remove the extensions when resolving the base
