### ISSUE TITLE
Comment for Extension.value[x] is wrongly set to "A stream of bytes, base64 encoded"

### ISSUE THREAD

**Issue by Rob5045** [FirelyTeam/firely-net-sdk#1828]
When updating an Extension resource through the snapshot generator, the comment for the element **Extension.value[x]** is wrongly set to _"A stream of bytes, base64 encoded"_. This is caused by 

        public static ElementDefinition.TypeRefComponent PrimaryType(this ElementDefinition defn)
        {
            return defn.Type != null && defn.Type.Count > 0 ? defn.Type[0] : null;
        }

always selecting the first type as the primary type even if there are more to choose from. In this case the **base64Binary** is selected and somehow the comment for that type will end up in the resource. If I select a different type (e.g. boolean) as the primary type, the comment stays null. I'm not sure what the best selection criterium would be to pick an appropriate type from a list as the primary type here.

**To Reproduce**

        [TestMethod]
        public async T.Task TestExtensionValueXCommentShouldBeNull()
        {
            const string ElementId = "Extension.value[x]";

            var zipSource = ZipSource.CreateValidationSource();
            var resolver = new MultiResolver(zipSource);
            var sd = await resolver.FindStructureDefinitionForCoreTypeAsync(nameof(Extension));

            var element = sd.Snapshot.Element.Single(x => x.ElementId == ElementId);
            element.Comment.Should().BeNull();

            var generator = new SnapshotGenerator(resolver, SnapshotGeneratorSettings.CreateDefault());

            generator.PrepareElement += (sender, e) =>
            {
                if (e.Element.Path == ElementId)
                {
                    // BaseElement for Extension.value[x] is "base64Binary"
                    Debug.WriteLine($"Element:{ElementId} BaseElement:{e.BaseElement.ElementId}");
                }
            };

            // Act
            await generator.UpdateAsync(sd);

            // Assert
            element = sd.Snapshot.Element.Single(x => x.ElementId == ElementId);
            element.Comment.Should().BeNull();
        }

**Version used:**
 - FHIR Version: R4
 - Version: 3.4.0

**Comment by mmsmits** [comment]
Ok, this is a bug indeed. But it goed a bit further than just comments. 
When defining a new element, the snapshot generator merges the information from a type into and the diff element, into the new element, and in the case of a polymorphic element, it indeed uses the first type of the list for this. 

However, in my opinion, it shouldn't use a type at all, and copy the polymorphic element over as is, no merging at all. 
We encountered something similar before here: https://github.com/FirelyTeam/firely-net-sdk/issues/1540
We solved it there for the constraints array specifically. But I'll see if I can solve it more generally this time.
