### ISSUE TITLE
Missing invariant check txt-2 on Narrative.div

### ISSUE THREAD

**Issue by Rob5045** [FirelyTeam/firely-net-sdk#1829]
According to the Fhir specification there should be a check on the content of the div to make sure it does not contains white-space only (invariant txt-2). 

Link to specification:
https://www.hl7.org/fhir/narrative-definitions.html#Narrative.div

**Version used:**
 - FHIR Version: R4
 - Version: 3.4.0

**Comment by marcovisserFurore** [comment]
Hi @Rob5045,

Looking at the [profiles](https://github.com/FirelyTeam/firely-net-sdk/blob/develop-r4/src/Hl7.Fhir.Specification/data/profiles-types.xml) that we ship with the package Hl7.Fhir.Specification.R4, I see that the element `Narrative.div` has the following constraints:

```xml
<constraint>
  <key value="txt-1" />
  <severity value="error" />
  <human value="The narrative SHALL contain only the basic html formatting elements and attributes described in chapters 7-11 (except section 4 of chapter 9) and 15 of the HTML 4.0 standard, &lt;a&gt; elements (either name or href), images and internally contained style attributes" />
  <expression value="htmlChecks()" />
  <xpath value="not(descendant-or-self::*[not(local-name(.)=('a', 'abbr', 'acronym', 'b', 'big', 'blockquote', 'br', 'caption', 'cite', 'code', 'col', 'colgroup', 'dd', 'dfn', 'div', 'dl', 'dt', 'em', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'i', 'img', 'li', 'ol', 'p', 'pre', 'q', 'samp', 'small', 'span', 'strong', 'sub', 'sup', 'table', 'tbody', 'td', 'tfoot', 'th', 'thead', 'tr', 'tt', 'ul', 'var'))]) and not(descendant-or-self::*/@*[not(name(.)=('abbr', 'accesskey', 'align', 'alt', 'axis', 'bgcolor', 'border', 'cellhalign', 'cellpadding', 'cellspacing', 'cellvalign', 'char', 'charoff', 'charset', 'cite', 'class', 'colspan', 'compact', 'coords', 'dir', 'frame', 'headers', 'height', 'href', 'hreflang', 'hspace', 'id', 'lang', 'longdesc', 'name', 'nowrap', 'rel', 'rev', 'rowspan', 'rules', 'scope', 'shape', 'span', 'src', 'start', 'style', 'summary', 'tabindex', 'title', 'type', 'valign', 'value', 'vspace', 'width'))])" />
</constraint>
<constraint>
  <key value="txt-2" />
  <severity value="error" />
  <human value="The narrative SHALL have some non-whitespace content" />
  <expression value="htmlChecks()" />
  <xpath value="descendant::text()[normalize-space(.)!=''] or descendant::h:img[@src]" />
</constraint>
```

So `txt-2` is performing the FhirPath function `htmlChecks()`, which is a function of the extended [FhirPath](https://www.hl7.org/fhir/fhirpath.html) set.

In code you can use it like this :
```c#
  var symbolTable = new SymbolTable();
  symbolTable.AddStandardFP();
  symbolTable.AddFhirExtensions();
  
  var fpCompiler = new FhirPathCompiler(symbolTable);

  var compiledExpression = fpCompiler.Compile("htmlChecks()");

  bool succes = compiledExpression .Predicate(instance);
```

The validator (part of the SDK) already uses this extra extension `AddFhirExtensions`.

**Comment by marcovisserFurore** [comment]
Thanks @Rob5045  for the extensive unit tests.

I had a quick look at the source code where we validate the xml in the Narrative to the `fhir.xsd` and `xml.xsd`. Those XML schemas should alarm us of any improper use of xml. Although, I see also that we ignore whitespaces before we give the xml to the schema validator. That smells a bit, so I will investigate it a bit deeper. Thanks again for the unit test, that's always a great help for our team!
