### ISSUE TITLE
Fix "Terminology service failed while validating code 'EUR' (system '')"

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#1857]
Validation of currencies against system `urn:iso:std:iso:4217` will fail since this system is not available as a FHIR ValueSet in `specification.zip`, so the "light-weight" terminology service available for free in the SDK does not know how to validate that code.

From a discussion on Stackoverflow (sorry, no link) it has become clear that this is available in a HL7-published package - we don't directly use these packages (yet) but we could look at how to provide access to this valueset.

**Describe the solution you'd like**
We could copy the provided valueset from the current location (in an NPM package I guess) to the specification.zip - that would probably be the easiest, but since this is a manual step it may require adapting our processes.

**Describe alternatives you've considered**
Switching to NPM packages for validation would solve it all, but that's a big step.

**Comment by ewoutkramer** [comment]
This issue originated from a side discussion to issue #1730. It was also suggested that we could construct a stub that would validate a limited set of currencies, about which I said there:

> The terminology services in the SDK are pretty flexible, as you only have to implement the ValueSetValidateCode() function on the ITerminologyService interface passed to the validator. If you'd create an implementation of this interface that validates the code "EUR" only for that valueset and otherwise passes it on to the original terminology service, you are set.

**Comment by ewoutkramer** [comment]
@UnixNetworks and @darthgizka might be interested in participating in this issue.

**Comment by UnixNetworks** [comment]
Thx for invite. I'll have a look after vacation.

**Comment by mmsmits** [comment]
Info on where to find the ValueSet to add is here:
https://stackoverflow.com/questions/67626063/how-to-make-a-fake-valueset-resource-with-e-g-currency-symbols-for-when-termi
