### ISSUE TITLE
FhirXmlParser -> Bundle -> type checking failure for Ingredient

### ISSUE THREAD

**Issue by mtomorowicz** [FirelyTeam/firely-net-sdk#1858]
Hi guys!

When an Ingredient is present in the Bundle and it contains both _presentation[x]_ and _presentationHighLimit[x]_ nodes (see structure image from http://hl7.org/fhir/2021May/ingredient.html below)

![image](https://user-images.githubusercontent.com/4983014/129721633-10e4910e-514f-4b99-bb42-dc93a6681524.png)

in that order (_pres..[x]_ then _pres..HighLimit[x]_), we are seeing an error whilst attempting to parse the Bundle XML:

`Type checking the data: Choice element 'presentationHighLimitRatio' is suffixed with unexpected type 'HighLimitRatio' (at Bundle.entry[15].resource[0].substance[0].strength[0].presentationHighLimitRatio[0])`

**To Reproduce**
Have an entry in your Bundle similar to 

![image](https://user-images.githubusercontent.com/4983014/129722800-9245d95a-8c9c-4b79-bbd8-5047c5726e27.png)

where _strength_ node has both types of _presentations_ then attempt to parse it with the use of 

`new FhirXmlParser().Parse<Bundle>(...)`

**Expected behavior**
Both _presentation[x]_ and _presentationHighLimit[x]_ should be recognised as valid elements given that they are post-fixed with a correct / allowed value.

**Version used:**
 - "Hl7.Fhir.R5" Version="3.4.0"
 - "Hl7.Fhir.Specification.R5" Version="3.4.0"

Many thanks for your help with this!

**Comment by ewoutkramer** [comment]
Thanks for this, I think we're a bit lazy here in assuming that if `yyyy` is an element then in `yyyXXXX` the `XXXX` must be the type. In fact I know for sure, look at my comments here: https://github.com/FirelyTeam/firely-net-common/blob/develop/src/Hl7.Fhir.ElementModel/TypedElementOnSourceNode.cs#L343:

> this should actually be the longest match, but that's kind of expensive,
> so as long as we don't add stupid ambiguous choices to a single type, this will work.

Well, there you go.

**Comment by ewoutkramer** [comment]
We need to fix this ASAP.

**Comment by mtomorowicz** [comment]
Many thanks for such a fast reply @ewoutkramer, appreciate it. Do you have a release schedule or an idea when this issue could be resolved and released ?

**Comment by ewoutkramer** [comment]
Yes, I have assigned it to the August 2021 sprint, so we will try to fix it this month.

**Comment by mtomorowicz** [comment]
Great, thank you!
