### ISSUE TITLE
Wrong slicing discriminator type and path in BaseElement in snapshot generator PrepareElement event callback

### ISSUE THREAD

**Issue by Rob5045** [FirelyTeam/firely-net-sdk#1892]
A bug has been reported for Forge:
https://firely.atlassian.net/browse/FOR-568

When creating a derived profile for _nl-core.patient.json_ without making any changes, Forge will add unexplainable slicing details in the differential (see Forge Jira issue).

I have created a unit test in this branch to reproduce the problem:
https://github.com/FirelyTeam/firely-net-sdk/tree/forge/FOR-568

The expected behavior is that the BaseElement contains the correct type and path.

 - FHIR Version: STU3 (may apply to other versions as well)
 - Version: develop

**Comment by marcovisserFurore** [comment]
[Update]: the solution in PR #1897 is not merged for R4 and higher, because from R4 the reslicing is done a bit differently.

**Comment by Rob5045** [comment]
Hi marco, does this mean it is not fixed for >= R4 or it does not apply?

**Comment by marcovisserFurore** [comment]
Well, that is the million dollar question. I am not sure. I think (and I hope) it does not apply. I cannot prove it with a unit test at the moment.
