### ISSUE TITLE
Library resource should be marked as a VersionableConformanceResource (R4 & R5)

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/firely-net-sdk#1902]
The Library resource should implement the IVersionableConformanceResource 
https://github.com/FirelyTeam/firely-net-sdk/blob/27c4f64ec2fe2d2bb06faef65d2290d3ad76c07d/src/Hl7.Fhir.Core/Model/IConformanceResource.cs#L77

**Version used:**
 - FHIR Version: R4 and R5 please

**Comment by ewoutkramer** [comment]
Yes, I think so too ;-)

**Comment by marcovisserFurore** [comment]
Only from FHIR version 4 and above. For STU3 is this not possible.

**Comment by ewoutkramer** [comment]
https://github.com/FirelyTeam/firely-net-sdk/issues/1902
