### ISSUE TITLE
.net core 6 unable to find Hl7.Fhir.Model in visual studio

### ISSUE THREAD

**Issue by fasteddys** [FirelyTeam/firely-net-sdk#1936]
Hello the build breaks with .NET core 6 and .Net Core 5, since the nuget does not list Hl7.Fhir.Model in visual studio search while targeting the above frameworks

**Comment by marcovisserFurore** [comment]
Hi @fasteddys,

I tested this and everything works fine. I created a .net 6 core webapp and opened the NuGet Package Manager. I search for hl7.fhir.r4 and you see the results in the attached screenshot.

Did you set the Package source to `nuget.org`?

![image](https://user-images.githubusercontent.com/31658535/148349051-cebeb2d1-c52d-46ef-ba10-114b6c94915c.png)

**Comment by fasteddys** [comment]
thank you. I thought it was its own nuget package, @marcovisserFurore Let me try that and get back

Also can you tell if there a collection of all the resources/types from the FRIR mode and where are they located in your pacakge.
Do you have a client GUI to run tests 
Do you have any sample data
Lastly, I dont see the Payor enrollment resource or payload exchange between providers in a network, how would that work
