### ISSUE TITLE
Cannot Create BinaryResource in FHIR

### ISSUE THREAD

**Issue by mohibakhan** [FirelyTeam/firely-net-sdk#1942]
I am trying to create a Binary Resource and not able to:

Here's the code for creating that:
pdFForms is a string[] of base64strings.

```

            Bundle BinaryBundle = new Bundle();
            BinaryBundle.Type = Bundle.BundleType.Collection;
            try
            {
                foreach (var item in pdfForms)
                {
                    Binary BinaryData = new Binary();

                    BinaryData.Data = Encoding.ASCII.GetBytes(item);
                    BinaryData.ContentType = "application/fhir+json";
                    var binaryResource = client.Create(BinaryData);
                    BinaryBundle.AddResourceEntry(BinaryData, resource + "/BundleResource/" + binaryResource.Id);

                }
            }
            catch (Exception ex)
            {
                throw;
            }
```

I am getting an invalid JSON error:
`The Error I am getting: {"Operation was unsuccessful because of a client error (BadRequest). OperationOutcome: Overall result: FAILURE (1 errors and 0 warnings)\r\n\r\n[ERROR] (no details)(further diagnostics: Error occurred when parsing model: 'Invalid Json encountered. Details: Unexpected character encountered while parsing value: e. Path '', line 0, position 0.'.)."}`

I serialized the BinaryData object and found it was a valid JSON.

{
   "ContentTypeElement":{
      "Value":"application/fhir+json",
      "ElementId":null,
      "Extension":[
         
      ]
   },
   "SecurityContext":null,
   "DataElement":{
      "Value":"**Truncated -  Readability purposes**",
      "ElementId":null,
      "Extension":[
         
      ]
   },
   "IdElement":null,
   "Meta":null,
   "ImplicitRulesElement":null,
   "LanguageElement":null
}

I then went ahead in the Firely-net-sdk repository to the test cases
https://github.com/FirelyTeam/firely-net-sdk/blob/8251e590aea54411a933966db2bde55ecadda849/src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs#L1770

And tried with the same piece of code but again, was unsuccessful

```
var lclient = new LegacyFhirClient(testEndpoint);
                    byte[] arr = File.ReadAllBytes(GetFullPathForExample(@"abc.png"));
                    var binary = new Binary() { Data = arr, ContentType = "image/png" };
                    var binaryResource = lclient.Create(binary); 
```

Now, I am getting an error saying Accept Header value is incorrect.  

Please help in resolving this.

**Comment by mmsmits** [comment]
Hi @mohibakhan ,

To me it seems that the content-Type of first attempt seem incorrect.
```
Binary BinaryData = new Binary();
BinaryData.Data = Encoding.ASCII.GetBytes(item);
BinaryData.ContentType = "application/fhir+json";
var binaryResource = client.Create(BinaryData);
```

The ContentType element of the Binary field is meant to indicate the type of content that is added to the Binary.value element. (so an entry of pdfForms in your case). This is probably not FHIR Json ( ```application/fhir+json```), but I guess a pdf, so (```application/pdf```). Hope that works!

I can't see a reason why you second attempt doesn't work. Can you check the AcceptHeader from your second attempt?

Btw, it's probably better to use ```FhirClient``` instead of ```LegacyFhirClient```, since ```LegacyFhirClient``` is the previous version, but only kept alive for people that the newer implementation didn't work for immediately.

**Comment by mohibakhan** [comment]
So, I tried it again and this is the exception that I get on creating a binary resource

```
Binary BinaryData = new Binary() { Data = Encoding.ASCII.GetBytes(item), ContentType = "application/pdf" };
var binaryResource = BinaryBundleClient.Create(BinaryData);
```

`{"Operation was unsuccessful because of a client error (UnsupportedMediaType). OperationOutcome: Overall result: FAILURE (1 errors and 0 warnings)\r\n\r\n[ERROR] (no details)(further diagnostics: Value supplied for the \"Content-Type\" header is not supported.)."}`

**Comment by mmsmits** [comment]
I really think that this is an error from the FHIR server you are sending this to. 
Can you send it to: http://server.fire.ly/r4 to check if you still get the error?

**Comment by mohibakhan** [comment]
You are correct.  I tried sending to http://server.fire.ly/r4 and it worked.  What might be the problem?

**Comment by mmsmits** [comment]
Probably the FHIR server only accepts application/fhir+json or application/fhir+xml as Content-Types and tries to serialize the content as such. (hence the first error). But you have to contact the developers of the FHIR server for this issue.

**Comment by brianpos** [comment]
The fhir client works fine for our server (and the public facade too) and I have specific unit tests for this feature.
