### ISSUE TITLE
FHIRPath: Improve error message for string functions invocations on different data types

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-net-sdk#1944]
Invoking a string function on a different datatype (without trying to cast it) fails with a correct but unclear error message.
Real life example: A profile on Observation defined an invariant on valueInteger with a constraint using the "matches" function.
This fails with the following error message: ```Invocation of 'matches' failed: Cannot cast from 'Int32' to 'String'```. For a regular user this seems like an internal error. It would be helpful if the FP engine could report that matches cannot be executed on an integer and that an explicit cast is needed.

**Comment by alexzautke** [comment]
See also https://jira.hl7.org/browse/FHIR-37521

**Comment by brianpos** [comment]
My static fhirpath validator has good messages for things like this - I think

**Comment by mmsmits** [comment]
We will not plan this, due to the complexity of the issue.

**Comment by brianpos** [comment]
If anyone wants to have more user friendly messages they can use the static validator project at
https://github.com/brianpos/Hl7.Fhir.FhirPath.Validator
Which validates a parsed Expression.
