### ISSUE TITLE
New xml parser, based on  the new json parser

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/firely-net-sdk#1948]

**Comment by brianpos** [comment]
I'm happy to take this one on, I've already done a version of this and would compare the 2 and get it done.

**Comment by marcovisserFurore** [comment]
Hi Brian, thanks for the offer. My colleague Marten is going to work on this. We would like to share the knowlege in our team, so this is a great opportunity for him to learn it. Perhaps, you can do the review of the PR when he's done with it?

**Comment by brianpos** [comment]
Cool, can we organize a call next week for us to connect and then he can look at what I've already done so we don't end up re-doing work I've already completed?

**Comment by mmsmits** [comment]
Hi Brian, I'll contact you next week so we can take a look
