### ISSUE TITLE
Improve validation of canonical urls

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-net-sdk#1960]
The following error message is generated by the Java validator when validating relative canonical urls:
```Canonical URLs must be absolute URLs if they are not fragment references (<original string violating the constraint>)```

It would be a nice addition to have this issue as well as a best practice warning on-top of the regex constraint for the canonical datatype.

**Comment by marcovisserFurore** [comment]
This has been solved as a manual rule in the new validator. See also https://firely.atlassian.net/browse/VONK-4620.
