### ISSUE TITLE
Fix unittest StructureDefinitionSummaryProviderTest

### ISSUE THREAD

**Issue by mmsmits** [FirelyTeam/firely-net-sdk#1970]
There is a difference between pocoSdProvider en sdProvider in R4B and R5:

For example `Account.coverage.id`:
- type in pocoSdProvider is `string`
- type in sdProvider is `id`.

Should this corrected in the specification?

**Comment by mmsmits** [comment]
specification.zip -> profiles-types.xml is the STU3 version (3.0.2) in the SDK

**Comment by mmsmits** [comment]
Same for R5

**Comment by marcovisserFurore** [comment]
Are you sure? When I open `profiles-types.xml` in `specification.zip` in the branch `release/4.0.0-beta1-R4B` I see structuredefinitions with elements `<fhirVersion value="4.3.0-snapshot1" />`

**Comment by mmsmits** [comment]
It wasn't an incorrect specification.zip. But an error in the spec. 
See: https://jira.hl7.org/browse/FHIR-36036

**Comment by marcovisserFurore** [comment]
The issues is applied in FHIR version  4.1.0 (R4B). We still have to wait for a new version of R5.
