### ISSUE TITLE
BUG: Search patient by identifier FAILS due to historic date of birth values

### ISSUE THREAD

**Issue by dustinmoris** [FirelyTeam/firely-net-sdk#1989]
The problem is that the (official) Microsoft FHIR server in Azure which we use saved patient's date of births as a DateTime in the past and now a new application that uses the `FhirClient` cannot search for patients due to this validation error in this library.

Even setting the `parserSettings.TruncateDateTimeToDate ` doesn't help:

```
var parserSettings = ParserSettings.CreateDefault();
		parserSettings.TruncateDateTimeToDate = true;
		parserSettings.PermissiveParsing = true;
		
		var fhirClient =
			new FhirClient(
				fhirServerUrl,
				new FhirClientSettings
				{
					PreferredFormat = ResourceFormat.Json, 
					PreferredReturn = Prefer.ReturnRepresentation,
					ParserSettings = parserSettings
				});
```

How can we use the `FhirClient` to work with a FHIR Server which has some historic records with DateTimes in a Date field?

_Originally posted by @dustinmoris in https://github.com/FirelyTeam/firely-net-sdk/issues/1559#issuecomment-1049066633_

**Comment by dustinmoris** [comment]
I have tried several versions of the `Hl7.Fhir.R4` NuGet package, working my way backwards from `4.0.0-beta1` all the way to `1.9.0` and it is only `1.9.0` where I was able to read existing Patient resources which had a `DateTime` stored in the date of birth field. I know it's an error on the server, but there are old FHIR servers across the world - including the official Microsoft Azure managed FHIR service - which have made that mistake in the past and to me it is a complete mistake that all the newer versions of this SDK cannot cope with such a minor forgivable error. This is a big issue in our application right now and we're kind of blocked until this gets fixed. Is this something you can expedite?

**Comment by ewoutkramer** [comment]
Fixing bugs in an API while keeping options open to keep supporting buggy behaviour from the past is quite a challenge, I'll admit, but we're trying. `TruncateDateTimeToDate` is supposed to support exactly your case, so it's a bit of a mystery what's going on here. This is the bit of code from `TypedElementOnSourceNode.cs` that is supposed to handle your case:


``` csharp
              // Check for the exception we have made to allow 1.x behaviour
                // where datetime's were considered acceptable for date elements.
                // In addition the TruncateDateTimeToDate will also "correct" the
                // datetime values to correct just-date values while parsing here.
                if (_settings.TruncateDateTimeToDate && ts == typeof(P.Date))
                {
                    if (P.Any.TryParse(sourceText, typeof(P.DateTime), out var dateTimeVal))
                    {
                        // TruncateToDate converts 1991-02-03T11:22:33Z to 1991-02-03+00:00 which is not a valid date! 
                        var date = (dateTimeVal as P.DateTime).TruncateToDate();
                        // so we cut off timezone by converting it to timeoffset and cast back to date.
                        return P.Date.FromDateTimeOffset(date.ToDateTimeOffset(0, 0, 0, TimeSpan.Zero));
                    }
                }

                raiseTypeError($"Literal '{sourceText}' cannot be parsed as a {InstanceType}.", _source, location: _source.Location);
                return sourceText;
``` 

As we can see -- if a field fails to parse AND the setting is true, we'll parse it into a DateTime instead (and then truncate it). This is from a PR by Microsoft, which was supposed to fix exactly this case.

So I am wondering whether we there is another factor at play.  Can you show the exact value in the Patient's birthdate?  What kind of exception are you getting?  Is it possible to test whether it does give the same error when you are using the `FhirJsonParser` directly (with a local copy of the data)?

**Comment by ewoutkramer** [comment]
There is no final answer to this question.  If you expect the parsing and serialization infrastructure to produce and accept correct FHIR, you'd get bug reports about the parser accepting invalid dates (and we do get these). For other cases, you'd like to accept this, since you don't really care, or check afterwards.

There was no way we could fit that behaviour in some kind of backwards-compatible way into these parsers, so when we revised the parsers to work with System.Text.Json and do performance updates, we wrote a new set of parsers that will not throw exceptions, but will keep on parsing and just report back a set of (coded) results - you can then decide for yourself which matter to you.

Check them out here: https://docs.fire.ly/projects/Firely-NET-SDK/parsing/system-text-json-deserialization.html

**Comment by pjirsa** [comment]
I cannot use the hapi.fhir.org sample public API with this library either now due to this issue. Please fix the backward compatible datetime parsing!
