### ISSUE TITLE
Invalid JSON representation for primitive types with data absent extension

### ISSUE THREAD

**Issue by maggusw** [FirelyTeam/firely-net-sdk#1994]
:information_source: 

As per the [spec](http://hl7.org/fhir/json.html#primitive)

> Note: If the primitive has an id attribute or extension, but no value, only the property with the _ is rendered.

and

> In the case where the primitive element may repeat, it is represented in two arrays. JSON null values are used to fill out both arrays so that the id and/or extension are aligned with the matching value in the first array, as demonstrated in this example:

**Describe the bug**
Let's assume a Patient resource (that claims conformance to the german MII profile) and does not have a Patient.name.given. I am not able to create an empty `given` array and a `_given` array with the extension on the null value.

**To Reproduce**

My code looks as follows:

```c#
if (record.TryGetStringValue("Vorname", out var firstName)) 
{
    name.GivenElement = new List<FhirString> { new(firstName) };
} 
else 
{
    name.Given = new List<string>(); // I am aware that I overwrite name.Given. See below for what I tried
    name.GivenElement = new List<FhirString> { new FhirString().AddExtensionForAbsentData() as FhirString };    
}
```

And the code for `AdExtensionForAbsentData()`:

```c#
        public static IExtendable AddExtensionForAbsentData(this IExtendable element, string reason = "unknown")
        {
            element.Extension ??= new List<Extension>();
            element.AddExtension("http://hl7.org/fhir/StructureDefinition/data-absent-reason", new Code(reason));
            return element;
        }
```

Adding `null` to name.Given will still only render the `_given` array in the JSON representation, while adding an empty string, i.e. `""`, will result in this:

```json
    "given": [
        "",
        null
    ],
    "_given": [
        null,
        {
            "extension": [
                {
                    "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
                    "valueCode": "unknown"
                }
            ]
        }
    ]
```

**Expected behavior**

As a result, I would expect this (I reduced it to only showing the expected representation for `given` and `_given`):

```json
"name": [
  {
   "given": [ null ],
    "_given": [
      {
        "extension": [
          {
            "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
            "valueCode": "unknown"
          }
        ]
      }
    ]
  }
]
```

**Version used:**
 - FHIR Version: R4
 - Version: 3.5.0

**Comment by ewoutkramer** [comment]
I do not fully understand what you are trying to do, but I do see this:

```csharp
else 
{
    name.Given = new List<string>(); // I am aware that I overwrite name.Given. See below for what I tried
    name.GivenElement = new List<FhirString> { new FhirString().AddExtensionForAbsentData() as FhirString };    
}
```

Setting `GivenElement` will overwrite whatever you put in `Given`.  So you *either* should use `Given` (and then you cannot add extensions) *or* you should use `GivenElement` (and then you should set both Value and Extensions to your liking).

**Comment by ewoutkramer** [comment]
In other words, `Given` is just a shortcut for `GivenElement.Value`.  Setting one, will change the other.

**Comment by maggusw** [comment]
Hi Ewout,

thanks for getting back to me.

I am aware that I overwrite `Given` with `GivenElement`. However, I want to add an absent data extension on a collection of primitives. 

So, in other words, I want to implement 

> In the case where the primitive element may repeat, it is represented in two arrays.

and

> Note: If the primitive has an id attribute or extension, but no value, only the property with the _ is rendered.

So basically, we only want to have the extension point to a single primitive of the collection as opposed to having the extension on the collection itself (https://www.hl7.org/fhir/extensibility.html#Special-Case)

**Comment by maggusw** [comment]
In other words, what would be the JSON representation for a primitive where the cardinality is 2...*, but one is missing?

**Comment by ewoutkramer** [comment]
You cannot have an element of a list completely missing (which would be a null in both `given` and `_given`), so every element in a list must have a value, an extension or both.
