### ISSUE TITLE
Validation of a Bundle which has a fullUrl containing a host in upper case causes problems

### ISSUE THREAD

**Issue by MatthijsvdWielen** [FirelyTeam/firely-net-sdk#1996]
Check out the validation results of these 2 snippets on Simplifier: 
Bundle 1: https://simplifier.net/snippet/matthijsvanderwielen/2/$validate
Bundle2: https://simplifier.net/snippet/matthijsvanderwielen/3/$validate

Both bundles are identical apart from the use of capitals in the fullUrl. As the host component should be case insensitive, there shouldn't be different validation behavior between these two cases.

Screenshot of difference between fullUrl
![image](https://user-images.githubusercontent.com/60686559/156135628-8ee56944-8f38-4984-9dfb-178964684d20.png)

**Version used:**
 - FHIR Version: R4
 - Version: Simplifier 28.4 with SDK 3.8.0

Attached both bundles to compare. Validation scope is the package [kbv.ita.eau v1.0.2](https://simplifier.net/packages/kbv.ita.eau/1.0.2)
[TestBundleNOcapitals.xml.txt](https://github.com/FirelyTeam/firely-net-sdk/files/8160168/TestBundleNOcapitals.xml.txt)
[TestBundleCapitals.xml.txt](https://github.com/FirelyTeam/firely-net-sdk/files/8160169/TestBundleCapitals.xml.txt)

**Comment by grahamegrieve** [comment]
I don't agree. These are URIs that are documented as case sensitive for comparison purposes, even though you are more generally right about URLs

**Comment by marcovisserFurore** [comment]
Like Grahame says, URIs that are documented as case sensitive for comparison purposes. Closing this issue.
