### ISSUE TITLE
Validation of MedicationStatement fails when value of MedicationStatement.status is one of these value: "completed", "intended" and "entered-in-error"

### ISSUE THREAD

**Issue by tiwari-ravi** [FirelyTeam/firely-net-sdk#2008]
We are using "Hl7.Fhir.Specification.STU3" package with version 3.8.0 for FHIR profile validation. If we use "completed", "intended" or "entered-in-error" as value for MedicationStatement.status then we get the following error:
![image](https://user-images.githubusercontent.com/77834107/157391995-aae46597-9073-4f03-967c-2471b03720be.png)

I am also attaching the resource that we are trying to validate:
[MedicationStatement.txt](https://github.com/FirelyTeam/firely-net-sdk/files/8212533/MedicationStatement.txt)

Hoping for a quick resolution.

**Comment by mmsmits** [comment]
Hi @tiwari-ravi ,

I created a unit test with your test case, and all works fine here:

```
  [Fact]
  public void ValidateMedicationStatement()
  {
      // PREPARE

      // Creates a resolver to access all "FHIR Core" artifacts, like Valuesets, CodeSystems, and Profiles
      var resolver = ZipSource.CreateValidationSource();

      //adds the resolver to the settings
      var settings = new ValidationSettings()
      {
          ResourceResolver = resolver,
          GenerateSnapshot = true,
          EnableXsdValidation = true,
          Trace = false,
          ResolveExternalReferences = true
      };

      //adds settings to the validator
      var validator = new Validator(settings);

      //reads your test medication statement
      var json = File.ReadAllText(Path.Combine("TestData", "validation", "medicationstatement.json"));
      var medStatement = new FhirJsonParser().Parse(json);

      //ACT 
      var outcome = validator.Validate(medStatement);

      //TEST
      Assert.True(outcome.Success);
  }
```

It could be that you didn't add a resolver to your validator that has access to all the FHIR artifacts you need for validation. like profiles, valuesets, and codesystems. I added all core resources to the validator in the unit test, by create a "validation source".

Hope this works out for you.

**Comment by tiwari-ravi** [comment]
Hi @mmsmits,

Thank you for the quick reply. We were able to resolve our issue. We were using MultiResolver with multiple sources as our validation source. One of these sources had a custom FHIR profile which contained only three values as part of MedicationStatement.status. Therefore, the validation of our resource was failing.
