### ISSUE TITLE
How to configure HttpClient in intgeration test

### ISSUE THREAD

**Issue by wilsonchenbhs** [FirelyTeam/firely-net-sdk#2014]
Hi,

We are trying to do the integration test after we implemented the RESTful APIs with the Firely SDK.

As a standard integration test solution in .NET 6, we use `WebApplicationFactory` to hook up with the Startup of our Web API project.

From there we can use the following to obtain an instance of `HttpClient`:
```
    internal class ApiFactory : WebApplicationFactory<Startup>
    {
    }

// usage:
            var factory = new ApiFactory();
            var client = factory.CreateClient();
```

If we directly make calls the endpoints like `/v1.0/MedicationRequest?patient=123` etc, it works fine.

But, if we use `FhirClient`, it would complain:

> System.Net.Http.HttpRequestException: 'No connection could be made because the target machine actively refused it. (localhost:80)'

Despite we have use `MessageHandler` via the constructor of `FhirClient` to specify the authorization info as documented in https://docs.fire.ly/projects/Firely-NET-SDK/client/request-response.html

I don't seem to see a way how to just specify the `HttpClient` obtained from `WebApplicationFactory` for our test purpose.

**Comment by marcovisserFurore** [comment]
Hi @wilsonchenbhs,

Thanks for your feedback.

As far as I understand is the only client that can communicate with the TestServer, the client that comes from the factory. So that's why `FhirClient` is not able to communicate with the TestServer.

 What you can do, is to obtain a `HttpMessageHandler` from the `TestServer`, and use this handler in the `FhirClient`:

```c#
            var application = new WebApplicationFactory<Program>()
                .WithWebHostBuilder(builder =>
                {
                    
                    // ... Configure test services
                });

            var handler = application.Server.CreateHandler();

            var fhirClient = new FhirClient("http://localhost", settings: null, handler);
```

This should work.

**Comment by wilsonchenbhs** [comment]
Thanks @marcovisserFurore , with your sample, that HttpRequestException is now gone.

However, with the following query:

```
            var fhirClient = new FhirClient("http://localhost/", messageHandler: handler);
            var query = new SearchParams()
                .Add("patient", "123")
                .Include("MedicationRequest:patient")
                .Include("MedicationRequest:medication")
                .Include("MedicationRequest:performer")
                .LimitTo(1);
            var medicationRequestResult = await fhirClient.SearchAsync<MedicationRequest>(query);
```

It now complains:
> System.InvalidOperationException: 'Root object has no type indication (resourceType) and therefore cannot be used to construct an FhirJsonNode. Alternatively, specify a nodeName using the parameter.'

Any idea why? I get the above search sample from the unit tests.

**Comment by wilsonchenbhs** [comment]
Oh, I think I may have missed the Authorization header after I managed to find out I can do below, it works:

```
var fhirClient = new FhirClient("http://localhost/", messageHandler: handler);
fhirClient.RequestHeaders.Authorization = new AuthenticationHeaderValue(JwtBearerDefaults.AuthenticationScheme, "token-here");
var query = new SearchParams()
                .Add("patient", "123")
                .Include("MedicationRequest:patient")
                .Include("MedicationRequest:medication")
                .Include("MedicationRequest:performer")
                .LimitTo(1);
            var medicationRequestResult = await fhirClient.SearchAsync<MedicationRequest>(query);

```

**Comment by wilsonchenbhs** [comment]
Ok, the search does work. It's with my response that has issue. 

All good. Thanks!
