### ISSUE TITLE
What should be returned from FHIR service if _summary is set

### ISSUE THREAD

**Issue by wilsonchenbhs** [FirelyTeam/firely-net-sdk#2015]
Hi,

We've implemented the FHIR service with Firely SDK (great work, thanks!). 

Now we would like to know what to be returned if consumer specifies _summary, like to be "count".

According to http://www.hl7.org/implement/standards/fhir/search.html#summary , it's pretty vague. With Firely SDK, what is practice / sample (data struct) to return if _summary is "count"?

<img width="883" alt="image" src="https://user-images.githubusercontent.com/95388682/159843693-9f770f43-9fab-4586-9c3c-417a17567f42.png">

For example, we should at least return the "Total", right? But in what data struct? Do we simply set the `Bundle.Total`?

Or it is automagically being handled by FHIR json/xml serializer for all cases of summary values?

- data
- text
- true
- false
- count

Thanks.

**Comment by ewoutkramer** [comment]
This is handled by the serializer - we've tried to follow the spec as exactly as possible. But as you noticed, the spec is actually pretty vague in this respect, so there are still differences between, say, the HAPI summary and the .NET summary.  

E.g., if you are interested, take a look here: #1653 for more info.

**Comment by wilsonchenbhs** [comment]
Ah, right, if we use `JsonSerializerOptions().ForFhir`, we will need to use `FhirJsonPocoSerializerSettings`, and pick the `SummaryFilter` accordingly

**Comment by ewoutkramer** [comment]
Yes - indeed, those are the 4.0 bits - which you seem to be using already!

I have some documentation about these - though I guess if you found out about these classes all by yourself, you have probably found the unit tests and source code for it already ;-)

**Comment by brianpos** [comment]
@wilsonchenbhs are you manually creating your own controller layers?
Have you tried one of the open source facade layers?
Like the fhir-net-web-api project?
(or the vonk facade one)

**Comment by wilsonchenbhs** [comment]
@brianpos  ah, no. just realized there is such implementation already. we've implemented most of the functionalities. But I do see places where I can learn from your project. Thanks!

would be good to mention projects like yours in the main readme.md in this repo to avoid future users doing it from scratch.
