### ISSUE TITLE
Bundle validation returns type errors not in base profile

### ISSUE THREAD

**Issue by MatthijsvdWielen** [FirelyTeam/firely-net-sdk#2016]
In the attached Simplifier project we get a strange validation error. 

![image](https://user-images.githubusercontent.com/60686559/159872162-32a536a1-454c-42f0-9759-cc8a428bfc99.png)

Which would normally indicate that the instance type could not be matched to any of the types in the base profile. However in the [base profile](https://simplifier.net/packages/nictiz.fhir.nl.stu3.zib2017/1.3.15/files/382889/~xml) there are is no CarePlan, ProcedureRequest or ReferralRequest. 

[bundlevalidationerror.zip](https://github.com/FirelyTeam/firely-net-sdk/files/8339606/bundlevalidationerror.zip)

**Comment by mmsmits** [comment]
@MatthijsvdWielen found the reason for the error.

**Comment by marcovisserFurore** [comment]
I am now very curious about the reason ;)

**Comment by MatthijsvdWielen** [comment]
The list.entry.MedicationAgreement there is a target profile to http://nictiz.nl/fhir/StructureDefinition/zib-MedicationAgreement in the base profile provides the Data Types to the validator. 

This profile: https://simplifier.net/packages/nictiz.fhir.nl.stu3.zib2017/1.3.15/files/382654 has the Reference (CarePlan | MedicationRequest | ProcedureRequest | ReferralRequest) which trigger the validation errors.
