### ISSUE TITLE
Async operations on FhirClient to take a CancellationToken that is can pass to any web requests it makes

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/firely-net-sdk#2024]
**Is your feature request related to a problem? Please describe.**
When performing async requests the ability to provide a cancellation token will assist in permitting cancelling the requests - such as those to a web api - when a call is cancelled.
Very useful in terminology validations or resolving resources which may be cancelled too.

**Describe the solution you'd like**
Include the CancellationToken to any async FhirClient calls, and use that on any web/directory async calls it makes.

**Additional context**
Server validations, client validations, or any other async general requests performed.
I would like this on the ResourceResolver interfaces too, but can do that seperately.

**Comment by holpit** [comment]
I was asking exactly the same thing.   Votes++

**Comment by brianpos** [comment]
I was going to add it in with an optional parameter with a default value, does that still count as a non-breaking change (have started the work)

**Comment by ewoutkramer** [comment]
Yes, adding an optional param counts as a non-breaking change (for us ;-)

**Comment by ewoutkramer** [comment]
We basically strive for updates that won't produce errors when you need to recompile your software when you upgrade the SDK package. So, not necessarily binary compatibility.

**Comment by JockeM** [comment]
Anything being done on this? If not do you take outside prs?

**Comment by brianpos** [comment]
I'll check where my code got to.

**Comment by aignatovich** [comment]
Could anyone confirm cancellation support was added to one of the latest releases?

**Comment by marcovisserFurore** [comment]
Sorry, in some way it lost our attention. We try to add it to the next release (5.0).

**Comment by ewoutkramer** [comment]
Done.
