### ISSUE TITLE
FhirClient  is 10* slower than httpClient

### ISSUE THREAD

**Issue by holpit** [FirelyTeam/firely-net-sdk#2032]
**Describe the bug**
FhirClient is very slow also with few resources.

The same call with native httpClient or PostMan is about 10 * faster then FhirClient.

The query is: 

https://myFhirServer/DocumentReference?_count=10&_include=DocumentReference:subject&_include=DocumentReference:author&_include=DocumentReference:encounter&_sort=-date&_security=http://mycompamy.com/CodeSystem/tenant|2&patient:Patient.identifier=http://mycompany.com/CodeSystem/users|1012

The result bundle contains 1 document reference, 1 patient, 1 practitioner, 1 episode of care
Db contains 30730 DocumentRefernce, 360632 Patient, 292706 EpisodeOfCare, 1051 Practitioner

Average time:
FhirClient 30 seconds
PostMan 2 seconds
HttpClient 3 seconds

**Version used:**
 - FHIR Version: R4 
 - FhirClient Sdk: 3.8.2

**Comment by brianpos** [comment]
Did I read that right that you have 360,000 patient resources in the bundle that it's reading?
If that's the case, then I expect this is the parser adding the extra time here.

**Comment by brianpos** [comment]
You might try comparing using json, and also with the SDK v4 alpha which has a new JSON parser in it too.

**Comment by holpit** [comment]
Yes you are right.
The resources in the response are only 4. 
After further investigation and debugging, I've found that the bottleneck is in HttpClientRequester.cs on this line:

using var response = await Client.SendAsync(requestMessage).ConfigureAwait(false);

If I replace "Client" with a new httpClient  created from scratch, the response time is fast as aspected.

**Comment by brianpos** [comment]
Interesting, is there an option there to try the Async version of the specific request you're doing?

**Comment by holpit** [comment]
Sorry, but the request is already Asynchronous.
This is slow:
``` 
using var client = new FhirClient("https://myserver", new FhirClientSettings
            {
                PreferredFormat = ResourceFormat.Json,
            });
            var criteria = new List<string>();
           ..add criterias

            var includes = new List<string>();
          ..add included
           
            var bundle = await client.SearchAsync("DocumentReference", criteria.ToArray(), includes.ToArray());
```

and this is fast:
```
  static HttpClient clientHttp = new HttpClient();

            clientHttp.BaseAddress = new Uri("https://myserver);
            clientHttp.DefaultRequestHeaders.Add("Accept", "application/json");
                
            var bundle = await clientHttp.GetAsync($"DocumentReference?---add all query params)
```

**Comment by brianpos** [comment]
Hmm, very interesting indeed. Is the data something that you can post to another server for others to take a peek at?
(or share the search bundle that comes back)

**Comment by holpit** [comment]
Sure, I can share the boudle. IMHO the bundle and parsing it is not a problem because is fast also with a large number of entry. The main and only issue is with the call to the server. 
```
{
    "resourceType": "Bundle",
    "id": "dbc89355-293f-4a95-8d3f-8052cd432909",
    "meta": {
        "lastUpdated": "2022-04-01T06:13:59.6844288+00:00"
    },
    "type": "searchset",
    "link": [
        {
            "relation": "self",
            "url": "http://localhost:5000/DocumentReference?_count=10&_include=DocumentReference%3Asubject&_include=DocumentReference%3Aauthor&_include=DocumentReference%3Aencounter&_sort=-date&_security=http%3A%2F%2Fmycompany.com%2FCodeSystem%2Ftenant%7C2&patient%3APatient.identifier=http%3A%2F%2Fmycompany.com%2FCodeSystem%2Futenti%7C1012"
        }
    ],
    "entry": [
        {
            "fullUrl": "http://localhost:5000/DocumentReference/17d72da0-06b6-4716-a780-5ed2ed0032e7",
            "resource": {
                "resourceType": "DocumentReference",
                "id": "17d72da0-06b6-4716-a780-5ed2ed0032e7",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2021-08-31T05:58:24.614+00:00",
                    "security": [
                        {
                            "system": "http://mycompany.com/CodeSystem/tenant",
                            "code": "2"
                        }
                    ]
                },
                "status": "current",
                "docStatus": "final",
                "type": {
                    "coding": [
                        {
                            "system": "http://loinc.org",
                            "code": "34746-8",
                            "display": "Diario infermieristico"
                        }
                    ]
                },
                "category": [
                    {
                        "coding": [
                            {
                                "system": "http://mycompany.com",
                                "code": "Dolore",
                                "display": "Dolore"
                            }
                        ]
                    }
                ],
                "subject": {
                    "reference": "Patient/cd75991a-ab51-439a-8a08-9100d62cd645"
                },
                "date": "2021-08-31T07:57:00+02:00",
                "author": [
                    {
                        "reference": "Practitioner/bfa21615-aaea-44f9-b6fc-b367cee16bcb"
                    }
                ],
                "description": "prelievo",
                "content": [
                    {
                        "attachment": {
                            "contentType": "text/plain",
                            "url": "Binary/e4cf239f-0fa2-40fa-bc87-32083c7d6a21"
                        }
                    }
                ],
                "context": {
                    "period": {
                        "start": "2021-08-31T07:57:00+02:00",
                        "end": "2021-08-31T07:57:00+02:00"
                    }
                }
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "http://localhost:5000/Patient/cd75991a-ab51-439a-8a08-9100d62cd645",
            "resource": {
                "resourceType": "Patient",
                "id": "cd75991a-ab51-439a-8a08-9100d62cd645",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2021-06-19T10:15:03.709+00:00",
                    "security": [
                        {
                            "system": "http://mycompany.com/CodeSystem/tenant",
                            "code": "2"
                        }
                    ]
                },
                "identifier": [
                    {
                        "use": "secondary",
                        "system": "http://mycompany.com/CodeSystem/utenti",
                        "value": "1012"
                    }
                ],
                "name": [
                    {
                        "text": "ANT*** VITTORIA",
                        "family": "ANT***",
                        "given": [
                            "VITTORIA"
                        ]
                    }
                ]
            },
            "search": {
                "mode": "include"
            }
        },
        {
            "fullUrl": "http://localhost:5000/Practitioner/bfa21615-aaea-44f9-b6fc-b367cee16bcb",
            "resource": {
                "resourceType": "Practitioner",
                "id": "bfa21615-aaea-44f9-b6fc-b367cee16bcb",
                "meta": {
                    "versionId": "10",
                    "lastUpdated": "2021-09-08T12:13:45.54+00:00",
                    "security": [
                        {
                            "system": "http://mycompany.com/CodeSystem/tenant",
                            "code": "2"
                        }
                    ]
                },
                "identifier": [
                    {
                        "use": "secondary",
                        "system": "http://mycompany.com/CodeSystem/risorse-umane",
                        "value": "21"
                    }
                ],
                "name": [
                    {
                        "text": "LIP*** EDYTA",
                        "family": "LIP***",
                        "given": [
                            "EDYTA"
                        ]
                    }
                ]
            },
            "search": {
                "mode": "include"
            }
        }
    ]
}
```

**Comment by holpit** [comment]
I noticed that every request creates a new httpClient `Client = new HttpClient (messageHandler);` instead of using a static reference as suggested because of degrading response time.
Our app make a huge number of call to Fhir Server. Maybe is this the issue?

**Comment by brianpos** [comment]
Is that slow all the time, or it degrades overtime?

**Comment by holpit** [comment]
Degrades overtime

**Comment by ewoutkramer** [comment]
The constructor in the `FhirClient` is creating a `HttpClientRequester`, which is its turns is creating a new `HttpClient`.  The .NET documentation has this to say about `HttpClient`:

> [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-6.0) is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads.

So, if you are not re-using the FhirClient instance (did I understand that correctly?), but creating new instances, you are creating new instances of HttpClient - and probably run in problems as sketched by the .NET SDK documentation.

**Comment by brianpos** [comment]
This was a major problem back in 1.9.0 of the fhir client, and I wrote a replacement fhirclient specifically for this workaround.
https://github.com/brianpos/fhir-net-web-api/blob/develop-r4/src/Hl7.Fhir.HttpClient/FhirHttpClient.cs
It's available on NuGet https://www.nuget.org/packages/brianpos.Fhir.R4.HttpClient/

If you're going to use it, do thoroughly test it as it's only been tested on some narrow use cases, and wasn't intended to be used in versions newer than 1.9.0 - if it fixes your problem do let us know and we'll get the firely client fixed properly - If you use it in production do at your own risk - and review the code closely.

In it's code it uses the HttpClientFactory to create/retrieve a HttpClient in a managed way (without needing a singleton)

I thought this same approach went into the 2.0 Firely versions (but I never went to re-check)

**Comment by brianpos** [comment]
https://github.com/FirelyTeam/firely-net-common/blob/e9fd688bb25b0883fb6df54923f767e0c6a20a98/src/Hl7.Fhir.Support.Poco/Rest/HttpClientRequester.cs#L28
This code here really should be calling the HttpClientFactory instead of just new'ing one as my code does.
https://github.com/brianpos/fhir-net-web-api/blob/5a6b44f074346eb1fe0b021782bff85dd2e731fc/src/Hl7.Fhir.HttpClient/FhirHttpClient.cs#L27
This then lets the factory manage the pool of those connections.
This is also assuming that you're getting socket errors or something.
A general slowdown feels like some other sort of leaking...

**Comment by holpit** [comment]
Ok, thank you.
I'll take some time to implement the advices and I'll come back in case of further need

**Comment by ewoutkramer** [comment]
> This is also assuming that you're getting socket errors or something.
A general slowdown feels like some other sort of leaking...

Yeah, agree.... still we need to start somewhere....

**Comment by ewoutkramer** [comment]
What HttpClientFactory are we talking about?

This one: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.ihttpclientfactory?view=dotnet-plat-ext-3.1

or this one: https://docs.microsoft.com/en-us/previous-versions/aspnet/hh995280(v%3Dvs.118)

The latter doesn't seem to be doing anything interesting according to this: https://stackoverflow.com/questions/60362914/what-is-the-purpose-of-the-httpclientfactory-system-net-http-formatting

**Comment by brianpos** [comment]
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests?msclkid=580e3af7b5ee11ec8c6cb7bf16e81260

**Comment by brianpos** [comment]
@holpit this is now released, keen to hear how you go with it.
