### ISSUE TITLE
Introduce HttpClientFactory in HttpClient

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2036]
In (closed) issue #2032 , the discussion centered around re-using instances of the HttpClient.  Currently, every instance of the FhirClient creates an instance of the HttpClient, but Microsoft recommends having a single HttpClient per application - which means the FhirClient should re-use one single instance.

**Describe the solution you'd like**
@brianpos suggests using a class called `HttpClientFactory` but it is unclear to me how this solves the problem.

**Describe alternatives you've considered**

**Additional context**
See issue the discussion in #2032 for more info.

**Comment by brianpos** [comment]
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests?msclkid=580e3af7b5ee11ec8c6cb7bf16e81260
which also links back to https://www.aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by brianpos** [comment]
Noting through those posts it makes the point that it's not the actual HttpClient that is the issue, its the HttpMessageHandler that is the problem, and that's the thing you need to hang onto and the Factory helps manage things better.

**Comment by brianpos** [comment]
I think with these changes to include the HttpClient via the constructor, then we don't need to do the HttpClientHandlerFactory stuff, and if someone wants to use that stuff, they can and we don't need to be involved.
(and we get the other unit testing benefits too as I've mentioned in the PRs.)

**Comment by vankampenp** [comment]
The HttpClientFactory creates and manages HttpClient instances and takes an available message handler from the pool. The HttpClient should be included in the constructor rather than the factory, so the consumer can reuse the same HttpClient.

**Comment by brianpos** [comment]
@ewoutkramer,  Now that the 3.8.3 and 4 beta release have the httpclient in the constructor of the fhirclient, I think we can close this issue as it enables the HttpClientFactory to be used without change in this library
