### ISSUE TITLE
Invalid snapshot is produced by inheriting slicing on choice type 

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-net-sdk#2065]
**Describe the bug**
The attached profile contains an invalid snapshot on Specimen.processing:lagerprozess.time[x]. On that element the slicing contains no "rules" element. The main issue is that the slicing is inherited from Specimen.processing:time[x] ("All Slices" for Specimen.processing). Here we have an open slicing as we further constrain Specimen.processing:time[x].period (setting MS flags on .start and .end). According to https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Type.5Bx.5D.2C.20Slices.2C.20open.2Fclosed/near/188924523 the open slicing is expected here as we don't limit the choice types. However, the lagerprozess limits time[x] to only period. Therefore, it should either be a closed slicing or just have an implicit discriminator. 

**Expected behavior**
No slicing element is present on Specimen.processing:lagerprozess.time[x] in the snapshot.

**Version used:**
 - FHIR Version: [R4]
 - Version: [e.g. 3.8.0]

**Comment by alexzautke** [comment]
[ProfileSpecimenBioprobeCore.json.zip](https://github.com/FirelyTeam/firely-net-sdk/files/8610421/ProfileSpecimenBioprobeCore.json.zip)

**Comment by alexzautke** [comment]
See https://firelyteam.slack.com/archives/C011XD1TKL0/p1651517052925909 for internal discussion

**Comment by mmsmits** [comment]
also related:
https://github.com/FirelyTeam/firely-net-sdk/issues/1253

**Comment by mmsmits** [comment]
I recreated the profile for testing, and encountered that the element paths are incorrect. This should be the corrected format:
https://simplifier.net/snippet/martensmits/9, which also works with our snapshotgenerator

**Comment by alexzautke** [comment]
These path were generated by SUSHI. The project team managing the profiles will re-try with the latest version of SUSHI to see if this was changed. Otherwise we need to talk to them about this behaviour.

**Comment by mmsmits** [comment]
Alright, I'll close this issue for now. Please re-open it if we still need to fix something.

**Comment by alexzautke** [comment]
Feedback: These paths are still generated by SUSHI as of version v2.6.0. Original FSH file: https://github.com/medizininformatik-initiative/kerndatensatzmodul-biobank/blob/main/input/fsh/Modul_Biobank.fsh

**Comment by alexzautke** [comment]
Re-opened the issue because I think that our tooling should work with the generated profiles from SUSHI.

**Comment by mmsmits** [comment]
I think Sushi has some work to do:
https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Choice.20Type.20Renaming

**Comment by alexzautke** [comment]
Will be solved in SUSHI.
