### ISSUE TITLE
Incorrect validation warning in bundle references. 

### ISSUE THREAD

**Issue by MatthijsvdWielen** [FirelyTeam/firely-net-sdk#2074]
In [this snippet](https://simplifier.net/snippet/matthijsvanderwielen/2/$validate) the bundle references are not resolvable.

According to https://www.hl7.org/fhir/bundle.html#references

_If the reference is not an absolute reference, convert it to an absolute URL:

- if the reference has the format [type]/[id], and
- if the fullUrl for the bundle entry containing the resource is a RESTful one (see the [RESTful URL regex](https://www.hl7.org/fhir/references.html#regex))

extract the [root] from the fullUrl, and append the reference (type/id) to it_

And

_Except for transactions and batches, each entry in a Bundle must have a fullUrl which is the identity of the resource in the entry. Note that this is not a versioned reference to the resource, but its identity. Where a resource is not assigned a persistent identity that can be used in the Bundle, a UUID should be used (urn:uuid:...)._

In general: As the spec states references don't have to resolve within the context of a a Bundle (of any type, including documents). So a warning when validating would seem appropriate, the validator is unable to validate certain constraints that may apply to these referenced resources.
In this specific Bundle e.g. the referenced Patient does exist, and fullUrl is populated, so the warning is erroneous.

**Comment by ewoutkramer** [comment]
No, they don't need to be in the bundle. The validator will try to resolve them outside of the bundle (if configured to do so), or not to follow the references at all (also configuration).  Do you know how the validator is configured? I guess this is in Simplifier?

**Comment by MatthijsvdWielen** [comment]
Yes, this is on Simplifier indeed. If you use urn/uri as the reference I believe Simplifier does resolve them. It only seems to be when you use type/id that Simplifier can not resolve them.

**Comment by mmreith** [comment]
problem is the different behaviour of simplifier regarding these two bundles:
Bundle 1: https://simplifier.net/snippet/matthijsvanderwielen/2/$validate 
Bundle2: https://simplifier.net/snippet/matthijsvanderwielen/3/$validate 

Bundle1 got warnings (Cannot resolve reference Patient/0112ef01-6b01-4501-83df-ec00c16cba90)
Bundle 2 no issues
the only difference is "pvs.AM.local" (bundle1) and  "pvs.am.local" (bundle2)

**Comment by marcovisserFurore** [comment]
Is this issue similar to #1996?

**Comment by mmreith** [comment]
Sorry but i did not understand? These problems are related but not similar. If the Full-URl would differ in one bundle the problem could be https://github.com/FirelyTeam/firely-net-sdk/issues/1996, but it does not differ, so its not a problem of case-sensitiveness

**Comment by mmreith** [comment]
yes they differ, but not in a single bundle...so its not a case-sensitiveness problem.
