### ISSUE TITLE
Allow invalid datetimes in Parser

### ISSUE THREAD

**Issue by tstolker** [FirelyTeam/firely-net-sdk#209]
Right now, when using Search() for Observations for a specific patient, I am getting the error: "The string '2015-04-15T12:00:00+0200' is not a valid AllXsd value". This aborts the successful reception of the Observations for this patient.

I am requesting an option similar to parser.Settings.AllowUnrecognizedEnums, e.g. parser.Settings.AllowInvalidDateTimes.

**Comment by ewoutkramer** [comment]
We could solve this in the same way we did this to support unparseable enums: a parser setting that would allow this, and then have the original representation in Primitive.ObjectValue, while .Value (for backwards-compat) remains the "correct" value (or null if unparseable).

**Comment by tstolker** [comment]
Great, sounds good!

**Comment by sharushetty** [comment]
Did this even get fixed? I see the same issue within Hl7.Fhir.STU3 Nuget package. I get the below error upon trying to get an Organization bundle:

The string '2018-08-27T00:00:00.000+0000' is not a valid AllXsd value.

Any idea how to fix the issue?

**Comment by ewoutkramer** [comment]
No, it's an enhancement that we have not done yet.

**Comment by ewoutkramer** [comment]
Yes, I have an idea how - it's in the ComplexTypeReader.cs - where we have special code to handle invalid enumerations while parsing. We could do the same thing for datetimes.

**Comment by marcovisserFurore** [comment]
We had a discussion about this in our team and we came to the conclusion that we don't want to accept invalid data, which can be very dangerous (missing data). The settings `AllowUnrecognizedEnums` and `AcceptUnknownMembers` are more for backward and forward compatibility.
