### ISSUE TITLE
New serializer fails to deserialize extensions on primitive fields when primitive field has more than one possible type

### ISSUE THREAD

**Issue by almostchristian** [FirelyTeam/firely-net-sdk#2097]
**Describe the bug**
I encountered this error after updating our project to use the new System.Text.Json based deserializer with the version 4.0.0 of the libraries. Our project use an extension on the Condition.abatement field so our tests failed.

**To Reproduce**

```csharp
var serOptions = new JsonSerializerOptions().ForFhir();
var condition = new Condition
{
    Subject = new ResourceReference("Patient/213"),
    Abatement = new FhirDateTime("2000"),
    RecordedDate = "2001",
};

// Recorded date extension works
// condition.RecordedDateElement.AddExtension("test", new ResourceReference($"Patient/abc"));

// Abatement fails
condition.Abatement.AddExtension("test", new ResourceReference($"Patient/abc"));

var json = JsonSerializer.Serialize(condition, serOptions);
var parsed = JsonSerializer.Deserialize<Condition>(json, serOptions);
Console.WriteLine(parsed.ToJson());
```
**Version used:**
 - Hl7.Fhir.R4 4.0.0 nuget package

![image](https://user-images.githubusercontent.com/2035340/169651615-f7e2421a-aaf5-4818-965e-6cb6724d921a.png)

**Comment by almostchristian** [comment]
I believe I found the root cause of the error.

In `FhirJsonPocoDeserializer.tryGetMappedElementMetadata`, the call to `parentMapping.FindMappedElementByChoiceName` should use `elementName` instead of `propertyName`.

![image](https://user-images.githubusercontent.com/2035340/169683405-309a1379-7463-4bb7-b8ee-8f59597e101c.png)

**Comment by brianpos** [comment]
That appears correct, I'll take a look.

**Comment by ewoutkramer** [comment]
Yeah, that seems likely indeed.

**Comment by brianpos** [comment]
Testing with the TestPatient unit test works (choosing the deceasedDateTime property in the test) so chasing further with a model based unit test further down the stack to better simulate the specific case here.

**Comment by brianpos** [comment]
Yup, more to it than just that line. Hunting it down further

**Comment by ewoutkramer** [comment]
Since we don't have the xml deserializer yet, I could not create a version of the fullroundtrip integration test, which would have caught this probably.  Maybe it's still worth doing it, but then just roundtripping all examples with json (no xml serializer in the loop).

**Comment by brianpos** [comment]
Also needs to have this line updated too.
https://github.com/FirelyTeam/firely-net-common/blob/f80c687becf769b8a14d024704cd189401365c28/src/Hl7.Fhir.Support.Poco/Serialization/FhirJsonPocoDeserializer.cs#L860

Here's the branch for a potential PR.
https://github.com/FirelyTeam/firely-net-common/compare/develop...brianpos:feature/2097-json-deserializer
I was able to create a very simple unit test in the R4 branch, but didn't get one in the common library.
I can give that a try to get the extension into the `TestPatient` class that you've faked into that test project from STU3

**Comment by brianpos** [comment]
My branch in brianpos referenced above now has a unit test on it too that could create a PR from (and include in the various 4.x builds.

**Comment by brianpos** [comment]
https://github.com/FirelyTeam/firely-net-common/pull/203
