### ISSUE TITLE
POSTing a Bundle should not append /Bundle to the URL

### ISSUE THREAD

**Issue by johnkwaters** [FirelyTeam/firely-net-sdk#2100]
See except from Smile  CDR:

**If you POST to [baseUrl]/Bundle you are submitting the bundle for storage as-is.** In other words, the bundle is stored as a Bundle, and the contents inside aren’t looked at by the server (aside from any validation that is enabled). This mode is generally used to store Bundle resources with Bundle.type values such as document, and collection. In its default configuration, Smile CDR will prohibit storing a Bundle with a type value of transaction or batch as this is generally a sign that the client is attempting to perform the operations described below but with an incorrect request URL.

Naming: This is not a FHIR Transaction, but instead is simply a simple resource create where the resource happens to be a Bundle resource.

If you POST to [baseUrl] and your Bundle has a Bundle.type value of transaction you are performing a FHIR “transaction operation”, meaning that all of the individual resources inside the bundle will be processed. It is also possible to include other REST operations such as searches in this kind of bundle. The processing works as an atomic unit, meaning that if anything fails (e.g. invalid data in an individual element) the entire thing will be rolled back.

Naming: This operation is referred to as a FHIR Transaction operation.

If you POST to [baseUrl] and your Bundle has a Bundle.type value of batch, the same processing as the transaction applies, except that individual operations are executed in individual database transactions, so an individual failure doesn’t cause the entire operation to be rolled back. In this case, the response Bundle returned by the server will include status entries indicating the outome for the individual operations within. Note that the batch operation does require the entire Bundle to be valid FHIR at a minimum. This means that it can’t have non-existent resource types in it, malformed datatypes, etc.

Naming: This operation is referred to as a FHIR Batch operation.

**Comment by johnkwaters** [comment]
This is the transaction I am sending - it's that Bundle on the end of the URL that is objectionable.
Code to generate this is
```

            var tx = new TransactionBuilder(fc.Endpoint, Bundle.BundleType.Transaction)
                .Update(p.Id, p);
            var b = tx.ToBundle();

            var res = await fc.CreateAsync(b);

```
Where p is a new Patient

This is in order to do Client Assigned IDs.

```
POST https://fhir-st-mpi-clinical-dev.apps.okd.healthconcourse.com/Bundle
{
  "resourceType": "Bundle",
  "type": "transaction",
  "entry": [
    {
      "resource": {
        "resourceType": "Patient",
        "id": "00000005",
        "identifier": [
          {
            "system": "http://ger911.com/fhir/hc",
            "value": "ORG-GER-00000005"
          }
        ],
        "active": true,
        "name": [
          {
            "family": "Waters",
            "given": [
              "005"
            ]
          }
        ]
      },
      "request": {
        "method": "PUT",
        "url": "Patient/00000005"
      }
    }
  ]
}

```

**Comment by mmsmits** [comment]
Hi @johnkwaters,

What is your question exactly? Is there an issue in our FHIR Client with posting transaction bundles to a /Bundle endpoint?

**Comment by johnkwaters** [comment]
The Philips CDR team told me the same thing - a bundle transaction should post to the base path, not /Bundle:

http://hl7.org/fhir/r4/http.html#transaction

**Comment by johnkwaters** [comment]
I guess I am a little confused here...
So my code was doing this:

```
            var tx = new TransactionBuilder(fc.Endpoint, Bundle.BundleType.Transaction)
                .Update(p.Id, p);
            var b = tx.ToBundle();

            var res = await fc.CreateAsync(b);

```

And looking at the source code for TransactionAsync, I see:

```
        public Task<Bundle> TransactionAsync(Bundle bundle)
        {
            if (bundle == null) throw new ArgumentNullException(nameof(bundle));

            var tx = new TransactionBuilder(Endpoint).Transaction(bundle).ToBundle();
            return executeAsync<Bundle>(tx, HttpStatusCode.OK);
        }

```

So I already have a TransactionBundle ... with an Update in it - then your code turns the TransactionBundle into.... a TransactionBundle? Seems the only difference is that you then call executeAsync?

So would all of this just be the same as:

```
            var tx = new TransactionBuilder(fc.Endpoint, Bundle.BundleType.Transaction)
                .Update(p.Id, p);
            var b = tx.ToBundle();

            var res = await fc.executeAsync(b, HttpStatusCode.OK);

```

And the reason I am doing this convoluted call, is that I am trying to do a client assigned ID for the Patient p, and the CDR vendor said I can only do that by create a request that has this form:

```
POST https://fhir-st-mpi-clinical-dev.apps.okd.healthconcourse.com
{
  "resourceType": "Bundle",
  "type": "transaction",
  "entry": [
    {
      "resource": {
        "resourceType": "Patient",
        "id": "00000005",
        "identifier": [
          {
            "system": http://ger911.com/fhir/hc,
            "value": "ORG-GER-00000005"
          }
        ],
        "active": true,
        "name": [
          {
            "family": "Waters",
            "given": [
              "005"
            ]
          }
        ]
      },
      "request": {
        "method": "PUT",
        "url": "Patient/00000005"
      }
    }
  ]
}
```
 
The outer part is a POST to the endpoint WITHOUT /Bundle, and inside of it is a PUT for the patient with an ID.

**Comment by johnkwaters** [comment]
I can confirm that the change above
```
var tx = new TransactionBuilder(fc.Endpoint, Bundle.BundleType.Transaction)
  .Update(p.Id, p);
var b = tx.ToBundle();

var res = await fc.executeAsync(b, HttpStatusCode.OK);

```
 generates the request I was looking for:

```
POST https://cdr-stu3-sandbox.us-east.philips-healthsuite.com/store/fhir/5b1ffebe-46f3-40c4-b12a-653364078073
{
  "resourceType": "Bundle",
  "type": "transaction",
  "entry": [
    {
      "resource": {
        "resourceType": "Patient",
        "id": "00000005",
        "identifier": [
          {
            "system": "http://ger911.com/fhir/hc",
            "value": "ORG-GER-00000005"
          }
        ],
        "active": true,
        "name": [
          {
            "family": "Waters",
            "given": [
              "005"
            ]
          }
        ]
      },
      "request": {
        "method": "PUT",
        "url": "Patient/00000005"
      }
    }
  ]
}
```

**Comment by mmsmits** [comment]
Good! I'll close this issue then :)

**Comment by johnkwaters** [comment]
Thanks @mmsmits . I don't know if you can respond the the discussion on the topic - see #2099 
I am hearing different things from diffferent CDR vendors (HAPI, Smile, Philips)
What is your take on how a client assigned ID should be sent for a new Patient record?

**Comment by brianpos** [comment]
Is this all a result of using the TransactionBuilder class to make a bundle rather than just hand creating the Bundle resource itself?

and yes, CreateAsync passing a bundle would be going to the generic Create method with Bundle as the implied type parameter
![image](https://user-images.githubusercontent.com/1557083/170413998-c3997e21-0610-45c1-9993-bcfde3eafeaa.png)
