### ISSUE TITLE
FromJson() Extension Request

### ISSUE THREAD

**Issue by chrisparkeronline** [FirelyTeam/firely-net-sdk#2109]
**Request Background**
Hello team, first would like to say great work with this component. While using this library, in many situations I find myself wanting to create an object like HealthcareService from a JSON string.

**Request Solution**
To help me with creating objects from the JSON string, I added some extensions in my code to do this for me. Others might need this as well. Sample code;

```
public static Hl7.Fhir.Model.HealthcareService FromJson( this Hl7.Fhir.Model.HealthcareService resource, string json )
{
    try
    {
        if ( string.IsNullOrEmpty( json ) == false )
            return new Hl7.Fhir.Serialization.FhirJsonParser().Parse<Hl7.Fhir.Model.HealthcareService>( json );
    }
    catch { }

    return null;
}
```
I'm sure there is a more elegant way to do this, but I have created this block of code for each object I use in our solution. This is just a feature request and completely understand if you do not want to implement it. If not and others need it please feel free to use this to help yourself. Also please post any code of a better way to do this if you find one, I would love to reduce my code.

Thanks team, keep up the good work!

**Comment by brianpos** [comment]
Tips, would be an easy generic to create there. So only 1 simple function, not 1 for each resource type.
Also not a fan of the catch anything and discard/ignore... Would recommend being more particular on that.

**Comment by ewoutkramer** [comment]
Hi @chrisparkeronline - thanks for your nice words and reaching out to us!

I have a few issues with your proposal:

* You have written an extension method on an instance of type X, which parses a resource into another instance of type X. So, basically - you need a pre-existing instance to parse a new instance.  I can see why you would do that - C# has no support for  a `static` extension method, e.g. adding a static `ToJson` to all POCO `classes`.  Still, users will not quickly understand this design without documentation (e.g. you can see that you are not actually using the `resource` parameter at all).

* The main part of your function `new FhirJsonParser().Parse<Base>(json);`, is actually really short, so we're not gaining much by adding this extension method.
* What this extension method really does is ignore errors or an empty json text, and turn them into nulls - something I don't want the SDK to do (ignoring parse exceptions and turning them into a null looks like a bad idea to me).

I don't think it adds enough value to add it to the public interface of the SDK.

For your own codebase, I wondered whether you have considered defining the extension method on a generic type `T`? That way you only have to create 1 such method (not one for every type you are using):

```
public static T FromJson( this T _, string json ) where T: Base
{
    try
    {
        if ( string.IsNullOrEmpty( json ) == false )
            return new Hl7.Fhir.Serialization.FhirJsonParser().Parse<T>( json );
    }
    catch {  }

    return null;
}
```
