### ISSUE TITLE
Missing Release / Release Note and/or Link so that consumer can see diff from dependenbat/renovate

### ISSUE THREAD

**Issue by tebeco** [FirelyTeam/firely-net-sdk#2110]
NOTE:
I am NOT related to SixLabor team or product, just using that as an example here
This is also not a critical issue at all, I just noticed that recently

**Is your feature request related to a problem? Please describe.**
When bots, like `renovate`, open a pull request and update packages in repository from consumer of packages, 
they seems smart enought to crawl release note / diff.
It seems that this information from [Hl7.Fhir.R4](https://togithub.com/FirelyTeam/firely-net-sdk) is not detected somehow.

## Probable cause:
The relerase tags do not match the package version.
https://github.com/FirelyTeam/firely-net-sdk/tags
eg: `v3.8.3-stu3` instead of `3.8.3`

## Describe the solution you'd like
Here is what's generates for this library:
![image](https://user-images.githubusercontent.com/2266487/172772277-41f1d0db-0c0e-4179-a6ae-800f340660aa.png)

Here is an example of [SixLabors.ImageSharp](https://togithub.com/SixLabors/ImageSharp):
![image](https://user-images.githubusercontent.com/2266487/172772183-84d7b0b6-e513-425e-8788-ebea9565e210.png)
![image](https://user-images.githubusercontent.com/2266487/172772207-fd378816-07ab-453d-b8cc-f6b05884a44c.png)

![image](https://user-images.githubusercontent.com/2266487/172772637-8121e567-d79e-410f-b72f-9b07a84e4aca.png)

##  Describe alternatives you've considered
There's no alternative, as I do not own either bots or the package.
For the `v` the bot maintainers might have some logic to elide it, no clue, not tested.
My guess is that the main issue here is probably the use `-stu3` or `-r???` that no automate can guess if these are custom for that repo. (Unless it's a standard tooling thing ?)

## More Information
I suspect it's linked to the fact you're using a monorepository
Here's apparently a PR fixing that issue for repository using `learna` generated release notes for mono repo. It also provide an example of a such repo.
https://github.com/renovatebot/renovate/pull/7457

I do understand that learna is JS/TS specifics, but there's apparently "something" that it can looks for regardless of the tool used to create the release notes

**Comment by marcovisserFurore** [comment]
We moved all to 1 repo and we have only 1 main branch. So be doing this we resolved this issue here. See for example a recent dependabot PR:



![Image](https://github.com/FirelyTeam/firely-net-sdk/assets/31658535/5aff0698-4738-4d86-8b8e-5c4268883700)
