### ISSUE TITLE
Missing profiles for an extension should not produce validation errors, but warnings

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2114]
**Describe the bug**
When an extension refers to a profile that cannot be found, the validator treats this as an error. We do this on several occasions (e.g. when a valueset cannot be found), but in the specific case of an extension, this should *not* generate an error.

**To Reproduce**
Create an instance of a Patient, with an extensions referring to, say, http://www.miniaf.alp/extension/written-signature. Validate.

**Expected behavior**
For extensions, this should be a warning. For modifierExtensions this should be an error (I think)

**Additional context**
This was found while Rene Spronk was creating snippets for our upcoming training. We can contact him for the actual example or extension definition.

**Comment by marcovisserFurore** [comment]
Duplicate of #2105

See also #1258

**Comment by ewoutkramer** [comment]
This was fixed by https://github.com/FirelyTeam/firely-net-sdk/pull/2187, closing.
