### ISSUE TITLE
Add fullUrl to Bundle entry with TransactionBuilder

### ISSUE THREAD

**Issue by mbaltus** [FirelyTeam/firely-net-sdk#2115]
When adding entries to the TransactionBuilder, there is no option to set a fullUrl, and the TransactionBuilder logic does not add the fullUrl itself. This means that you need to convert to a Bundle and then run through all the entries to add the fullUrls by hand after the transaction has been setup.

I would like an overload to the TransactionBuilder methods to be able to set the fullUrl when needed.

**Comment by LodewijkSioen** [comment]
This is something we ran against. We need to set the FullUrl property with a reference containing searchparams so references further in the bundle get referenced correctly when the transaction completes.
eg
``` 
    public TransactionBuilderPlus CreateIfNotExists(Resource body, SearchParams condition, out string fullUrl)
    {
        _inner.Create(body, condition);
        fullUrl = $"{body.TypeName}?{condition.ToUriParamList().ToQueryString()}";
        _entryFullUrls.Add(fullUrl);

        return this;
    }
```
and then:
```
    public Bundle ToBundle()
    {
        var bundle = _inner.ToBundle();
        for (int i = 0; i < _entryFullUrls.Count; i++)
        {
            bundle.Entry[i].FullUrl = _entryFullUrls[i];
        }
    }
```

Then I can use it like this:
```
transaction.CreateIfNotExists(patient, patient.Identifier[0].ToSearchParameter(), out var patientUrl);
var encounter = new Encounter
{
    Subject = new ResourceReference(patientUrl),
}
```
And then the server will link the two using the correct identifiers.
