### ISSUE TITLE
Make FhirClient more version agnostic

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/firely-net-sdk#2131]
**Describe the solution you'd like**
It should be possible that, for example, a R4 FhirClient can also handle R4B resources. Or a R5 FhirClient can handle R4B resources.

This issue needs more refinement.

**Comment by brianpos** [comment]
Don't know that an R5 FhirClient should be able to handle R4B resources...

**Comment by marcovisserFurore** [comment]
Well, a R5 client should be able to handle a R4B Patient resource for example. Because it is a normative resource. But not all the resources could be handled of course. So, we have to find out how to report these errors to the end user.

**Comment by marcovisserFurore** [comment]
In the meantime I did some tests:

- The setting `FhirClientSettings.VerifyFhirVersion` is default `false`. So, the FhirClient is not checking the version of the server by default. 
- Running a R4B client on a R4 server works fine with normative resources. 
- Switch on `FhirClientSettings.VerifyFhirVersion` to `true` will crash FhirClient, because it is going to parse a `CapabilityStatement` of another FHIR version that has always unknown resources.

What we have to do is:
- create an informative message when there is an exception in the FhirClient and when the setting `FhirClientSettings.VerifyFhirVersion`  is `false`. Like: "_You are running perhaps an incompatible FhirClient. Please use the same version of the FhirClient and the server. Or switch on the `FhirClientSettings.VerifyFhirVersion`_"
- solve the crash when using `FhirClientSettings.VerifyFhirVersion`

**Comment by brianpos** [comment]
This is where the discussion needs to head with regards to the normative package of stuff.
But I must add that these normative things may still change too.
(just less often - so we will need to handle that at some stage too)
