### ISSUE TITLE
Implement (limited) validation of message bundle based on linked MessageDefinition

### ISSUE THREAD

**Issue by wardweistra** [FirelyTeam/firely-net-sdk#2137]
**Is your feature request related to a problem? Please describe.**
NHS is creating MessageDefinition artifacts to specify how specific message Bundles need to look like.
[MessageDefinition](https://www.hl7.org/fhir/messagedefinition.html) for example describes in the `focus` element how many of each resource (optionally with a specific profile) can/must be included in the Bundle.

When a Bundle declares it is of type 'message' (https://www.hl7.org/fhir/messaging.html) the first resource in the bundle is (can? must be?) a [MessageHeader](https://www.hl7.org/fhir/messageheader.html). The `MessageHeader` can refer with its `definition` element to a `MessageDefinition` resource.

Currently, when this reference is put in place the Validator will not validate whether the bundle actually complies to the MessageDefinition.

**Describe the solution you'd like**
When the reference from a messaging Bundle is set up as above: validate whether the bundle adheres to the resource list specified in the `focus` element of the `MessageDefinition`

**Describe alternatives you've considered**
Currently NHS has customised the Validator internally to look at the MessageHeader.eventcode and find the matching MessageDefinition event code and then validate the focus profiles. This is a custom point solution.

**Additional context**
Validation of the message will be only a subset of the information that is defined in `MessageDefinition`, where other aspects are more around behavioral validation (Touchstone/Inferno). (see https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Validation.20of.20messages.20and.20operations)
There's a bunch of other definitional artifacts that could eventually also be considered to see what we can validate from them in the Validator: https://www.hl7.org/fhir/resourcelist.html.

**Comment by NaminderSoorma** [comment]
This is the NHS D BARS project where I have been using MessageDefinitions with a reference in the Bundle > MessageHeader.definition to link. https://simplifier.net/NHSBookingandReferrals

The Bundle examples will show how it links together. Here is a direct link to one: https://simplifier.net/nhsbookingandreferrals/86e3371d-1c15-4862-9552-d9560f8292ba-duplicate-2

If the validation engine could work by following the MessageDefinition.focus entries and validate the Bundle that would be great!

**Comment by marcovisserFurore** [comment]
Asked some [feedback](https://firelyteam.slack.com/archives/DJX4KATLJ/p1658394268430269) from @wardweistra about this issue. (Internal only)

**Comment by marcovisserFurore** [comment]
This functionality is out of scope for the opensource validator. It will be added to the enterprise (to be developed yet) Firely validator. 
For internal, see [here ](https://firely.atlassian.net/browse/VONK-4818) the Jira issue (VONK-4818).
