### ISSUE TITLE
ElementModel ToTypedElement discrepency targetting R4 standard

### ISSUE THREAD

**Issue by christopher-watanabe-snkeos** [FirelyTeam/firely-net-sdk#2147]
Hello all, 

I'm working with the Firely .Net SDK within the scope of the [Microsoft Tools for Health Data Anonymization project](https://github.com/microsoft/Tools-for-Health-Data-Anonymization). I noticed recently that version 3.4.0 is used there still, so I'm attempting to upgrade to the newest v4.0.0 and get these nice, new benefits of faster, more efficient FHIR processing.

My interest is purely within the scope of the R4 standard, and I've perhaps found a discrepancy. I found it while running unit tests after updating the SDK reference to v4.0.0. Shortly put, there are unit tests to ensure that while working in the R4 standard, attempts to parse STU3 standard-specific json data throws errors, since the R4 standard does not have definitions for these. The specific unit test can be found [here](https://github.com/microsoft/Tools-for-Health-Data-Anonymization/blob/106d7de2b5f81e41505e7e906af40194c9af6735/FHIR/src/Microsoft.Health.Fhir.Anonymizer.R4.FunctionalTests/VersionSpecificTests.cs#L55). 

The STU3-specific types that are used in the tests are the [DeviceComponent](http://hl7.org/fhir/stu3/devicecomponent.html), [ProcessRequest](http://hl7.org/fhir/stu3/processrequest.html), and [ProcessResponse](https://hl7.org/fhir/STU3/processresponse.html). The json data representing these datas can be found [here](https://github.com/microsoft/Tools-for-Health-Data-Anonymization/tree/master/FHIR/src/Microsoft.Health.Fhir.Anonymizer.Shared.FunctionalTests/TestResources/Stu3OnlyResource). Interestingly, the DeviceComponent throws the expected error. However, since updating to v4.0.0 Hl7.Fhir.R4, I notice that the ProcessRequest and ProcessResponse json data can suddenly be cast to TypedElements, even though there appears to be no R4 standard definitions for them! 

Perhaps someone else in this community also works with the Microsoft tools? Or can explain to me how this can be? I've created a simple project to demonstrate my findings [here](https://github.com/christopher-watanabe-snkeos/hl7-fhir-r4-v4.0.0-discrepancy). I've simply copied the data from the Microsoft repo and turn the json data into TypedElements within Program.cs. 

Much appreciated! Looking forward to digging into this more!

**Comment by christopher-watanabe-snkeos** [comment]
Interestingly, none of the json data can be parsed and cast into TypedElements when using Hl7.Fhir.R4 v3.8.3. This seems then to be an issue coming from the new 4.0 release.

**Comment by marcovisserFurore** [comment]
Thanks @christopher-watanabe-snkeos for your issue. I have cloned your repo and have the same findings. I am not sure why this is happening. Next week I will create an unit test in our R4 base and see what is going on. 
I will keep you posted.

**Comment by brianpos** [comment]
Yup, this is a model generations issue.
Looks like when merging stu3 back into R4 at some point here it has re-introduced the resources removed in R4....
@marcovisserFurore suggest deleting the generated folder, rebuilding it and then check the diffs.

**Comment by brianpos** [comment]
@christopher-watanabe-snkeos if you want to try out the 4.1.0 versions, the recent R4B release, you'll need to comment out the MedicinalProduct from the list of R4 only resources, as that was removed in R4B.
Also the attribute validation checks are failing as the error messages from the SDK have changed, so the assertions are checking for explicit messages are failing (due to wording, not behaviour), then all the unit tests in that project succeed.
(I don't know if that makes everything all good in there then, but worth a look)
Updating to net60 and all the latest other nuget packages in VS2022 also still work with the defined unit tests.
https://github.com/brianpos/Tools-for-Health-Data-Anonymization/tree/develop-r4b

**Comment by marcovisserFurore** [comment]
We scheduled this bug for the next minor release (4.2)
