### ISSUE TITLE
Citation resource only partially included in the R4B build 4.1.0

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/firely-net-sdk#2149]
https://chat.fhir.org/#narrow/stream/294899-dotnet.2Fcommitters/topic/SDK.20v4.20Stuff

**Describe the bug**
The `Citation` resource is not included in several parts of the R4B release, the file is code generated and included in the supported resources collection, however the type is not listed in the string to type dictionaries.
Suspect is due to this line in the code generator.
https://github.com/microsoft/fhir-codegen/blob/d7185a77ccd42088c3d7723202a242220c7fd286/src/Microsoft.Health.Fhir.SpecManager/Language/CSharpFirely2.cs#L167

**Expected behavior**
Should be able to use the Citation resource (serialize and de-serialize)

**Version used:**
 - FHIR Version: R4B
 - Version: 4.1.0 (and the older R4Bs too)

**Additional context**
I came across it in the unit tests in my facade project while trying to upgrade to this build, and failed the loading all the examples from the zip file.
(Maybe the examples.zip file in the unit tests hasn't been updated to the R4B version too?)

I added this to my project to get it to work
``` c#
            // workaround for the citation resource.
            if (!ModelInfo.FhirTypeToCsType.ContainsKey("Citation"))
            {
                ModelInfo.FhirTypeToCsType.Add("Citation", typeof(Citation));
                ModelInfo.FhirCsTypeToString.Add(typeof(Citation), "Citation");
            }
```

**Comment by brianpos** [comment]
@marcovisserFurore I think this is already dealt with 4.2.1?

**Comment by marcovisserFurore** [comment]
For R4B this has been solved, but not for R5.
