### ISSUE TITLE
Manually correct Invariants ref-1, sdf-24 and sdf-25

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/firely-net-sdk#2153]
**Describe the bug**
The invariants `sdf-24` and `sdf-25` are causing problems because of negative values. This should be manually corrected in the validator (and FhirPath?)

See also the HL7 issue [FHIR-37761](https://jira.hl7.org/browse/FHIR-37761)

**Version used:**
 - FHIR Version: R4B
 - Version: 4.1.0

**Comment by marcovisserFurore** [comment]
We solve this in the new validator,  Let's solve it in `StructureDefinitionCorrectionsResolver`

**Comment by ewoutkramer** [comment]
ref-1/substring() is also broken.
