### ISSUE TITLE
POCO-Validation on Extension incorrect

### ISSUE THREAD

**Issue by izydorkowalsky** [FirelyTeam/firely-net-sdk#2158]
**Describe the bug**

Extension with null-Value is set at a Fhir-Resource
The Validate-Extension on Resource doesn't adress this invalidity. No Error is thrown, what should be the case.
The core specification says: 
> Rule: Must have either extensions or value[x], not both

**Expected behavior**
validation error is thrown

**Version used:**
 - FHIR Version: R4
 - Nuget: Hl7.Fhir.R4 Version 4.1.0

**Comment by mbaltus** [comment]
Can you add some example code to reproduce this? I've tried supplying a null value, and an empty one and get these messages:
null value: "Instance count for 'Extension.value[x]' is 0, which is not within the specified cardinality of 1..1" and "Instance failed constraint ext-1 \"Must have either extensions or value[x], not both\""
empty value: "Element must not be empty"

**Comment by izydorkowalsky** [comment]
Hi, think you did it with the validator in Hl7.Fhir.Specification.R4 and not with the Extension-Method in Hl7.Fhir.R4

`
try
{
var patient = new Patient();
patientX.AddExtension("http://someExtensionUrl", null);
patient.Validate(true);
}
catch(Exception ex){

//No exception is thrown, but should be, cause Extension.value was empty
}
 `

**Comment by mbaltus** [comment]
Ah, yes, you're correct, I did use the validator and not the extension method. I overlooked that in your original message.

**Comment by ewoutkramer** [comment]
When you run <resource>.Validate(), you are invoking validation based on attributes on the POCO (documented here: https://docs.fire.ly/projects/Firely-NET-SDK/validation/poco-validation.html).  Attribute-based validation of POCOs just cover basic structural things like cardinalities and using the right choice type (e.g. for Observation.value[x]).

There are many more constraints and invariants that are stated in the FHIR profiles only (e.g. slicing, fhirpath rules).  The invariant you are referring to is formulated as a FhirPath rule in the StructureDefinition for Patient - and so is not part of the validations covered by the attribute validation.

If you need to do more complete validation, you have to run profile validation. We have not yet documented this, but this project (https://github.com/FirelyTeam/Furore.Fhir.ValidationDemo) shows how to do that.
