### ISSUE TITLE
Validator incorrectly checks contained resource against all stated profiles instead of one

### ISSUE THREAD

**Issue by njnikodym** [FirelyTeam/firely-net-sdk#2161]
**Describe the bug**
Validator incorrectly checks contained resource against all stated profiles instead of one

**To Reproduce**
See Issue01 in the following project on Simplifier: https://simplifier.net/test-cases-for-validation-issues . Profile Issue01Appointment contraints the TargetProfiles of Appointment.participant.actor by replacing the Patient and Practitioner targets with custom profiles. The Issue01Appointment instance contains one contained reference that conforms to the Issue01Practitioner profile. Validation using the QA results in a lot of errors. It looks like the validator checks the contained resource to every target profile in the profile.

**Expected behavior**
No error message

**Screenshots**
![image](https://user-images.githubusercontent.com/68131234/180737097-e221b422-0ef9-4865-82ce-15bc562b2caa.png)

**Version used:**
 - FHIR Version: R4

**Comment by marcovisserFurore** [comment]
I discussed this with Nathalie and this issue has not the highest priority. 
We will solve this bug in the new validator.

**Comment by marcovisserFurore** [comment]
We will solved this in the new validator. See issue [AB#767](https://dev.azure.com/firely/Firely%20Suite/_sprints/backlog/Firely%20Team/Firely%20Suite/2022%20Q3/Sprint%2014%20(wk%2033)?workitem=767)
