### ISSUE TITLE
Unexpected htmlCheck() occurred 

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/firely-net-sdk#2162]
**Describe the bug**
_From Rene Spronk_

Validating the following will raise some invariant failures.

```xml
  <text>
    <status value="generated"/>
    <div xmlns="http://www.w3.org/1999/xhtml">
        <b>Patient:</b> Adam EVERYMAN, M, 16-Feb-1987, Cit.id 1020304050, AlphaId 622883245 
        <UL>
          <LI>Previous name: Adam JONES</LI>
          <LI>Address: 62, Anystreet, 59450 Alphatown. Home phone: 020 7422 3666</LI>
        </UL>
    </div>
  </text>
```

The failures are:
- Instance failed constraint txt-1 &quot;The narrative SHALL contain only the basic html formatting elements and attributes described in chapters 7-11 (except section 4 of chapter 9) and 15 of the HTML 4.0 standard, &lt;a&gt; elements (either name or href), images and internally contained style attributes&quot;
- and Instance failed constraint txt-2 &quot;The narrative SHALL have some non-whitespace content&quot;

By the way, the HTML spec states that trailing  `</LI>` may be omitted. Nasty, because then it's not valid XML anymore.

**Comment by ewoutkramer** [comment]
What is incorrect about this?  The narrative is validated against the HL7-provided XSD schema.  Maybe the uppercase UL?   Well txt-2 looks a bit silly.

**Comment by ewoutkramer** [comment]
> By the way, the HTML spec states that trailing </LI> may be omitted. Nasty, because then it's not valid XML anymore.

Yes, HTML did, but this is XHTML - which does not allow it fortunately.

**Comment by ewoutkramer** [comment]
I can see that it would be nice to know WHY txt-1 failed - we need to handwrite a special case of txt-1 for that....

**Comment by ewoutkramer** [comment]
Yes, that's it. This is an appropriate document to look at: https://www.w3.org/TR/xhtml1/diffs.html

4.2. [Element and attribute names must be in lower case](https://www.w3.org/TR/xhtml1/diffs.html#h-4.2)
4.3. [For non-empty elements, end tags are required](https://www.w3.org/TR/xhtml1/diffs.html#h-4.3)

**Comment by marcovisserFurore** [comment]
The validator is correct according to the standards. Perhaps we can improve the errortext in the new validator. I have created a [ticket](https://dev.azure.com/firely/Firely%20Suite/_sprints/backlog/Firely%20Team/Firely%20Suite/2022%20Q3/Sprint%2014%20(wk%2033)?workitem=768) for that
