### ISSUE TITLE
CoreZipExpander should recover from crashing after creating an empty directory

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2164]
**Is your feature request related to a problem? Please describe.**
Quite a few times while switching branches, my CoreZipResolver is not able to resolve the basic core FHIR types. This is often caused by (probably) the CoreZipResolver or its associated process crashing/being stopped while doing the initial unpack of the zip file. When this happens, all we have is an empty directory FhirArtifactCacheXXXX, which means every subsequent run will fail, until you delete this empty directory and the CoreZipResolver will try to re-unpack the zip.

**Describe the solution you'd like**
I'd like to enhjance the CoreZipResolver so it recognizes a previous failed attempt (= empty directory -- never seen just a few files) and recover from it, so for it to continue unpacking.

**Describe alternatives you've considered**
Deleting these directories from %TEMP% works too, but most of the time after a frustrating period of looking for the root cause of resolution failing on basic core types.

**Additional context**
This happens on other peoples machines too, I do get mails about it. Doing this would save time on responding to mails - but more importantly, it would help people who have no clue what's going on and not emailing us.

**Comment by timorosenblatt** [comment]
I've hade the same problem on two different machines so far.
I understand this only happens during initialization of a Validator using ZipResolvers, correct?

My work around for the time being will be to try to resolve "http://hl7.org/fhir/StructureDefinition/Bundle" by URI using the settings I'm about to use to create my validator.
If that fails I'll delete the %temp% folders and try again.

**Comment by brianpos** [comment]
There are cases I've had over the years where the folder is cleaned by something outside the process, os grabbing disk space from temp folder?

**Comment by ewoutkramer** [comment]
The folder being clean up completely is fine. But the CoreZipExpander looks for the existence of the directory - and then concludes it has no work to do. So if the directory gets created, but then the unzip fails, the unzip will never be retried. And the resolver will scan an empty directory -> it will not find any of the types from the spec.zip.
