### ISSUE TITLE
To ``ScopedNode`` or not to ``ScopedNode`` in the FP Engine

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2176]
**Is your feature request related to a problem? Please describe.**
All extension methods provided to evaluate FhirPath on a POCO or `ITypedElement` call ``ToSopedNode`` to make sure that the FP engine runs on scoped nodes. The `resolve` handler however, will just return `ITypedElement` (unless the resolve() resolved within the current instance, which is a ScopedNode).  This means that any node accessed after invoking a `resolve()` in FhirPath might *not* be a `ScopedNode`, especially when the resolve() resolved to an external resource, not the current instance.

**Describe the solution you'd like**
We should make sure the node returned by resolve() is turned into a `ScopedNode`.

**Comment by mmsmits** [comment]
This will be replaced by other issues
