### ISSUE TITLE
The default context for FhirPath evaluation is leaving out `%resource`

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2177]
**Is your feature request related to a problem? Please describe.**
When you execute one of the extension methods for FhirPath on POCO or ITypedElement - and you don't supply the optional parameter for the context, a default, empty context is provided.  This means that `%resource` and `%rootResource` will return null. Although these environment variables are not used often, they are not expected to be null.  In fact, the constructor for `FhirEvaluationContext` that takes a `ScopedNode` as a parameter, will try to locate the nearest resource in the input data and then set the `%resource` accordingly. It makes total sense that this is the default. In fact, when we ourselves invoke the FP engine in the validator, we *are* always supplying the correct parameters.

**Describe the solution you'd like**
Pick a sensible default, instead of null. Preferably the same approach as the constructor taking `ScopedNode`.

**Comment by ewoutkramer** [comment]
Note that finding defaults is only possible if the caller supplies input data that is itself a resource, or a node within a ScopedNode - otherwise we won't be able to find a sensible default "resource" node within the parents of the data passed in.

**Comment by mmsmits** [comment]
See also:
[#327](https://github.com/FirelyTeam/firely-validator-api/issues/327)
