### ISSUE TITLE
Make sure ToFhirValues() works as documented in the docs

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/firely-net-sdk#2189]
See https://docs.fire.ly/projects/Firely-NET-SDK/

**Comment by marcovisserFurore** [comment]
@ewoutkramer can you explain what is wrong with the function `ToFhirValues()`? Looking at the code I can only come up with an idea that the function crashes when the TypedElement is a resource, for example `Patient`.

**Comment by brianpos** [comment]
It's been working fine to me (did I write it?)

**Comment by ewoutkramer** [comment]
Coordinated with @brianpos - I had misunderstood the use of this function - I will need to change the FhirPath documentation.

**Comment by ewoutkramer** [comment]
See https://github.com/FirelyTeam/firely-docs-firely-net-sdk/pull/28
