### ISSUE TITLE
fhirClient with Basic Authentication

### ISSUE THREAD

**Issue by extential** [FirelyTeam/firely-net-sdk#2191]
when using the fhirClient with Basic Authentication the api hangs and does not return anything.

the code:

var authenticationString = "user:password";
var base64EncodedAuthenticationString = Convert.ToBase64String(System.Text.ASCIIEncoding.ASCII.GetBytes(authenticationString));
var handler = new AuthorizationMessageHandler();
handler.Authorization = new AuthenticationHeaderValue("Basic", base64EncodedAuthenticationString);

var client = new FhirClient("https://192.168.1.133:9443/fhir-server/api/v4/", settings, handler);
var patientBundle = client.Search<Patient>();

**Expected behavior**
I could see it's returning the data using fiddler however it does not populate patientBundle.

**Version used:**
 - FHIR Version: R4
 - Version: [e.g. 1.9.0]

**Additional context**

**Comment by extential** [comment]
Hi mmsmits,

I've tried with the following and still getting the same outcome. 

var patientBundle = client.Search<Patient>(new string[] { "family:exact=Levin" });

**Comment by mmsmits** [comment]
Are you using fiddler as a client or to peek at the http traffic the FhirClient generates?

Since this a commonly used part of the SDK, we are surprised by this issue. But it's hard for us to replicate without access to your environment. 

Does everything work fine when you try doing the same with Postman or Fiddler as a client?

**Comment by extential** [comment]
This is what I'm getting with fiddler:

Postman:
![image](https://user-images.githubusercontent.com/47131795/184264954-855c540b-e06b-4a89-8350-0fd3aad5ce5d.png)

![image](https://user-images.githubusercontent.com/47131795/184264988-71e061a8-13d1-43d8-b2d6-eb45e1aed31a.png)

using the code above:
![image](https://user-images.githubusercontent.com/47131795/184265024-5f95a685-9b19-46d5-901f-ef4381fb9f85.png)

![image](https://user-images.githubusercontent.com/47131795/184265034-db8f66b1-b00a-4a50-b1cf-18e0bca40d97.png)


I can see both returning data in fiddler, however this line gets stuck and doesnt return data.

var patientBundle = client.Search(new string[] { "family:exact=Levin" });

**Comment by mmsmits** [comment]
@extential Thanks for checking and comparing with postman.
Have you tried doing a simple `GET` on a single resource instead of a search? 
Since this is about interacting with a specific FHIR server, it's really hard for us to reproduce.
