### ISSUE TITLE
Harmonise behaviour with Java validator for parsing strings as integers in JSON

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-net-sdk#2193]
**Is your feature request related to a problem? Please describe.**
Example resource:

```
{
    "resourceType": "CodeSystem",
    "status": "active",
    "content": "example",
    "count": "10"
}
```

The count element in the JSON is erroneously represented as a string, not as a number. The Java tooling catches this error and throws a parsing exception "Error parsing JSON: the primitive value must be a number". The .NET SDK happily accepts this resource.

The following unit tests will fail:

```
[TestMethod]
public void ParseJsonNumber()
{
     var json = "{\"resourceType\": \"CodeSystem\",\"status\": \"active\",\"content\": \"example\",\"count\": \"10\"}";
     var parser = new FhirJsonParser();
     ExceptionAssert.Throws<StructuralTypeException>(() => parser.Parse<Patient>(json));
}
```

**Describe the solution you'd like**
The JSON parser should throw a StructuralTypeException here. Otherwise make sure that at least the validator will report this as an error.

**Comment by grahamegrieve** [comment]
Note that the regular Java parser is fine with a string here. It's only the validator parser that complains (in case that's not clear from @alexzautke's comments)

**Comment by ewoutkramer** [comment]
Right. In the .NET API we're moving things around a little bit. Our new parsers that we are releasing currently actually catch this in the parser - but the new parsers will allow you to ignore that and continue parsing and will represent this as a string in the .NET POCO model - where the validator will catch it in that case.

Let's keep this issue around to make sure that after the dust settles with the new parsers, this is indeed the case.

**Comment by ewoutkramer** [comment]
This is indeed done as described. The new parsers catch this + allow you to ignore it too.
