### ISSUE TITLE
Fhir Json Parser question: stripping out blank in patient address

### ISSUE THREAD

**Issue by awootton1** [FirelyTeam/firely-net-sdk#2206]
Hi, I have a patient resource fhir json input string with an Address Line 1 as blank and an Address Line 2 with data.  
 "address": [
                    {
                        "line": [
                            "",
                            "Address Line 2 Only"
                        ],

If the user makes a mistake like this and uses address 2 instead of address 1, we were expecting to still see address 1 come back through the FhirJsonParser() as a blank.  However, address 1 is not coming back at all in this scenario.  Is it being stripped out in the FhirJsonParser()?  Is this expected?  

The results after the parser look like this: 

"address": [
        {
            "line": [
                "Address Line 2 Only"
            ]
        }
    ]

Thank you

**Comment by marcovisserFurore** [comment]
Thanks for your feedback @awootton1 . We will discuss this issue in our next sprint.

**Comment by mbaltus** [comment]
The parser has a setting to allow it to recover from certain errors in the input. By default this is enabled. If you add `PermissiveParsing = false` to the ParserSettings, the FhirJsonParser will throw the expected error on parsing your Patient string: "Parser: The property 'line' has an empty string value, which is not allowed."

**Comment by marcovisserFurore** [comment]
I am closing this issue because the error is found by using the option `PermissiveParsing = false`. Empty lines (so empty string values) are not allowed in FHIR (See also [here](https://www.hl7.org/fhir/datatypes.html#string))
