### ISSUE TITLE
Parameters with Patient with Invalid birthDate confuses FhirJsonParser

### ISSUE THREAD

**Issue by scottc-WellSky** [FirelyTeam/firely-net-sdk#2207]
**Describe the bug**
We've implemented Patient $match that accepts Parameters. When the parameters.resource is a Patient with an invalid birthdate ("1938-05-") parameters passed to the controller method is null.

Our implementation uses a TestInputFormatter:
```
        public ResourceJsonInputFormatter()
        {
            // We don't want the parser to throw exceptions here so we can catch
            // validation errors in code and include an appropriate error message
            parser = new FhirJsonParser(new ParserSettings { AllowUnrecognizedEnums = true, PermissiveParsing = true, AcceptUnknownMembers = true });
            charPool = new JsonArrayPool(ArrayPool<char>.Shared);

            SupportedEncodings.Clear();
            SupportedEncodings.Add(Encoding.UTF8);

            foreach (var mediaType in ContentType.JSON_CONTENT_HEADERS)
            {
                SupportedMediaTypes.Add(mediaType);
            }
        }
```

**Expected Result**
Any of the following would work:
- Throw an exception with an indication of an error with the birthdate so a 500 will be returned to caller
- Parse the parameters with everything except the invalid birthDate
- Almost anything would be better than current scenario

**Version used:**
 - FHIR Version: R4
 - Version: 3.8.2 and 4.2.1

**Comment by brianpos** [comment]
Which version of the FirelySDK?
4.1.0/4.2.0?
You can see how I've done this in my facade project (also no nuget)
https://github.com/brianpos/fhir-net-web-api/blob/develop-r4/src/Hl7.Fhir.WebApi.AspNetCore/JsonFhirFormatter.cs#L73
What you are likely missing is catching the exception and then throwing that correctly so at least the caller is able to see the what the error was.
With 4.1 and 4.2 there is a new Json Parser using the new System.Text.Json serializers.
(have in a private branch of the facade project that do plan to release shortly)

**Comment by brianpos** [comment]
Actually, that's the default in my public r4b version. https://www.nuget.org/packages/brianpos.Fhir.R4B.WebApi.AspNetCore/4.1.0-beta1

https://github.com/brianpos/fhir-net-web-api/blob/feature/r4b/src/Hl7.Fhir.WebApi.AspNetCore/FhirFacadeBuilder.cs#L69
https://github.com/brianpos/fhir-net-web-api/blob/feature/r4b/src/Hl7.Fhir.WebApi.AspNetCore/JsonFhirFormatter2.cs

**Comment by scottc-WellSky** [comment]
Sorry, this was actually a problem with our error handling that I missed. 

@brianpos, many thanks for pointing me to your project -- looks great!
