### ISSUE TITLE
NullRefEx on FhirDateTime.TryToDateTimeOffset

### ISSUE THREAD

**Issue by izydorkowalsky** [FirelyTeam/firely-net-sdk#2218]
Invoking TryToDateTimeOffset on FhirDateTime throws an Exception if FhirdateTime is null

It ist not expected that a Try-Method throws an error. Instead it should return false

Example Code:

```
var period = new Period();
var success = period.StartElement.TryToDateTimeOffset(out var start) //throws NullRefException
```

**Comment by ewoutkramer** [comment]
We don't think this is applicable. See https://github.com/FirelyTeam/firely-net-common/pull/231.
