### ISSUE TITLE
Need way to provide ExceptionHandler (ExceptionNotificationHandler) to Serializers

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/firely-net-sdk#2222]
**Is your feature request related to a problem? Please describe.**
The serializers have an awesome internal class PocoBuilder that is internally used to create objects during serialization, this has an ExceptionHandler which would permit the injection of a custom handler to catch errors during serialization (which is its purpose), however there is no way to provide this handler.
One of the reasons that I would like to be able to do this is so that I can over-ride the "validations" on date values that occurs during serialization and permit that to continue, (and possibly put the string value encountered into the property anyway). This is of particular concern when posting a large bundle and have 1 field with a dud date - then everything just halts.

**Describe the solution you'd like**
Expose the PocoBuilder as public (then I can inject it there) or add the ExceptionHandler into the PocoBuilderSettings/ParserSettings objects.
(settings I guess is the preferred option, then can be in all 4 of the serializers, old/new xml.json)

**Comment by brianpos** [comment]
Would be nice if this also interacted with the ComplexTypeReader so that when it is doing the throws it could pass through there also. But I guess you could just use the other settings to skip those checks.

**Comment by brianpos** [comment]
This commit shows my thoughts on the settings object dragging the content through.
https://github.com/FirelyTeam/firely-net-common/commit/3005151222a71df25b8df04ebe1180d27612816c
Then in the buildPocoBuulderSettings, copy that value over too.
https://github.com/FirelyTeam/firely-net-sdk/blob/30a8c3e4c0fab72e3d9357451c12c15d198172a3/src/Hl7.Fhir.Core/Serialization/BaseFhirParser.cs#L24
``` c#
        private PocoBuilderSettings buildPocoBuilderSettings(ParserSettings ps) =>
            new PocoBuilderSettings
            {
                AllowUnrecognizedEnums = ps.AllowUnrecognizedEnums,
                IgnoreUnknownMembers = ps.AcceptUnknownMembers,
                ExceptionHandler = ps.ExceptionHandler,
#pragma warning disable CS0618 // Type or member is obsolete
                TruncateDateTimeToDate = ps.TruncateDateTimeToDate
#pragma warning restore CS0618 // Type or member is obsolete
            };
```

**Comment by brianpos** [comment]
As a part of this request, can we expand the StructuralTypeException with more granular error information than just the message?
Making all the parameters coming in here be populated on properties in the exception, that way if intercepting the exception you have all the raw data to reconstruct the error in your own format.
https://github.com/FirelyTeam/firely-net-common/blob/86207d30f3afb2d487bd4d69292159387d0dcb44/src/Hl7.Fhir.ElementModel/TypedElementOnSourceNode.cs#L82

**Comment by brianpos** [comment]
And this specific type parsing error message will have the location injected into the error message twice too.
https://github.com/FirelyTeam/firely-net-common/blob/86207d30f3afb2d487bd4d69292159387d0dcb44/src/Hl7.Fhir.ElementModel/TypedElementOnSourceNode.cs#L392
Looking at all the calls to the raiseTypeError, they all had some form of element name in the messages too. This feels like we should have a coding to facilitate translations here too.

**Comment by brianpos** [comment]
You could cherry pick this commit into R4B for the settings handler passing and unit test...
https://github.com/brianpos/fhir-net-api/commit/72140c7e930bbc6de89dc3e2ac5b0be73f69ff91

**Comment by rajithaalurims** [comment]
Hello @brianpos 

My requirement is to catch both Unknown elements and unrecognized enum values and report all errors at once.
I did set ExceptionHandler( see below) to parser settings. It works fine for Unknown elements, but parser throws an exception for unrecognized enum values and quits.

What should I do to continue with parsing instead of quitting when it seens an unrecognized enum value?

**Parset ExceptionHandler setting:**
            _parser.Settings.ExceptionHandler = (object source, Hl7.Fhir.Utility.ExceptionNotification args) =>
            {
                if (args.Exception is StructuralTypeException && args.Severity == Hl7.Fhir.Utility.ExceptionSeverity.Error)
                {
                    context.ModelState.TryAddModelError(string.Empty, string.Format(Api.Resources.ParsingError, args.Exception.Message));
                }
            };

**Comment by brianpos** [comment]
That's an area that I think could be improved.
Permitting those cases where the exception is thrown immediately via `RaiseFormatError` which just throws immediately to instead route to the ExceptionHandler if it is registered would be great, but that's unlikely to happen in the 4.x series now that the 5.x Firely libs are about ready to be released too.

What I've done to handle this is to permit the unknown enums, and catch that later in the validator (as I've shown above in some earlier comments in this thread)

**Comment by rajithaalurims** [comment]
Similar question for date fields. How to ignore date parsing errors? I want the parsing to continue so I can catch date issues later in the validator.
