### ISSUE TITLE
problem with nested extensions

### ISSUE THREAD

**Issue by jbaumflek** [FirelyTeam/firely-net-sdk#2239]
:information_source: Do you want to ask something or start a discussion, then go [here](https://github.com/FirelyTeam/firely-net-sdk/discussions)

:information_source: Is your bug report about Firely Server Facade, please send an email to [server@fire.ly](mailto:server@fire.ly) or submit a bug report to Jira if you are a paying customer.

**Describe the bug**
us core patient/us-core-ethnicity extension ends up with a nested extention that is misnamed valueExtension.  
![image](https://user-images.githubusercontent.com/23502719/190866546-3460df10-92fe-4428-9b86-d3a63517627a.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version used:**
 - FHIR Version: [e.g. STU3, R4, R5]
 - Version: [e.g. 1.9.0]

**Additional context**

**Comment by marcovisserFurore** [comment]
Hi @jbaumflek , thanks for you feedback. Can you explain what you are doing here? The added screenshot is indeed not correct. `valueExtension` should be `extension`. What operation of our SDK ends up with this result?
