### ISSUE TITLE
Validator generates invalid eld-20 warnings on logical model

### ISSUE THREAD

**Issue by Rob5045** [FirelyTeam/firely-net-sdk#2260]
**Describe the bug**
Quote from Ardon:
```
I don't why I get complains of violating eld-20 in our Logical Models within Forge. The same QA file in Simplifier does not give any errors.

Our Element path's (and thus names) look like this AdministrationAgreement.PeriodOfUse.StartDateTime
Which should conform to the eld-20 if I am correct:

eld-20[Warning](https://www.hl7.org/fhir/conformance-rules.html#warning)(base)Element names should be simple alphanumerics with a max of 64 characters, or code generation tools may be brokenpath.matches('^[A-Za-z][A-Za-z0-9]*(\\.[a-z][A-Za-z0-9]*(\\[x])?)*$')

https://www.hl7.org/fhir/elementdefinition.html
```

**To Reproduce**
Unit test **Issue2260LogicalModelValidationEld20Test** in this branch:
https://github.com/FirelyTeam/firely-net-sdk/commits/bugfix/issue-2260

**Expected behavior**
No warning generated.

**Screenshot from Forge 29.1**
![image](https://user-images.githubusercontent.com/81365724/193631822-87fb66f0-c6ab-4abd-a860-b97f91778ff2.png)

**Version used:**
 - FHIR Version: R4
 - Version: 4.3.0

**Additional context**
In the SDK 3.8.0 using Firely Terminal I got a different error message (don't know if it is relevant):

`Instance failed constraint dom-6 "A resource should have narrative for rubost management"`

Note that Firely Terminal has the validation setting **ConstraintBestPractices** set to the default value **Ignore**. That is why Ardon does not get the warning with Firely Terminal or Simplifier as both are still on SDK version 3.8.0.

**Comment by Rob5045** [comment]
Ewout:

It seems the newest version in 4.3 runs Eld-20 better than the previous version, since the names do indeed not match the required pattern:

eld-20 says names have to look like this: "path.matches('[A-Za-z][A-Za-z0-9]*(\\.[a-z][A-Za-z0-9]*(\\[x])?)*')"
This regex says:  paths must begin with a letter (A-Z or a-z) then any number of alphanumerics.  Then possibly a dot, followed by a lower case letter ([a-z]), then any number of alphanumerics etc.

The name should have been AdministrationAgreement.periodOfUse.startDateTime

**Comment by ewoutkramer** [comment]
It seems the newest version in 4.3 runs Eld-20 better than the previous version, since the names do indeed not match the required pattern:

eld-20 says names have to look like this: `path.matches('[A-Za-z][A-Za-z0-9]*(\\.[a-z][A-Za-z0-9]*(\\[x])?)*')`
This regex says:  paths must begin with a letter (A-Z or a-z) then any number of alphanumerics.  Then possibly a dot, followed by *a lower case letter ([a-z])*, then any number of alphanumerics etc.

So the validator is correct.

The name should have been `AdministrationAgreement.periodOfUse.startDateTime`
