### ISSUE TITLE
Use GET for termservice calls when possible

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2262]
Currently, the http terminology client (built on top of the Fhir http client) will always use a POST method to invoke a terminology service. However this is not strictly necessary, since for some calls, the parameters are actually simple types, and so we could use GET:

E.g. to validate a:
* Code, use GET (code=)
* Coding, use GET (code=, url=)
* CodeableConcept, need to use POST (or multiple calls)

When we would use GET, the HTTP infrastructure can cache the calls - something that is not possible with a POST.

**Comment by mmsmits** [comment]
We are probably never going to do this.
The external terminology service already has this option.
