### ISSUE TITLE
Add terminology support for some non-supplied codesystems

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2264]
There are a few popular codesystems that are not supplied as a FHIR codesystem resource, but for which basic support should be built into our terminology services. E.g. by supplying an `ITerminologyService` implementation that is specifically written to handle these codesystems.

The codesystems that we should support are:
* Currencies
* Country codes
* Languages
* Mime types

For some of these, we can write some basic validations (e.g. the allowed first parts of mime types, syntax of language codes). In fact, since these lists are (somewhat) volatile, we probably should not try to be complete.

**Comment by brianpos** [comment]
I have some of these already...

**Comment by mmsmits** [comment]
We have a MimeTypeTerminologyService, we could do the rest too now easily.
