### ISSUE TITLE
Convert Java POCO inter-version conversion to C#

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2265]
Grahame has generated+handwritten a set of Java classes that convert DSTU2<->R3<->R4<->R4B.  It seems possible to convert this Java code to C#, either using smart search/replace, or writing a Java parser (ANTLR?) + output with something like Roslyn.

**Comment by brianpos** [comment]
I was looking into it originally then switched over to porting the mapping engine, which I completed and is on github and NuGet.

I also investigated what it might take to get the fhirpath expressions in it converted to code too, however stalled at that point. Got enough for most search parameters, but that was it at the time.

The cql generation that is now open source might make this more interesting too as the main step I stalled on was type casting. Maybe time to revive the effort.

**Comment by mmsmits** [comment]
It seems this is not going to happen.
