### ISSUE TITLE
Utility class for processing Canonical Urls (to split version)

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/firely-net-sdk#2268]
When using Canonical URLs there's often a need to be able to quickly split the version from the actual canonical.
Implementation I'm using in my facade project would be good to have added to the core support library (isn't version specific)
https://github.com/brianpos/fhir-net-web-api/blob/feature/r4b/src/Hl7.Fhir.StructuredDataCapture/CanonicalUrl.cs
Example where I've been using it is for references from QuestionnaireResponses to Questionnaires, and Questionnaires to ValueSets.
(This could also be used in the validator where version specific references are detected)

Would also consider adding the processing to be able to detect and strip out a bookmark appended to it also.

**Describe the solution you'd like**
Move the class referenced into the Firely SDK.

**Comment by ewoutkramer** [comment]
I have one in the (to be public) new validator code as well.  Clearly there is a need for this ;-)

**Comment by brianpos** [comment]
@ewoutkramer I guess this can be closed then?

**Comment by ewoutkramer** [comment]
Yes! It has all landed on the right spot I think!
