### ISSUE TITLE
Possibility to add additional attributes to a serialized xml bundle 

### ISSUE THREAD

**Issue by JayJay1989** [FirelyTeam/firely-net-sdk#2271]
**Is your feature request related to a problem? Please describe.**
There is no way to add additional xhtml attributes to a serialized XML bundle.

for example:

```xml
<!--<Bundle xmlns="http://hl7.org/fhir">-->
<Bundle xmlns="http://hl7.org/fhir" xmlns:xhtml="http://www.w3.org/1999/xhtml">
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mmsmits** [comment]
This is not a prio
