### ISSUE TITLE
CommonFhirPackageSource.ListResourceUris does not return uri's

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/firely-net-sdk#2280]
**Describe the bug**
`CommonFhirPackageSource.ListResourceUris` does not return uri's, but return canonicals. The unit test `ResolverAndSourceExtensionTests. FindAllResources()` proves this. Set `source` to `FhirPackageSource.CreateFhirCorePackageSource()` and the unit tests fails. 

**Expected behavior**
The static class `PackageContextExtensions` should implement a method `ListUris` which results in a list of uris (`Resource/id`).  The `CommonFhirPackageSource.ListResourceUris` should call this new method `ListUris`.

**Version used:**
 - FHIR Version: all
 - Version: 4.3.1

**Comment by ewoutkramer** [comment]
This was fixed by https://github.com/FirelyTeam/Firely.Fhir.Packages/pull/46, closing.
