### ISSUE TITLE
Check whether to render "null" values for extensions of empty arrays in json

### ISSUE THREAD

**Issue by mmsmits** [FirelyTeam/firely-net-sdk#2282]
Implement the following behavior:

Note: when one of the repeating elements has no value, it is represented in the first array using a null. When an element has a value but no extension/id, the second array will have a null at the position of that element. **If the length of a JSON "element" array is different from the length of its JSON "_element" array, implementations SHALL infer null values in the suffix of the shorter array. If an array has only null elements, implementations SHOULD omit it entirely.**

Also alter ```JsonAssert``` so that it  an array with only null values equals that of it being not present.

**Comment by ewoutkramer** [comment]
Note that I have now built support for this into the deserialize: we will now accept "jagged" arrays, and assume null for the missing values.
