### ISSUE TITLE
Snapshot generation of "slicing" element bug, rules excluded

### ISSUE THREAD

**Issue by Sieuwkje-firely** [FirelyTeam/firely-net-sdk#2284]
Issue is resolved in https://github.com/FirelyTeam/firely-net-sdk/issues/2065, stays open just to check with customer if there are no additional bugs.

#In Firely terminal we use the snapshot generator. However, the resulting snapshot does not always seem to include rules for slicing elements. When we for example snapshot our ILSConsent.structuredefinition.xml with firely-terminal 3.0.0 (push, snapshot, save) we get an invalid snapshot.

In the snapshot generated with firely-terminal we get the snippet:

{
    "id": "Consent.provision.extension:location.value[x]",
    "path": "Consent.provision.extension.value[x]",
    "slicing": {
        "discriminator": [{
            "type": "type",
            "path": "$this"
        }]
},

If we do the same with hl7-validator we get:

{
    "id": "Consent.provision.extension:location.value[x]",
    "path": "Consent.provision.extension.value[x]",
    "slicing": {
        "discriminator": [{
            "type": "type",
            "path": "$this"
        }],
        "ordered": false,
        "rules": "closed"
},

The firely-terminal outcome seems to be missing the mandatory element “rules” (http://hl7.org/fhir/R4/elementdefinition.html#ElementDefinition

Generating the Snapshot in Forge yields the same issue.

For additional files for troubleshooting, see https://firely.atlassian.net/browse/SD-1273
For the StructureDefinition, see https://simplifier.net/Test-SD/ILSPatient/~overview

**Comment by ewoutkramer** [comment]
This was fixed in 4.3.0.

**Comment by ewoutkramer** [comment]
See also https://github.com/FirelyTeam/firely-net-sdk/issues/2232,
