### ISSUE TITLE
Refer to our FhirClient's mixed R4/R4B support in the HL7 guidance page

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2291]
**Is your feature request related to a problem? Please describe.**
We have coordinated with Grahame on how to deal with R4/R4B on the client side. We have adopted the same strategy as HAPI.

**Describe the solution you'd like**
The page at https://confluence.hl7.org/pages/viewpage.action?pageId=94663178#StrategiesfordealingwithR4andR4B-Libraryspecificguidance now only mentions the Java solution, ours should go in here too.

**Comment by mmsmits** [comment]
This would have been a nice thing todo at the time.
