### ISSUE TITLE
HumanName.Given.Append removes HumanName.GivenElement.Extension

### ISSUE THREAD

**Issue by FoppeCrezee** [FirelyTeam/firely-net-sdk#2294]
**Describe the bug**
When executing HumanName.Given.Append, previously added extensions on GivenElement are removed. After adding a name to HumanName.Given and adding the appropriate extension to the HumanName.GivenElement, the extension is removed when adding another name to HumanName.Given.

**To Reproduce**

```
var name = new HumanName()
{
    Given = new string[] {}
};

string firstName = "test";
string inititals = "t";

if (firstName != null)
{
    name.Given = name.Given.Append(firstName); 
    name.GivenElement[name.Given.Count() - 1].Extension.Add(new Extension("test", new Code("CL")));
}
if (Inititals != null)
{
    name.Given = name.Given.Append(initials); // removes extension at name.GivenElement[0] ?
    name.GivenElement[name.Given.Count() - 1].Extension.Add(new Extension("test", new Code("IN")));
}
```

**Expected behavior**
The Extension "CL" would remain on the appropriate GivenElement after adding a new name.Given

**Version used:**
 - FHIR Version: [STU3]
 - Version Vonk.Core & Vonk.Fhir.R3: 4.10

**Comment by marcovisserFurore** [comment]
`HumanName.Given` is helper property for `HumanName.GivenElement`. The value of  `HumanName.Given` is derived from `HumanName.GivenElement`. When you set a value to this property then `HumanName.GivenElement` is overwritten by the values in `HumanName.Given` . And that is happening here.

You instantiate a new value for `name.Given`  the first time for firstname. Then  `name.GivenElement` is instantiated as well. When you append the initials, again `name.Given`  is getting a new value and  `name.GivenElement` is build up again with the list of `name.Given`. So building `name.GivenElement`  again with new values and so there are no extensions.

The best to do this is:

```c#
            var name = new HumanName();

            string FirstName = "test";
            string Initials = "t";

            if (FirstName is not null)
            {
                var firstname = new FhirString(FirstName);
                firstname.AddExtension("test", new Code("CL"));
                name.GivenElement.Add(firstname);
            }

            if (Initials is not null)
            {
                var initials = new FhirString(Initials);
                initials.AddExtension("test", new Code("IN"));
                name.GivenElement.Add(initials);
            }

```

**Comment by FoppeCrezee** [comment]
That was my current solution as well, thanks!
