### ISSUE TITLE
Override a FhirPath function

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/firely-net-sdk#2311]
When you use the FhirPath compiler with default symbols loaded, you are not able to define you own implementation of some functions. In rare cases you need something like this, for example Firely Server has its own `resolve()` function. 

The provide this behavior we can add a `replace` method on the class `SymbolTable`. The entries in the `SymbolTable` are in a `ConcurrentBag`, so the implementation of `replace` should be first to remove the existing symbol first with `TryTake` and then `Add`.

**Comment by marcovisserFurore** [comment]
Before adding this functionality, let's wait for the results from Firely Server. They do that now through reflection. @alexzautke can you give us a heads up if you have any experience with this behavior?

**Comment by alexzautke** [comment]
@cknaap mentioned that the implementation will check the parent's symbol table after checking its own methods. Therefore you can override methods provided by the SDK. This behaviour should be documented. No code change needed here.

**Comment by brianpos** [comment]
Wouldn't you do this on load time, not at execution time as a one time activity into the default symbol table?
I'm pretty sure that's what I've done in my implementations.

**Comment by marcovisserFurore** [comment]
Like @alexzautke said: there is no need for a code change here. That is why I close this issue.
