### ISSUE TITLE
Support for .NET 6.0/7.0

### ISSUE THREAD

**Issue by kavitap0810** [FirelyTeam/firely-net-sdk#2327]
Hi,
I am using Hl7.Fhir.R4 with my Xamarin.Forms application, and it is working fine. Version in use - 4.2.1
But soon, we will be migrating to .NET MAUI. In your documentation, I do not see that even the latest version i.e., 4.3.0 is supporting .NET 6.0 or .NET 7.0

Can you please confirm what is the plan to support .NET 6.0/7.0? If there's any plan, also let us know by when can we expect the update. So, that we can plan to migrate to. MAUI

**Comment by brianpos** [comment]
I've been using it with 6 and 7 in some aspnetcore projects I use, so it should be fine. I coukd give it a whirl and let you know.

**Comment by marcovisserFurore** [comment]
Our target frameworks are now:
- .NET Framework 4.5.2
- netstandard2.0 (see compatibility [here](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0))
- .NET 6.0

This SDK will drop .NET Framework 4.5.2 from version 5.0 (release in the beginning of next year). 

.NET MAUI uses .NET 6.0 which will be supported already by our SDK.
