### ISSUE TITLE
Some spelling mistakes in the documentation

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2328]
https://docs.fire.ly/projects/Firely-NET-SDK/model/readonlydictionary.html

"for the vlaue of a FHIR primitive" =>
"for the value of a FHIR primitive"

"Note that, in contrast to the Json serialization of FHIR, resources will not additional magic resourceType entry in their dictionary." =>
"Note that, in contrast to the Json serialization of FHIR, resources will not contain additional magic resourceType entries in their dictionary." ...??..

"and interface that contains" =>
"an interface that contains"

https://docs.fire.ly/projects/Firely-NET-SDK/model/model-metadata.html

"each of these carry additional metadata expresses as attributes on the classes and properties" =>
"each of these carry additional metadata expressed as attributes on the classes and properties"

"Each of these carry additional metadata expresses as attributes on the classes and properties" =>
"Each of these carry additional metadata expressed as attributes on the classes and properties"

"As you can see, this declaration expresses a few things" =>  ...suggestion...
"As you can see, this declaration shows a few things"

https://docs.fire.ly/projects/Firely-NET-SDK/model/multiple-fhir-versions.html
"When do not want to fully express the namespace everytime, you can use an alias in the using part:" =>
"When you don't want to fully express the namespace everytime, you can use an alias in the using part:"

**Comment by marcovisserFurore** [comment]
These spelling mistakes are already corrected in the documentation.
