### ISSUE TITLE
EnumUtility.ParseLiteral throws for null when ignoreCase is true

### ISSUE THREAD

**Issue by IlIlIllIllI** [FirelyTeam/firely-net-sdk#2338]
**Describe the bug**
If the string to parse is `null`, `EnumUtility.ParseLiteral` throws an exception only when the `ignoreCase` parameter is set to true.

**To Reproduce**
1. `EnumUtility.ParseLiteral(null)` does not throw an exception
2. `EnumUtility.ParseLiteral(null, ignoreCase: true)` throws a `NullReferenceException`

**Expected behavior**
Method handles `null` correctly in both cases, for `ignoreCase: true` and `ignoreCase: false`

**Version used:**
 - FHIR Version: R4
 - Version: 3.5.0, Latest

**Additional context**
https://github.com/FirelyTeam/firely-net-common/blob/5899ce463f6cf166520cbbe6322310940942f81c/src/Hl7.Fhir.Support/Utility/EnumUtility.cs#L97

`literal.ToLowerInvariant()` should have a null-conditional operator (`?`):  `literal?.ToLowerInvariant()`

**Comment by ewoutkramer** [comment]
Classic.

```
    if (ignoreCase)
    {
        _lowercaseLiteralToEnum.TryGetValue(literal.ToLowerInvariant(), out result);
    }
    else
    {
        _literalToEnum.TryGetValue(literal, out result);
    }
```

This will certainly fail because of the `ToLowerInvariant()` here.  This 14 year-old code does not have nullability checks enabled (yet)  ;-)
