### ISSUE TITLE
R4 CapabilityStatement acceptUnknown

### ISSUE THREAD

**Issue by evozniak** [FirelyTeam/firely-net-sdk#2354]
**Describe the bug**
Enabling the `UseFhirVersionInAcceptHeader` flag makes the client query for the server CapabilityStatement
This throws an exception when connecting to our FHIR server. `Hl7.Fhir.ElementModel.StructuralTypeException : Type checking the data: Encountered unknown element 'acceptUnknown' at location 'CapabilityStatement.acceptUnknown[0]' while parsing.`

Looking into the FHIR documentation the `acceptUnknown` field was dropped in R4
http://hl7.org/fhir/STU3/capabilitystatement.html
http://hl7.org/fhir/R4/capabilitystatement.html

Our server is R4, so as expected it does not return an `acceptUnknown` field.

**To Reproduce**
1. Enable `UseFhirVersionInAcceptHeader` in `FhirClientSettings`
2. Connect to an R4 FHIR server that does not have the `acceptUnknown` in CapabilityStatement
3. Try to create a resource using `fhirClient.CreateAsync()`

**Expected behavior**
The R4 library should not try to parse the `acceptUnknown` field, this should be exclusive to STU3 version.

**Version used:**
 - FHIR Version: R4
 - Version: 4.3.0

**Comment by evozniak** [comment]
It is possible to reproduce by doing:
`fhirClient.Get("metadata");`

Hl7.Fhir.ElementModel.StructuralTypeException : Type checking the data: Encountered unknown element 'acceptUnknown' at location 'CapabilityStatement.acceptUnknown[0]' while parsing

**Comment by evozniak** [comment]
> The error message should only appear when the CapabilityStatement that is sent by the server has the `acceptUnknown` field filled in. The library parses the CS, and if it encounters an element that is not valid R4, it will throw the error. Please check your server's CS again, to make sure it does not contain the `acceptUnknown` field. I was not able to reproduce the issue on https://server.fire.ly/R4 or on https://hapi.fhir.org/baseR4.
> 
> If your server sends out a non-compliant CS, you can add `ParserSettings` to the `FhirClientSettings` where you set `AcceptUnknownMembers` to true to avoid the error being thrown.

The server is not sending the `acceptUnknow` in the `CapabilityStatement` endpoint.
Unfortionally the server is closed-sourced, but I will add here the unusual CS response.
https://controlc.com/846bef2f

`AcceptUnknownMembers` didn't fix the problem, perhaps the library is having a hard time with this `CapabilityStatement`
Is there a way of manually setting the FHIR version and don't rely on the `CapabilityStatement` result?

**Comment by marcovisserFurore** [comment]
Let's check whether this issue is still valid in the newest version of the SDK.

**Comment by mmsmits** [comment]
I could not recreate the problem either with both the legacy and the current serializer in this unit test:

```
[TestMethod]
[TestCategory("IntegrationTest"), TestCategory("FhirClient")]
public async T.Task TestAcceptUnknown()
{
    var settings = FhirClientSettings.CreateDefault();
    settings.UseFhirVersionInAcceptHeader = true;

    var client = new FhirClient(TestEndpoint, settings);
    var patient = new Patient { Active = true };
    var result = await client.CreateAsync<Patient>(patient);

    result.Should().NotBeNull();
    result.Active.Should().BeTrue();
}
```

If you want to be fully lenient on incoming data and want as less errors as possible, you can use the clients in Ostrich mode (from SDK version 5 and up) like this:

```var client = new FhirClient(TestEndpoint, settings).WithOstrichModeSerializer();```

Please reopen if the error still occurs in the newest version.
