### ISSUE TITLE
Validator is sensitive to order

### ISSUE THREAD

**Issue by Sieuwkje-firely** [FirelyTeam/firely-net-sdk#2375]
A customer noticed that with the following fixed value constraint on a profile:
```json
            {
                "id": "ServiceRequest.category",
                "path": "ServiceRequest.category",
                "short": "Type of ServiceRequest",
                "min": 1,
                "max": "1",
                "fixedCodeableConcept": {
                    "coding":  [
                        {
                            "code": "LAB_PRESLINE",
                            "system": "urn:oid:1.3.182.5.56"
                        }
                    ]
                }
            }
```
The validator gives an error when, in an ServiceRequest instance, you use the right values for code and system, but put them in the reverse order. Is that expected?

**To Reproduce**
1. Go to the snippet with incorrect order at https://simplifier.net/snippet/wardweistra/54/$validate
2. Click on validate.
3. See error: `Value is not exactly equal to fixed value '{"coding":[{"system":"urn:oid:1.3.182.5.56","code":"LAB_PRESLINE"}]}'`

**Expected behavior**
1. Go to the snippet with correct order at https://simplifier.net/snippet/wardweistra/53/$validate
2. Click on validate.
3. No error here.

We expect no errors for https://simplifier.net/snippet/wardweistra/54/$validate as well, as the validator should be insensitive to order.

Also described in https://firely.atlassian.net/browse/SD-1345

**Comment by marcovisserFurore** [comment]
I would suggest to bring the `ITypedElement.IsExactlyEqualTo(ITypedElement)` to the SDK and fix the error about the order there. In the legacy validator and the new validator can then use this extension method.
