### ISSUE TITLE
Add SearchParameterDefinition.Code next to .Name

### ISSUE THREAD

**Issue by cknaap** [FirelyTeam/firely-net-sdk#2385]
**Describe the solution you'd like**
https://github.com/FirelyTeam/firely-net-sdk/blob/9301fc66bb39927d40f37a2e255a24851a3da5e1/src/Hl7.Fhir.Core/Model/ModelInfo.cs#L44

`SearchParamDefinition` has the property `Name` but not `Code`. Please add `Code` as an extra property. 

**Describe alternatives you've considered**
-

**Additional context**
As the `Code` is needed to recognize the parameter on a search URL, it makes sense to add that too. So far in the core spec - and thus in the generated SearchParamDefinitions - the Name and Code always have the same value. But that is not required by the spec, so they might deviate in the future or in SearchParamDefinitions that users add themselves.

**Comment by marcovisserFurore** [comment]
This involves also a change in codegen to populate the new property `Code` in `SearchParamDefinition`.
