### ISSUE TITLE
Deserialization of Fhir object requires elements beyond "resourceType" when using JsonSerializer.Deserialize

### ISSUE THREAD

**Issue by cames-be** [FirelyTeam/firely-net-sdk#2391]
**Describe the bug**
The Fhir specification states that the "resourceType" element is a required element for a resource, but no other elements are required. When deserializing a resource using the `FhirJsonParser.Parse` function only the "resourceType" element is required to be present.  When attempting to deserialize the same resource using the `JsonSerializer.Deserialize` function, an exception is thrown that states `An object needs to have at least one property.` This goes against the guidance in the developer guide http://hl7.org/fhir/r4/overview-dev.html since the "data" or subsequent elements are Optional

> Each instance of a resource consists of:
> 
> - resourceType (line 2) - Required: FHIR defines many different types of resources. See [the full index](http://hl7.org/fhir/r4/resourcelist.html)
> - id (line 3) - The id of this resource. Always present when a resource is exchanged, except during the create operation (below)
> - meta (lines 4 - 7) - Usually Present: [Common use/context data to all resources](http://hl7.org/fhir/r4/resource.html#meta) and managed by the infrastructure. Missing if there is no metadata
> - text (lines 8 - 11) - Recommended: XHTML that provides a [human readable representation](http://hl7.org/fhir/r4/narrative.html) for the resource
> - extension (lines 12 - 17) - Optional: [Extensions](http://hl7.org/fhir/r4/extensibility.html) defined by the extensibility framework
> - data (lines 18 - 43) - Optional: data elements - a different set, defined for each type of resource

**To Reproduce**
The following code will reproduce the behavior:
```
string str = "{\"resourceType\": \"Parameters\"}";

// This will deserialize fine
var works = new FhirJsonParser().Parse<Parameters>(str);

JsonSerializerOptions options = new JsonSerializerOptions().ForFhir(typeof(Parameters).Assembly);
// This will throw an exception
var throws = JsonSerializer.Deserialize<Parameters>(str, options);
```

**Expected behavior**
The `JsonSerializer.Deserialize` function should not throw an exception and instead should return a deserialized resource with no populated elements.

**Screenshots**
![image](https://user-images.githubusercontent.com/96362956/220152722-62cad463-4bf6-4d67-bbec-a47bf7f95193.png)

**Version used:**
 R4
 - 4.3.0

**Additional context**
The `ERR.OBJECTS_CANNOT_BE_EMPTY` error should not be added to the `state.Errors` collection https://github.com/FirelyTeam/firely-net-common/blob/develop/src/Hl7.Fhir.Support.Poco/Serialization/FhirJsonPocoDeserializer.cs#L285

**Comment by marcovisserFurore** [comment]
This is due to constraint `ele-1`, but it is actually the responsibility of the validator instead of serializer.  We have to research this.

**Comment by ewoutkramer** [comment]
See #2235.
