### ISSUE TITLE
validation profile for fhir R4

### ISSUE THREAD

**Issue by pritammcdac** [FirelyTeam/firely-net-sdk#2394]
Hello Sir
Can u please Help me on

ERROR --
{"Overall result: FAILURE (1 errors and 0 warnings)\r\n[ERROR] Resolution of profile at 'http://hl7.org/fhir/StructureDefinition/Patient' failed: Type checking the data: Encountered unknown element 'requirements' at location 'StructureDefinition.requirements[0]' while parsing (at Patient)\r\n"}

Patient.json // Patient Profile
//////////////////
{
"resourceType": "Patient",
"identifier": [
{
"system": "pat_id",
"value": "Patient-01"
}
],
"name": [
{
"use": "official",
"family": "Parks",
"given": [
"ABC",
"C.H."
],
"prefix": [
"Mr."
]
}
],
"gender": "male",
"address": [
{
"line": [
"3300 Washtenaw Avenue, Suite 227"
],
"city": "Ann Arbor",
"state": "MI",
"postalCode": "48104",
"country": "USA"
}
],
"contact": [
{
"telecom": [
{
"system": "phone",
"value": "4443232223"
}
]
}
]
}
//////////////////////// This Json file created programitically

var source = new CachedResolver(new MultiResolver(new DirectorySource(profileDirectory), ZipSource.CreateValidationSource()));
var ctx = new ValidationSettings()
{
ResourceResolver = source,
GenerateSnapshot = true,
EnableXsdValidation = true,
Trace = true,
ResolveExternalReferences = true,
};
var validator = new Validator(ctx);
var results = validator.Validate(patient);
if(!results.Success)
{
results = validator.Validate(patient, "https://nrces.in/ndhm/fhir/r4/StructureDefinition/Patient");
Console.WriteLine(results);
}

Dear All,

I created Patient Profile - json attached with code.
I have given the same json to validation with the structure definition - https://nrces.in/ndhm/fhir/r4/StructureDefinition/Patient
But I am getting following error - Kindly guide me .. I am recently straterd working with FHIR-- ( I have cleared to temp folder as few suggested)
4.{"Overall result: FAILURE (1 errors and 0 warnings)\r\n[ERROR] Resolution of profile at 'http://hl7.org/fhir/StructureDefinition/Patient' failed: Type checking the data: Encountered unknown element 'requirements' at location 'StructureDefinition.requirements[0]' while parsing (at Patient)\r\n"}

What specification.zip contain---- how to create it ??

**Comment by ewoutkramer** [comment]
Everything seems to work fine - the validator reports that the Patient profile you are giving it ( https://nrces.in/ndhm/fhir/r4/StructureDefinition/Patient) contains an element `requirements` at the root level of the StructureDefinition. This is incorrect, StructureDefinition does not have a `requirements` element. (the elements in the StructureDefinition do, however).  So, the profile you have been given is incorrect!
