### ISSUE TITLE
Support implicit packages/extension packages pre-R5

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2415]
HL7 has taken the step to remove extensions from the core specification, so they can be published and updated separately.  This means these packages are always in scope. The new R5 stuff will explicitly reference the extensions, but it's likely we'll encounter them in older versions too (the old ones are still part of the pre-R5 publications itself, but newer ones won't). 

See: https://chat.fhir.org/#narrow/stream/179294-committers.2Fannounce/topic/Removal.20of.20extensions.20from.20Core

We should study the discussion here and make sure we find a way  to support these new forms of publishing extensions.

See also #2408 for the implicit tooling packages (related to https://chat.fhir.org/#narrow/stream/179239-tooling/topic/New.20Implicit.20Package)

**Comment by wardweistra** [comment]
I had previously reported #2407 for `hl7.fhir.uv.extensions`, but the info there is now outdated so let's continue here.

* The dependency on `hl7.fhir.uv.extensions` will be made explicit for new IGs published in R5 and, soon, in R4 too.
* There are already a few R4 packages out there which are using extensions only defined in `hl7.fhir.uv.extensions`

Two suggestions for @ewoutkramer to consider: 
* Don't allow package generation with two same canonicals in scope (with exception of core/extensions)
* Resolving: two canonicals in scope, take a random one? (R4 extensions package vs core: take core)

**Comment by wardweistra** [comment]
![CleanShot 2023-06-19 at 10 34 01@2x](https://github.com/FirelyTeam/firely-net-sdk/assets/779157/2c632ed2-1112-4c7a-9713-4464e1d5031e)
Note that these packages are there for R4 now, but in a broken state where they still claim to be R5 resources. [Discussion here](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/R5.20extensions.20in.20R4/near/367469778).

**Comment by mmsmits** [comment]
Two things we need to think about:
- Which packages to implicitly resolve? When? Is there even something implicit to do here?
- How do we give an extension package more priority than the "core extension" during resolution? Check extension version?
