### ISSUE TITLE
Custom search parameter fails to resolve on custom resources.

### ISSUE THREAD

**Issue by richfirely** [FirelyTeam/firely-net-sdk#2419]
**Is your feature request related to a problem? Please describe.**
For G.10 we added custom AccessPolicy resources to Firely Server. They import ok. When adding this [custom search parameter](https://simplifier.net/vonk-resourcesr4/accesspolicy-subject) for custom resources in the same simplifier project to Firely Server via errata or the import folder, there is an error in this method:
`Hl7.Fhir.Specification.Source ResolveByUri`

```
System.FormatException
  HResult=0x80131537
  Message=While building a POCO: Literal 'AccessPolicy' is not a valid value for enumeration 'ResourceType' (at SearchParameter.base[0])
  Source=Hl7.Fhir.Base
  StackTrace:
   at Hl7.Fhir.Serialization.ComplexTypeReader.RaiseFormatError(String message, String location)
   at Hl7.Fhir.Serialization.ComplexTypeReader.read(ClassMapping mapping, IEnumerable`1 members, Base existing)
   at Hl7.Fhir.Serialization.ComplexTypeReader.Deserialize(ClassMapping mapping, Base existing)
   at Hl7.Fhir.Serialization.RepeatingElementReader.Deserialize(PropertyMapping prop, String memberName, IList existing)
   at Hl7.Fhir.Serialization.ComplexTypeReader.read(ClassMapping mapping, IEnumerable`1 members, Base existing)
   at Hl7.Fhir.Serialization.ComplexTypeReader.Deserialize(ClassMapping mapping, Base existing)
   at Hl7.Fhir.Serialization.PocoBuilder.BuildFrom(ITypedElement source)
   at Hl7.Fhir.Serialization.PocoBuilder.BuildFrom(ISourceNode source, Type dataType)
   at Hl7.Fhir.ElementModel.PocoBuilderExtensions.ToPoco[T](ISourceNode source, ModelInspector inspector, PocoBuilderSettings settings)
   at Hl7.Fhir.Specification.Source.CommonDirectorySource.loadResourceInternal[T](ArtifactSummary summary)
   at Vonk.Fhir.R4.Internal.FhirR4ConformanceSourceReader`1.<Import>d__10.MoveNext() in 
```

**Describe the solution you'd like**
Open to a discussion with myself and @alexzautke , but a methodology where custom search parameters can target custom resources. Looking for guidance or SDK adjustments mostly.

**Describe alternatives you've considered**
- list the allowable custom resources and check each imported resource and manually de-serialize with AllowUnrecognizedEnums. Slow. Not clean code.
- skip the importing and hardcode custom search parameters. Not dynamic for future custom resource usage.

**Comment by brianpos** [comment]
This looks like a vonk issue rather than SDK issue. A custom resource won't have a POCO for it in a generic server, so requesting to build a poco from it should do what is shown above. It would need to use the non poco area.

**Comment by richfirely** [comment]
I don't think I would want a POCO for it because I agree with you, but maybe a way to override the checking like is done in manual deserialization. The other custom conformance resources import fine so there is some flexibility in it already and I can see some custom resource logic in the SDK in a brief search.

**Comment by brianpos** [comment]
That's an interesting problem, as the resourcetype in the searchparameter resource is constrained to only FHIR types, so putting in non-fhir types (custom) shouldn't be conformant - maybe would want to do that via extensions, though don't know how Vonk is intending to handle this area. Will leave that for @cknaap to respond.

**Comment by alexzautke** [comment]
In Firely Server our main problem is here that we are trying to read an ArtifactSummary from an ISummarySource (DirectorySource in this concrete case). What we could do is to rewrite that whole logic, use the new parser, skip the error, and finally build the summary ourselves. This ticket was meant to see if we can somehow build a workaround for this issue and change only as much code as possible.

**Comment by mmsmits** [comment]
Currently we can't think of a workaround. 
- We'll add an issue to make it more ArtifactSummary more flexible regarding serialization (actually in DirectorySource)
- We can assist you with implementing your first suggestion.

**Comment by mmsmits** [comment]
Alternatively, you could put everything in a FHIR package, and use the FhirPackageSource. We can (and should) make this more flexible regarding serialization. Is that an option?

**Comment by alexzautke** [comment]
Thanks, I'll try if using "AllowUnrecognizedEnums" will work for us.

**Comment by marcovisserFurore** [comment]
From our standup 2023-05-17: @mmsmits will discuss this with @alexzautke.

**Comment by alexzautke** [comment]
@mmsmits @marcovisserFurore I’ll try this out in Firely Server as soon as I’m back from holiday (Monday 29th). It’s high up on my todo list. Sorry for the delay.
