### ISSUE TITLE
Inconsistent internal/public access for the SemVersion class

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/firely-net-sdk#2420]
**Describe the bug**
I was using this SemVersion class in my Facade project (in place of bringing in a dependency to an external package) which has now been marked as `internal` for netcore based projects (but still `public` for net452)
https://github.com/FirelyTeam/firely-net-sdk/blob/7d63b1e1b2eafa9ff1d53c98f87cac409bd1f5e6/src/Hl7.Fhir.Base/Utility/SemVersion.cs#L16-L21
Can this be made public again?

**Version used:**
 - FHIR Version: R4B
 - Version: 5.0.0

https://github.com/brianpos/fhir-net-web-api/blob/feature/r4b/src/Hl7.Fhir.WebApi.Support/CurrentCanonical.cs#L149-L153

**Comment by mmsmits** [comment]
SemVer is a class we copied from an external library, something we don't want to maintain for the community.

We made it internal to encourage the community to use an external nuget package instead like:

https://www.nuget.org/packages/Semver

Or

https://www.nuget.org/packages/SemanticVersion

**Comment by brianpos** [comment]
Any reason why you don't use the external library then? A shame that different parts in an install will use different engines.

**Comment by mmsmits** [comment]
We don't want to add an extra dependency to the SDK, and leave the flexibility of choosing a SemVer library to our users.
