### ISSUE TITLE
PositiveInt accepts values < 0

### ISSUE THREAD

**Issue by cknaap** [FirelyTeam/firely-net-sdk#2424]
:information_source: Do you want to ask something or start a discussion, then go [here](https://github.com/FirelyTeam/firely-net-sdk/discussions)

:information_source: Is your bug report about Firely Server Facade, please send an email to [server@fire.ly](mailto:server@fire.ly) or submit a bug report to Jira if you are a paying customer.

**Describe the bug**
The constructor for datatype PositiveInt can be called with values <0 without any error.

**To Reproduce**
1. `new PositiveInt(-42);`
2. Observe no errors

**Expected behavior**
`ArgumentOutOfRangeException()`

**Screenshots**
n/a

**Version used:**
 - FHIR Version: [Common]
 - Version: [e.g. 5.0.0]

**Additional context**

**Comment by ewoutkramer** [comment]
The constructors of the FHIR datatypes do not do any validation, e.g. these lines also won't throw:

```
var fhirDate = new Date("Ewout");
var id = new Identifier("1234-not-right%^$%$$");
```

Whether that was a good idea or not, it's been like that for 10+ years, so I am hesitant to change in this area.

**Comment by marcovisserFurore** [comment]
This is not inline with other constructors. It could also introduce breaking changes. We will investigate the attribute validation for this.
