### ISSUE TITLE
Valueset `name-use` cannot be resolved in R5 snaphot-3

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2427]
**Describe the bug**
The legacy validator (and probably the new validator too) has a problem resolving 'http://hl7.org/fhir/ValueSet/name-use|5.0.0'.

**To Reproduce**
See https://chat.fhir.org/#narrow/stream/179171-dotnet/topic/R5.20Validation for the error the validator produces in R5 (snapshot 3).

**Expected behavior**
The valueset should be resolvable. It's unclear currently whether this is a problem with the publication, this specific valueset or a new kind of resolution introduced with R5. A new resolution sounds unlikely, since this would mean resolution of many other vs's would have failed, which we would have seen in our unit tests.

**Screenshots**
See https://chat.fhir.org/#narrow/stream/179171-dotnet/topic/R5.20Validation

**Version used:**
 - FHIR Version: R5-snapshot3
 - Version: 5.0

**Comment by brianpos** [comment]
I'd love for the resolution for this issue to be to properly handle versions in canonical URLs in the resolver chain.
(but ok if this is resolved as others in the past have just stripped the value and another issue tracks proper versioned canonical resolutions through the chain)

**Comment by marcovisserFurore** [comment]
I performed the following test and everything works fine. Also the version in the canonical URL. The input for this test is this Patient resource (in Json):

```json
{
  "resourceType" : "Patient",
  "name" : [
     {
        "use" : "official",
        "family" : "Visser"
     }
  ]
}
```

```c#

        [Fact]
        public async T.Task Issue_2427Async()
        {
            // use the specification.zip here
            var source = new CachedResolver(ZipSource.CreateValidationSource());
            var json = "{ \"resourceType\" : \"Patient\",  \"name\" : [{ \"use\" : \"official\", \"family\" : \"Visser\"}] }";

            // parsing
            var node = await FhirJsonNode.ParseAsync(json);
            var data = node.ToTypedElement(new StructureDefinitionSummaryProvider(source));

            // validate
            var report = _validator.Validate(data);

            report.Warnings.Should().Be(0);

            // check the binding on "HumanName.use"
            var sdHumanName = await source.ResolveByCanonicalUriAsync(ModelInfo.CanonicalUriForFhirCoreType(FHIRAllTypes.HumanName)) as StructureDefinition;
            var nav = ElementDefinitionNavigator.ForSnapshot(sdHumanName);
            nav.JumpToFirst("HumanName.use").Should().BeTrue();
            nav.Current.Binding.ValueSet.Should().Be("http://hl7.org/fhir/ValueSet/name-use|5.0.0-snapshot3");
        }
```

So something else must be not working.

**Comment by marcovisserFurore** [comment]
I used your example to test it in our build environment with the newest FHIR version (R5, v5.0.0) and I don't get any issues. This is the unit test:

```c#
        [Fact]
        public void Issue_2427()
        {

            // Files "Patient-CommunicationPatient.json" and "StructureDefinition-CommunicationPatient" are placed
            // in folder `.\TestData\issue_2427`

            string igdirectory = Path.Combine("TestData", "issue_2427");
            var specificationZipSource = ZipSource.CreateValidationSource();

            var dirSettings = new DirectorySourceSettings() { IncludeSubDirectories = true };
            var igsource = new DirectorySource(igdirectory, dirSettings);

            var multiResolver = new CachedResolver(new SnapshotSource(new MultiResolver(specificationZipSource, igsource)));
            var provider = new StructureDefinitionSummaryProvider(multiResolver);

            var settings = ValidationSettings.CreateDefault();
            settings.ResourceResolver = multiResolver;

            var validator = new Validator(settings);

            var patientJson = File.ReadAllText(Path.Combine("TestData", "issue_2427", "Patient-CommunicationPatient.json"));

            var patient = (new FhirJsonParser()).Parse<Patient>(patientJson);

            var sourceNode = FhirJsonNode.Parse(patientJson);
            var typedElement = sourceNode.ToTypedElement(provider);
                        Hl7.Fhir.Model.OperationOutcome outcome = validator.Validate(typedElement, "http://bki.skane.se/invanartjanster/fhir/StructureDefinition/CommunicationPatient");
            outcome.Success.Should().BeTrue();
        }
````

An important addition is that I used `SnapshotSource`. This is because the profile `http://bki.skane.se/invanartjanster/fhir/StructureDefinition/CommunicationPatient` has no snapshot and this `SnapshotSource` will create a snapshot in memory. Without this `SnapshotSource` I get an error about a missing snapshot.

A new version of the SDK with the new FHIR 5.0,0 version will be released soon. Hopefully next week.

**Comment by marcovisserFurore** [comment]
I close this issue since we haven't received a response. If you have any further questions or comments, please don't hesitate to let us know.

**Comment by barbrovessman** [comment]
I updated to use version 5.1.0 of the SDK, but unfortunately the issues remain. I also notice that it is not only warnings in the Outcome, but  Exceptions are being thrown:

Exception thrown: 'Hl7.Fhir.Rest.FhirOperationException' in Hl7.Fhir.Conformance.dll
Cannot retrieve valueset 'http://hl7.org/fhir/ValueSet/name-use|5.0.0'

![image](https://user-images.githubusercontent.com/60477041/236130387-fea8a79a-9ab2-4845-ae53-8b0987c4d109.png)

**Comment by marcovisserFurore** [comment]
hmm, I am not sure what you are doing in the above code snippet. But can you replay my [unit test](https://github.com/FirelyTeam/firely-net-sdk/issues/2427#issuecomment-1520278860) in your environment? That is working for me and also be working for you. 
I am looking forward to your results..

**Comment by barbrovessman** [comment]
Yes, it works here too! But it does not validate with the IG, just the single StructureDefinition.

**Comment by barbrovessman** [comment]
So something is wrong with the IG then. Any tips on how to troubleshoot?

**Comment by barbrovessman** [comment]
I works also with the IG now. I guess that it was updating the specification.zip that finally helped,. Some initial cache issues confused me. Thanks a lot for all help 🙂

**Comment by marcovisserFurore** [comment]
Great to hear that the problem has been solved. 
Thanks that you are using our SDK.

Happy coding!

**Comment by barbrovessman** [comment]
However, I experience that the validation takes a lot longer now when the warnings/exceptions are gone. For example, running the unit test above takes 4 seconds. Is it the same when you run it?

**Comment by marcovisserFurore** [comment]
In the unit test [here](https://github.com/FirelyTeam/firely-net-sdk/issues/2427#issuecomment-1520278860) I used a `SnapshotSource`, which creates a snapshot of the profile. That is a costly operation. I don't know your IG, but probably all profiles will have a snapshot besides the differential. If that is the case, the  `SnapshotSource` won't be needed here. This will save a lot of time.
