### ISSUE TITLE
trying to get started using your software

### ISSUE THREAD

**Issue by AlexFJaxFL** [FirelyTeam/firely-net-sdk#2433]
Hello, 

      we are looking to implement SDK Hl7.Fhir.R4B using your software from .NET
      according to https://github.com/FirelyTeam/firely-net-sdk/releases/tag/v5.0.0 entire SDK was restructured so i am not sure if i should still get entire package or ..

      would it be possible to provide specific instructions on how to obtain it

regards,
Alex

**Comment by brianpos** [comment]
The code repo structures were refined, the actual code is mostly the same for usage.

The biggest change was the validator moved to a new package.

What did you have troubles with?

**Comment by AlexFJaxFL** [comment]
not sure how to incorporate Hl7.Fhir.R4 package from https://github.com/FirelyTeam/firely-net-sdk/releases/tag/v5.0.0

i do not have much experience with github so if you could provide more details it would be very helpful

**Comment by AlexFJaxFL** [comment]
was able to figure out how to get your package installed
