### ISSUE TITLE
FhirPath function comparable() should use UCUM library

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/firely-net-sdk#2439]
At the moment the Fhir FhirPath function `comparable()` is not able to check 2 Quantities of the same UCUM system but with a different units. For example `cm` should be comparable with `[in_i]`. In order to check that, we should use the [Fhir.Metrics](https://github.com/FirelyTeam/Fhir.Metrics) library.

**Comment by alexzautke** [comment]
@ewoutkramer PR #2444 is not related to UCUM. Did you mean to close #2429? Just saw this ticket notification in my inbox, I was curious how you'd implement the UCUM solution.

**Comment by ewoutkramer** [comment]
I have no idea why I closed this issue. Must have been meaning to close something else.
