### ISSUE TITLE
Fhirpath Split bug - removes empty strings

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/firely-net-sdk#2445]
**Describe the bug**
The split fhirpath function is removing empty strings from it's output.
This behaviour is not defined in the specification, and I've logged an issue to clarify this in the fhirpath spec itself too.
'A,B,C'.split(',') => 'A', 'B', 'C'
'A,,C'.split(',') => 'A', '', 'C'  _(not 'A', 'C' which is what the current implementation does)_
https://build.fhir.org/ig/HL7/FHIRPath/#splitseparator-string-collection
https://jira.hl7.org/browse/FHIR-41033

HAPI has already implemented this to not remove empty strings.
If desired, the user can use a where clause to remove the empty strings.
The bi-product of this bug is that `'A,,C'.split(',').join(',')` does not return the same string.

**To Reproduce**
This unit test will demonstrate the issue:
``` c#
        [TestMethod]
        public void StringSplit()
        {
            Assert.IsTrue(AssertArray(StringOperators.FpSplit("A,B,C", ","), new[] { "A", "B", "C" }));
            Assert.IsTrue(AssertArray(StringOperators.FpSplit("A,,C", ","), new[] { "A", "", "C" })); // verify the empty string
            Assert.IsTrue(AssertArray(StringOperators.FpSplit("A,B,C,C", ","), new[] { "A", "B", "C", "C" })); // verify it doesn't remove dups

            // The test from the spec
            Assert.AreEqual(5, StringOperators.FpSplit("Peter,James,Jim,Peter,James", ",").Count());
        }

        private bool AssertArray(System.Collections.Generic.IEnumerable<ITypedElement> arr, string[] values)
        {
            if (values.Length != arr.Count())
                return false;
            int index = 0;
            foreach (var item in arr) {
                if (values[index] != item.Value.ToString())
                    return false;
                index++;
            }
            return true;
        }
```

**Expected behavior**
Unit test should pass.

**Version used:**
 - FHIR Version: R4B/R5 (all)
 - Version: 5.1.0

**Additional context**

**Comment by ewoutkramer** [comment]
This behaviour was clearly introduced on purpose. It requires an additional parameter, and even the test suggests we agreed it needed to skip the entry:

``` csharp
            dummy = ElementNode.ForPrimitive("a,,b,c,d"); // Empty element should be removed
            result = dummy.Select("split(',')");
            Assert.IsNotNull(result);
```

Since it's been a while that we coded this, it's probably hard to figure out when/how we agreed, but it's not clear to me that the behaviour is wrong.

**Comment by ewoutkramer** [comment]
Note: I am not against changing it, but it's a breaking change (well, we are reacting to a clarification), and if we somehow agreed to do it otherwise back in the days, we need to make sure we're contradicting ourselves.

**Comment by marcovisserFurore** [comment]
Also, should we not wait for the outcome of [this Jira issue](https://jira.hl7.org/browse/FHIR-41033) before we are going to change this behavior of this function?
