### ISSUE TITLE
FhirJsonPocoDeserializer should throw an error when encountering the same property multiple time.

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2465]
Comparable to #2435, the json poco deserializer will not complain when a json file contains the same property multiple times. This is illegal in json itself, not only in FHIR, but the streaming System.Text.Json reader will -for obvious reasons- not catch it.  So we need to do it ourselves. 

The recovery behaviour would be to keep adding to the repeating element when a property is encountered multiple times, if the element is indeed a repeating element.  We should probably consider it a non-recoverable error when there is a mixture of repeating primitive elements + extension elements (name and _name), since it's unlikely these repeats can be interpreted to be in sync with each other, e.g.

```
"name": { 1,2,3,4 },
"_name": { null, { "id": .... }, null, null},
"name": {5,6}
"_name": { {"id": ....} }
```

Should we try to combine the primitives + extension elements here? A lot of effort.

**Comment by brianpos** [comment]
This one is resolved in my PR (incase you weren't already aware)
