### ISSUE TITLE
How to use HumanName.NameUse or Address.AddressUse

### ISSUE THREAD

**Issue by testlorenzospa** [FirelyTeam/firely-net-sdk#2509]
Hello.

I have problems to use some instructions.

Using HumanName.NameUse or Address.AddressUse I get this error
(HumanName.NameUse|Address.AddressUse) is a type which is not valid in the given context

How can I solve this issue?

Sorry if this problem can be obvious, but I am not very expert about C#.

Many thanks.

**Comment by marcovisserFurore** [comment]
Hi @testlorenzospa,

Thank you for contacting us. Could you please provide some additional context about what you are working on? It would be helpful if you could share a code snippet or any relevant information.

In the meantime, I recommend checking out our documentation on working with POCOs. You can find detailed information [here](https://docs.fire.ly/projects/Firely-NET-SDK/model.html). It might provide insights related to your current task.

**Comment by testlorenzospa** [comment]
Hello @marcovisserFurore 

Thanks for your response.
Looking better, and through your link I am found the reason for my problems about the instructions.

Can you help me with this other post ([patient informations](https://github.com/FirelyTeam/firely-net-sdk/discussions/2510))?

Thanks again.
