### ISSUE TITLE
Snapshot generator merge does not handle the new R5 ElementDefinition properties mustHaveValue and valueAlternatives

### ISSUE THREAD

**Issue by Rob5045** [FirelyTeam/firely-net-sdk#2513]
In R5, ElementDefinition now contains 2 new properties:

- mustHaveValue
- valueAlternatives

When using the SDK 5.2 in Forge and opening a profile where these properties are set in the differential, these elements do not get merged by the snapshot generator.

Looking at the SnapshotGenerator method ElementDefnMerger, these new properties are not processed.

**Comment by marcovisserFurore** [comment]
Hi @Rob5045, these properties are new in R5 and are not used by the SnapshotGenerator yet. I think it is a easy fix. Should we do it, or do we get a PR from you?

**Comment by Rob5045** [comment]
Hi @marcovisserFurore , because these are R5 only additions, something special needs to be done to avoid duplicating code. That is an architectural problem that I think you can better solve.

**Comment by marcovisserFurore** [comment]
Great Rob, then we will take care of it!
