### ISSUE TITLE
Performance degradation in FHIR server for high patient registration volume

### ISSUE THREAD

**Issue by LumiProj** [FirelyTeam/firely-net-sdk#2515]
**Describe the bug**
I am experiencing a performance issue with the FHIR server in a hospital environment where approximately 3000 patients register daily. Initially, the server was performing well, with FHIR operations completing in milliseconds. However, after around 2 months of usage, the response time for each operation has increased to 3-4 seconds, causing significant delays in patient care.
 

**Expected behavior**
The FHIR server should maintain consistent response times in the millisecond range, regardless of the number of patients registered.
 

**Spark version**
  - Version: 1.5.17.0

**Operating system + Database**
  - OS: Linux Ubuntu Focal
  - Database:MongoDB

**Comment by mbaltus** [comment]
This issue mentions problems on the side of your server, not an issue with the Firely .NET SDK. There is nothing we can do on this library to fix that. Please reach out to the server admins or developers to get assistance on your performance problems.
