### ISSUE TITLE
Support position information in FHIRPath expressions

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/firely-net-sdk#2517]
**Is your feature request related to a problem? Please describe.**
The FhirPath `Expression` and derived classes have support for location information however this is never populated by the sprache parser.

**Describe the solution you'd like**
During the parsing of a fhirpath expression optionally support the inclusion of the position information for each sub-expression in the AST.

**Additional context**
I plan to use this information in the fhirpath-lab project through my open source FhirPath Expression validator nuget package.
This will help significantly with error messages and also highlighting expressions in related tooling.

**Comment by ewoutkramer** [comment]
I did make it work in the MappingLanguage parser (which was based on Superpower). Too bad we cannot use that code anymore. Are we sure we can make this work in sprache? maybe by patching the original code, which we have included anyway?

**Comment by brianpos** [comment]
After spending some time in there, I do believe that we can. Just wanted to check before I really started into it to ensure I hadn't missed something already.

**Comment by brianpos** [comment]
I've progressed with this and have something to demonstrate, but not quite to the level of a branch to show.
@ewoutkramer Any chance we have a catchup to show what I have and see if I'm not doing something too drastic that would prevent it merging in if completed...

**Comment by brianpos** [comment]
As noted in the PR this is now fully functional and combined with the comments/whitepsace branch code will permit full round tripping with ObjectModel, which can permit some manual tweaks to the Model and then back out to a string again without losing the whitespace/comments
