### ISSUE TITLE
Migrate SearchParamDefinition into the Base versionless level

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/firely-net-sdk#2531]
**Is your feature request related to a problem? Please describe.**
The SearchParamDefinition class is an internal class used in each of the versions ModelInfo classes to hold the code generated search parameter code.
I'd love to have this definitional class in Base so that it can be used in generic services that handle more than one version.
My specific case is for a versionless Search Expression validator - It will be using this class for it's information, and likely have an extension method to take the version specific SearchParameter and produce this class for validations (and also be able to scan any allready pre-generated.
As shown in this code:
https://github.com/brianpos/UploadFIG/blob/98408a0d8ad33993d57e90905f8ed22e0c360a77/UploadFIG/ObjectValidator.cs#L88

**Describe the solution you'd like**
Migrate the class into the Base assembly

**Describe alternatives you've considered**
The only other alternatives for me are to replicate the code in my validator to each version, or have my own generic class and request project users provide the mapping.

**Comment by marcovisserFurore** [comment]
I am afraid that is not possible without a breaking change. The class `SearchParamDefinition` contains a property `Target` of type `ResourceType[]`, which is bound to a specific FHIR version. So that type is not available in Base.

**Comment by ewoutkramer** [comment]
So, for 6.x, we could change this to this new enum that has all historical types and was introduced in R5 (sorry, forgot the name)?
