### ISSUE TITLE
Improve performance of Poco Instant

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/firely-net-sdk#2532]
The POCO date types have their `ObjectValue` set to string, and will parse the string into a `DateTimeOffset` every time a something is "done" with the type (e.g. comparing, getting Utc dates, etc). This causes performance issues in the CQL engine, so we should try to cache the conversion from string to `DateTimeOffset` (invalidating it when the ObjectValue/Value is changed).

See for inspiration PR #2529 where it is already implemented for `FhirDateTime`.

**Comment by ewoutkramer** [comment]
The existing Instant datatype is already stored as a DateTimeOffset internally, so we do not have to cache or speed things up for this datatype. Closing this issue.
