### ISSUE TITLE
Add support for multiple valuesets and system filters to the ValueSetExpander

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2555]
The CQL engine uses valuesets, and some of the valuesets in its test set have multiple compose.include.valueset.  We do not support that yet. In order to get the SDK's terminology stuff into the CQL engine (and not break the unit tests), we need to add support for this feature.

Specifically, from https://www.hl7.org/fhir/valueset.html#compositions, do this:

* valueSet(s) only: Codes are 'selected' for inclusion if they are in all the referenced value sets
* valueSet and System: Codes are 'selected' for inclusion if they are selected by the code system selection (after checking for concept and filter) and if they are in all the referenced value sets

We currently only accept a single referenced value set (while the first bullet requires value set*s*), and we don't use the system to limit the codes coming in from the valueset isn the second bullet.

**Comment by mmsmits** [comment]
Fixed by: https://github.com/FirelyTeam/firely-net-sdk/pull/2558
