### ISSUE TITLE
FhirClient throws wrong exception when the server sends a non-FHIR error 

### ISSUE THREAD

**Issue by priyankasyal** [FirelyTeam/firely-net-sdk#2557]
We have an APIM service that handles sending requests to FHIR. In case of non FHIR errors (invalid authorization, unauthorized, missing headers) the server respond to a request with an HTTP error and a JSON body which is not a FHIR exception (like an authorization error), however when we call the APIM server using the fhirclient,  the resulting exception is FhirOperationException, with a message like: 

`Operation was unsuccessful because of a client error (NotFound). Body: {\"error\":{\"title\":unauthorized\".\",\"status\":404,\},\",\"method\":\".GET\”}`

Is there a way to get the correct exception (HTTPRequestException) with the message without the initial string 'Operation was unsuccessful because of a client error (NotFound)' appended to the JSON body? 

Is every exception thrown by the server supposed to be FhirOperationException? What is the best way to handle the non-FHIR exceptions vs FHIR exceptions when using fhirclient? 

We are currently using the R4 nuget package - https://www.nuget.org/packages/Hl7.Fhir.R4

**Comment by ewoutkramer** [comment]
>Is there a way to get the correct exception (HTTPRequestException) with the message without the initial string 'Operation was > unsuccessful because of a client error (NotFound)' appended to the JSON body?

No, since there is no exception thrown, the underlying .NET HttpClient almost never throws an exception:

> "HttpClient does not throw an exception when the HTTP response contains an error code. Instead, the IsSuccessStatusCode  property is false if the status is an error code.

But you can get to the details by inspecting the FhirClient's `LastBody` or `LastBodyAsText` and `LastResult` (which has status/last modified/etag etc. all the headers)

> Is every exception thrown by the server supposed to be FhirOperationException? What is the best way to handle the non-FHIR exceptions vs FHIR exceptions when using fhirclient?

No, that was a design error I made over a decade ago, but since the FhirClient is used so widely I cannot really break that contract anymore!

**Comment by priyankasyal** [comment]
Thanks for your response! :)
