### ISSUE TITLE
Bundle Generates New Id Every Search

### ISSUE THREAD

**Issue by cgtholdingsllc1** [FirelyTeam/firely-net-sdk#2561]
**Describe the bug**
When using client.ContinueAsync( previousBundle ), the new bundle returned has a different Id. I am not sure this is by design but becomes more difficult to track different users' bundles by id if while they are paging, a new bundle id is generated every time.

**To Reproduce**
1. Search for resources and limit the return to a number you know is less than the total. This creates a bundle with the next uri.
2. Call Continue on fhir client and return the new bundle. The new bundle has a different id than the old bundle passed into the Continue call.

**Expected behavior**
Unless this is by design, which it could be, and if so I will delete this bug, but I would expect the same bundle id to be used with updated Entry information. This would allow for storing the bundles in something like Redis much easier to manage during continuous paging operations.

**Screenshots**
N/A

**Version used:**
 - FHIR Version: R4
 - Version: 5.3.0

**Additional context**
If this is by design, my apologies for creating this bug report.

**Comment by brianpos** [comment]
This is server driven, and I would normally expect that each bundle ID returned is different, as they are all different pages, and dynamically generated.
(I definitely wouldn't be relying on this as a client, unless I knew exactly which server I was talking too, and didn't plan on changing without going through some grief)
Not something that I believe the fhir client should be able to make any changes to here.

**Comment by cgtholdingsllc1** [comment]
Understand. I am closing this ticket. Thank you for the feedback.

**Comment by cgtholdingsllc1** [comment]
Understand. I am closing this ticket. Thank you for the feedback.
