### ISSUE TITLE
Continue Functionality Total Value

### ISSUE THREAD

**Issue by realchrisparker** [FirelyTeam/firely-net-sdk#2562]
**Is your feature request related to a problem? Please describe.**
When using the client.Continue method, there is no way to tell the client you want the total returned. Right now it always returns null.

**Describe the solution you'd like**
Would like the ability to tell the continue method to return the total value in the bundle Total field. Would like to continue to know what the total is, as in an active system, that number can change over the course of paging for several seconds.

**Describe alternatives you've considered**
Storing the total from the original search method but this doesn't allow for paging to be updated when new content arrives.

**Additional context**
N/A

**Comment by brianpos** [comment]
If new content arrives, what do you expect to occur?
did it arrive in pages before this one, after this one?
Did it result in content being missed, or duplicated in the pages?

**Comment by cgtholdingsllc1** [comment]
In my scenario data could be inserted on a previous page than the one the user is on. Encounters come in consistently, but all queries are -date based. So if someone is looking at the encounters for a specific date range and another is created while they are on page 3, the total would help me know that. This isn't a not a must-have. This is more of a would-like feature request.

**Comment by mmsmits** [comment]
We just return the information 1 on 1 as it comes back from the search. There is no FHIR client magic here. 
So if total is null, the server has not responded with a total in the page bundle.
