### ISSUE TITLE
Add environment variables to FhirPath

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2570]
At this moment, it is possible to add constants to the SymbolTable so you can supply your own external values (just like functions) and refer to them from FhirPath.

However, it is also really useful to supply extrernal variables that can be different from invocation to invocation of a compiled fhirpath statement, variables that are specific for a single run of an expression.

We already pass in an `EvaluationContext` when we run an expression, so a natural extension point would be to make it possible to add context variables here, that can then be referenced from the FhirPath, e.g. with the normal %<variablename> syntax.

Alternatively, we could introduce our own syntax in FhirPath, but that requires changes to the parser and brings little added value.

**Comment by brianpos** [comment]
I'd also love to see this too.
To date i've been just using a new Symbol table each time I need to do this, but that does mean it needs to be compiled each time.

**Comment by brianpos** [comment]
Also happy to contribute to this, as would love to see this type of capability also make implementing a proposed `withVariable` function...
https://chat.fhir.org/#narrow/stream/179266-fhirpath/topic/.22grouping.22.20elements
```fhirpath
group.select(
  withVariable('grp')
  .select(
    element.select(
      withVariable('src')
      .target.select(
        %grp.source & '#' & %src.code
        & ' ' & equivalence & ' '
        & %grp.target & '#' & code
      )
    )
  )
)

```
:test_tube: [Test with FHIRPath-Lab](https://fhirpath-lab.com/FhirPath?parameters=N4IgpgHgDgTmDO8CWB7AdiAXCA5jFArlAHTxgA2YAxgC4AUAOjA2gASsDuSNAFgGoBDGEgEAjSnQDkeKJICUTFu1IVq9RW3atVAWzBoaKyrUbNNWzt35CR4sFPgwq8jReU0hOMIbLH1Zty0AUhlSQicwVgAyVkkAYklo1iDHKmIqFAATMFdApMTEmLAARwIkADcBSjQqSJiC3MCYkJgSDxgvGnyEpIzsxq0FAMHcoZYxjAAaEDh4cNqsEABhdFqoGgBZASgAeioqITAAWhRReBBp-RwkNDBFgDMeJFaBXmIAK3PpmjAYHRuUOQUDgAJ4AZV+5V+ix4NBoUHgmB2O3gxSBaEezyOMAALMQBAAvAhwDhgM7cBDEW40HaYmAXECVYRiSjnTAAbVAaAEekWMhAAF9JlyeXdsKlBQBdAVAA)

**Comment by mmsmits** [comment]
- How do other libraries this? Peak at an open source JavaScript library?
- Also consider defineVariable, when designing this.
