### ISSUE TITLE
String Validation for Serializing vs Deserializing is different

### ISSUE THREAD

**Issue by Narnian12** [FirelyTeam/firely-net-sdk#2577]
**Describe the bug**
When I generate a Firely `Bundle`, I can run `bundle.Validate(true)` that will recursively validate fields within the model. I have been using that to do structural validation of `Bundle` objects I am creating. However, when I tried to serialize that `Bundle` into a string and then deserialize that exact string, it throws various validation errors. I am wondering whether the validation methods between `bundle.Validate(true)` and `Deserialize` are different?

**To Reproduce**
1. Generate a valid Bundle with just one resource in it, for example, `Claim`
2. For any of the `Claim`'s object that has a `System` field, set that field as an empty string ""
3. Run `bundle.Validate(true)` on it, expect it to pass
4. Serialize as string and deserialize back as `Bundle`, expect it to pass but instead it will throw an error saying "Properties cannot be empty strings."

**Expected behavior**
I expected that if the `Bundle`'s built-in validation did not throw any exceptions, then deserializing the string-form of that object would also not throw any validation exceptions.

**Example Test Code**
```
[Fact]
public void Test() {
  var bundle = GenerateBundle(...); // Generate a Bundle with a Claim that has one object's System field set to an empty string
  bundle.Validate(true); // This will pass
  var options = new JsonSerializerOptions().ForFhir();
  var bundleString = JsonSerializer.Serialize(bundle, options);
  var deserializedBundle = JsonSerializer.Deserialize<Bundle>(bundleSring, options); // This will fail
}
```

**Version used:**
 - FHIR Version: R4
 - Version: N/A

**Comment by ewoutkramer** [comment]
The attribute-based validation that you are using cannot validate everything, so the deserializer is more precise.  But specifically in this case, I guess we could check whether values are empty string. I think we are checking using regex patterns, but maybe only when the values of string are not null or empty. Sounds like something additional we should do.

**Comment by Narnian12** [comment]
Interesting, thanks for the response! I am curious - even if the field is not required based on the PAS profile, would the validator/deserializer still throw an error if the field is empty? Is there a general requirement to ensure that when fields are added into a `Bundle`, all/most fields cannot be empty strings?

**Comment by mmsmits** [comment]
Refinement:
Attribute validation will not be the same for deserializing and serializing, but we can try to make this as consistent as possible in this case.
Check if there is a [Validation] attribute on FhirString attributes.
