### ISSUE TITLE
`FhirEvaluationContext.TerminologyService` should be of type `ICodeValidationTerminologyService`

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/firely-net-sdk#2590]
In the current implementation, the terminology service defined within the `FhirEvaluationContext` class is of the type `ITerminologyService`, which is overly broad for our specific needs. Our sole requirement within FhirPath is to utilize the `ValueSetValidateCode()` method. Therefore, it would be more appropriate to reconfigure `FhirEvaluationContext.TerminologyService` to be of the type `ICodeValidationTerminologyService` to align with our focused functionality.

**Comment by alexzautke** [comment]
```
Our sole requirement within FhirPath is to utilize the ValueSetValidateCode() method.
```

That is until some ImplementationGuide requires the usage the subsumes FHIRPath  operation. It took some years until users wanted to have memberOf, so it’s unlikely but at least it’s defined.
