### ISSUE TITLE
ITypedElement.VisitAll: check also the definition property

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/firely-net-sdk#2597]
**Describe the bug**
In Firely Server, for the patch operation, we create a `PartToElementAdapter` (see https://github.com/FirelyTeam/Vonk/blob/0b352a37b8d717b4c590622dc5d89347670e5c54/src/Vonk.Core/ElementModel/FhirPatchedElement.cs#L176) with the field to patch. In case of a non-existing field for the resource type to be patched, when getting the definition of the element, we get an exception. So, as part of the prevalidation for the patch operation, we would like to check that both the value but also the definition of all the `PartToElementAdapter` are valid.

**Version used:**
 - Version: 5.3.0

**Additional context**
Suggested PR:
Add an access to the Definition property when visiting all descendants of a ITypedElement in order to detect element with an invalid definition . See https://github.com/FirelyTeam/firely-net-sdk/pull/2594

**Comment by mmsmits** [comment]
closed by https://github.com/FirelyTeam/firely-net-sdk/pull/2594
