### ISSUE TITLE
Behaviour of json validation wrt duplicate keys

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2610]
How to deal with json resources with duplicate keys?

``` json
{
    "a" : "x",
    "a" : "y"
}
```

The Json ECMA spec is silent about it, the RFC "recommends" unique keys, and the FHIR spec, luckily, is explicit: these are not allowed.

The fact that the JSON spec itself is not explicit is probably the reason that Json.net will not complain, the default behaviour is to let subsequent occurrences of a key overwrite the previous ones:

https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_Linq_JsonLoadSettings_DuplicatePropertyNameHandling.htm

* We should hardwire this setting to "Error" for Json.net
* In the new parsers, we are using a forward-only json reader, so the task of detecting this rests on our own shoulders.

**Comment by ewoutkramer** [comment]
Marking this as a bug, since we're not compliant to the FHIR spec.

**Comment by brianpos** [comment]
I think there is already a test for this in the new parser, but I'm not 100%.
(or maybe I have something local still...)

**Comment by wardweistra** [comment]
Please also add trailing commas to this! See https://chat.fhir.org/#narrow/stream/179239-tooling/topic/Simplifier.20Packages/near/398385874

```
{
  "resourceType": "Patient",
  "id": "PatDisp8C66632E5A2E111BE05400144FF84F18",
  "identifier": [
    {
      "system": "https://fhir.infoway-inforoute.ca/NamingSystem/ca-on-patient-hcn",
      "value": "5259156783",
      }
  ],
  "name": [
    {
      "family": "Chen",
      "given": [
        "Patrick",
      ]
    }
  ],
  "gender": "male",
  "birthDate": "1961-01-01",
}
```

![CleanShot 2023-10-25 at 12 03 52@2x](https://github.com/FirelyTeam/firely-net-sdk/assets/779157/5fcff72a-87b6-4450-9748-2d2b4484d2c0)

**Comment by wardweistra** [comment]
Yay!

So I guess trailing commas should get it's own issue, right?
