### ISSUE TITLE
The `if-match` header is now also defined on DELETE interactions.

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2621]
https://firely.atlassian.net/browse/VONK-5627

https://jira.hl7.org/browse/FHIR-40772

**Comment by mmsmits** [comment]
Refinement: 

We should:
-  add a new overload in `TransactionBuilder` called  
`Delete(SearchParams condition, Resource body, string? versionId = null, string? bundleEntryFullUrl = null)`
Handle the if-match header here (see _Update_ for inspriration).

- Also make sure the BaseFhirClient.DeleteAsync uses this new overload.

- Add a test in the FhirClientMockTests to make sure the header is set.
