### ISSUE TITLE
LocalTerminologyService should return original FhirOperationException from getExpandedValueSet

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-net-sdk#2631]
**Describe the bug**
In PR #2560 the behaviour of the LocalTerminologyService in ValueSetValidateCode was changed. L179 does not account for the fact that getExpandedValueSet might already return a FhirOperationException with a status code != HTTP 500. The exception handling is too generic here. For example if the ValueSet cannot be found, an HTTP 400 status code will be overwritten.

**Expected behavior**
Return the original status code to the caller.

**Version used:**
 - FHIR Version: [e.g. R4]
 - Version: [5.4.0]

**Comment by marcovisserFurore** [comment]
This is a regression bug
