### ISSUE TITLE
Location differs for choice elements between ITypedElement adapters on POCO and SourceNode

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2642]
We discovered that TypedElementOnSourceNode and PocoElementNode produce different locations for children that are *choice types*:

```
            var p = new Patient
            {
                BirthDate = "1972-11-30",
                Photo = new List<Attachment>() { new Attachment() { ContentType = "text/plain" } },
                Deceased = new FhirDateTime(1972)
            };
            var pocoTypedNode = p.ToTypedElement();

            var json = p.ToJson();
            var sourceNode = FhirJsonNode.Parse(json, settings: new FhirJsonParsingSettings { AllowJsonComments = true, PermissiveParsing = true });
            var sourceTypedNode = sourceNode.ToTypedElement(ModelInfo.ModelInspector);

            var l = pocoTypedNode.Children("deceased").Single().Location; // Patient.deceased[0]
            var l2 = sourceTypedNode.Children("deceased").Single().Location; // Patient.deceasedDateTime[0]
```

Since the `MaskingNode` is depending on the Location to do its work, generating a summary using the MaskingNode only works well on POCO-based models but not on SourceNode-based models.

**Comment by mmsmits** [comment]
This turns out to be by design. Location can differ between implementations.
This also means the masking node will have limited functionality, but we'll leave it at that for now.

**Comment by alexzautke** [comment]
@mmsmits The context was lost between Slack and creating the issue. In FS we rely on MaskingNode for the implementation of _elements. In FS the location always comes from a SourceNode. That’s why it currently fails on choice types. See https://firelyteam.slack.com/archives/C011XD1TKL0/p1703004394364199

**Comment by mmsmits** [comment]
Reopened by request of the Firely Server team, but not urgent
