### ISSUE TITLE
Nullability Checks On Try ..like method ie: TryGetIdentifier

### ISSUE THREAD

**Issue by dibiancoj** [FirelyTeam/firely-net-sdk#2653]
First off want to thank the team for all the hard work with this code. It's been great for us. 

One new feature / change which would be nice is for c# nullability checks with your try-get methods.

In - https://github.com/FirelyTeam/firely-net-sdk/blob/develop/src/Hl7.Fhir.Base/Model/IIdentifiable.cs#L57C28-L57C44 (as an example)

Even if the method returns true - the c# compile will think it can be null so we have to add a guard regardless or ignore the compiler warning.

The solution which will correct these warnings would be to add the **[NotNullWhen(true)]**
`public static bool TryGetIdentifier(this IIdentifiable<List<Identifier>> identifiable, string system, [NotNullWhen(true) out Identifier? identifier)`

Which basically says if the method returns true, the identifier out parameter will not be null. Then the calling code won't need to add an additional guard.

If your open to it - I can create a PR but wanted to add the request first. 

Thank you again for this great nuget package. It's a really robust codebase.

**Comment by ewoutkramer** [comment]
I have been thinking about doing this for a while, but since we also need to get this to compile on netstandard 2.0, we need to think of a trick to make this compile under both without ifdefs.  Maybe add our own definition of the attribute under netstandard that simply does nothing?

**Comment by dibiancoj** [comment]
Targeting 2.0 makes sense since you need to support .net framework. The nullability attributes sit in net standard 2.1 but that kills support for .net framework.

Those attributes are all sealed so I think the only way to truly support this is multi targeting which gets messy quickly. I can't find anything to switch the attribute types so the compiler looks for your attributes.

I think you can close this and if you ever decide to multi target bring it back in. This was helpful to understand the complexities with trying to support .net core and .net framework.

**Comment by mmsmits** [comment]
@dibiancoj Thanks for getting in touch, and offering to create a PR. I'll close this now, and will reopen when we move away from 2.0 .

**Comment by dibiancoj** [comment]
I did find an example where you can polyfill the nullability stuff in .net standard 2.0. Towards the bottom you can add System.Diagnostics.CodeAnalysis...class essentially. I tried it out and and works well.

Not sure if the effort is worth it though.

https://www.meziantou.net/how-to-use-nullable-reference-types-in-dotnet-standard-2-0-and-dotnet-.htm

**Comment by ewoutkramer** [comment]
This guy has so many useful things on his blog, I should read it more often ;-)

**Comment by mmsmits** [comment]
Refinement:
- can only be done for files which are #nullable enabled.
- Around 100 of Try methods which are not generated or in tests.
- Start with doing this for a couple of functions, and see how long this takes.
- Make a decision on continuing later.
- Possible nullable rabbit hole hazard.

**Comment by dibiancoj** [comment]
Thank you for this change! The more nullable annotations that get added the easier it is for us to determine what can be null for the consumer (and makes our code less error prone). I really appreciate all the work on this and the library in general. Thank you!
