### ISSUE TITLE
Add support for sending the JSON PATCH interaction to FhirClient

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2664]
### Discussed in https://github.com/FirelyTeam/firely-net-sdk/discussions/2217

<div type='discussions-op-text'>

<sup>Originally posted by **timammons** August 30, 2022</sup>
I am trying to patch a patient in the following way, but getting an error **body: must be a list of patch operation requests**.  **_Any idea why?_**

**Code:**
`static void UpdatePatientName(FhirClient fireClient, string patientID)
{
    var pat = fireClient.Read<Patient>($"/Patient/{patientID}");
    var eTag = fireClient.LastResult.Etag;

    Parameters patParams = new Parameters();
    patParams.AddReplacePatchParameter("name/0/given", new HumanName().WithGiven("Beulah").WithGiven("Z"));

    fireClient.RequestHeaders.IfMatch.Add(new EntityTagHeaderValue($"\"{eTag}\"", true)); 
    var updatedPat = fireClient.Patch<Patient>($"{patientID}", patParams);
}`

**This is the body it created, which appears to be a list of patch operation requests:**
{"resourceType":"Parameters","parameter":[{"name":"operation","part":[{"name":"type","valueCode":"replace"},{"name":"path","valueString":"name/0/given"},{"name":"value","valueHumanName":{"given":["Beulah","Z"]}}]}]}

Thanks,
Tim</div>

**Comment by mmsmits** [comment]
Refinement:
- First, add a custom Patch operation to the FhirClient, where users can define their own payload.
- Maybe add some helper methods to make JsonPatch easier. Is there an existing library for that?
- Test against a cerner sandbox (integration test). Or find out another server that supports this.
- Also create a Moq test.
