### ISSUE TITLE
R5 MedicationStatement Adherence error

### ISSUE THREAD

**Issue by dennisbrox** [FirelyTeam/firely-net-sdk#2673]
:information_source: Do you want to ask something or start a discussion, then go [here](https://github.com/FirelyTeam/firely-net-sdk/discussions)

:information_source: Is your bug report about Firely Server Facade, please send an email to [server@fire.ly](mailto:server@fire.ly) or submit a bug report to Jira if you are a paying customer.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version used:**
 - FHIR Version: [e.g. STU3, R4, R5]
 - Version: [e.g. 1.9.0]

**Additional context**

**Comment by dennisbrox** [comment]
Having a problem assigning a codeable concept to the adherence property in a medicationstatement R5.  Where med is defined to be a medicationstatement, the following code:

 cc = new CodeableConcept();
 c = new Coding();
 c.Code = "taking";
 c.System = "http://hl7.org/fhir/CodeSystem/medication-statement-adherence";
 c.Display = "Taking"; ;
 cc.Coding.Add(c);
 med.Adherence.Code = cc;

Results in a null error on the assignment to the adherence property.  All the other properties accept assignment no problem.  What can be the issue?

**Comment by ewoutkramer** [comment]
Did you set the `Adherance` member to anything? They are not initialized by default to not waste memory on unused properties, so you have to explicitly do:

```
med.Adherance = new 
{
    Code = cc
};
```

**Comment by dennisbrox** [comment]
No, I just assigned it.  I'll try that, thanks.
*Dennis Brox*
President Applied Robotics Inc.
Phone: 778 891-4300

**Comment by ewoutkramer** [comment]
No problem!
