### ISSUE TITLE
Using quantities in dates is currently not validating correctly. 

### ISSUE THREAD

**Issue by MatthijsvdWielen** [FirelyTeam/firely-net-sdk#2691]
Executing the examples in https://hl7.org/fhirpath/N1/#subtraction-2, provides an error in the [FHIRPath playground](https://simplifier.net/fhirpath?filepath=package/CapabilityStatement-base.json&scope=hl7.fhir.r4.core@4.0.1&query=%402019-03-01%20-%2024%20months). 

This can be worked around by [adding a '+' to the fhirpath](https://simplifier.net/fhirpath?filepath=package/CapabilityStatement-base.json&scope=hl7.fhir.r4.core@4.0.1&query=%402019-03-01%20%2B%20-24%20months).

_Originally posted by @MatthijsvdWielen in https://github.com/FirelyTeam/firely-net-sdk/issues/2431#issuecomment-1744681689_

**Comment by ewoutkramer** [comment]
I don't think we ever implemented adding quantities to dates in the first place, so it's a miracle you can work around it ;-)

**Comment by mmsmits** [comment]
- Add new overload for the subtraction and addition operators of quantities from dates,
- Precision is hard here, see the spec for examples. (subtracting months from years for example)
- Metrics library is not needed here.
- Check unit in ucum.

See equals and comparison operations for inspiration
