### ISSUE TITLE
Does firely .net SDK support patient data from multiple organizations? like EPIC Care Everywhere

### ISSUE THREAD

**Issue by fayazshaik07** [FirelyTeam/firely-net-sdk#2700]
We're actively using Firely .Net SDK for EPIC FHIR Integration in our Application. I have a scenario where I need to get patient's past medical history if it is spread across multiple organizations?
Does Firely .Net sdk team know how to achieve it? If possible , could you please suggest.
@mbaltus  your expertise is needed. Thanks in advance.

**Comment by mmsmits** [comment]
This is not an issue, but something for the discussion topic.
