### ISSUE TITLE
Update Readmes reflecting the new validator

### ISSUE THREAD

**Issue by wardweistra** [FirelyTeam/firely-net-sdk#2705]
**Is your feature request related to a problem? Please describe.**
I was trying to find the new validator repo.

**Describe the solution you'd like**

1. In the readme of this SDK, provide pointers to [the new validator repo](https://github.com/FirelyTeam/firely-validator-api). For example at:

> This SDK provides:
> * [...]
> * Validation of instances based on profiles
> * [...]

> The profile validator has been split off into its own [repository](https://github.com/FirelyTeam/Hl7.Fhir.Validation.Legacy). The [NuGet](https://www.nuget.org/packages?q=Hl7.Fhir.Validation.Legacy) packages for the validator that are compatible with the SDK 5.0 release can be found on NuGet.

2. In [the legacy validator repo](https://github.com/FirelyTeam/Hl7.Fhir.Validation.Legacy), point to the [new validator repo](https://github.com/FirelyTeam/firely-validator-api)
3. In the issue template for this SDK repo, add a pointer to report issues on the validator in the new repo, just like:

> :information_source: Is your feature request about Firely Server Facade, please send an email to [server@fire.ly](mailto:server@fire.ly) or submit a feature request to Jira if you are a paying customer.

4. In [the new validator repo](https://github.com/FirelyTeam/firely-validator-api), provide a link to [the example implementation in Firely.Fhir.ValidationDemo](https://github.com/FirelyTeam/Firely.Fhir.ValidationDemo)

**Comment by ewoutkramer** [comment]
Ha! Good suggestion.
