### ISSUE TITLE
Improve roundtrip tests performance 

### ISSUE THREAD

**Issue by mmsmits** [FirelyTeam/firely-net-sdk#2707]
Question from @GinoCanessa 

> A lot of the 'long' tests are reading and writing contents to disk for all intermediate stages - are those artifacts necessary somewhere, or could we remove them?  
> 
> For example, skipping the intermediate file IO on my machine takes the execution of `FullRoundtripOfAllExamplesJsonNewSerializer` from 4.1 minutes down to 25.3 seconds.

It would be very nice to make this faster, that would improve the duration of our build pipeline greatly.

**Comment by ewoutkramer** [comment]
Note: even the original FullRoundTripOfallExamplesJsonNewSerializer only took 40 seconds on my machine, so I think Gino has an anti-virus messing with his temp output directory!  Even so, I'll make all of this in memory (per file ;-)) instead of using file storage as an intermediate.
