### ISSUE TITLE
Consider reporting the name of missing elements in error messages, not just in the path

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-net-sdk#2734]
If the POCO-based parser reports error messages about missing mandatory elements the error message does not contain the name of the element that is missing. Example: "Element has 0 elements, but minium cardinality is 1. At ImplementationGuide.definition, line 10, position 4."

It would be more readable in the form: "Element has 0 elements, but minium cardinality for element '< elementName >' is 1. At ImplementationGuide.definition, line 10, position 4."

Also note that "minium" is spelt wrong.

**Comment by mmsmits** [comment]
We decided not to do this.
