### ISSUE TITLE
Help with Vonk.Facade.Relational, R4, .Net 8.0 Parameter Detection Not Working

### ISSUE THREAD

**Issue by charlejc** [FirelyTeam/firely-net-sdk#2746]
### Discussed in https://github.com/FirelyTeam/firely-net-sdk/discussions/2745

<div type='discussions-op-text'>

<sup>Originally posted by **charlejc** March 26, 2024</sup>
I'm trying to update to .Net 8.0 and Vonk.Facade.Relation 4.7.1 and other Vonk 4.7.1 packages. I've implemented the QueryFactory patern and inherited code like the example below.

My problem is that the parameter detection does not seem to be working and the only override function that is being called is the one:

`
	public class ObservationQueryFactory : RelationalQueryFactory<myObservation, myRelationalQuery<myObservation>>, IResourceSpecificQueryFactory
	{
		public override myRelationalQuery<myObservation> AddValueFilter(string parameterName, TokenValue value)
		{
// This code is not being called....
			if(String.Compare(parameterName, VonkConstants.ParameterNames.Id, StringComparison.OrdinalIgnoreCase) == 0
				|| String.Compare(parameterName, "identifier", StringComparison.OrdinalIgnoreCase) == 0)
			{
				return PredicateQuery(observation => observation.Id == value.Code);
			}
                        ....
                }

		public override myRelationalQuery<myObservation> AddValueFilter(string parameterName, RawValue value)
		{
// This code is called instead :-( ....
			throw new NotImplementedException();
		}
         }
`

An error is being swallowed that complains that:

System.Security.Cryptography.XmlSerializers, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL cannot be found. 

I'm not sure if that is the cause of the problem. I'm assuming the webhost is trying to read the specification.zip file that is present in the output directory and process monitor shows it being read, but not many parameters are found when reading the xsd files present in the zip.

Any help or pointers would be greatly appreciated.

Thanks!</div>

**Comment by mmsmits** [comment]
@charlejc , this is not an SDK question but a Firely Server specific issue. 
We've informed our colleagues about this, they'll also inform you where you can post questions in the future

**Comment by alexzautke** [comment]
Conversation is continued in https://github.com/FirelyTeam/Vonk.Facade.Relational/issues/6
