### ISSUE TITLE
Can some important exceptions make it across the ITerminologyService barrier?

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2756]
When our local terminology service encounters an exception (i.e. an expansion fails), it seems that it is not communicated across the FHIR terminology service interface. At least, it seems not to reach our validator.  At least, not the old one ;-)

See https://firelyteam.slack.com/archives/CJQEVLTR7/p1712145910288669 and below.

**Comment by brianpos** [comment]
I've seen this issue too.
Can't tell if there were issues rather than just no result - esp when used alongside the fhirpath engine.
