### ISSUE TITLE
Make Validator mockable

### ISSUE THREAD

**Issue by cknaap** [FirelyTeam/firely-net-sdk#277]
I'd like to be able to mock Validator, in order to unittest a service into which I have a Validator injected.

Since the Validate methods are not virtual, the mocking framework (Moq in my case) cannot setup expectations on these methods. 
Maybe extracting an interface from Validator is the best solution to this.

**Comment by ewoutkramer** [comment]
The Validator interface is built up using a few basic methods + a set of extension methods. Unless mocking the basic methods is good enough, I would not know how to mock these extensions methods - or vice versa if I put these methods on an interface, I think an extension method would not count toward implementing methods on an interface. This could be interesting....

**Comment by cknaap** [comment]
Yes, extension methods are hard with mocking.
But since the code is open source I can predict the correct expectations on the basic methods when one of the extension methods is called. That's not pretty but it would work.
So an interface with only the basic methods is good enough for now.

**Comment by marcovisserFurore** [comment]
We are working on a new validator which is more flexible than the current one. Also introducing a new interface only for the purpose of unit testing is not what we want.
