### ISSUE TITLE
Value systems from Code system https://terminology.hl7.org/5.5.0/CodeSystem-hl7TermMaintInfra.json.html are  not expanded correctly

### ISSUE THREAD

**Issue by aswathikrishnan24** [FirelyTeam/firely-net-sdk#2792]
**Describe the bug**

The Value sets : 
356	http://terminology.hl7.org/ValueSet/mif-conceptRelationshipKind
357	http://terminology.hl7.org/ValueSet/mif-conceptRelationshipReflexivity
358	http://terminology.hl7.org/ValueSet/mif-conceptRelationshipSymmetry
359	http://terminology.hl7.org/ValueSet/mif-conceptRelationshipTransitivity

Belonging to Code system : https://terminology.hl7.org/5.5.0/CodeSystem-hl7TermMaintInfra.json.html are not expanded.

![image](https://github.com/FirelyTeam/firely-net-sdk/assets/146727970/385cba4d-df5d-4cae-8728-e855b9e00d5a)

Value set expansion of http://terminology.hl7.org/ValueSet/mif-conceptRelationshipTransitivity (value set 359) should pick all codes under "MIF-ConceptRelationshipTransitivity" and then exclude itself which is MIF-ConceptRelationshipTransitivity . 

All codes :
1. MIF-ConceptRelationshipTransitivity
2. transitive
3. antitransitive

The expanded codes should be 
1. transitive
2. antitransitive

In the Codes table, the corresponding codes are not present. 
Value set IDs 356 - 359 have no codes

**To Reproduce**
1. Install firely-car tool
2. Generate car file from us core 5.0.1 package.
```
{
    "name": "Us-core-test-5.0.1",
    "version": "0.1.0",
    "description": "describe your package",
    "author": "supply your name here",
    "dependencies": {
      "hl7.fhir.us.core": "^5.0.1"
    }
  }
```
4. Verify the Value set 359 from Value set table
5. Verify if the codes are generated in Codes table

**Expected behavior**
The expanded codes should be 
1. transitive
2. antitransitive

**Version used:**
 - FHIR Version: R4
 - Version: Firely-car tool 2.1.2

**Comment by mmsmits** [comment]
Looking at this, we seem to throw away the children of the codes when we throw away the parent. 

Todo:
- When we delete a code, check for children
- If children, then put them on the level of the code you want to delete and delete the original code.

**Comment by aswathikrishnan24** [comment]
307	http://hl7.org/fhir/ValueSet/encounter-participant-type also seems to expand incorrectly because of the same issue.
