### ISSUE TITLE
Snapshot generator does not expand complex extensions defined in a an extension.

### ISSUE THREAD

**Issue by Rob5045** [FirelyTeam/firely-net-sdk#2799]
The bug was originally submitted to Forge:
https://firely.atlassian.net/browse/FOR-872

The project to reproduce the issue is attached.
The issue is for file: NLLArticleInfoCorrect.xml.

The snapshot generator method Generate returns 2 of the same errors:

`https://electronichealth.se/fhir/StructureDefinition/NLLArticleInfo2 (Element Extension.extension.extension has neither a type nor a nameReference.) 
`

They correspond to the extension element definitions for **currentProductName** and **history**.
These two element definitions are not expanded.

 - FHIR Version: R4
 - Version: 5.8.1

[swedishnationalmedicationlist(5).zip](https://github.com/user-attachments/files/15788483/swedishnationalmedicationlist.5.zip)

**Comment by mmsmits** [comment]
Don't spend more than 2 days researching what's going on here

**Comment by mmsmits** [comment]
@MatthijsvdWielen You've had a call about this with @alexzautke , what was the conclusion ?

**Comment by MatthijsvdWielen** [comment]
@mmsmits that call did not solve the issue unfortunately. 

The customer provided some additional information. In version 23 everything was still working and from version 24 the issue started. https://simplifier.net/SwedishNationalMedicationList/NLLMedication/~history

**Comment by mmsmits** [comment]
I found out the problem. It's not the snapshot generator. But the order of the ElementDefinitions in the differential.

I attached the correct file here: 
[NLLArticleInfoCorrect.txt](https://github.com/user-attachments/files/17160988/NLLArticleInfoCorrect.txt)

Please note that the order of the elements in a Differential matter a lot.
And Extension.extension comes before Extension.url and Extension.value[x].

I don't if Forge created this (I think not), but the user should be informed.

**Comment by mmsmits** [comment]
See unit test for this here as well:
https://github.com/FirelyTeam/firely-net-sdk/pull/2877/files
