### ISSUE TITLE
Extend IResourceResolver with the ability to also report back issues

### ISSUE THREAD

**Issue by mmsmits** [FirelyTeam/firely-net-sdk#2808]
Currently IResourceResolver only supports returning either a resource or null. 
We run into the issue more and more that we also want to know why a resource wasn't returned, or when a resource is returned if there are any warnings to report.

Think about issues that have occurred during snapshot generation or something wrong with the package.

**Comment by ewoutkramer** [comment]
Duplicate of #2778
