### ISSUE TITLE
ValueSet loading is overriding default display with desgination

### ISSUE THREAD

**Issue by GinoCanessa** [FirelyTeam/firely-net-sdk#2809]
**Describe the bug**
When loading the R5 Units of Time ValueSet (`ValueSet-units-of-time.json`), the concepts all have the Chinese (`zh`) values for the `display` element instead of the English value.

**To Reproduce**
1. Load the `ValueSet-units-of-time.json` ValueSet from the R5 expansions package (`hl7.fhir.r5.expansions#5.0.0`), using the `FhirJsonPocoDeserializer`.
2. Examine the `Expansion.Contains` elements.

Unit Test (from my project, not Hl7.Fhir) for review:
```csharp
FhirJsonPocoDeserializer parser = new(new FhirJsonPocoDeserializerSettings()
{
    DisableBase64Decoding = false,
    Validator = null,
});

// always use lenient parsing
Resource parsed = parser.DeserializeResource(json);

parsed.Should().NotBeNull();
parsed.Should().BeOfType<ValueSet>();

ValueSet vs = (ValueSet)parsed;

vs.Expansion.Should().NotBeNull();
vs.Expansion.Contains.Should().NotBeEmpty();
vs.Expansion.Contains.Count.Should().Be(7);

foreach (ValueSet.ContainsComponent cc in vs.Expansion.Contains)
{
    cc.Display.Should().StartWith(cc.Code);
}
```

Each of the English displays match the beginning of the code values, so the test should pass.  Instead it fails:
```
Expected cc.Display to start with "s", but "秒" differs near "秒" (index 0).
```

**Expected behavior**
The `display` element value should represent what is in the resource and not override with the `designation` value.

**Screenshots**
The image below is from the watch of the above unit test.  The `Display` string _should_ have `second` in it, but has the Chinese `秒` instead.

![image](https://github.com/FirelyTeam/firely-net-sdk/assets/50417653/5498af7b-f908-492f-9d23-c06f2f608dac)

**Version used:**
 - FHIR Version: FHIR R5 5.0.0
 - Version: `Hl7.Fhir.R5` version `5.8.1`

**Additional context**

**Comment by ewoutkramer** [comment]
I think this issue is in the wrong repo, maybe you wanted to report this to HL7?

When looking at the expansion provided in the hl7.fhir.r5.expansions#5.0.0 package NPM file I see:

```json
"contains": [
      {
        "system": "http://unitsofmeasure.org",
        "code": "s",
        "display": "秒",
        "designation": [
          {
            "language": "zh",
            "value": "秒"
          }
        ]
      },
      {
        "system": "http://unitsofmeasure.org",
        "code": "min",
        "display": "分钟",
        "designation": [
          {
            "language": "zh",
            "value": "分钟"
          }
        ]
      },

     (etcetera)
```

So, it seems the expansion tooling in the Java stack is indeed overwriting the display. Not sure what to do about that here!

**Comment by GinoCanessa** [comment]
Thanks, I missed that looking at `compose.include`, which has the correct info.  Apologies!
