### ISSUE TITLE
SampledData not supported?

### ISSUE THREAD

**Issue by vivara-keithpatton** [FirelyTeam/firely-net-sdk#2816]
**Describe the bug**
It doesn't seem possible to use SampleData as a DataType when adding components to observations. 

**To Reproduce**

create a component using SampledData data type object and specify Data with IntervalElement or OffsetsElement. 

When you create the observation a Fhir Serialization error occurs saying that the elements are not supported, and if you leave them out it will say they are required (but with different casing in that message). I suspect there's some mapping/serialization bug. 

We are using Azure Health Data Services FHIR Api.

**Expected behavior**
IT would be expected that the SDK should support SampledData. 

**Screenshots**

**Version used:**
 - FHIR Version: R4 (

**Comment by mbaltus** [comment]
I think you are trying to mix the R5 SampledData datatype with the R4 Observation, which causes the errors. The R4 SampledData does not have an Interval or Offset element.

But if not, please add a code example that reproduces the errors. Also please list the exact text of the error messages.

**Comment by vivara-keithpatton** [comment]
@mbaltus ah yes indeed, i'm using the latest R5 library against the Azure FHIR Service which is R4. I will downgrade my SDK library to the R4 one to avoid hitting issues thanks
