### ISSUE TITLE
FhirJsonConverter breaking change in 5.8.0

### ISSUE THREAD

**Issue by darena-antonw** [FirelyTeam/firely-net-sdk#2818]
**Describe the bug**
wanted to report a breaking change introduced in ba3cf03602cc59b8f915de6b3ca9747f3ae3b200 to the `FhirJsonConverter`

we've been overriding the `FhirJsonConverter` implementation using this constructor:

```cs
[Obsolete("Using this directly is not recommended. Instead, try creating a converter using the .ForFhir static method of the JsonSerializerOptions class")]
        public FhirJsonConverter(
            ModelInspector inspector,
            FhirJsonPocoSerializerSettings? serializerSettings,
            FhirJsonPocoDeserializerSettings? deserializerSettings,
            Predicate<CodedException>? ignoreFilter = null)
        {
            _engine = FhirSerializationEngineFactory.Custom(inspector, ignoreFilter ?? (_ => false), deserializerSettings,
                serializerSettings);
        }
```

but looks like it's been obsoleted and then changed in the same version; and all other constructors are obsolete.

Our use case is to override serialization logic of certain value types, could you please advise what we should be switching over to.

**Version used:**
 - FHIR Version: R4
 - Version: 5.7.0 -> 5.8.2

**Comment by ewoutkramer** [comment]
We have made this method obsolete, but it should not consitute a breaking change. Can you elaborate on how this breaks your usecase?

Also, when using ForFhir(), you can also add and remove converter, and include your own converters. Can you tell us what more you need to meet your requirements?

**Comment by Kasdejong** [comment]
ah, I see it now! we accidentally deleted a public constructor. To circumvent this, I recommend using either the FhirJsonConverterFactory or using the overload which takes a custom serializer/deserializer. We will add the constructor back ASAP!
