### ISSUE TITLE
Consider switching to netstandard2.1

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2882]
Although we currently do not use newer features, supporting netstandard 2.0 is becoming a burden. In particular, to give us more freedom to change APIs in the SDK6 timeframe, I would like to at least move to netstandard2.1 to be able to use default interface implementations.  It would also allow us to simplify string operations by using slices.

We have also thought about jumping onto the .NET Core bandwagon, so actually releasing for a .NET version (say, 6.0 or 7.0).  This of course will cause our code no longer to run on Unity or Xamarin, but .NET is widely supported on Mac, Android, Linux and Windows, so I am not sure this is a problem.

**Comment by mmsmits** [comment]
Maybe we should ask the dotnet stream on Zulip as well

**Comment by ewoutkramer** [comment]
See also https://community.devexpress.com/blogs/news/archive/2023/07/05/net-net-standard-2-0-deprecation-support-for-net-6-or-net-8-lts-by-default-in-libraries-and-more-v23-2.aspx
