### ISSUE TITLE
plain/text responses are not support for OperationAsync

### ISSUE THREAD

**Issue by fonzmeister** [FirelyTeam/firely-net-sdk#2924]
:information_source: Do you want to ask something or start a discussion, then go [here](https://github.com/FirelyTeam/firely-net-sdk/discussions)

:information_source: Is your bug report about Firely Server Facade, please send an email to [server@fire.ly](mailto:server@fire.ly) or submit a bug report to Jira if you are a paying customer.

**Describe the bug**
The function ReadResourceFromMessage throws an exception whenever the response type is not a json/xml. However, for the $convert-data endpoint supported by fhir an plain/text is returned. Please refer to https://github.com/microsoft/fhir-server/blob/main/docs/ConvertDataOperation.md

`Note the Content-Type is the response header is set to text/plain because the output format is determined by the mapping definition from your templates.`

**To Reproduce**
1. send a $convert-data request using FhirClient.OperationAsync
2. See error: ![Image](https://github.com/user-attachments/assets/24ef9590-9402-491b-8478-65d163957195)

**Expected behavior**
I would expect these return types to be supported since it is part of the fhir standard

**Screenshots**

**Version used:**
 - FHIR Version: r4 
 - Version: 5.9.0

**Comment by mmsmits** [comment]
Hi @fonzmeister ,
Microsoft has defined their own operation here (it's not part of the FHIR spec), but the fact that this operation returns `text/`plain` makes that this operation is non-conformant with the FHIR standard and not supported by the SDK.
If you want to support this in your use-case be aware of this. You can however, use a simple HttpClient to support this operation yourself.
