### ISSUE TITLE
Align Java & .NET validators

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#353]
We should align the validators on:

1. Error codes
2. Settings
3. Interface used to resolve resources

Ad 1. This makes it easier to write unit-tests for both platforms
Ad 3. Maybe align IResourceResolver with the Conformance Service specs (as yet to be written in R4)

**Comment by wardweistra** [comment]
Perhaps this one can be closed in favor of #1262
