### ISSUE TITLE
[Source] A failing ResolveByUri (etc) should throw, not return null

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#422]
We need ResolveXXX() to throw on error (for errors occuring at resolution time - for more static errors discovered by the source, use #421) - and let "null" be returned when the source simply does not have the requested url.

For the MultiResolver - this would mean either
* On exception - try the other sources, if all fail return the *first* exception
* Or create a new MultiResolverResolutionException with a list of all exceptions encountered (much like the AggregateException on Task)

**Comment by ewoutkramer** [comment]
The new Async resolvers will return Result<T>, instead of throwing or returning null.

**Comment by marcovisserFurore** [comment]
Discussed in our stand-up of March 4th, 2021. It is a good idea, but `IResourceResolver` is used everywhere and altering the signature of this interface would break of lot things in the code of the SDK and also in the code of our users. We missed the opportunity to solve this when we've made this Async, but there was too less time for doing this. Therefor, we close this issue.
