### ISSUE TITLE
[Validator] Optimize fetching the same external resource multiple times

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#467]
Somewhere there should be caching involved.....but how to go about cache invalidation?

**Comment by wmrutten** [comment]
CachedResolver exposes InvalidateByUri and InvalidateByCanonicalUri methods for cache invalidation.
Access to the internal data structure is synchronized, so it should be thread safe.
E.g. while the validator is running, another thread could invalidate a cache entry. Subsequent requests to for that entry will cause the CachedResolver to try and re-load the requested artifact from the backing source.

**Comment by ewoutkramer** [comment]
You're right, but I am not fetching external resources using an IResourceResolver I think. Or maybe I do ;-)  Well, I'll double check and if not see how to integrate IResourceResolver into resolving external (instance) references (not necessarily to conformance resources)

**Comment by marcovisserFurore** [comment]
External resources are fetched by subscribing to the event `OnExternalResolutionNeeded`. When you are not doing that, the `Validator` tries to resolve the resource with his own `IResourceResolver`, which is not cached. 
When you are using the  `OnExternalResolutionNeeded` you can control, as an end-user, the way how external resources are fetched and thus implement a caching mechanism for that as well.
