### ISSUE TITLE
PocoNavigator.Value is too expensive

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#482]
The Value property of IElementNavigator is accessed pretty frequently by all the supporting infrastructure (Validator, FhirPath evaluator, serializer) and therefore needs to be fast. The current implementation will frequently call out to methods that parse and serialize raw values - which takes too much time.

I propose we cache this property in the PocoNavigator.

**Comment by ewoutkramer** [comment]
Discovered by @marcovisserFurore

**Comment by ewoutkramer** [comment]
Note, the `PocoNavigator` is now an empty shell, just calling ITypedElement.Value, which is generally implemented by TypedElement.Value (which still has the same problem) or PocoElementNode.Value (which just does some casting).  So, now, we should look at `TypedElement.Value`.

**Comment by mmsmits** [comment]
Info on where to find the ValueSet to add is here:
https://stackoverflow.com/questions/67626063/how-to-make-a-fake-valueset-resource-with-e-g-currency-symbols-for-when-termi
