### ISSUE TITLE
No Description for SearchParameterDefinition

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/firely-net-sdk#509]
There is no description (string) for the SearchParameterDefinition with url = "http://hl7.org/fhir/SearchParameter/clinical-code". In de specification there is a description for it: http://hl7.org/fhir/searchparameter-registry.html#clinical-code

**Comment by ewoutkramer** [comment]
What we could do is update the source data (coming straight from the spec) to include the description. We've done that with DSTU2 as well.  Disadvantage: *if* a new STU3 release gets published, these "manual" changes will be overridden....

**Comment by marcovisserFurore** [comment]
Today (June 24th, 2021) this description is present in STU3 and R4.
