### ISSUE TITLE
Incorporate the standard snapshot test suite

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/firely-net-sdk#539]
The .NET API should implement the standard snapshot test suite:

https://chat.fhir.org/#narrow/stream/conformance/subject/Changing.20to.20how.20slicing.20works.20for.20element.5Bx.5D

This would facilitate comparing & harmonizing different implementations.

**Comment by ewoutkramer** [comment]
This is a great idea, but it's abundantly clear now this will never get prio.
