### ISSUE TITLE
Integrate unit-tests from the FHIR spec for the validator and snapshot generator

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#554]
To ensure consistencies between the .NET and Java implementations, we should run our snapshot generator on the set of differentials that Grahame has created, so we can compare outputs.

Same holds true for the test-instances and expected validation messages - though these are harder to compare.

**Comment by wmrutten** [comment]
Also see #539

**Comment by mmsmits** [comment]
Done this for the validator, see https://github.com/FirelyTeam/firely-net-sdk/issues/539 for snapshot generator.
Closed as duplicate
