### ISSUE TITLE
Validator succeeds on invalid choice datatypes

### ISSUE THREAD

**Issue by mbaltus** [FirelyTeam/firely-net-sdk#622]
When you add an invalid type to the choices of a value[x] element in a profile, validating the StructureDefinition succeeds without any errors. See for example the attached profile, where I've added a Reference type to the Questionnaire.item.option.value[x].

[MyQuestionnaire.StructureDefinition.txt](https://github.com/ewoutkramer/fhir-net-api/files/2114244/MyQuestionnaire.StructureDefinition.txt)

**Comment by ewoutkramer** [comment]
This *should* be fixed in the 1.0 release, but it's worth verifying before I close the issue.

**Comment by ewoutkramer** [comment]
I am only now reading this thoroughly, this is not about an instance conforming to a structuredefinition, this is about the fact that when you create a structuredefinition, you can use datatypes in value[x] that are not in the base for that structuredefinition.

That's right, the validator does not catch that: there simply isn't any computable rule in the FHIR spec that specifies this behaviour (e.g. using FhirPath as an invariant).  It would probably will have to be hand-coded into the validator.

**Comment by mmsmits** [comment]
Authoring tools should be responsible for validating this, this is too complicated for the profile validator at that point.
