### ISSUE TITLE
Implement v3 xml support

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#653]
With minimal adaptions, our infrastructure can read v3 messages, backed by StructureDefinitions that use the v3 representation hints.  The newly refreshed parser infrastructure should be able to handle it, but it needs to be tested and tuned based on some actual data+definitions found here: https://build.fhir.org/ig/HL7/fhir-cda/

**Comment by mmsmits** [comment]
This is done
