### ISSUE TITLE
SnapshotGenerator - publicly expose method to merge element definitions

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/firely-net-sdk#669]
The SnapshotGenerator uses an internal utility class (see ElementDefnMerger.cs) to merge differential element constraints onto snapshot element constraints. Forge sometimes needs to merge element constraints on the fly, e.g. when the user changes the type of an element. Propose to change the SnapshotGenerator to publicly expose a method that allows consumers to merge element constraints.

**Comment by marcovisserFurore** [comment]
This has been solved already on Aug 16, 2018. See PR #671
