### ISSUE TITLE
Make working with resource type/string/enum consistent

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#73]
The API has three ways to convey a type of resource to client and other sources (e.g. ModelInfo):
- An actual POCO .NET type
- A string
- The ResourceType enum

It would be good to make these consistent and have a way to easily convert from one to the other

**Comment by ewoutkramer** [comment]
Nice idea - we should revisit this when creating the new HttpClient, since we cannot change the current API surface for the client anymore.

**Comment by ewoutkramer** [comment]
Putting this on the 2.x roadmap, since @mmsmits is now revisiting this interface.

**Comment by marcovisserFurore** [comment]
We close this issue. Not important enough
