### ISSUE TITLE
Make sure we don't generate errors voor invariants marked as "guideline"

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#796]
http://hl7.org/fhir/2018Sep/conformance-rules.html#constraints

**Comment by brianpos** [comment]
I'm still going to include these invariants, but have added code to check for the extension and skip them.
Until we add a settings property to use them.
(as these will be in others defintions too)

**Comment by ewoutkramer** [comment]
We don't. That's 100% sure.
