### ISSUE TITLE
Should SelfLink be preserved even if _summary=count is specified?

### ISSUE THREAD

**Issue by jackliums** [FirelyTeam/firely-net-sdk#826]
I've noticed that when serializing a bundle with Summary=Count specified, it wipes out the SelfLink since it looks like the the code below does not maintain the links.

```
        public static MaskingNode ForCount(ITypedElement node) =>
          new MaskingNode(node, new MaskingNodeSettings
          {
              IncludeMandatory = true,
              IncludeElements = new[] { "id", "total" },
          });
```

I think SelfLink should be included since it is used to indicate what search parameters were actually being used for the executed search?

**Comment by ewoutkramer** [comment]
Unfortunately, this is not up to us to decide - we have to align with the FHIR spec here. 

This section deals with it: http://hl7.org/fhir/search.html#summary

As you can see in the spec, it's unclear whether this is expected behaviour or not.  Best is if we pose this question on Zulip.  Are you familiar with the FHIR Zulip chat? Could you do that?

**Comment by ewoutkramer** [comment]
Server developers @brianpos what do you think? @cknaap ?

**Comment by brianpos** [comment]
That's actually an interesting question. The intent is not to include the entries, but nothing on the links. I think take it to zulip, and sunbmit an issue for clarification.

**Comment by jackliums** [comment]
@ewoutkramer Yes I will bring the issue up with the FHIR chat. I realized that it's probably a spec issue after filing issue here.

**Comment by jackliums** [comment]
@ewoutkramer based on conversation in the chat, the link should be returned regardless of which option is specified for the _summary parameter. 

https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Should.20selfLink.20be.20returned.20when.20_summary.3Dcount.20is.20specified

Also, filed spec issue here: https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=20419

**Comment by ewoutkramer** [comment]
Hi @jackliums - the HL7 FHIR-I committee has voted persuasive on that tracker item.  We can start to implement it.  Should be possible by a trivial change to the settings for the MaskingNode.  Will you make a PR?

**Comment by jackliums** [comment]
@ewoutkramer yes I will make the change and submit a PR.

**Comment by ewoutkramer** [comment]
This is now https://jira.hl7.org/browse/FHIR-20419.

Don't think we ever had a PR for it, but we could still do it if relevant.
