### ISSUE TITLE
Make structural validations configurable

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#852]
Since 1.2 (the actual version on develop), the parsers use ITypedElement, which also does additional structural validations, e.g. check correct XHTML in narrative - even in json, check element order, check use of json arrays for repeating elements.

All these checks were not done before - and the element order one will probably cause many files we previously accepted to start failing.  

Although we have PermissiveParsing, this is an all-or-nothing switch.  Maybe, even with PermissiveParsing = false, we can have a switch to disable the new validations that are based on type information.

Disadvantage is more configuration settings (more mental load for the user) and more ifs in the parser code to enable/disable the tests.

**Comment by ewoutkramer** [comment]
After toying with this for 2 years (how on earth are you going to make this configurable for the user), I have settled on this solution for the new generation of POCO-based deserializers:

* Document all possible errors produced by the XML and Json deserializers, giving them a unique ID.
* List those errors that are "permissible", which means there is no data loss when you choose to disregard the error.
* Let the deserializers continue parsing on encountering an error, and list all encountered errors as a result.
* The deserializers will *only* return a POCO if there were no errors encountered *at all*. In all other cases, a subclass of `AggregateException` is thrown, which lists all errors the deserializer encountered. This subclass has a special property `PartialResult` that contains the POCO with as much data as the parser was able to recover from the json/xml.
* So, just calling the deserializer is equivalent to the old parsers "non permissive/strict" mode.  And we can emulate "permissive" by catching the `AggregateException`, and then checking whether all of the reported errors are listed in the "permissible" set. If so, we can return `PartialResult`. In all other cases, rethrow the AggregateException - there were non-permissible errors present.
* Developers can make their own judgement on how to interpret the list of errors - this way it is guaranteed that we can read as much of the existing databases in servers parsed by the older parsers as possible.

We will expose the new deserializer in three ways:

* As a public class that can be used directly (as described above)
* Wrapped so it can be used as a System.Text.Json Converter.
* Behind the old existing parser interface, we'll simulate the old behaviour as described above.

**Comment by ewoutkramer** [comment]
@ginocanessa, @brianpos @marcovisserFurore - I would be happy to have your feedback on these ideas.

**Comment by ewoutkramer** [comment]
There's a bit more (not implemented yet):

* Make XHTML validation (Narrative) configurable (default:off) - it's expensive
* Validate the date/time/datetime strings encountered (instant is already validated, as is base64 data) - default on - you can chose to ignore the errors, as these errors will be in the permissible set (we will store them in the POCO anywayas the current datatypes are string based, so they can contain "incorrect" date/times).
* Have a callback on when we encounter invalid data, so developers can chose a recovery mechanism (like the MS usecase, where we wanted to accept times on a date, but truncate the time in the POCO model).

**Comment by brianpos** [comment]
The approach is sounding good, I can compare this to the list that I have in my custom XML parser.
Do you have a branch with this in progress?

**Comment by brianpos** [comment]
As for the xhtml validation, do you think that might be better done as a superpower parser?
(at least for consideration)

**Comment by ewoutkramer** [comment]
The validation needs to take the HL7-supplied XSD files into account, so this goes way beyond just parsing the XML itself! It's therefore quite expensive.  Might be worth having an enum then:  no validation/validate xhtml/validate FHIR narrative XHTML

**Comment by marcovisserFurore** [comment]
Done
