### ISSUE TITLE
Check XHtml rule should be moved from SourceNode

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#857]
We have a set of rules that bubble up using the AdditionalStructuralRule annotation.  This is useful for rules that are specific to a source format (that's why this annodation is served from FhirXmlNode and JsonXmlNode), however it is now also used to include rules that require type information in general - but are not format specific, i.e. the check that validates the xhtml content of narrative.

These rules should be moved to the ITypedElement implementer instead - otherwise content of nodes that are created from other sources or are constructed using SourceNode  will not get validated.

This is a specific instance of a more general problem:  everything that is not format specific, we should be able to enforce on all implementations of ISourceNode. And also (and this is not the case now), every rule that requires type information context should be run on *any* ITypedElement, not just the internal implementation we have now.  So it should be a wrapper around TypedElementOnSourceNode, rather than in TypedElementOnSourceNode.

**Comment by marcovisserFurore** [comment]
Discussed in our standup of 2021-12-13, we decided to close this issue. The next deserializer/serializer handles this much better. See version 4.0
