### ISSUE TITLE
Expand IsNullOrEmpty() to complex values

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#87]
We currently have an extension method IsNullOrEmpty() available for Primitives.  We should split this in a generated method IsEmpty() that recursively calls IsEmpty on the containing elements. The original extension method can do the null check.

This way we can expand IsNullOrEmpty to cover complex types too.

**Comment by marcovisserFurore** [comment]
We close this enough. Too less prio
