### ISSUE TITLE
[FhirPath] Add support for defining your own %variables

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#900]

**Comment by kennethmyhra** [comment]
The thought is that this can better the readability and the process of writing longer FhirPath expressions.

Example with support for defining your own variables:
```
%relatedPersons	- List of RelatedPerson
%patient	- Patient

iif(%relatedPersons.where(relationship.where(coding.where(code = 'represents' and system = 'http://terminology.ehelse.no/CodeSystem/RoleCode'))).exists(), 
	// true part
	%relatedPersons.where(relationship.where(coding.where(code = 'represents' and system = 'http://terminology.ehelse.no/CodeSystem/RoleCode'))).identifier.where(system = 'http://terminology.fhir.org/CodeSystem/MRN').value
,
	// false part
	%patient.identifier.where(system = 'http://terminology.fhir.org/CodeSystem/MRN').value
)
```

Example without support for defining your own variables, reading from a Bundle:
```
iif(entry.where(resource.relationship.where(coding.where(code = 'represents' and system = 'http://terminology.ehelse.no/CodeSystem/Relationship'))).exists(),
	// true part
	entry.where(resource.relationship.where(coding.where(code = 'represents' and system = 'http://terminology.ehelse.no/CodeSystem/Relationship'))).resource.identifier.where(system = 'http://terminology.fhir.org/CodeSystem/MRN').value
,
	// false part
	entry.where(resource is Patient).resource.identifier.where(system = 'http://terminology.fhir.org/CodeSystem/MRN').value
)
```

**Comment by ewoutkramer** [comment]
Yes, and we  need to find a way to provide the value of these things for every call to the evaluator.  I know we discussed doing this using the FpInit (which initialises the symbol table also used for functions) but I realized that's actually wrong, since you do that only once.  So we indeed need a separate way to pass environment variables into the FP evaluator, separate from the predefined ones in the spec.

**Comment by brianpos** [comment]
The fhirpath engine has full support for this already - I've been using it in the SDC processing for some time.
Create a new SymbolTable and pass the base symbolTable in the constructor, then call addVar() to include your variables.
If you need to add in arrays of values, this works too.
``` c#
public static void AddVariable(Hl7.FhirPath.Expressions.SymbolTable table, string name, IEnumerable<ITypedElement> value)
{
    table.Add(name, () => { return value; });
}
```

**Comment by kennethmyhra** [comment]
We haved used `AddVar()` and solved the original issue pretty nicely with that. From my point of view this issue be closed.
