### ISSUE TITLE
ResourceIdentity - Handle invalid input

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/firely-net-sdk#91]
If `ResourceIdentity.parseComponents` fails due to invalid input, the instance is left in an indeterminate state. In that case, the `ResourceIdentity.Form` property returns the default enum value (0) = `ResourceIdentityForm.AbsoluteRestUrl` and the `ResourceIdentity.IsAbsoluteRestUrl` property returns `true`. However this is not guaranteed to be correct, e.g. for input "/Test".

Suggestion: define an explicit indeterminate default value for `enum ResourceIdentityForm`, e.g. `ResourceIdentityForm.Unknown = 0`.

**Comment by marcovisserFurore** [comment]
Closed due to inactivity
