### ISSUE TITLE
Change author to Firely

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/firely-net-sdk#964]
- change the author of the Nuget packages to Firely and contributors
- show a license screen when installing the NuGet package

**Comment by ewoutkramer** [comment]
I'd think this is done by now, @marcovisserFurore ?

**Comment by marcovisserFurore** [comment]
No, not yet. We can change this with the final release of 2.0.0

![image](https://user-images.githubusercontent.com/31658535/93996258-561cc500-fd92-11ea-9906-30d66c7db58d.png)
