### ISSUE TITLE
Debug symbols in nuget

### ISSUE THREAD

**Issue by explunit** [FirelyTeam/firely-net-sdk#972]
Would it be possible to include the debug symbols (.PDB file) in the published nuget package for easier debugging and better support in static analysis tools?

**Comment by ewoutkramer** [comment]
I thought we did, but I see this in our project file:

```
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
     <DebugType>full</DebugType>
     <DebugSymbols>True</DebugSymbols>
     <NoWarn>1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\FhirNetApi.snk</AssemblyOriginatorKeyFile>
    <IncludeSymbols>True</IncludeSymbols>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>
```

Clearly, we only do DebugSymbols on a debug build. I am pretty sure that I have been pushing separate packages with pdb files to NuGet in older versions.  Is this something that changes when we switched from manual building to our Azure CI, @marcovisserFurore ?

**Comment by ewoutkramer** [comment]
Also, we should probably add a prop `SymbolPackageFormat` as described here: https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

**Comment by ncoussemacq** [comment]
That would be great to have debugging symbols alongside with Assemblies in Nuget packages.
Any reason not to have them (except lack of time for this changes) ?

**Comment by marcovisserFurore** [comment]
The reason was lack of time. But just for the Christmas holidays, I have found some time to do this. 

So in the next release (beginning of Januari 2021), the debug symbols are part of the NuGet packages

**Comment by ncoussemacq** [comment]
Great news !
Many thanks
